### ISSUE TITLE
OpenCover with xunit runs the tests, but produces 0% coverage report

### ISSUE THREAD

**Issue by conderol** [OpenCover/opencover#1011]
**Support requests** should initially be raised on [GitHub discussions](https://github.com/OpenCover/opencover/discussions) 
Hi. I am using openCover OpenCover version 4.7.922.0 with xUnit.net Console Runner v2.4.1 to run the test cover report
Here is the the covered code .It is .Net framework 4.6.1 class
`using Xunit;

namespace IConduct.DAL.Tests.DataAdapterTests
{
    public class ExtraSettingsTests
    {
        private const string ConnectionString =    "Data Source=qa-db; Initial Catalog = IConductQ1; User Id = sa; Password=+2K20ICcloud+";
        [Fact]
        public void CanSelectExisting()
        {
            //Arrange
            IExtraSettingsDataAdapter dataAdapter = new DataAdapter(ConnectionString);
            
            //Act
            var target = dataAdapter.GetExtraSettings("testmachine", ExtraSettingsType.ProviderCryptoKeys);

            //Assert
            Assert.NotNull(target);
        }`

I run the following command with the following output

```
OpenCover.Console.exe -oldstyle -skipautoprops -target:C:\Tools\net472\xunit.console.exe  -targetargs:"C:\agent\_work\3\s\IConduct.DAL.Tests\bin\Release\IConduct.DAL.Tests.dll -noshadow -verbose -diagnostics" -output:C:\tools\Dal.Tests.xml -register:user -filter:+[*]*
```

Executing: C:\Tools\net472\xunit.console.exe
xUnit.net Console Runner v2.4.1 (64-bit Desktop .NET 4.7.2, runtime: 4.0.30319.42000)
  Discovering: IConduct.DAL.Tests (app domain = on [no shadow copy], method display = ClassAndMethod, method display options = None)
  Discovered:  IConduct.DAL.Tests (found 10 test cases)
  Starting:    IConduct.DAL.Tests (parallel test collections = on, max threads = 8)
    IConduct.DAL.Tests.DataAdapterTests.TransactionsTests.CanCheckIfTransactionIsEnded [STARTING]
    IConduct.DAL.Tests.DataAdapterTests.InterfacesTests.IsAllowRunOnApiForExistingInterface [STARTING]
    IConduct.DAL.Tests.DataAdapterTests.TransactionLogsTests.CanInsertTransactionLog [STARTING]
    IConduct.DAL.Tests.DataAdapterTests.ExtraSettingsTests.CanSelectNotExistingPreconfiguredCommand [STARTING]
    IConduct.DAL.Tests.DataAdapterTests.TransactionLogsTests.CanInsertTransactionLog [SKIP]
      Fails, should be rewritten. Also no Idisposable implementation to to clean up test data
    IConduct.DAL.Tests.DataAdapterTests.TransactionsTests.CanCheckIfTransactionIsEnded [SKIP]
      Fails, should be rewritten
    IConduct.DAL.Tests.DataAdapterTests.TransactionLogsTests.CanInsertTransactionLog [FINISHED] Time: 0s
    IConduct.DAL.Tests.DataAdapterTests.TransactionsTests.CanCheckIfTransactionIsEnded [FINISHED] Time: 0s
    IConduct.DAL.Tests.DataAdapterTests.TransactionsTests.CanGetTransactionIdBySchedulerTaskId [STARTING]
    IConduct.DAL.Tests.DataAdapterTests.TransactionsTests.CanGetTransactionIdBySchedulerTaskId [SKIP]
      Fails, should be rewritten
    IConduct.DAL.Tests.DataAdapterTests.TransactionsTests.CanGetTransactionIdBySchedulerTaskId [FINISHED] Time: 0s
    IConduct.DAL.Tests.DataAdapterTests.UpdateExecutionGroupInterfacesTest.CanUpdateExecutionGroupInterfaces [STARTING]
    IConduct.DAL.Tests.DataAdapterTests.UpdateExecutionGroupInterfacesTest.CanUpdateExecutionGroupInterfaces [SKIP]
      Must rewrite for ADO.NET
    IConduct.DAL.Tests.DataAdapterTests.UpdateExecutionGroupInterfacesTest.CanUpdateExecutionGroupInterfaces [FINISHED] Time: 0s
    IConduct.DAL.Tests.DataAdapterTests.ExtraSettingsTests.CanSelectNotExistingPreconfiguredCommand [FINISHED] Time: 0.9778912s
    IConduct.DAL.Tests.DataAdapterTests.InterfacesTests.IsAllowRunOnApiForExistingInterface [FINISHED] Time: 0.9783712s
    IConduct.DAL.Tests.DataAdapterTests.ExtraSettingsTests.CanSelectNotExisting [STARTING]
    IConduct.DAL.Tests.DataAdapterTests.InterfacesTests.IsAllowRunOnApiForNonExistingInterface [STARTING]
    IConduct.DAL.Tests.DataAdapterTests.ExtraSettingsTests.CanSelectNotExisting [FINISHED] Time: 0.0059887s
    IConduct.DAL.Tests.DataAdapterTests.ExtraSettingsTests.CanSelectExistingPreconfiguredCommand [STARTING]
    IConduct.DAL.Tests.DataAdapterTests.InterfacesTests.IsAllowRunOnApiForNonExistingInterface [FINISHED] Time: 0.0061867s
    IConduct.DAL.Tests.DataAdapterTests.ExtraSettingsTests.CanSelectExistingPreconfiguredCommand [FINISHED] Time: 0.0060921s
    **IConduct.DAL.Tests.DataAdapterTests.ExtraSettingsTests.CanSelectExisting [STARTING]
    IConduct.DAL.Tests.DataAdapterTests.ExtraSettingsTests.CanSelectExisting [FINISHED] Time: 0.0014762s**
  Finished:    IConduct.DAL.Tests
=== TEST EXECUTION SUMMARY ===
   IConduct.DAL.Tests  Total: 10, Errors: 0, Failed: 0, Skipped: 4, Time: 61.303s

According to this output my test was covered. But when I view the XML file 

I see 
<FullName>IConduct.DAL.Tests.DataAdapterTests.ExtraSettingsTests</FullName>
          <Methods>
            <Method visited="false" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" crapScore="2" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="4" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" maxCrapScore="2" minCrapScore="2" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="1" />
              <MetadataToken>100663299</MetadataToken>
              <Name>System.Void IConduct.DAL.Tests.DataAdapterTests.ExtraSettingsTests::CanSelectExisting()</Name>
              <FileRef uid="1075" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="15295" ordinal="0" offset="0" sl="18" sc="13" el="18" ec="87" bec="0" bev="0" fileid="1075" />
                <SequencePoint vc="0" uspid="15296" ordinal="1" offset="11" sl="21" sc="13" el="21" ec="108" bec="0" bev="0" fileid="1075" />
                <SequencePoint vc="0" uspid="15297" ordinal="2" offset="25" sl="24" sc="13" el="24" ec="36" bec="0" bev="0" fileid="1075" />
                <SequencePoint vc="0" uspid="15298" ordinal="3" offset="31" sl="25" sc="9" el="25" ec="10" bec="0" bev="0" fileid="1075" />
              </SequencePoints>
              <BranchPoints />

And when I convert it with ReportGenerator:
**dotnet   C:\agent\_work\_tasks\reportgenerator_be803a55-9253-4895-a525-be570d86f161\4.8.7\tools\netcoreapp2.1\ReportGenerator.dll -reports:C:\agent\_work\3\s\Coverage\Dal.Tests.xml -targetdir:C:\tools\CoverageSummary -reporttypes:HtmlInline_AzurePipelines;Cobertura**

I get 0 line coverage
![image](https://user-images.githubusercontent.com/2535935/110244474-84204b00-7f67-11eb-927a-81252ae1c33e.png)

![image](https://user-images.githubusercontent.com/2535935/110244443-5a672400-7f67-11eb-96aa-02e9804f2e1f.png)

I also tried to remove -oldstyle as I found in google. It didn't help

Please advice

**Comment by sawilde** [comment]
responding in discussions
