### ISSUE TITLE
Cannot compile an run the opencover code through command line and visual studio

### ISSUE THREAD

**Issue by namratachaudhar** [OpenCover/opencover#1022]
**Support requests** should initially be raised on [GitHub discussions](https://github.com/OpenCover/opencover/discussions) 
Can you tell me the steps to how to run the opencover code through visual studio. I was trying to build it through visual studio and the in opencover/bin/debug a opencover console is generated and i run my application project through command line which is 
OpenCover.Console.exe "-target:X:\Container\Bin\Assemblies\Debug\somtest.exe" " searchdirs:X:\Container\Bin\Assemblies\Debug\" -register:user

Please help with how to compile the opencover code and make use of it.

**Comment by sawilde** [comment]
Instructions are in the readme.md

However you do not need to compile opencover to use it - you can download from GitHub (installer, zip) and also via nuget and chocolatey
