### ISSUE TITLE
Very poor performance (1500x overhead or more)

### ISSUE THREAD

**Issue by pkrukp** [OpenCover/opencover#1035]
### My Framework

- [x] .NET 4.7.2

### My Environment

- [x] Windows 10

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### Describe the bug

I'm collecting coverage from a small application that compresses files in a folder. There is a very big performance overhead when running the application under OpenCover. 

compressed | small file | big file
-|------------|---------
without OpenCover | 51 ms | 67 ms
with OpenCover | 1092 ms | 100489 ms

So it's:
* 21x slower for when compressing "small file" (10 bytes files)
* 1499x slower when compressing "big file" (1 MB file)

I tried 10 MB file too, where without OpenCover it took 160ms to compress, but with OpenCover I waited for a long time and it didn't finish - so I suppose the overhead is even bigger than 1500x in that case.

It does not feel correct. Even if profiling added new call for each instruction, it does not seem reasonable to expect such big performance degradation in my opinion? It makes OpenCover basically unusable...

Looking at result.xml it seems to exclude system assemblies and only instrument 2 assemblies (the driver "program" and the DotNetZip dll from nuget [that's what I want]).

What is your opinion on this?

If this is expected, is there a way to improve performance?

### Steps to reproduce the problem:

Attaching zip with the application from which I tried collecting coverage (outputreader.sln), input files (input_small, input_big), example batch file to run test (runTest.bat), my results.xml

How to use:
1. build the outputreader.sln
2. unpack opencover to opencover.4.7.1204 folder (or update paths in runTest.bat)
3. execute runTest.bat

[outputreader.zip](https://github.com/OpenCover/opencover/files/6617085/outputreader.zip)

### Example output

In my case it produced following output:

```
C:\Users\pkruk\source\repos\outputreader>"outputreader\bin\Debug\outputreader.exe" output.zip input_small
Adding file: input_small\small.txt
Saving output.zip...
Done.
Elapsed time: 51 ms

C:\Users\pkruk\source\repos\outputreader>"outputreader\bin\Debug\outputreader.exe" output.zip input_big
Adding file: input_big\binary_file_1MB
Saving output.zip...
Done.
Elapsed time: 67 ms


C:\Users\pkruk\source\repos\outputreader>"opencover.4.7.1204\OpenCover.Console.exe" "-target:outputreader\bin\Debug\outputreader.exe" "-targetargs:output.zip input_small"
Launching OpenCover 4.7.1204.0
Executing: C:\Users\pkruk\source\repos\outputreader\outputreader\bin\Debug\outputreader.exe
Adding file: input_small\small.txt
Saving output.zip...
Done.
Elapsed time: 1092 ms
Committing...
Visited Classes 19 of 79 (24.05)
Visited Methods 192 of 1256 (15.29)
Visited Points 1430 of 10581 (13.51)
Visited Branches 653 of 6206 (10.52)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 19 of 81 (23.46)
Alternative Visited Methods 192 of 1296 (14.81)

C:\Users\pkruk\source\repos\outputreader>"opencover.4.7.1204\OpenCover.Console.exe" "-target:outputreader\bin\Debug\outputreader.exe" "-targetargs:output.zip input_big"
Launching OpenCover 4.7.1204.0
Executing: C:\Users\pkruk\source\repos\outputreader\outputreader\bin\Debug\outputreader.exe
Adding file: input_big\binary_file_1MB
Saving output.zip...
Done.
Elapsed time: 100489 ms
Committing...
Visited Classes 20 of 79 (25.32)
Visited Methods 211 of 1256 (16.8)
Visited Points 1692 of 10581 (15.99)
Visited Branches 815 of 6206 (13.13)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 20 of 81 (24.69)
Alternative Visited Methods 211 of 1296 (16.28)
```

**Comment by pkrukp** [comment]
Looking at the results.xml it seems OpenCover counts the number of times each sequence point was covered (the "vc" in "SequencePoint").

If my guess is correct, I think that could be the reason for poor performance...

Is there a way to disable it? For example if I'm only interested in line and branch coverage, without counting how many times each line or branch was covered...

Or maybe only disable counting of number of times given sequence point was covered, although not sure if that would improve a lot.

**Comment by sawilde** [comment]
The only options available to you are  

1.  use the `-threshold` switch eg `-threshold:1`
2. exclude the code in question using an attribute eg see `-excludebyattribute:`

**Comment by pkrukp** [comment]
Sorry for delay. Just wanted to confirm that -threshold improved the performance tremendously. I wonder, maybe it would be better if it was the default... 

I also apologize for missing "-threshold" in documentation (in fact I saw it, but somehow I assumed/understood that it changes threshold for coverage, e.g. 80% coverage as minimum...)

New measurement with "-threshold:1"

compressed | 10 B file | 1 MB file | 10 MB file
-|------------|---------|-------------
without OpenCover | 54 ms | 70 ms | 170 ms
with OpenCover | 1040 ms |  1180 ms | 2240 ms
% | 1925 % | 1671 % | 1317 %

**Comment by sawilde** [comment]
If we made it default now it would impact those that are expecting the original behaviour
