### ISSUE TITLE
OpenCover v4.7.1221 reports almost zero coverage on a large net40 application

### ISSUE THREAD

**Issue by psmacchia** [OpenCover/opencover#1047]
I tried OpenCover v4.7.1221 to run tests on the NDepend code base but it doesn't work. Until now we used an older version of NCover that worked fine. But now we are moving most of our non-UI code to `netstandard2.0` and `net50`, and other code is moved from `net40` to `net472` hence we need another way to cover out tests.

I first reported the problem on the version of NDepend _under-development_ with `netstandard2.0,` `net50` and `net472` assemblies. Then I realized that the problem also occurs on the version in production with mostly `net40` code. So better focus on this version to eliminate the potential source of problems that are `netstandard2.0,` `net50` and `net472`.

Here are assemblies under coverage with their target framework versions, all compiled to PDB full with PDB file side-by-side.

![image](https://user-images.githubusercontent.com/511445/125946306-efda1c94-b1e8-48ba-bf1c-b0ae85a344fd.png)

-----------------------------------

The command line is:

`C:\My\NDepend\Tests\OnOpenCover\4.7.1221>OpenCover.Console.exe -target:C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe  -output:C:\temp\Now\OC.xml -targetdir:C:\My\NDepend\2021.1.0\bin\Debug -searchdirs:C\My\NDepend\2021.1.0\bin\Debug\Lib -log:All -register:Path64`

To eliminate the potential source of problem that are NUnit and NUnit3.Console.exe I just cover the starting of the executable **VisualNDepend.exe** and then close it manually. Here is the screenshot of the console:

![image](https://user-images.githubusercontent.com/511445/125949721-6dd45c95-5037-435f-b034-aa5329d5a60a.png)

Very few lines get covered, only 97. Here is the result [when importing the OpenCover coverage result in NDepend](https://www.ndepend.com/docs/code-coverage#OpenCoverFile):

![image](https://user-images.githubusercontent.com/511445/125947159-d91b1f74-7748-49a6-9cf8-b3ff384a4676.png)

Even worse, only NDepend.UI.dll and NDepend.API.dll are taken account by OpenCover. Here is [the treemap view](https://www.ndepend.com/docs/treemap-visualization-of-code-metrics#Coverage) of the coverage.

![image](https://user-images.githubusercontent.com/511445/125947477-29f5cf93-76d4-4efa-aecf-f7b7899e1725.png)

-------------------
Then I run VisualNDepend.exe monitored with JetBrains DotCover and this time I obtain 12.424 lines of code covered.

![image](https://user-images.githubusercontent.com/511445/125947726-15a4b69b-0647-4cbd-8fc2-54df66c12cb3.png)

Here is the same treemap view of the DotCover coverage. Code covered is in green and code not covered is in red.

![image](https://user-images.githubusercontent.com/511445/125948410-e59b5904-1881-4a8a-8712-6b4fbee41091.png)

----------------------------------------------

The only special point that could disturb OpenCover is that .exe assemblies are in `C:\My\NDepend\2021.1.0\bin\Debug` and .dll assemblies are in the sub-directory `.\Lib` this is why in the command line I added the argument `-searchdirs:C\My\NDepend\2021.1.0\bin\Debug\Lib`.

Any help in making OpenCover work in our scenario would be highly appreciated.

**Comment by sawilde** [comment]
Hi @psmacchia, in the output xml file does it show the other assemblies and if so does it give a reason as to why they are skipped?

**Comment by psmacchia** [comment]
Hi @sawilde other assemblies are missing in the output xml. 

For example _NDepend.API.dll_ and _NDepend.UI.dll_ are taken account by OpenCover but with zero covered line but _NDepend.Core.dll_ is not taken account at all (as shown in the first treemap screenshot above). In the output xml I can find the string _"NDepend.UI.dll"_ but not _"NDepend.Core.dll"_ (screenshot below). Same for other assemblies not taken account like _"NDepend.Platform.DotNet.dll"_ or _"NDepend.Analysis.dll"_, there are not mentioned in the xml output.

_NDepend.API.dll_, _NDepend.UI.dll_, _NDepend.Core.dll_, _NDepend.Platform.DotNet.dll_, _NDepend.Analysis.dll_ are all stored in the same directory with their PDB full file, they are all net40. What could provoke a different processing with no reported error?

I also search for all occurrences of _"<Module "_ in the output xml and found 2x _"skippedDueTo="Filter""_ for _mscorlib.dll_ and _System.dll_. There is no _"<Module "_ occurrence related to an error.

![image](https://user-images.githubusercontent.com/511445/126297846-de0859ed-c0bf-4943-a21b-b68ff31e60b7.png)

**Comment by sawilde** [comment]
Odd - if they are not being recorded then it would indicate that the profiler is not seeing the assemblies being loaded by the runtime. Are you using multiple processes? If so, are the child processes using the same environment variables as the parent process that was started by OpenCover for the profiler to track?

**Comment by psmacchia** [comment]
There is a single proces and single AppDomain involved. _VisualNDepend.exe_ is in its root dir and .dll assemblies are in the child directory _.\Lib_. 

We use an _AssemblyResolver_ class to resolve child assembly based on _AppDomain.CurrentDomain.AssemblyResolve += s_AssemblyResolver.AssemblyResolveHandler_ and _Assembly.LoadFrom(asmFilePath)_. 

I though it could be the culprit but no. In the GIF below I disabled _AssemblyResolveHandler_ registration and use an App.Config file instead. The .dll assemblies are loaded _naturally_ by the CLR when it JIT compiles _MainSub()_. 

I also tried copy _NDepend.Core.dll_ in the root dir. This makes crash the application but before crashing _NDepend.Core.dll_ is effectively loaded by the CLR from the root dir. Even in that scenario OpenCover doesn't report any _<Module>_ tag for _NDepend.Core.dll_.

Is there anything more that I could try to identify what makes OpenCover blind? 

![VisualNDependStartup](https://user-images.githubusercontent.com/511445/126451937-4fc3cf61-5134-42a7-9a27-9e214b364d7f.gif)

**Comment by sawilde** [comment]
At the moment I am at a loss, you could try running debugview and see what runtime logging is being produced it may provide additional hints.

**Comment by psmacchia** [comment]
I guess you refer to this DebugView?  https://docs.microsoft.com/en-us/sysinternals/downloads/debugview
Just started holiday, will come back on this thread asap in August

**Comment by sawilde** [comment]
Yes 

no worries - enjoy your break.

**Comment by psmacchia** [comment]
Hi Shawn, I just tried DebugView on the exact same command line...

`C:\My\NDepend\Tests\OnOpenCover\4.7.1221>OpenCover.Console.exe -target:C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe -output:C:\temp\Now\OC.xml -targetdir:C:\My\NDepend\2021.1.0\bin\Debug -searchdirs:C\My\NDepend\2021.1.0\bin\Debug\Lib -log:All -register:Path64`

...and here are all the logs (below). 

There is no mention of not covered assemblies loading failure (`NDepend.Core.dll` or `NDepend.Platform.DotNet.dll`) apart maybe log number 31 
`00000031	11.09382248	[30636] OpenCover: (Profiler) ProfilerCommunication::RequestInformation(...) => Communication (Chat channel - TrackAssembly) with host has failed (0x102, 10000)	`

`(...)` represents the exact same logs repeated again and again with different method addresses

```
00000001	0.00000000	[30636] OpenCover: (Profiler)     ::Initialize(...) => CLSID == {1542C21D-80C3-45E6-A56C-A9C1E4BEB7B8}	
00000002	0.00022550	[30636] OpenCover: (Profiler)     ::Initialize(...) => EXE = C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe	
00000003	0.00031920	[30636] OpenCover: (Profiler)     ::Initialize(...) => PROFILER = C:\My\NDepend\Tests\OnOpenCover\4.7.1221\x64\OpenCover.Profiler.dll	
00000004	0.00044720	[30636] OpenCover: (Profiler)     ::Initialize(...) => key = 93EBF9D	
00000005	0.00055270	[30636] OpenCover: (Profiler) File Version: 4.7.1221.0	
00000006	0.00055270	[30636] 	
00000007	0.00736380	[30636] OpenCover: (Profiler) ProfilerCommunication::Initialise(...) => Initialised results interface => 93EBF9D1	
00000008	0.00744920	[30636] OpenCover: (Profiler) ::Initialize - Done!	
00000009	0.01928730	[30712] OpenCover: (Host) Starting Process Block => 1	
00000010	0.01971570	[30636] OpenCover: (Profiler) ::ModuleLoadFinished(...) => Adding methods to mscorlib...	
00000011	0.02032270	[30712] OpenCover: (Host) Started Process Block => 1	
00000012	0.02659340	[30636] OpenCover: (Profiler) ::ModuleLoadFinished(...) => Added methods to mscorlib	
00000013	0.04795510	[30636] OpenCover: (Profiler) cuckoo nest => mscorlib	
00000014	0.27950171	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6b74b80, ...) => 100663299, 7ffba6b74148 => C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe	
00000015	0.28651190	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6b74c30, ...) => 100663300, 7ffba6b74148 => C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe	
00000016	0.31478351	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6b74b60, ...) => 100663297, 7ffba6b74148 => C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe	
00000017	0.31543270	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6e65e68, ...) => 100663302, 7ffba6b74148 => C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe	
00000018	0.38521811	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6b74c40, ...) => 100663301, 7ffba6b74148 => C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe	
00000019	0.95889682	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6e674e8, ...) => 100663815, 7ffba6e660b0 => C:\My\NDepend\2021.1.0\bin\Debug\lib\NDepend.API.dll	
00000020	0.95962793	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6e67930, ...) => 100663308, 7ffba6b74148 => C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe	
00000021	0.95993870	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6e67a10, ...) => 100663817, 7ffba6e660b0 => C:\My\NDepend\2021.1.0\bin\Debug\lib\NDepend.API.dll	
00000022	0.96036160	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6e67b60, ...) => 100663316, 7ffba6b74148 => C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe	
00000023	0.96074867	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6e67b80, ...) => 100663318, 7ffba6b74148 => C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe	
00000024	0.96488881	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6b74b70, ...) => 100663298, 7ffba6b74148 => C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe	
00000025	2.93486476	[11936] Client Verbose: 0 : 	
00000026	2.93509841	[11936] Common model for csharp intellisense-members is cached. 	
00000027	2.93559170	[11936] Client Verbose: 0 : 	
00000028	2.93604469	[11936] Attempting to get team models for csharp intellisense-members at C:\My\NDepend\7.Current\. 	
00000029	2.98756409	[11936] Client Verbose: 0 : 	
00000030	2.98766351	[11936] The path C:\My\NDepend\7.Current\ does not belong to a Git repository, and cannot have any team models attached to it. 	
00000031	11.09382248	[30636] OpenCover: (Profiler) ProfilerCommunication::RequestInformation(...) => Communication (Chat channel - TrackAssembly) with host has failed (0x102, 10000)	
00000032	11.35715294	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba704cde8, ...) => 100664119, 7ffba6e660b0 => C:\My\NDepend\2021.1.0\bin\Debug\lib\NDepend.API.dll	
00000033	11.52710533	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6e67638, ...) => 100663827, 7ffba6e660b0 => C:\My\NDepend\2021.1.0\bin\Debug\lib\NDepend.API.dll	
00000034	11.54224014	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7260f90, ...) => 100663819, 7ffba6e660b0 => C:\My\NDepend\2021.1.0\bin\Debug\lib\NDepend.API.dll

(...) 

00000148	14.36887836	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6e674f8, ...) => 100663816, 7ffba6e660b0 => C:\My\NDepend\2021.1.0\bin\Debug\lib\NDepend.API.dll	
00000149	18.31071091	[30636] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7276c30, ...) => 100663455, 7ffba6e660b0 => C:\My\NDepend\2021.1.0\bin\Debug\lib\NDepend.API.dll	
00000150	18.44201279	[30636] OpenCover: (Profiler) ::Shutdown - Starting	
00000151	18.44203949	[30636] OpenCover: (Profiler) ::Shutdown - Nothing left to do but return S_OK(C:\My\NDepend\2021.1.0\bin\Debug\VisualNDepend.exe)	
00000152	18.53661346	[30712] OpenCover: (Host) Waiting for 1 processes to close	
00000153	19.03981209	[30712] OpenCover: (Host) Waiting for 1 processes to close	

(...) 
	
00000180	32.74534988	[30712] OpenCover: (Host) Waiting for 1 processes to close	
00000181	33.25709534	[30712] OpenCover: (Host) Waiting for 1 processes to close	
00000182	165.45027161	[8488] Client Verbose: 0 : 	
00000183	165.45043945	[8488] Common model for csharp intellisense-members is cached. 	
00000184	165.45091248	[8488] Client Verbose: 0 : 	
00000185	165.45106506	[8488] Attempting to get team models for csharp intellisense-members at C:\My\NDepend\7.Current\. 	
00000186	165.49896240	[8488] Client Verbose: 0 : 	
00000187	165.49899292	[8488] The path C:\My\NDepend\7.Current\ does not belong to a Git repository, and cannot have any team models attached to it. 	
```

**Comment by sawilde** [comment]
There is a switch `-communicationtimeout:` where you can change the default timeout from 10s (10000ms) to a max of 60s (60000ms) - I am going to say that the assemblies are really big and so will take more processing than normal

**Comment by psmacchia** [comment]
So `-communicationtimeout:60000` indeed help but I even needed to put it to 10 minutes (600.000). But then running even the fastest tests is extremely slow (1682 seconds instead of 13 seconds, 144 slower!). Below screenshots and logs

With OpenCover
![image](https://user-images.githubusercontent.com/511445/128488719-e9abc174-a26b-4307-b46a-b8ae3c638e9c.png)

Without OpenCover
![image](https://user-images.githubusercontent.com/511445/128489057-49b6128f-aa7f-4b6c-95fd-653512a277c6.png)

```
00000001	0.00000000	[27432] OpenCover: (Profiler)     ::Initialize(...) => CLSID == {1542C21D-80C3-45E6-A56C-A9C1E4BEB7B8}	
00000002	0.00047700	[27432] OpenCover: (Profiler)     ::Initialize(...) => EXE = C:\My\NDepend\7.Current\bin\NDepend.Test.All.exe	
00000003	0.00053250	[27432] OpenCover: (Profiler)     ::Initialize(...) => PROFILER = C:\My\NDepend\Tests\OnOpenCover\4.7.1221\x64\OpenCover.Profiler.dll	
00000004	0.00056930	[27432] OpenCover: (Profiler)     ::Initialize(...) => key = 7A8DC860	
00000005	0.00078940	[27432] OpenCover: (Profiler) File Version: 4.7.1221.0	
00000006	0.00078940	[27432] 	
00000007	0.00763440	[27432] OpenCover: (Profiler) ProfilerCommunication::Initialise(...) => Initialised results interface => 7A8DC8601	
00000008	0.00771020	[27432] OpenCover: (Profiler) ::Initialize - Done!	
00000009	0.01805810	[29920] OpenCover: (Host) Starting Process Block => 1	
00000010	0.01885050	[27432] OpenCover: (Profiler) ::ModuleLoadFinished(...) => Adding methods to mscorlib...	
00000011	0.01922770	[29920] OpenCover: (Host) Started Process Block => 1	
00000012	0.02630220	[27432] OpenCover: (Profiler) ::ModuleLoadFinished(...) => Added methods to mscorlib	
00000013	0.04758990	[27432] OpenCover: (Profiler) cuckoo nest => mscorlib	
00000014	0.31397060	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6b84b48, ...) => 100663302, 7ffba6b84148 => C:\My\NDepend\7.Current\bin\NDepend.Test.All.exe	
00000015	64.18341827	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba6b8afd8, ...) => 100663301, 7ffba6b84148 => C:\My\NDepend\7.Current\bin\NDepend.Test.All.exe	
00000016	66.36228180	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba75366a8, ...) => 100666420, 7ffba75346a8 => C:\My\NDepend\7.Current\bin\nunit.framework.dll	
00000017	66.36327362	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7536568, ...) => 100663318, 7ffba75346a8 => C:\My\NDepend\7.Current\bin\nunit.framework.dll	
(...)
00000631	110.16654205	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7ca7bf8, ...) => 100666918, 7ffba75346a8 => C:\My\NDepend\7.Current\bin\nunit.framework.dll	
00000632	110.16667175	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7ad3ad0, ...) => 100664057, 7ffba75346a8 => C:\My\NDepend\7.Current\bin\nunit.framework.dll	
00000633	110.16714478	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7ca1c00, ...) => 100665396, 7ffba75346a8 => C:\My\NDepend\7.Current\bin\nunit.framework.dll	
00000634	110.16744995	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7ad8e98, ...) => 100664438, 7ffba75346a8 => C:\My\NDepend\7.Current\bin\nunit.framework.dll	
00000635	110.16766357	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7ad8f18, ...) => 100664448, 7ffba75346a8 => C:\My\NDepend\7.Current\bin\nunit.framework.dll	
00000636	110.16790009	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7ad43d8, ...) => 100664604, 7ffba75346a8 => C:\My\NDepend\7.Current\bin\nunit.framework.dll	
00000637	110.16847229	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba784c128, ...) => 100663613, 7ffba77b13c8 => C:\My\NDepend\7.Current\bin\NDepend.Test.Unit.dll	
00000638	110.16943359	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7ca7cd0, ...) => 100669465, 7ffba7940020 => C:\My\NDepend\7.Current\bin\Debug\Lib\NDepend.UI.dll	
00000639	110.17127991	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba79cdd88, ...) => 100666932, 7ffba77b13c8 => C:\My\NDepend\7.Current\bin\NDepend.Test.Unit.dll	
00000640	164.81146240	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7cab190, ...) => 100663318, 7ffba7ca9348 => C:\My\NDepend\7.Current\bin\Debug\Lib\NDepend.Platform.DotNet.dll	
00000641	164.81239319	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7cab180, ...) => 100663317, 7ffba7ca9348 => C:\My\NDepend\7.Current\bin\Debug\Lib\NDepend.Platform.DotNet.dll	
00000642	164.81535339	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7de36c8, ...) => 100664805, 7ffba77bcff8 => C:\My\NDepend\7.Current\bin\Debug\Lib\NDepend.Core.dll	
00000643	164.82337952	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7de5a18, ...) => 100663321, 7ffba790f188 => C:\My\NDepend\7.Current\bin\Debug\Lib\NDepend.Platform.DotNet.Winforms.dll	
00000644	164.82456970	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7de5c70, ...) => 100663348, 7ffba790f188 => C:\My\NDepend\7.Current\bin\Debug\Lib\NDepend.Platform.DotNet.Winforms.dll	
00000645	164.82489014	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7de5c20, ...) => 100663343, 7ffba790f188 => C:\My\NDepend\7.Current\bin\Debug\Lib\NDepend.Platform.DotNet.Winforms.dll	
00000646	164.93898010	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7de76d8, ...) => 100671596, 7ffba7940020 => C:\My\NDepend\7.Current\bin\Debug\Lib\NDepend.UI.dll	
00000647	164.93931580	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7de5c90, ...) => 100663350, 7ffba790f188 => C:\My\NDepend\7.Current\bin\Debug\Lib\NDepend.Platform.DotNet.Winforms.dll	
00000648	164.93983459	[27432] OpenCover: (Profiler) ::JITCompilationStarted(7ffba7de5cb0, ...) => 100663352, 7ffba790f188 => C:\My\NDepend\7.Current\bin\Debug\Lib\NDepend.Platform.DotNet.Winforms.dll
```

**Comment by sawilde** [comment]
The profiler injects extra IL for every sequence point, and to do so has to disable any optimisation so this will heavily impact on performance. You could also try the `-oldschool` switch which injects less IL but will fail if you have any assembly security in place (it isn't popular nowadays and I think scrapped in .net core but YMMV)

**Comment by psmacchia** [comment]
Thanks Shaun, unfortunately with the `-oldstyle` switch I still obtain around _x140_ slower which is not practicable for us. OpenCover is popular and I am pretty sure that other users are experimenting more acceptable slow down rate. With NCover it was only 20% overhead (x1.2). Something in our code or tests must be slowing down OpenCover.

**Comment by sawilde** [comment]
@psmacchia the final switch I would look at is `-threshold` ie how many times is a point counted. If you just want to record a hit and not care about how many times it was hit, then set this to 1 eg `-threshold:1`.

**Comment by psmacchia** [comment]
Thanks Shaun, it helped get faster, now the 13.4 seconds to pass the 4000 unit tests became 114 seconds (8.5x slower). Unfortunately this is still way too slow for a practical usage. With NCover we were used to 1.2x slower, a 20% overhead only.

On a technical side I think NCover used to host the CLR and get events from it instead of injecting IL (not completely sure)

**Comment by sawilde** [comment]
@psmacchia no worries, I am sure they have managed to make their profiler integration more performant - more time and resources to commit to it.

**Comment by psmacchia** [comment]
Thanks Shaun for your help on this, it might be worth capitalizing on this thread and explain on the documentation the various switches we investigated to make OpenCover work on a large code base  `-log:All -communicationtimeout:600000 -oldstyle -threshold:1`  + DebugView usage

**Comment by sawilde** [comment]
They are in the Usage document but I have called them out into a separate wiki

https://github.com/OpenCover/opencover/wiki/Addressing-performance-problems-with-OpenCover

**Comment by psmacchia** [comment]
Great!
