### ISSUE TITLE
how do i "install" opencover?

### ISSUE THREAD

**Issue by AndyAtTogether** [OpenCover/opencover#112]
this may seem like a slightly lame question but i'm having difficulty getting to the point where i have an opencover.console.exe file to use

I've cloned the repo (and also downloaded the zip file) and i've build the code using Build.bat

the only opencover.console.exe file i can find is at   sawilde-opencover-4b4e9fa\main\OpenCover.Console\obj\Debug\opencover.console.exe

now when i run this i get an exception regarding opencover.framework

I can't help feeling that i'm missing something obvious - can someone point me in the right direction?

**Comment by equiman** [comment]
Download MSI/ZIP are located: https://github.com/OpenCover/opencover/releases
