### ISSUE TITLE
Quotes are not working for target or targetargs

### ISSUE THREAD

**Issue by marcofranssen** [OpenCover/opencover#140]
I'm using the following line in my batch file

`"%OPENC%" -register:user -target:"%mspecrunner%" -targetargs:"%unittests%" %FILTER% -output:"%RPT_DIR%\UnitTests\opencovertests.xml"`

However I wrapped all my things in quotes (") I get the following error.

> Missing Assembly: D:\Users\A500535\Documents\Projecten\Blue
> Committing...
> No results - no assemblies that matched the supplied filter were instrumented
>     this could be due to missing PDBs for the assemblies that match the filter
>     please review the output file and refer to the Usage guide (Usage.rtf)`

So my directory gets cut off here  D:\Users\A500535\Documents\Projecten\Blue ..................

I can't find why it does this. I get at least an opencovertests.xml in my output so it seems the target or target args are failing.

When running my msspec tests with the same variables everything goes ok.

**Comment by summea** [comment]
I ran into this "spaces in directory path" issue when using **PowerShell**:

`PS C:\> C:\Users\username\OpenCover\OpenCover.Console.exe "-target:C:\Users\username\NUnit.Console-3.6.1\nunit3-console.exe" "-targetargs:\"C:\Users\username\Documents\Visual Studio 2015\Projects\RabbitMQ\RabbitMQTests\bin\Debug\RabbitMQTests.dll\"" -output:coverage.xml -register:user`

> Incorrect Arguments: The argument 'C:\Users\username\Documents\Visual' is not recognised

But [this other approach](https://github.com/OpenCover/opencover/issues/140#issuecomment-11803434) seemed to work when using a plain **Command Prompt**:

`set nunitpath=C:\Users\username\Documents\Visual Studio 2015\Projects\RabbitMQ\RabbitMQTests\bin\Debug`

`C:\Users\username\OpenCover\OpenCover.Console.exe "-target:C:\Users\username\NUnit.Console-3.6.1\nunit3-console.exe" "-targetargs:\"%nunitpath%\"\RabbitMQTests.dll" -output:coverage.xml -register:user`

**Comment by sawilde** [comment]
@summea we have a section in the wiki about spaces - https://github.com/OpenCover/opencover/wiki/Usage#notes-on-spaces-in-arguments

**Comment by summea** [comment]
@sawilde Thank you for your reply! I did read that section on the wiki page, but the only combination that seemed to work in my case was the approach described in my last comment. As you can see in my PowerShell attempt from earlier, the quotes were indeed surrounding the entire `"-targetargs: ..."` option, as the wiki page seems to suggest, as well as having inner quotes around the path to the .dll — but if you see a reason why this may have been happening from my earlier example, please let me know!

**Comment by smithmw** [comment]
@sawilde I've experienced the same issue as @summea here: https://github.com/OpenCover/opencover/issues/140#issuecomment-289582451

As in, I was unable to get double quotes needed within **targetArgs** to work properly using powershell by using the technique of escaped double quotes with a backslash.  E.g. Using \" where a " is needed.
E.g.:

> "-targetArgs:\"C:\My Path With Spaces\Test.dll\" /logger:trx"


The result is the following error:

> Incorrect Arguments: The argument `Source` is not recognised

Is there any workaround to get spaces to work properly in powershell or any other recommended workarounds?

**Comment by sawilde** [comment]
It looks like there is an argument named `-Source` and that is not an opencover argument 
I would need to see the whole command to even start to help
