### ISSUE TITLE
Support Coverage of Windows Store Applications on Windows 8

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#144]
If possible gather coverage of a running windows store application.

References:
http://blogs.msdn.com/b/davbr/archive/2013/01/09/writing-a-profiler-of-windows-store-apps.aspx
http://go.microsoft.com/fwlink/?LinkID=271485

**Comment by syeds-git** [comment]
Hi, does this mean that it does not support the Windows Phone 8.1 apps yet? If it does then can you please answer [this](http://stackoverflow.com/questions/30897009/opencover-missing-pdbs-exception) question? Thanks

**Comment by sawilde** [comment]
nope - the profiler will only run on windows OS as it uses native c++ and the profiler API - you can however profiler your libraries on windows if you use Portable Class Libraries and run your tests locally.

**Comment by uilquegb** [comment]
@syeds-git, did you do the code coverage with opencover?
I'm having the same issue.

**Comment by andresvettori** [comment]
I think support for Universal (Windows 10) Apps development would benefit a lot from support from a tool like this one. Currently VS2015 doesn't support calculating code coverage, although it does support unit tests for UWP Apps.
