### ISSUE TITLE
Setup OpenCover with IIS

### ISSUE THREAD

**Issue by DinohJ** [OpenCover/opencover#147]
Hi, 

I'm trying to setup OpenCover to profile assemblies running in IIS.
I can't find documentation on how to set up the console parameters.

e.g. I have some assemblies + .pdb files in 
C:\inetpub\wwwroot\MyWebSite\bin
which runs as a separate webapp.

I want to start coverage, run some tests on IIS (e.g. through the browser), and then stop coverage. Is this scenario possible?

can you provide any help on this?
regards,
Jerry

**Comment by hghanta** [comment]
Tried to profile IIS ON WIN 10 Machine. Basically not able to get the website working when using open cover( getting forbidden:18) any ideas?

**Comment by sawilde** [comment]
@hghanta please don't resurrect old 'closed' issues - please raise new ones and follow the instructions - thanks
