### ISSUE TITLE
OpenCover - No results in Jenkins builder system.

### ISSUE THREAD

**Issue by huynguyencc** [OpenCover/opencover#167]
Hi sawilde,
I created an console application C# (OpenCoverReport.exe) to execute this script:

OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\MSTest.exe" -targetargs:"/noisolation /testcontainer:D:\UnitTests.dll" -filter:"+[_]_" -output:"out\opencover-mstest.xml"

This console app works perfectly(fully code coverage result) when I run it directly.

When I integrate it in Jerkin to run this app through xml build file (ant) , I received the following result in Jerkin:

![opencover-2](https://f.cloud.github.com/assets/4004085/991287/73b4f45a-0959-11e3-9e9f-c00d35b38827.png)

My sample build xml file:
![opencover](https://f.cloud.github.com/assets/4004085/991254/ff10f97e-0957-11e3-9d12-131de38a5838.png)

Could you please help me review on this issue ?
Thanks.

**Comment by Shammah** [comment]
I was having the same problem, where using `-register:user` worked on my local PC, but not on our Jenkins build. Using `-register:path32` instead made it work. This switch however was undocumented, so it wasn't easy to find. Would be nice if this undocumented feature would be mentioned in the Usage docs. I'd do it myself, but I'm not entirely sure how this works, and why it works.

**Comment by sawilde** [comment]
@Shammah - https://github.com/OpenCover/opencover/wiki/Usage

**Comment by Shammah** [comment]
Ah, I see. Was looking only at https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf as it was apparently richer, according to the wiki documentation.

**Comment by sawilde** [comment]
> as it was apparently richer, according to the wiki documentation.

It usually is but things do get missed
