### ISSUE TITLE
OpenCover.Profiler.dll (x64) fails to register on Windows Server 2003 x64

### ISSUE THREAD

**Issue by rcook** [OpenCover/opencover#185]
I run the following command from a Windows command prompt:

```
regsvr32 /n /i:user x64\OpenCover.Profiler.dll"
```

This results in a dialog popping up:

```
Title: RegSvr32
Message: LoadLibrary("OpenCover.Profiler.dll") failed - The specified procedure could not be found.
```

The x86 version of OpenCover.Profiler.dll registers as expected. I've tried both versions of regsvr32 (`C:\WINDOWS\System32\regsvr32.exe` and `C:\WINDOWS\SysWOW64\regsvr32.exe`) and both fail. I ran Dependency Walker in "profiler" mode and it complains about `GetProcAddress` failing to load `ImmGetImeMenuItems` from imm32.dll. However, this same issue is reported when loading the x86 version, so this might not be relevant.

**Comment by timotei** [comment]
@rcook Have you managed to find the issue? I get the similar issue.

**Comment by rcook** [comment]
@timotei : It's been a couple of years since I worked on this project, so I don't remember where I ended up. Sorry!
