### ISSUE TITLE
Integration tests, IIS and Web Services

### ISSUE THREAD

**Issue by carpnick** [OpenCover/opencover#197]
Hello,

I have recently forked OpenCover.  I am lookiing at some of your nice features you build in.

 Thinks I would like to add naively:
--Native support for iIS applications.  Looking to see how we can attach to the w3wp process.
--WebService call to delineate the end of a test. WebApp/Site/Service tests are run on a different machine than the code coverage system.  So I will begin investigating adding a REST service, that remote test runners can call.  Idea here is you have native support to measure coverage per test, I would like the same functionality for integration tests that are run remotely.

For both of these,
Do you have any design documents of the architecture of OpenCover, or should I just dive in?  Also would you have any interest in bringing these features back into Main?

**Comment by thiagoalves** [comment]
@sawilde Do you have any news on this issue? If you have any news on it I would be happy to hear them from you. Thanks

**Comment by sawilde** [comment]
@thiagoalves - what issue, this one was closed as @carpnick was no longer pursuing it.

**Comment by thiagoalves** [comment]
@sawilde Since this happened more than one year ago, and many commits have been added to the code, I was wondering if the status of this issue is still the same

**Comment by sawilde** [comment]
We have the same support for IIS as we did a year ago by allowing coverage of a locally hosted IIS instance; it is however occasionally problematic and YMMV (your mileage may vary). 

Other users have provided [instructions](https://github.com/OpenCover/opencover/wiki/IIS-Support) that may help you.
