### ISSUE TITLE
OpenCover support of IIS

### ISSUE THREAD

**Issue by AndiVlad** [OpenCover/opencover#234]
Hi i'm trying to use OpenCover to detect the current coverage through automation tests of a WPF Clinet->WCF Server based application.

i've managed to start the program for the w3svc but i can't get it to detect any pdb files for one of the WCF based app servers (each app has its own app pool):
![apps](https://cloud.githubusercontent.com/assets/9350062/4899180/39c2e132-6419-11e4-9486-ca67f8572a19.jpg)
OPenCover was started with both registration switches and with the targetdir set to the application's root folder and dll/pdb folder, variances of OpenCover.Console.exe -service:byname -target:w3svc -output:coverage.xml -register:user

P.S. to get it to work with the LocalSystem account name i had to tweak the MachineQualifiedserviceAccountName method

```
    public static string MachineQualifiedServiceAccountName(string serviceName)
    {
        string serviceAccountName = GetServiceAccountName(serviceName);
        if (serviceAccountName.StartsWith(@".\"))
        {
            serviceAccountName = Environment.MachineName + serviceAccountName.Substring(1);
        }
        else if (serviceAccountName.ToLower().Contains("localsystem"))
        {
            serviceAccountName = "NT Authority\\SYSTEM";
        }
```

Any ideea on what am i doing wrong? is this suppose to work? 

Can't run w3wp in command line as it doesn't seem to open up https and those are the only allowed bindings  (and i couldn't how to do it). The command line won't work on a longer term/integration as the deployment & configurations are done automatically but at least it would show it works.

**Comment by tborg2793** [comment]
Hi so just to clarify, for IIS Support,  RunService method is being utilized in this instance or the RunProcess method?
