### ISSUE TITLE
Exclude methods from coverage

### ISSUE THREAD

**Issue by Jericho** [OpenCover/opencover#235]
Is there a way to indicate that a given method and/or class should be excluded from test coverage? If not, could we add an attribute like `[CodeCoverage(false)]`? 

Conceptually, this would be similar to Stylecop's `SuppressMessage` attribute that can be used to indicate that StyleCop should ignore the fact that a given method doesn't follow a rule. Something like: 
`[SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:FileMustHaveHeader", Justification = "Reviewed.")]`

By the way, one nice feature of the SuppressMessage attribute is that you can add a short justification which is a nice way to document why you are excluding a given rule.

There are a few reasons why I would like to be able to exclude some of my code:
- certain methods are private and cannot be tested (see #222 for discussion)
- I want to exclude concrete implementation of certain interfaces from code coverage
- some Linq extension methods are not unit testable (as far as I know). For instance:

``` C#
[DbFunction("Edm", "AddDays")]
public static DateTime? LinqAddDays(this DateTime time, int? value)
{
    return DbFunctions.AddDays(time, value);
}
```
- Some methods have environmental dependencies and cannot reliably be unit tested. The following snippet shows an example where code is dependent on the machine time zone and therefore will yield different result if run by someone in US Est versus someone in India:

``` c#
public static DateTime ConvertToUtc(this DateTime dateTime, string timeZone)
{
    return TimeZoneInfo.ConvertTime(dateTime, TimeZoneInfo.FindSystemTimeZoneById(timeZone), TimeZoneInfo.Utc);
}
```

For illustration purposes, let's assume a fictitious C# library where 40% of the code consists of un-testable code and let's also assume that you have written unit tests for all public methods. If you run OpenCover/ReportGenerator on this library, the resulting report will show that only 60% of the code is covered despite the fact that you have covered every line of code that could possibly be covered. What I'm trying to achieve is to exclude the 40% un-testable from the final report and to show 100% coverage.

Hopefully I'm making sense.

**Comment by surbhi05** [comment]
Hi, using excludebyattribute and [ExcludeFromCodeCoverage], i am able to exclude the code, but if a delegate or a ling is present in the excluded code, then those lines are not covered. Any suggestions?
