### ISSUE TITLE
FYI : Static analysis at commit 3ede247ad7 shows some minor issues

### ISSUE THREAD

**Issue by SteveGilham** [OpenCover/opencover#242]
I got a chance to do a static analysis run of a recent master; and setting aside the reports that are in tests, in system header files, are clearly false positives, or indicate that something has already gone horribly wrong (such as bad inputs) and all that could be done is emit more diagnostics as we terminate; we are left with the following:

* Access in ProfilerManager.cs to `MemoryManger._blocks` is not guarded by the lock used to guard all the other accesses (`GetBlocks` could take a predicate and return a reified list from a lock clause)
* `MemoryManager.Initialise()` could double-checked lock to consistently guard the initialised fields
* `ProfilerManager.StartProcessingThread()` could call `threadActivated.Dispose()` before exiting to release the system handle
* `ProfilerManager.RunProcess()` could call `queueMgmt.Dispose()` before exiting to release the system handle
* `ProfilerManager.RunProcess()` could call `environmentKeyRead.Dispose()` before exiting to release the system handle
* `CCodeCoverage::Initialize()` local `nCount` written but not read
* `Method::GetInstructionAtOffset(`5 args`)` last argument is always true (bitwise `&` with zero constant)
* `Method::InsertInstructionsAtOffset()` local `actualOffset` written but not read
* `Method::EndOfBranch` sets `next->m_jump` then checks `next` against `NULL`

and about half of those are primarily aesthetic.

**Comment by molnargab** [comment]
@SteveGilham, how would one reproduce these results? Is it a simple Visual Studio Code Analysis?

**Comment by SteveGilham** [comment]
No, this is a selection of the results from running Coverity over the code.

**Comment by sawilde** [comment]
I've actually registered for coverity and plan on adding the output to the build pipeline (which I was going to do as part of this card)

**Comment by sawilde** [comment]
Hi can anyone provide steps on coverity for me (saves reinventing the wheel)

I also see that appveyor have recently added coverity to their build servers so we can bootstrap on that as well.

**Comment by SteveGilham** [comment]
I just used the wizard to wrap a Visual Studio build.  Default settings
should suffice for c# code (though I switched up the inspection level to
high, which gives a lot of false positives).  The command line I haven't
touched.

**Comment by sawilde** [comment]
@SteveGilham  thanks - I'll give it a go - can't get the thing to download at the mo

**Comment by ddur** [comment]
>Hi can anyone provide steps on coverity for me (saves reinventing the wheel)
>I also see that appveyor have recently added coverity to their build servers so we can bootstrap on that as well.

@sawilde 

1) Login into Coverity via your GitHub account
2) Add project from GitHub, select primary and secondary language (C++/C#)
3) Download Coverity tools from [this page](https://scan.coverity.com/download?tab=cxx)
4) Unzip tools somewhere
5) run ```[path?]cov-build --dir cov-int build create-release```
6) run ```zip -r myproject.zip cov-int```
7) submit myproject.zip to Coverity
8) Change badge URL-s

Can be automated but Coverity imposes limitations to frequency for build submissions [Coverity FAQ](https://scan.coverity.com/faq). 
That's why AppVeyor build for Coverity should be scheduled. [Sample appveyor.yml](https://github.com/arkfps/smart-splash/blob/34ab7d398c8b1c824779b92cdd7175e27575a88b/appveyor.yml)

**Comment by SteveGilham** [comment]
Sparked by [this blog post on MSDN](http://blogs.msdn.com/b/visualstudioalm/archive/2015/09/29/quickstart-analyzing-net-projects-with-sonarqube-msbuild-or-visual-studio-online-and-third-party-analyzers-stylecop-resharper.aspx), I did some investigation of the SonarQube static analysis tool in the days running up to Christmas; and it gives a different slant on the subject to Coverity, and finds a different set of issues.

So of course I ran it against OpenCover as well, and the results (JSON format) for the version of master I pulled on the morning of the 24th are [attached here](https://github.com/OpenCover/opencover/files/79032/sonarqube.zip)  -- look down for "issues"

Most of them are cosmetic, but there are a few undisposed `IDisposeable`s amongst them.

**Comment by ddur** [comment]
![coveritystatus](https://cloud.githubusercontent.com/assets/3501612/12144119/f1652080-b485-11e5-909c-a55a25864411.png)

**Comment by sawilde** [comment]
It would be interesting to run sonarqube as part of the build but I think that should be a separate card
