### ISSUE TITLE
Report Generated by Visual Studio is different than the report generated from OpenCover+MSTest command

### ISSUE THREAD

**Issue by SunnyAgrawal** [OpenCover/opencover#251]
Hi

I am using Opencover to generate both the coverage and the test-result reports.But When i am feeding both the reports to the sonarqube the test-result is displaying properly but the coverage report is showing different values than the one generated by visual studio (coveragexml fille).

Note : When I am running unit test from Visual Studio the code coverage is coming 90% and when I am running using OpenCover the test result is coming 32%. I think the Visual studio uses vsTest.Console.exe to generate the report and i am using opencover + mstest to generate the report.

Also I have observed code coverage for test dll are showing more than the code coverage for the actual dll's for which the test cases are return.

Below is the command that i am using to generate the reports

"C:\Program Files (x86)\OpenCover\OpenCover.Console.exe" -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\MSTest.exe" -targetdir:"%1\Build" -targetargs:"/resultsfile:D:\RunTime_Reports\Test-Result.trx /testcontainer:Test.dll /runconfig:"\*\*\Local.testsettings"" -filter:+[\*]\* -output:D:\RunTime_Reports\coverage-report.xml

All the test are passing successfully and both the coverage and the test result files are getting generated.

Please help.

**Comment by SunnyAgrawal** [comment]
Hi

I will try this and will let you know.

One doubt : If I exclude the test dll using filter then in the coverage report only test dll coverage will be excluded rest other modules coverage will not change.
Please correct me if i am wrong.

**Comment by sawilde** [comment]
you are correct, you will need to exclude any assemblies that you do not wish to see in the report. First try including those that you do want and then exclude those you don't

**Comment by SunnyAgrawal** [comment]
Hi
i am excluding test dll from the sonar side.
My doubt is why visual studio reports shows a coverage of module to 90% while opencover reports shows coverage report to 32%.
Applying filter will only exclude or include the modules and will not increase the module coverage.
Please correct me if i am wrong.

My question is that whether the report generated by Visual studio are different from the one generated by Opencover Or i am missing some important agrument in the opencover command.

However i will try applying the filter and let you know the result.

**Comment by sawilde** [comment]
Since you haven't supplied me with the XL output from OpenCover I can't tell you exactly, I can only guess.

OpenCover will attempt to instrument every assembly that you load that has an associated PDB. 

you may also need to use the `-mergebyhash` option for OpenCover as MSTest usually copies assemblies under test to a different location, leaving the PDB behind. This is detailed in the [Usage](https://github.com/OpenCover/opencover/wiki/Usage) guide.

**Comment by SunnyAgrawal** [comment]
Hi 

Adding -mergebyhash argument solved my problem.
Thank you very much for the quick response.

**Comment by sawilde** [comment]
no worries - glad to have helped

**Comment by sarfraz17** [comment]
Hi,
  Initailly we were also facing the same issue but after using -mergebyhash it resolved but now we are facing different issue.
We have a gated build in tfs in which we will first run the msbuild which will build the msi and then trigger the opencover command to generate the report and then run the sonar analysis.
But when we are triggering through tfs the coverage is coming less and when we will manually run the opencover command the coverage is coming properly.

Please find the attached zip file containing both the coverage file.
- the one in not working folder is generated by tfs
- the other one manually.

Please suggest

**Comment by sarfraz17** [comment]
Oops
We are not able to attach the zip file pls suggest the alternative so that we can share the files with you.

**Comment by sawilde** [comment]
why not post them is a [gist](https://gist.github.com/)?

**Comment by sarfraz17** [comment]
Tried with no luck.

**Comment by sarfraz17** [comment]
Hi,
 Please let me know how can I send you the files for your reference.

**Comment by sawilde** [comment]
You can send them to shaun(_)wilde(@)hotmail(.)com

**Comment by sarfraz17** [comment]
Thanks Shaun. I have mailed you those 2 files, please review and let me know your suggestions.

**Comment by sawilde** [comment]
What filters are you using? I am seeing assemblies in the reports that are probably skewing the results.

If you use a tool like ReportGenerator you can use it to visualize the results.

e.g. `+[Tesco\*]\* -[\*Test\*]\*`

Also make sure you have PDBs available for all the assemblies you want coverage for (some appear to be missing.

Once you have ensured you are getting coverage only from the assemblies you want and no others should you start comparing.

Remember however that release and debug builds will also produce slightly different results due to compiler optimisations. This is why some tools like ReportGenerator convert the OpenCover output and change the coverage to lines of files covered.

**Comment by sawilde** [comment]
@sarfraz17 did the above response help - I looked at both files and provided my suggestion above. Try using ReportGenerator to visualize the results

**Comment by SunnyAgrawal** [comment]
Hi 

The PDB's are available but still in the coverage report it says PDB's are missing.
Any additional attribute we can use to fix this.

**Comment by sawilde** [comment]
The PDBs are probably not being copied to the location they are running from (but this is usually addressed by `-mergebyhash` as this is quite a common issue with mstest) or there is a mismatch between assembly and PDB (build/compilation issue). An alternative is to use `-targetdir` to locate PDB files, as described in the wiki, but I see you are already using it or were previously.

If you have a reproducible scenario I may be able to help more as I don't have a full picture what could be causing you issues.

**Comment by sarfraz17** [comment]
Hi Shaun,
       We tried the suggestion you have provided in one of the stackflow thread but giving an error message.Incorrect Arguments: The argument [*.Test]* is not recognised.

COmmand we are using: 
"C:\Program Files (x86)\OpenCover\OpenCover.Console.exe" -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\MSTest.exe" -targetdir:"D:\Builds\9\CustomerProfile\Main.CustomerProfile.CI\Sources\Build" -targetargs:"/resultsfile:D:\RunTime_Reports2\Test-Result.trx /testcontainer:Tesco.Com.CustomerProfile.Tests.Core.dll /testcontainer:CPSOracleRepository.Test.dll /testcontainer:CPSProvider.Tests.dll /testcontainer:CPSRepository.Test.dll /testcontainer:AutherizationHeader.Test.dll /runconfig:"D:\Builds\9\CustomerProfile\Main.CustomerProfile.CI\Sources\CustomerProfileProvider-v2.4\Local.testsettings"" -filter +[*]* -[*.Test.]* -mergebyhash -output:D:\Runtime_Reports2\coverage-report.xml > D:\RunTime_Reports2\log.txt

Thanks & Regards,
Sarfraz.

**Comment by sawilde** [comment]
use quotes as described in the [wiki](https://github.com/OpenCover/opencover/wiki/Usage#notes-on-spaces-in-arguments) 
    
    "-filter:+[*]* -[*.Test.]*"

**Comment by sarfraz17** [comment]
Thanks Shaun, now I am able to generate the right results when I am locally running the command locally and from TFS the issue still persist. Any idea what would be causing the issue.

Command used locally:

"C:\Program Files (x86)\OpenCover\OpenCover.Console.exe" -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\MSTest.exe" -targetdir:"D:\Builds\9\CustomerProfile\Main.CustomerProfile.CI\Sources\Build" -targetargs:"/resultsfile:D:\RunTime_Reports2\Test-Result.trx /testcontainer:CPSOracleRepository.Test.dll /testcontainer:CPSProvider.Tests.dll /testcontainer:CPSRepository.Test.dll /testcontainer:AutherizationHeader.Test.dll /runconfig:"D:\Builds\9\CustomerProfile\Main.CustomerProfile.CI\Sources\CustomerProfileProvider-v2.4\Local.testsettings"" "-filter:+[*]* -[*.Test.*]*" -mergebyhash -output:D:\Runtime_Reports2\coverage-report.xml > D:\RunTime_Reports2\log.txt

From TFS:
"C:\Program Files (x86)\OpenCover\OpenCover.Console.exe" -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\MSTest.exe" -targetdir:"%1\Build" -targetargs:"/resultsfile:D:\RunTime_Reports\Test-Result.trx  /testcontainer:CPSOracleRepository.Test.dll /testcontainer:CPSProvider.Tests.dll /testcontainer:CPSRepository.Test.dll /testcontainer:AutherizationHeader.Test.dll /runconfig:"%1\CustomerProfileProvider-v2.4\Local.testsettings"" -filter:"+[*]* -[*.Test.*]*" -mergebyhash -output:D:\RunTime_Reports\coverage-report.xml > D:\RunTime_Reports\log.txt

The only difference between the command is workspace is explicitly called when running locally and runtime when running from TFS.

Please suggest if I am missing something.

Thanks & Regards,
Sarfraz.

**Comment by sawilde** [comment]
locally you have 

    "-filter:+[*]* -[*.Test.*]*"

but TFS has

    -filter:"+[*]* -[*.Test.*]*"

the difference is subtle but does cause issues when running under powershell.

**Comment by sarfraz17** [comment]
Tried that option with no luck not sure how its working locally and not from TFS.

**Comment by sarfraz17** [comment]
Shaun,
      The issue is resolved from TFS as it was an issue with the xaml file which we were using as it was customized one.

Thanks again for your help on the filters which resolved 90% of the issue.

Thanks & Regards,
Sarfraz.

**Comment by sawilde** [comment]
awesome
