### ISSUE TITLE
Will OpenCover support NUnit's shadow-copy option?

### ISSUE THREAD

**Issue by wangnangg** [OpenCover/opencover#259]
I know that we must disable NUnit's shadow-copy option to get coverage from NUnit tests.
But I am under a situation where I really need shadow-copy while collecting coverage data.
So I am wondering if OpenCover have a plan of working on this problem? Or is there any way of modifying OpenCover to suit this need?

I did some research on the problem. Below is the question I asked in stackoverflow.

>I am doing some modifications on OpenCover and NUnit to suit my needs.

>Briefly, I want to get coverage information even when shadow-copy is enabled in Nunit. However, OpenCover is unable to track an assembly when the pdb file is absent. When shadow-copy is enabled in NUnit, the assembly under test is copied to a shadow directory and OpenCover fails to find the corresponding pdf file.

>At first, I thought that .Net Runtime just didn't copy pdf files to shadow directory. But After I investigated this problem further, I found out Runtime will copy pdf files but not the same time when assemblies are copied.

>My understanding now is that Runtime will first copy assemblies to shadow directories. And then those assemblies will be loaded and Opencover is notified. OpenCover find out that there are no pdb files, so these assemblies are ignored. Sometime later, pdb files are copied, but OpenCover failed to notice this fact thus failed to track these assemblies.

>So my question is what is the exact time that .Net Runtime copies pdb files to shadow directories? And is it possible that I modify OpenCover so that it will be able to track these shadow-copied assemblies?

**Comment by sawilde** [comment]
OpenCover uses various locations to look for PDBs

1) it looks in the same folder as the assembly was loaded from
2) it looks in the folder set by workingdir
3) it looks in its current directory

to support /noshadow I usually find 2) is the easiest to use

**Comment by wangnangg** [comment]
Thanks. 
-mergebyhash doesn't solve this problem, but 2) works.

**Comment by sawilde** [comment]
awesome :)
