### ISSUE TITLE
OpenCover hangs with mstest V10 on win 2K12

### ISSUE THREAD

**Issue by eliassal** [OpenCover/opencover#267]
I have OpenCover hanging and need to kill the MSTest in order to go through and having it committed 
I have already seen an issue #55 in this forum with same title which seemed resolved in version 2.1.5 which is not the case here for me.
This is a new fresh box I'm not sure what the exact problem is.
  Looking at task manager 
•I see opencover.console.exe at ~98% CPU
•mstest.exe is still there but not doing anything. 
•no expected stdout from opencover yet.

**Comment by molnargab** [comment]
You can see [the stack traces for .NET applications via ProcessExplorer](http://blogs.msdn.com/b/dotnet/archive/2012/06/26/new-net-diagnostic-info-added-to-process-explorer.aspx). Fortunately MSTest is also managed, so you should be able to see which application is hanging.

I'm not sure if we could get source line information, though the method name may give us some hint where the issue lies, also the address should be resolvable.

**Comment by eliassal** [comment]
Thanks molnargab, I went through thread 55, I prepared a bat files as done by dsteinbe, 1st I was getting errors of files not found because of spaces in the path for the test dll, I put the bat file in the directory where the Dll resides and the bat worked fine, here is the bat file. Can you please let me know how to escape the spaces in my path. With the following 2 statements, it was failing
"%ProgramFiles(x86)%\Jenkins\workspace\Hello World\HelloWorldTests\bin\Debug\HelloWorldTests.dll"
or
"PROGRA~2\Jenkins\workspace\HELLOW~1\HelloWorldTests\bin\Debug\HelloWorldTests.dll"

The bat file that went through successfully (as I said put it directly in the dll directory to avoid the NoFile found....)
REM SET OpenCover="%ProgramFiles(x86)%\MSBuild\OpenCover\OpenCover.Console.exe"
SET OpenCover="C:\Users\salam\AppData\Local\Apps\OpenCover\OpenCover.Console.exe"
SET MSTest="%ProgramFiles(x86)%\Microsoft Visual Studio 10.0\Common7\IDE\MSTest.exe"
SET TestDLL="HelloWorldTests.dll"
SET TestOutFILE=C:\tools\TestResults\testresult.trx
SET CoverOutFile=C:\tools\Coverage\CodeCoverageResults.xml
SET ReportGen="C:\tools\ReportGenerator\bin\ReportGenerator.exe"

MKDIR TestResults
MKDIR Coverage

%OpenCover% -register:user -target:%MSTest% -targetargs:"/noisolation /testcontainer:%TestDLL%" -output:%CoverOutFile% -mergebyhash
%ReportGen% %CoverOutFile% "Coverage\Report"

**Comment by molnargab** [comment]
There are some examples for this in the [Usage wiki](https://github.com/OpenCover/opencover/wiki/Usage#notes-on-spaces-in-arguments).

**Comment by sawilde** [comment]
If OpenCover is at 90% it is probably still receiving/processing data i.e. the target app or something it has launched is still sending data - if this is still an issue an example of the test that we can use to replicate the issue would be appreciated.

The other thing to do is use `-targetdir` to point to your folder where the test assemblies reside.

**Comment by eliassal** [comment]
Thanks sawilde, I revisited Usage Wike and managed to make my script work. I needed to add double quote for my parameter  :%TestDLL% which is a path where I had spaces and it worked like a charm
SET TestDLL="%ProgramFiles(x86)%\Jenkins\workspace\Hello World\HelloWorldTests\bin\Debug\HelloWorldTests.dll"
So
%OpenCover% -register:user -target:%MSTest% -targetargs:"/noisolation /testcontainer:%TestDLL%" -output:%CoverOutFile% -mergebyhash
Replaced with
%OpenCover% .............. /testcontainer:"%TestDLL%"" -output:%CoverOutFile% -mergebyhash

Now I need to do this in Jenkins and look how I can make use of the generated reports, any tutorial or steps to follow?

**Comment by sawilde** [comment]
This is probably the best I've seen http://jane.dallaway.com/jenkins-code-coverage-net/ but there are other tutorials out there. If you can run it on the command line then you should be able to script it for your build server.

I also see the corefx team use opencover and jenkins - http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/lastBuild/Code_Coverage_Report/

**Comment by eliassal** [comment]
sawilde, the 1st thread involves the use of Cobertura plugin and OpenCoverToCoverturaConverter, I am a little bit confused. Opencover and •ReportGenerator provide the html report, why Jane has added those 2 components, I am not able to understand the added value for those 2 components.
I nrowsed the 2nd thread, it seems that we can not see the configuration and how report is generated

**Comment by molnargab** [comment]
Jenkins has some support for code coverage (e.g. to display it on the project dashboard, or make a build unstable if coverage is too low). For this it needs some sort of coverage file (XML).

The OpenCover format is not (yet) directly supported, so the approach here is to transform the output to Cobertura, which already has a Jenkins plugin.

If you only need the HTML report, you don't have to use those 2 components.

In addition to the tutorial, I'd also recommend  using some test recorder plugin, for example the [MSTest Results](https://wiki.jenkins-ci.org/display/JENKINS/MSTest+Plugin) plugin enables the unstable outcome for the build if a test failed (you have to create a .trx file with the MSTest run though). There are some other plugins for other testing frameworks as well.

**Comment by sawilde** [comment]
I've never used Jenkins so can't directly advise how to integrate the two (hence the links for you to start your own investigation - google is your friend), I personally use ReportGenerator to convert the XML to HTML output but it is easy to extra data from the XML to make your own custom reports should you need to and most build systems I have used have the ability to run scripts and capture artifacts and bind them to the UI (as seen in the corefx implementation)

On a side-note I spend a lot of 'initial' time convincing my management that coverage is not the best metric - all it tells you is that you have no tests that cover a certain region of code not if they are the right sort of tests - only a good code review will do that.

**Comment by sawilde** [comment]
Issue has gone quiet and migrated from original issue
