### ISSUE TITLE
add extra stats in output xml

### ISSUE THREAD

**Issue by sarut0bi** [OpenCover/opencover#283]
Once openCover finished playing with nunit i ve got following output in my console:
Committing...
Visited Classes 547 of 778 (70.31)
Visited Methods 4612 of 8884 (51.91)
Visited Points 25700 of 44785 (57.39)
Visited Branches 10016 of 22091 (45.34)
Should it be possible to have it in output XML in <Summary> like numSequencePoints/visited... ?

**Comment by sawilde** [comment]
that's what the `results.xml` file is for - if you haven't specified an output file via the `-output` [switch](https://github.com/OpenCover/opencover/wiki/Usage) then that is what it will be called.

When looking at the results.xml file you will find a summary element at the top which will have the data you want.

You might find using ReportGenerator will give you the best visualization of your code.

**Comment by sarut0bi** [comment]
hi again,

I use -output switch. I Only have following element in my summary element using 4.5.3522:
<Summary numSequencePoints="44785" visitedSequencePoints="25700" numBranchPoints="22091" visitedBranchPoints="10016" sequenceCoverage="57.39" branchCoverage="45.34" maxCyclomaticComplexity="76" minCyclomaticComplexity="0" />
aka Visited Points & Visited Branches.

Is there extra argument to put on the commandline to have Visited Classes & Visited Methods in the XML?

**Comment by sawilde** [comment]
not at this moment in time - you can pull that information manually via the xml if you need it

**Comment by sawilde** [comment]
try this - https://www.nuget.org/packages/OpenCover/4.5.4212-rc137

**Comment by sawilde** [comment]
https://github.com/OpenCover/opencover/releases/tag/4.6.166
