### ISSUE TITLE
Coveralls Upload from Appveyor performance

### ISSUE THREAD

**Issue by d4nj0nes** [OpenCover/opencover#284]
This may or may not be an OpenCover issue but I was looking for guidance on best practice.
The scenario is that we run OpenCover on appveyor on two assemblies with a filter two include only two specific namespaces. I also specifiy the options 
```-log:Off -threshold:100 -skipautoprops -hideskipped:"File;MissingPdb;Attribute"```
The generated file is then sent with Coveralls.Net to our coveralls.io repo.
The whole process takes about  20 minutes - partly I imagine due to the generation of the output xml partly the sending to coveralls via coveralls.net. I will be asking the same question over at their issues page.
Basically 
 - is there anything else I am missing in the options to speed this up?
 - The outputted file is over 100mb I guess that's the core of the issue - can it be compressed? Again possibly not a question you can answer
 - We updated the coveralls package to 1.3.2 from 1.2.5-beta which gave an error about not finding a ```value for SourceDigest in the CoverageFile``` . To get around that we added the coveralls option for ```--full-sources``` , and then ultimately reverted back to the 1.2.5-beta. Is this a known issue or should the output file be compatible with this version? 
 Any help would be appreciated thanks.

**Comment by sawilde** [comment]
I can only really offer advice on OpenCover itself - there is a beta in nuget that is faster (currently being trialed by various teams).

What are the delays at each step?

`SourceDigest` is not a term I use in OpenCover

Can the  coveralls output be compressed possibly but again you'd have to contact the coveralls team to see if they support compression on their API and it would require coveralls.net to send up the json using a GZipStream.

**Comment by molnargab** [comment]
A couple of ideas off the top of my head:

   - You could add `Filter` to what you have in the `-hideskipped` option, or you can use `All`, but I don't think it would produce a significantly smaller file.
   - You could squeeze a bit more by removing insignificant whitespace, like indentation or line breaks, though I'm not sure if it would be worth to create a script for this. Perhaps it shouldn't be that hard with PowerShell (and .NET) at hand.
   - If the test execution and the compilation is included in that 20 minutes, you could have a look at them as well, e.g. AppVeyor could cache your NuGet dependencies and MSTest deployments may eat up precious time. Reducing the time the tests run would also have benefits during development, though I also imagine they aren't too significant even if included in the 20 minutes (even slow unit test suites tend to complete in a couple of minutes),
   - If you have a bunch of long methods, they may take more space in the reports than a couple of smaller ones, especially if used with `-coverbytest` (smaller methods also tend to mean less complexity and code duplication). Omitting `-coverbytest` may also reduce the size of the report, at the expense of not having by-test coverage in the report, just the hit count (?).

**Comment by d4nj0nes** [comment]
Thanks for your replies I will try a few of your points.
The overall build time is in fact 35 minutes. The first 10-15 of that is the build and JavaScript test execution, we do cache the Nuget dependencies.
On the white space truncation I imagine we would lose the ability to view the source file on coveralls but I can test that out. I may also try the beta. I do imagine that the bottleneck is the coveralls file transform > Json > upload which is why I wanted to focus on a smaller file and as mentioned, I have asked the question there as well. Thanks again for the replies
