### ISSUE TITLE
Lines showing as not covered

### ISSUE THREAD

**Issue by StephenCleary** [OpenCover/opencover#285]
I have a situation where code is being reported as not covered, when it definitely is. The report is online here: https://coveralls.io/builds/2205025/source?filename=..%2F..%2FNito.Collections.Deque%2FDeque.cs#L574

The local ReportGenerator shows the same results: ![ReportGenerator](https://cloud.githubusercontent.com/assets/900597/6861587/0333bbb2-d40f-11e4-8bc8-9a6a11b58fdd.png)

This is for a Release build with OpenCover 4.5.3809-rc94. The profilee is an xunit .NET Core test suite.

The xml coverage file does indeed show those lines were not covered:

    <Method visited="true" cyclomaticComplexity="1" sequenceCoverage="25" branchCoverage="100" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
      <Summary numSequencePoints="4" visitedSequencePoints="1" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="25" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
      <MetadataToken>100663342</MetadataToken>
      <Name>System.Int32 Nito.Collections.Deque`1::PostIncrement(System.Int32)</Name>
      <FileRef uid="5" />
      <SequencePoints>
        <SequencePoint vc="416" uspid="281" ordinal="0" offset="0" sl="581" sc="13" el="581" ec="31" bec="0" bev="0" fileid="5" />
        <SequencePoint vc="0" uspid="282" ordinal="1" offset="6" sl="582" sc="13" el="582" ec="30" bec="0" bev="0" fileid="5" />
        <SequencePoint vc="0" uspid="283" ordinal="2" offset="20" sl="583" sc="13" el="583" ec="33" bec="0" bev="0" fileid="5" />
        <SequencePoint vc="0" uspid="284" ordinal="3" offset="39" sl="584" sc="13" el="584" ec="24" bec="0" bev="0" fileid="5" />
      </SequencePoints>
      <BranchPoints />
      <MethodPoint xsi:type="SequencePoint" vc="416" uspid="281" ordinal="0" offset="0" sl="581" sc="13" el="581" ec="31" bec="0" bev="0" fileid="5" />
    </Method>

But pretty much every unit test I have exercises this method in its entirety.

The IL for this method (as shown by JustDecompile) is:

    .method private hidebysig instance int32 PostIncrement (
            int32 'value'
        ) cil managed 
    {
        IL_0000: ldarg.0
        IL_0001: ldfld int32 class Nito.Collections.Deque`1<!T>::_offset
        IL_0006: ldarg.0
        IL_0007: ldarg.0
        IL_0008: ldfld int32 class Nito.Collections.Deque`1<!T>::_offset
        IL_000d: ldarg.1
        IL_000e: add
        IL_000f: stfld int32 class Nito.Collections.Deque`1<!T>::_offset
        IL_0014: ldarg.0
        IL_0015: ldarg.0
        IL_0016: ldfld int32 class Nito.Collections.Deque`1<!T>::_offset
        IL_001b: ldarg.0
        IL_001c: call instance int32 class Nito.Collections.Deque`1<!T>::get_Capacity()
        IL_0021: rem
        IL_0022: stfld int32 class Nito.Collections.Deque`1<!T>::_offset
        IL_0027: ret
    }

**Comment by sawilde** [comment]
It looks like only the method enter is being instrumented - very odd - does this also happen under debug builds of `Nito`.

Can you supply the reproduce steps? Alternatively, if not already there, push it up as a branch on your repo then I can repeat easier.

**Comment by sawilde** [comment]
Hi - I tried pulling your code to investigate but I can't get it to build - it seems to wnat more of a set up then just the repo.

I also note that coveralls is now showing the file as covered does this mean the issue is resolved?

**Comment by sawilde** [comment]
Hi - I'd like to resolve your issue but if I can't repeat it then there is not much I can do.

**Comment by mdekrey** [comment]
I was able to download the git repo @StephenCleary suggested, build using VS2015 CTP6, and run the coverage.ps1 with OpenCover 4.5.3809-rc94 - I got a 97.7% coverage, and the lines he's showing 
are covered.
![capture](https://cloud.githubusercontent.com/assets/144461/7003983/41f6a7e4-dc32-11e4-9c00-540c591d300a.PNG)

I did have to remove my other OpenCover packages stored by the .k framework - perhaps that's where the issue was coming from?

(I'm having similar issues, and came across this issue, but I don't think it's the same one I'm having and I don't want to hijack.)

**Comment by sawilde** [comment]
@mdekrey - did you need anything else other than VS2015 CTP6 to get it to build? Perhaps I may need to upgrade to the latest and greatest.

Feel free to raise your issue - I'll try to help.

**Comment by mdekrey** [comment]
I had solved my issue; simple misconfiguration of finding PDB's and such. VS2015 CTP6 is sometimes tricky to get set up properly, and there's a major change coming for CTP7...

I actually followed @StephenCleary's own blog post (http://blog.stephencleary.com/2015/03/continuous-integration-code-coverage-open-source-net-coreclr-projects.html) to get it all set up for myself. So I'd be willing to bet he got it working, too!

Thanks for being responsive, @sawilde!

**Comment by sawilde** [comment]
I'd not actually seen that blog post :) - thank you @mdekrey for helping out

**Comment by StephenCleary** [comment]
So sorry for the driveby...

AFAIK this is still an issue. I'm working around it by only doing code coverage of Debug builds. So my CI build has to be Debug to push (the correct) code coverage data automatically. (This works for me because I don't - currently - use CI for any kind of deployment).

I'll try to get you a minimal test case with a Release build shortly.

**Comment by sawilde** [comment]
Hi Stephen - thanks a standalone project that I can build and test would make it much quicker to resolve the issue.

**Comment by sawilde** [comment]
Okay I eventually found some time and managed to repeat after a reinstall of CTP6 and only see this issue on `Release` builds.

The kvm stuff was a bit tricky to get going (that is when VS doesn't crash) I sure as hell hope that improves.

So I'll have a look to see what is going on and see if I can now repeat with debug builds of OpenCover.

**Comment by sawilde** [comment]
Interesting... it seems the IL we see in the assembly as seen in ILSPY

````
.method private hidebysig 
	instance int32 PostIncrement (
		int32 'value'
	) cil managed 
{
	// Method begins at RVA 0x2797
	// Code size 40 (0x28)
	.maxstack 8

	IL_0000: ldarg.0
	IL_0001: ldfld int32 class Nito.Collections.Deque`1<!T>::_offset
	IL_0006: ldarg.0
	IL_0007: ldarg.0
	IL_0008: ldfld int32 class Nito.Collections.Deque`1<!T>::_offset
	IL_000d: ldarg.1
	IL_000e: add
	IL_000f: stfld int32 class Nito.Collections.Deque`1<!T>::_offset
	IL_0014: ldarg.0
	IL_0015: ldarg.0
	IL_0016: ldfld int32 class Nito.Collections.Deque`1<!T>::_offset
	IL_001b: ldarg.0
	IL_001c: call instance int32 class Nito.Collections.Deque`1<!T>::get_Capacity()
	IL_0021: rem
	IL_0022: stfld int32 class Nito.Collections.Deque`1<!T>::_offset
	IL_0027: ret
} // end of method Deque`1::PostIncrement
````

but the IL I am getting from the runtime is

````
IL_0000 nop
IL_0001 ldarg.0
IL_0002 ldfld 0A00003B
IL_0007 stloc.0
IL_0008 ldarg.0
IL_0009 ldarg.0
IL_000A ldfld 0A00003B
IL_000F ldarg.1
IL_0010 add
IL_0011 stfld 0A00003B
IL_0016 ldarg.0
IL_0017 ldarg.0
IL_0018 ldfld 0A00003B
IL_001D ldarg.0
IL_001E call (0A)00003A
IL_0023 rem
IL_0024 stfld 0A00003B
IL_0029 ldloc.0
IL_002A stloc.1
IL_002B br.s IL_002D
IL_002D ldloc.1
IL_002E ret
````

so it looks like the IL from release assemblies is being modified before being passed up to the profiler.

When OpenCover tries to apply the instrumentation points and can't find the correct points it tries to fail safely leaving just the method instrumentation point.

Now to work out why/what they framework guys have been up to with release IL

**Comment by sawilde** [comment]
Okay it seems like something (probably using roslyn) is rewriting the `release` assembly and executing that instead and the IL being produced is sometimes too different (though functionally the same) for OpenCover to deal with at this moment in time.

One example of radical change is `set_Capacity`

As seen in ILSPY
````
.method public hidebysig specialname 
	instance void set_Capacity (
		int32 'value'
	) cil managed 
{
	// Method begins at RVA 0x269c
	// Code size 67 (0x43)
	.maxstack 3
	.locals init (
		[0] !T[] newBuffer
	)

	IL_0000: ldarg.1
	IL_0001: ldarg.0
	IL_0002: call instance int32 class Nito.Collections.Deque`1<!T>::get_Count()
	IL_0007: bge.s IL_0019

	IL_0009: ldstr "value"
	IL_000e: ldstr "Capacity cannot be set to a value less than Count"
	IL_0013: newobj instance void [mscorlib]System.ArgumentOutOfRangeException::.ctor(string, string)
	IL_0018: throw

	IL_0019: ldarg.1
	IL_001a: ldarg.0
	IL_001b: ldfld !0[] class Nito.Collections.Deque`1<!T>::_buffer
	IL_0020: ldlen
	IL_0021: conv.i4
	IL_0022: bne.un.s IL_0025

	IL_0024: ret

	IL_0025: ldarg.1
	IL_0026: newarr !T
	IL_002b: stloc.0
	IL_002c: ldarg.0
	IL_002d: ldloc.0
	IL_002e: ldc.i4.0
	IL_002f: call instance void class Nito.Collections.Deque`1<!T>::CopyToArray(class [mscorlib]System.Array, int32)
	IL_0034: ldarg.0
	IL_0035: ldloc.0
	IL_0036: stfld !0[] class Nito.Collections.Deque`1<!T>::_buffer
	IL_003b: ldarg.0
	IL_003c: ldc.i4.0
	IL_003d: stfld int32 class Nito.Collections.Deque`1<!T>::_offset
	IL_0042: ret
} // end of method Deque`1::set_Capacity
````

As received in profiler

````
IL_0000 nop
IL_0001 ldarg.1
IL_0002 ldarg.0
IL_0003 call (0A)00002C
IL_0008 clt
IL_000A stloc.1
IL_000B ldloc.1
IL_000C brfalse.s IL_001E
IL_000E ldstr (70)000077
IL_0013 ldstr (70)000323
IL_0018 newobj (0A)000027
IL_001D throw
IL_001E ldarg.1
IL_001F ldarg.0
IL_0020 ldfld 0A000028
IL_0025 ldlen
IL_0026 conv.i4
IL_0027 ceq
IL_0029 stloc.2
IL_002A ldloc.2
IL_002B brfalse.s IL_002F
IL_002D br.s IL_004D
IL_002F ldarg.1
IL_0030 newarr 1B00000C
IL_0035 stloc.0
IL_0036 ldarg.0
IL_0037 ldloc.0
IL_0038 ldc.i4.0
IL_0039 call (0A)000038
IL_003E nop
IL_003F ldarg.0
IL_0040 ldloc.0
IL_0041 stfld 0A000028
IL_0046 ldarg.0
IL_0047 ldc.i4.0
IL_0048 stfld 0A00003B
IL_004D ret
````

As you can see `nop`s have been inserted, branches have been modified in fact the overall IL has been messed with so much that the original instrumentation points have been lost; even the `ret` at IL_0024 has been turned into a `br.s`.

**Comment by sawilde** [comment]
okay a similar thing has been reported for dnx (https://github.com/OpenCover/opencover/issues/327) and the resolution was to use the --lib switch of dnx

**Comment by sawilde** [comment]
https://www.nuget.org/packages/OpenCover/4.6.515-rc

we have also added a `-safemode:on|off` switch with on being the default - if you have performance issues then try `-safemode:off` this uses thread based buffers but if the runtime closes the profiler without calling shutdown then you may suffer some data loss.

**Comment by sawilde** [comment]
We have published the release at https://www.nuget.org/packages/OpenCover/4.6.519 and https://github.com/OpenCover/opencover/releases/tag/4.6.519
