### ISSUE TITLE
vector subscript out of range

### ISSUE THREAD

**Issue by INRIX-Andrew-Lee** [OpenCover/opencover#287]
Sorry don't have debugger on this machine to get the call stack.

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: \\andrew01\opencover\x64\OpenCover.Profiler.dll
File: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector
Line: 1201

Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by sawilde** [comment]
What version are you running? 

Do you have a way to repeat?

**Comment by INRIX-Andrew-Lee** [comment]
I have the latest version that I synced yesterday.

Yes, it happens every time. It was a windows service and the error happened during its startup.

Andrew

**Comment by sawilde** [comment]
Can you share the repeat steps?

**Comment by INRIX-Andrew-Lee** [comment]
This is the command that I used:
`\\andrew01\opencover\OpenCover.Console.exe -target:Inrix.Tpeg.WindowsService.exe -register -filter:+[Inrix.CS.TPEG*]*`

**Comment by INRIX-Andrew-Lee** [comment]
Second Chance Assertion Failed: File C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector, Line 1202
(204c.13a4): Break instruction exception - code 80000003 (first chance)
OpenCover_Profiler!_CrtDbgBreak+0x2:
000007fe`d8321882 cc              int     3
1:054> k
Child-SP          RetAddr           Call Site
00000000`15b31018 000007fe`d8322782 OpenCover_Profiler!_CrtDbgBreak+0x2 [f:\dd\vctools\crt\crtw32\misc\dbgrptt.c @ 87]
00000000`15b31020 000007fe`d8305ee0 OpenCover_Profiler!_VCrtDbgReportW+0x1c2 [f:\dd\vctools\crt\crtw32\misc\dbgrptt.c @ 506]
00000000`15b39110 000007fe`d8305e70 OpenCover_Profiler!_CrtDbgReportWV+0x50 [f:\dd\vctools\crt\crtw32\misc\dbgrpt.c @ 263]
00000000`15b39160 000007fe`d8294165 OpenCover_Profiler!_CrtDbgReportW+0x60 [f:\dd\vctools\crt\crtw32\misc\dbgrpt.c @ 279]
00000000`15b391c0 000007fe`d829f7bc OpenCover_Profiler!std::vector<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<unsigned long const ,_MSG_SendVisitPoints_Request * __ptr64> > > >,std::_Wrap_alloc<std::allocator<std::_List_unchecked_iterator<std::_List_val<std::_List_simple_types<std::pair<unsigned long const ,_MSG_SendVisitPoints_Request * __ptr64> > > > > > >::operator[]+0x95 [c:\program files (x86)\microsoft visual studio 12.0\vc\include\vector @ 1202]
00000000`15b39200 000007fe`d8296d57 OpenCover_Profiler!std::_Hash<std::_Umap_traits<unsigned long,_MSG_SendVisitPoints_Request * __ptr64,std::_Uhash_compare<unsigned long,std::hash<unsigned long>,std::equal_to<unsigned long> >,std::allocator<std::pair<unsigned long const ,_MSG_SendVisitPoints_Request * __ptr64> >,0> >::_Vec_lo+0x3c [c:\program files (x86)\microsoft visual studio 12.0\vc\include\xhash @ 902]
00000000`15b39230 000007fe`d82a45e6 OpenCover_Profiler!std::_Hash<std::_Umap_traits<unsigned long,_MSG_SendVisitPoints_Request * __ptr64,std::_Uhash_compare<unsigned long,std::hash<unsigned long>,std::equal_to<unsigned long> >,std::allocator<std::pair<unsigned long const ,_MSG_SendVisitPoints_Request * __ptr64> >,0> >::_Begin+0x37 [c:\program files (x86)\microsoft visual studio 12.0\vc\include\xhash @ 921]
00000000`15b39260 000007fe`d8293d5f OpenCover_Profiler!std::_Hash<std::_Umap_traits<unsigned long,_MSG_SendVisitPoints_Request * __ptr64,std::_Uhash_compare<unsigned long,std::hash<unsigned long>,std::equal_to<unsigned long> >,std::allocator<std::pair<unsigned long const ,_MSG_SendVisitPoints_Request * __ptr64> >,0> >::lower_bound+0x76 [c:\program files (x86)\microsoft visual studio 12.0\vc\include\xhash @ 742]
00000000`15b39340 000007fe`d8284529 OpenCover_Profiler!std::unordered_map<unsigned long,_MSG_SendVisitPoints_Request * __ptr64,std::hash<unsigned long>,std::equal_to<unsigned long>,std::allocator<std::pair<unsigned long const ,_MSG_SendVisitPoints_Request * __ptr64> > >::operator[]+0x4f [c:\program files (x86)\microsoft visual studio 12.0\vc\include\unordered_map @ 309]
00000000`15b39430 000007fe`d821d41d OpenCover_Profiler!ProfilerCommunication::AddVisitPointToThreadBuffer+0x49 [c:\users\andrew\documents\github\opencover\main\opencover.profiler\profilercommunication.cpp @ 131]
00000000`15b39490 000007fe`d821fc3c OpenCover_Profiler!CCodeCoverage::AddVisitPoint+0xbd [c:\users\andrew\documents\github\opencover\main\opencover.profiler\codecoverage.cpp @ 205]
00000000`15b394d0 000007fe`911e17bd OpenCover_Profiler!InstrumentPointVisit+0x2c [c:\users\andrew\documents\github\opencover\main\opencover.profiler\codecoverage.cpp @ 186]

**Comment by sawilde** [comment]
Thanks very unusual.

I need to understand the data that is causing this problem as it appears to be trying to access a buffer for a thread that the runtime has not yet told the profiler about. 

Do you have the binaries (or sample source) available to repeat the issue?

**Comment by sawilde** [comment]
Do you have any more information for me?

**Comment by sawilde** [comment]
Do you get this with the production build (nuget) or only with one that you have built locally?

**Comment by INRIX-Andrew-Lee** [comment]
It was my own build.

Andrew
________________________________
寄件者: Shaun Wilde<mailto:notifications@github.com>
寄件日期: ‎4/‎24/‎2015 7:56 PM
收件者: OpenCover/opencover<mailto:opencover@noreply.github.com>
副本: Andrew Lee<mailto:Andrew@inrix.com>
主旨: Re: [opencover] vector subscript out of range (#287)


Do you get this with the production build (nuget) or only with one that you have built locally?

**Comment by sawilde** [comment]
Okay - I'll push up a `fix` but I am still not sure how to repeat it - so will you need you to pull and try it out

**Comment by sawilde** [comment]
it's on a branch

**Comment by sawilde** [comment]
@INRIX-Andrew-Lee have you had a chance to look?

**Comment by sawilde** [comment]
https://github.com/OpenCover/opencover/releases/tag/4.6.166
