### ISSUE TITLE
Crash with C++/CLI

### ISSUE THREAD

**Issue by beaudoinlaurent** [OpenCover/opencover#288]
Hi, 
i got a C# project with one C++/CLI project. When the CLI is excluded with filter, open cover work fine. When the C++/CLI is included, I get the following error:

Exception non gérée : System.IO.InvalidDataException: Données non valides détectées lors du décodage.
   à Mono.Cecil.Pdb.PdbReader.ReadScopeAndLocals(PdbScope scope, Scope parent, MethodBody body, InstructionMapper mapper
)
   à Mono.Cecil.Pdb.PdbReader.ReadScopeAndLocals(PdbScope[] scopes, Scope parent, MethodBody body, InstructionMapper map
per)
   à Mono.Cecil.Pdb.PdbReader.Read(MethodBody body, InstructionMapper mapper)
   à Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   à Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   à Mono.Cecil.MethodDefinition.get_Body()
   à OpenCover.Framework.Symbols.CecilSymbolManager.<GetInstrumentableTypes>b__8(MethodDefinition methodDefinition) dans
 c:\projects\opencover\main\OpenCover.Framework\Symbols\CecilSymbolManager.cs:ligne 166
   à System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   à System.Linq.Enumerable.<SelectManyIterator>d__31`3.MoveNext()
   à System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   à System.Linq.Enumerable.<DistinctIterator>d__81`1.MoveNext()
   à System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   à OpenCover.Framework.Symbols.CecilSymbolManager.GetInstrumentableTypes(IEnumerable`1 typeDefinitions, List`1 classes
, IFilter filter, String moduleName) dans c:\projects\opencover\main\OpenCover.Framework\Symbols\CecilSymbolManager.cs:l
igne 171
   à OpenCover.Framework.Symbols.CecilSymbolManager.GetFiles() dans c:\projects\opencover\main\OpenCover.Framework\Symbo
ls\CecilSymbolManager.cs:ligne 130
   à OpenCover.Framework.Model.InstrumentationModelBuilder.CreateModule(Boolean full) dans c:\projects\opencover\main\Op
enCover.Framework\Model\InstrumentationModelBuilder.cs:ligne 50
   à OpenCover.Framework.Model.InstrumentationModelBuilder.BuildModuleModel(Boolean full) dans c:\projects\opencover\mai
n\OpenCover.Framework\Model\InstrumentationModelBuilder.cs:ligne 29
   à OpenCover.Framework.Service.ProfilerCommunication.TrackAssembly(String modulePath, String assemblyName) dans c:\pro
jects\opencover\main\OpenCover.Framework\Service\ProfilerCommunication.cs:ligne 46
   à OpenCover.Framework.Communication.MessageHandler.StandardMessage(MSG_Type msgType, IManagedCommunicationBlock mcb,
Action`2 chunkReady, Action`2 offloadHandling) dans c:\projects\opencover\main\OpenCover.Framework\Communication\Message
Handler.cs:ligne 51
   à OpenCover.Framework.Communication.CommunicationManager.HandleCommunicationBlock(IManagedCommunicationBlock mcb, Act
ion`2 offloadHandling) dans c:\projects\opencover\main\OpenCover.Framework\Communication\CommunicationManager.cs:ligne 5
9
   à OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass24.<ProcessBlock>b__22(Object state) dans c:\projects\
opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:ligne 242
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object s
tate, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Bo
olean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by sawilde** [comment]
Do you have a sample project that we can use to repeat the issue?

**Comment by beaudoinlaurent** [comment]
Hi, I cannot give you my project source code, but i can try to narrow it down to the root cause inside the C++/CLI project by exlucding from build some source code...
Thereafter, it will be easier to create a failing project.
Is there a way to get more output from the crash error log ? something I could use to narrow down the problematic code
Laurent
Date: Thu, 9 Apr 2015 22:58:54 -0700

**Comment by sawilde** [comment]
not that I can tell - perhaps something to do with debug symbols since the crash is in a 3rd party component

**Comment by sawilde** [comment]
> Hi, I cannot give you my project source code, but i can try to narrow it down to the root cause inside the C++/CLI project by exlucding from build some source code...

Perhaps you can tel us more about your project 

* What are you using to build it with? 
* What version of OpenCover are you using?

**Comment by beaudoinlaurent** [comment]
Hi, 
using OpenCover 4.5.3723 via nuget.
using Visual Studio Express 2013 to build.
I've open my test.dll (that contain my NUNIT test) with ILSpy 2.3.0.1827 wihtout any problem
(im unable to post picture...)

**Comment by beaudoinlaurent** [comment]
ILSPY -> http://postimg.org/image/mo33ote61/

**Comment by sawilde** [comment]
I'm unable to view picture :(

**Comment by beaudoinlaurent** [comment]
updated link

**Comment by sawilde** [comment]
Hmmm... As I don't seem to be able to repeat it - I'll just have to add more tracking/tracing to the exception to help narrow down the issue in a future release.

**Comment by beaudoinlaurent** [comment]
If you want me to test it with an special instrumented release, let me know.
Otherwise, will retry with the next release i guess.

**Comment by sawilde** [comment]
try this build here - https://ci.appveyor.com/project/sawilde/opencover/build/artifacts

**Comment by beaudoinlaurent** [comment]
Hi, the exception wrapper does work, but be miss the exception detail.
It seems there is alot of error while trying to get body of methods. (on mine class and on system class)

Extract from the errors log:
Executing: xyz\packages\NUnit.Runners.2.6.3\tools\nunit-console-x86.exe
ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
Exception whilst trying to get the body of method System.Void modopt(System.Runtime.CompilerServices.CallConvThiscall) <Module>::std.basic_string<char,std::char_traits<char>,std::allocator<char> >._Tidy(std.basic_string<char,std::char_traits<char>,std::allocator<char> >* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst),System.Boolean,System.UInt32)
Exception whilst trying to get the body of method std.basic_string<char,std::char_traits<char>,std::allocator<char> >* modopt(System.Runtime.CompilerServices.IsImplicitlyDereferenced) modopt(System.Runtime.CompilerServices.CallConvThiscall) <Module>::std.basic_string<char,std::char_traits<char>,std::allocator<char> >.erase(std.basic_string<char,std::char_traits<char>,std::allocator<char> >* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst),System.UInt32,System.UInt32)
Exception whilst trying to get the body of method System.Int32 modopt(System.Runtime.CompilerServices.IsLong) modopt(System.Runtime.CompilerServices.CallConvCdecl) <Module>::__get_default_appdomain(IUnknown**)
Exception whilst trying to get the body of method System.AppDomain <Module>::<CrtImplementationDetails>.GetDefaultDomain()
Exception whilst trying to get the body of method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) <Module>::<CrtImplementationDetails>.DoCallBackInDefaultDomain(method System.Int32 modopt(System.Runtime.CompilerServices.IsLong) modopt(System.Runtime.CompilerServices.CallConvStdcall) *(System.Void*),System.Void*)
Exception whilst trying to get the body of method System.Void <Module>::<CrtImplementationDetails>.LanguageSupport.DomainUnload(System.Object,System.EventArgs)
Exception whilst trying to get the body of method System.Void <Module>::<CrtImplementationDetails>.LanguageSupport.Cleanup(<CrtImplementationDetails>.LanguageSupport* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst),System.Exception)
Exception whilst trying to get the body of method System.Void modopt(System.Runtime.CompilerServices.CallConvThiscall) <Module>::<CrtImplementationDetails>.LanguageSupport.Initialize(<CrtImplementationDetails>.LanguageSupport* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst))
Exception whilst trying to get the body of method System.Int32 <Module>::_atexit_helper(method System.Void *(),System.UInt32*,method System.Void *()**,method System.Void *()**)
Exception whilst trying to get the body of method System.Void <Module>::_exit_callback()
Exception whilst trying to get the body of method System.Int32 <Module>::_initatexit_m()
Exception whilst trying to get the body of method System.Void <Module>::_app_exit_callback()
Exception whilst trying to get the body of method System.Void <Module>::_initterm_m(method System.Void modopt(System.Runtime.CompilerServices.IsConst)* *() modopt(System.Runtime.CompilerServices.IsConst)*,method System.Void modopt(System.Runtime.CompilerServices.IsConst)* *() modopt(System.Runtime.CompilerServices.IsConst)*)
Exception whilst trying to get the body of method System.Void myClass::Function1()
Exception whilst trying to get the body of method System.Void myClass::Function2(My class AsParamter)
Exception whilst trying to get the body of method System.Void myClass::Function3()
Exception whilst trying to get the body of method myTemplatedClass`1::function(otherLocalCallTemplated`1<T>)
Exception whilst trying to get the body of method System.Void <CrtImplementationDetails>.ModuleUninitializer::SingletonDomainUnload(System.Object,System.EventArgs)
Exception whilst trying to get the body of method System.Void modopt(System.Runtime.CompilerServices.CallConvThiscall) <Module>::std.basic_string<char,std::char_traits<char>,std::allocator<char> >._Tidy(std.basic_string<char,std::char_traits<char>,std::allocator<char> >* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst),System.Boolean,System.UInt32)
Exception whilst trying to get the body of method std.basic_string<char,std::char_traits<char>,std::allocator<char> >* modopt(System.Runtime.CompilerServices.IsImplicitlyDereferenced) modopt(System.Runtime.CompilerServices.CallConvThiscall) <Module>::std.basic_string<char,std::char_traits<char>,std::allocator<char> >.erase(std.basic_string<char,std::char_traits<char>,std::allocator<char> >* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst),System.UInt32,System.UInt32)
Exception whilst trying to get the body of method System.Int32 modopt(System.Runtime.CompilerServices.IsLong) modopt(System.Runtime.CompilerServices.CallConvCdecl) <Module>::__get_default_appdomain(IUnknown**)
Exception whilst trying to get the body of method System.AppDomain <Module>::<CrtImplementationDetails>.GetDefaultDomain()
Exception whilst trying to get the body of method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) <Module>::<CrtImplementationDetails>.DoCallBackInDefaultDomain(method System.Int32 modopt(System.Runtime.CompilerServices.IsLong) modopt(System.Runtime.CompilerServices.CallConvStdcall) *(System.Void*),System.Void*)
Exception whilst trying to get the body of method System.Void <Module>::<CrtImplementationDetails>.LanguageSupport.DomainUnload(System.Object,System.EventArgs)
Exception whilst trying to get the body of method System.Void <Module>::<CrtImplementationDetails>.LanguageSupport.Cleanup(<CrtImplementationDetails>.LanguageSupport* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst),System.Exception)
Exception whilst trying to get the body of method System.Void modopt(System.Runtime.CompilerServices.CallConvThiscall) <Module>::<CrtImplementationDetails>.LanguageSupport.Initialize(<CrtImplementationDetails>.LanguageSupport* modopt(System.Runtime.CompilerServices.IsConst) modopt(System.Runtime.CompilerServices.IsConst))
Exception whilst trying to get the body of method System.Int32 <Module>::_atexit_helper(method System.Void *(),System.UInt32*,method System.Void *()**,method System.Void *()**)
Exception whilst trying to get the body of method System.Void <Module>::_exit_callback()
Exception whilst trying to get the body of method System.Int32 <Module>::_initatexit_m()
Exception whilst trying to get the body of method System.Void <Module>::_app_exit_callback()
Exception whilst trying to get the body of method System.Void <Module>::_initterm_m(method System.Void modopt(System.Runtime.CompilerServices.IsConst)* *() modopt(System.Runtime.CompilerServices.IsConst)*,method System.Void modopt(System.Runtime.CompilerServices.IsConst)* *() modopt(System.Runtime.CompilerServices.IsConst)*)

**Comment by sawilde** [comment]
I didn't dump the exception as I only wanted to identify the methods that it can't handle - interesting output but I can't see why the 3rd party DLL can't handle your assemblies.

Other than dumping the messages did you get any coverage output?

**Comment by sawilde** [comment]
I've upgraded to the next flavour of mono.cecil and also skipping methods for which it can't decode the body. These skipped methods are marked up in the XML. As I don't use the c++/cli much I'd appreciate the feedback if you think code is being either incorrectly included (that we could ignore) or if we have skipped methods incorrectly.

I'm going to produce a new release candidate to nuget and then a new release later this week probably.

**Comment by beaudoinlaurent** [comment]
Hi, sorry for late response.

<quote>Other than dumping the messages did you get any coverage output?</quote>
Yes and no... I now do get coverage for the CLI assembly. This is an amelioration. 
However, some functions are not covered at all while it is clear that my test harness should cover them. 

I will re-test with the new release.

**Comment by sawilde** [comment]
> However, some functions are not covered at all while it is clear that my test harness should cover them.

It would be interested to know what functions they are - then it may be easier to repeat and see what the issue is.

**Comment by beaudoinlaurent** [comment]
I've build a dummy project where i can repeat the error. Where can i send this to you ?
The funny thing is that the CLI code does basicly nothings, except class instancitation...

**Comment by sawilde** [comment]
you can send it via email `shaun(_)wilde(at)hotmail(dot)com`

**Comment by sawilde** [comment]
I can't get it to crash with the latest code so I am going to make another RC for you to test

**Comment by sawilde** [comment]
try this - https://www.nuget.org/packages/OpenCover/4.5.4212-rc137

**Comment by sawilde** [comment]
https://github.com/OpenCover/opencover/releases/tag/4.6.166

**Comment by beaudoinlaurent** [comment]
Thanks. Tested with release 4.6.166 and it's now working !

**Comment by sawilde** [comment]
:+1:
