### ISSUE TITLE
Getting different coverage depending on whether my code was built through VS or MSBuild

### ISSUE THREAD

**Issue by andrewducker** [OpenCover/opencover#289]
I get different coverage stats on some classes depending on whether the code was build through VS 2010 (locally on developer's boxes) or through MSBuild (as part of the build process).

Here's an example from a local build:
![localbuild](https://cloud.githubusercontent.com/assets/91378/7086565/8ebea70c-df7a-11e4-953a-28ab0a061da2.PNG)
and from one created with MSBuild:
![msbuild](https://cloud.githubusercontent.com/assets/91378/7086569/99a4d1c8-df7a-11e4-83f5-602990169ed9.PNG)

In both cases I'm taking the resulting folder and running the same command line invocation of OpenCover.Console on it.

What would cause them to be different?

(MSBuild version is v4.0.30319  installed on a build server as part of the Windows 7 SDK.  VS2010 is version 10.0.40219.1 SP1Rel, using .Net Framework 4.5.50709 SP1Rel)

**Comment by andrewducker** [comment]
For further info, I checked them both with a decompiler and found they both had the same assembly attributes:
[assembly: TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.EnableEditAndContinue | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.Default)]
[assembly: CompilationRelaxations(8)]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows=true)]

**Comment by sawilde** [comment]
> What would cause them to be different?

nothing springs to mind - release/debug builds perhaps - do you have a sample project to help replicate?

**Comment by andrewducker** [comment]
Sadly, it's happening in about four classes out of several hundred.
Is there a general thing that causes opening brackets to count as coverage in some cases?

**Comment by molnargab** [comment]
Debug builds tend to have them. You can compare the actual IL code with [ILSpy](http://ilspy.net/) for example.

**Comment by sawilde** [comment]
If you can put a break point on it then there is a usually a sequence point about that will be instrumented. All the sequence points are extracted from the PDB files and they have the file/line number associated with them.

**Comment by andrewducker** [comment]
I took a look with ILSpy, and there were a couple of extra nops in there (and some of the methods were in a different order).  Other than that it all looked very similar.

And so, instead, I am running msbuild against the project before running nunit/opencover, and that replaces the built items with ones that give me the same result as the build on the server.

I don't think there's anything else you can do to fix this, sadly.

**Comment by sawilde** [comment]
What visual studio (.NET) are you using? Do the PDBs get rebuilt and placed in the correct location?
