### ISSUE TITLE
The configuration section 'connectionStrings' has an unexpected declaration

### ISSUE THREAD

**Issue by bry4ngh0st** [OpenCover/opencover#290]
I'm getting the next message after try to run any NUnit test.

The configuration section 'connectionStrings' has an unexpected declaration.

![image](https://cloud.githubusercontent.com/assets/7027686/7142375/a77bbeb2-e29d-11e4-88ae-af91ff54510d.png)

Regards

**Comment by sawilde** [comment]
Not sure what that has to do with OpenCover perhaps you can expand with a little more detail.

**Comment by bry4ngh0st** [comment]
Below I show the installation steps, I don't know if there is a wrong or missing step.

OpenCover UI from https://visualstudiogallery.msdn.microsoft.com/6950a046-8919-4935-8542-c6f37956f688
![image](https://cloud.githubusercontent.com/assets/7027686/7161291/04d88a2a-e354-11e4-9158-260bd3a674b8.png)

OpenCover from https://github.com/sawilde/opencover/releases
![image](https://cloud.githubusercontent.com/assets/7027686/7161403/8155d4ae-e354-11e4-8e62-59c40a5e5cfe.png)

My installation path
![image](https://cloud.githubusercontent.com/assets/7027686/7161419/9981c84e-e354-11e4-9886-8c4d28700666.png)

Trying to run test coverage
![image](https://cloud.githubusercontent.com/assets/7027686/7161434/bb3bf07c-e354-11e4-83e0-78e8161c0ded.png)

Error message
![image](https://cloud.githubusercontent.com/assets/7027686/7161445/c406715a-e354-11e4-94e9-cdaa0a9530e5.png)

I appreciate your help, thanks

**Comment by sawilde** [comment]
Ah - [OpenCoverUI](https://github.com/OpenCoverUI/OpenCover.UI) is actually a different project developed by a different team - you should look to raise the issue with them.

As OpenCover does not have a connectionStrings [config section](https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Console/app.config) (no database you see) so this issue may be with the add-in or nunit itself.

**Comment by sawilde** [comment]
or even in the config files associated with your assemblies
