### ISSUE TITLE
Lines shown as not covered when they are

### ISSUE THREAD

**Issue by dcumbo** [OpenCover/opencover#291]
I have multiple scenarios where lines are shown as not covered by unit tests when they are, as shown in the image below:
![image](https://cloud.githubusercontent.com/assets/80220/7160276/49b14b26-e388-11e4-8509-b69535a609df.png)

If I run the same tests through dotCover I get the below:

![image](https://cloud.githubusercontent.com/assets/80220/7160337/a642c2c0-e388-11e4-8081-27dbec01826b.png)

I have tried running code coverage using both Debug and Release.

**Comment by sawilde** [comment]
What version of OpenCover are you running?

Please supply your code and tests if possible so we can replicate - I know this sounds odd but I have not seen this issue so I want to be able to replicate your scenario and not one of my own which may not reproduce your issue (I hope that makes sense).

**Comment by dcumbo** [comment]
Turns out this is not an opencover issue, but an OpenCoverUI issue (not merging results). I added a folder OpenCover to the solution and created the config file OpenCover.UI.config. In this file I put the following configuration:

```
<Root>
  <Parameters>
    <Parameter name='mergebyhash'>true</Parameter>
    <Parameter name='register'>user</Parameter>
  </Parameters>
</Root>
```

This was enough to get the correct output.

**Comment by sawilde** [comment]
awesome - the OpenCoverUI guys are looking at pushing out a new release soon.
