### ISSUE TITLE
Spec for the output XML

### ISSUE THREAD

**Issue by Jericho** [OpenCover/opencover#293]
Is there any documentation regarding the format of the XML that OpenCover writes in the output file?

**Comment by stevepeak** [comment]
:+1: I'm looking to add support to [Codecov](https://codecov.io) (I'm the founder).

I would like some help with understanding how I can translate the `xml` produced by your project. Thank you!

**Comment by molnargab** [comment]
I'm not aware if we had any. You could check [the model namespace](https://github.com/OpenCover/opencover/tree/e715910bb52e327ae6df059aeea71dff4b54ee50/main/OpenCover.Framework/Model) though, it has the classes with attributes used for producing the output file.

You can also use the [XSD tool](https://msdn.microsoft.com/en-us/library/x6c1kb0s%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) if you want to work with XSDs, e.g.: `xsd OpenCover.Framework.dll /type:OpenCover.Framework.Model.Module`

**Comment by sawilde** [comment]
The xml is, as @molnargab has pointed out, just a deserialized object. It is fairly simple and is already supported by [coveralls.net](https://github.com/csMACnz/coveralls.net) and [ReportGenerator](https://github.com/danielpalme/ReportGenerator) amongst others. 

When we make changes we only ever add to the model i.e. maintain backward compatibility. So you should be loose with your parsing in that your code should ignore elements and attributes within the xml it does not understand.

I hope the xml is self explanatory but feel free to ask questions.

**Comment by stevepeak** [comment]
Thanks @molnargab and @sawilde for your help! I'll review the modals and get back to you if I have questions.

> Uploading reports will be handled by Codecov's global uploaders via [python][0] or [bash][1]. There will be no "native" uploader for C# (unless someone contributes it). But the global uploader support all Codecov's features, which will do the trick. Thank you!

[0]: https://github.com/codecov/codecov-python
[1]: https://github.com/codecov/codecov-bash

**Comment by stevepeak** [comment]
I'm unable to fully understand the modal namespace (never seen C# before) so I came up with [this gist][0] file in hopes you can fill in the blanks. Its quit simple: I would like a hash of file names containing a hash of the lines covered.

I've already prepared Codecov to upload these files, just need a little assistance in the translation. I appreciate your help! And please point out any issues or missing data I may have in the provided `xml`, I stripped it down to only a couple lines for simplicity.

[0]: https://gist.github.com/stevepeak/ccb0f2c8061955ba2503
https://gist.github.com/stevepeak/ccb0f2c8061955ba2503

**Comment by sawilde** [comment]
hash? I assume you mean [ruby hash](http://ruby-doc.org/core-2.2.0/Hash.html) from the syntax in your code sample; whenever I see hash I instantly think of [cryptography](http://en.wikipedia.org/wiki/Cryptographic_hash_function).

Each method can only be in one file so it will have a reference `<FileRef/>` to the file in question.

Each method has a number of sequence points that count the lines (partial?) hit within that file

    @sl - source line
    @sc - source column
    @el - end line
    @ec - end column

* I think you will find it easier to consider all lines as partial unless you wish to determine if a line has been fully covered or not.

Each method has a number of branch points that count the IL branch paths taken - these may be less useful to you as these are IL paths (i.e. after C# has been compiled) and so do not always translate to the C#/VB/F# code being covered.

**Comment by stevepeak** [comment]
Not hash - a dictionary key=>val is what I ment, sorry for the typo. 




I'll use this information and finish the uploading. Codecov does support partial line coverage in its api and UI. So this should all work out.



Steve

**Comment by sawilde** [comment]
> Codecov does support partial line coverage in its api 

That's a shame - neither does coveralls (last time I looked)

**Comment by stevepeak** [comment]
Codecov does, I built it.

Coveralls does not...so I've been told.




Thanks



Steve

**Comment by sawilde** [comment]
:) oops - sorry mis-read what you said - awesome!

**Comment by stevepeak** [comment]
What is the naming schema for coverage xml files? Would it always match `*coverage.xml`. Thanks!

**Comment by sawilde** [comment]
whatever they want it to be - from the [wiki](https://github.com/OpenCover/opencover/wiki/Usage)

`-output:<output file>` - The location and name of the output Xml file. If no value is supplied then the current directory will be used and the output filename will be `results.xml`

**Comment by sawilde** [comment]
If you need any more help please reopen or raise a new issue

**Comment by stevepeak** [comment]
Hey @sawilde I'm revisiting this integration. Can you elaborate on [your comment above](https://github.com/OpenCover/opencover/issues/293#issuecomment-94325904)

I'm attempting to show customer partial line coverage as seen in the screenshot below. But I'm having trouble understanding the values for `sc` and `ec` they do not seem to be aligning with the code itself.

```
<SequencePoint vc="8" uspid="38" ordinal="2" offset="52" sl="190" sc="4" el="190" ec="24" bec="2" bev="2" fileid="1" />
<SequencePoint vc="1" uspid="39" ordinal="3" offset="61" sl="190" sc="25" el="190" ec="119" bec="0" bev="0" fileid="1" />
```

```
            if (status.HasValue) parameters.Add(new KeyValuePair<string, object>("status", status.Value.GetEnumMemberValue()));
```

But column 4 -> 24 is essentially `        if (status.H`. This is where I'm stuck.

Thank you again for your help!

**Comment by sawilde** [comment]
Sorry I don't understand where you are confused - as you said 4-24 is `if (status.HasValue)` so that piece of code was visited 8 times, the next sequence point 24-119 is the `parameters....` and that was visited once, all on the same line - so from what you have said above that is right.

**Comment by stevepeak** [comment]
I read this as:

- column `4-24` == `(status.HasValue) pa` not `if (status.HasValue)` (which would be `1-20`)
- column `24-119` == `rameters.Add(new KeyValuePair<string, object>("status", status.Value.GetEnumMemberValue()));   ` (not the trailing whitespace)

My questions
1. Where is column 1?
1. Is starting and trailing whitespace ignored?
2. How can you get `if (status.HasValue)` from column 4-24?

**Comment by sawilde** [comment]
I think you may find that the `if` is 4 chars in (white-space is included) note this is in the information in the PDB that is collected during compilation - OpenCover doesn't look at the actual file itself.

        if (status.HasValue) ...
        ^                   ^
    0123456789012345678901234567890
    0000000000111111111122222222223

I hope this makes more sense (the above needs a monospaced font)

**Comment by jrnail23** [comment]
I assumed OpenCover's xml output is the same as PartCover's output.  Is that incorrect?

**Comment by sawilde** [comment]
@jrnail23 - no - it was similar but OpenCover's output has changed as more data has been made available
