### ISSUE TITLE
Consider allowing exclusion attributes at the assembly level

### ISSUE THREAD

**Issue by stephentoub** [OpenCover/opencover#295]
Today an ExcludeFromCodeCoverage attribute can be placed on a method or class.  It'd be nice if it could also be recognized at the assembly level such that the entire assembly is excluded.  While the tool today does allow for assembly exclusion based on assembly name, it's not always practical to craft inclusion/exclusion naming rules that account for all cases.

**Comment by sawilde** [comment]
It's a thought - as you say we allow it at the class/method. 

I am not a big fan of exclusions as I feel it takes great willpower to `not` exclude stuff unnecessarily, something I feel that developers have easily succumbed to under giving the illusion of 100% coverage to management.

**Comment by stephentoub** [comment]
That's fair. In the case I'm looking at, the things I want to exclude are helper assemblies in the tests, not the actual code under test.

**Comment by stephentoub** [comment]
@sawilde, thanks for addressing this.  No pressure, but do you have a sense for when the next release will be?

**Comment by sawilde** [comment]
Soon - bit distracted with work and other stuff - I would say I hoping for things to calm down but they never seem to do so :)

**Comment by stephentoub** [comment]
Thanks :)

**Comment by stephentoub** [comment]
@sawilde, thanks for addressing this.  We updated corefx to use it, and it appears to be working well.
