### ISSUE TITLE
Coverage for Assemblies Not included in any test project

### ISSUE THREAD

**Issue by aaronmell** [OpenCover/opencover#300]
I have a rather large multiple solution .net project, and I am curious if this is the intended behavior. I only see coverage generated for the assemblies under test. IE: I have a large part of the project that is not referenced by any unit test project, and none of those assemblies are showing up as lacking test coverage.

I am using an nunit test project if that matters. 
Typically its a test project for each project in my sln.

Now, if that is the intended behavior, how can I get all of the projects for a given solution showing up? I want the coverage to reflect the complete state of the sln, even if my percentage is very low. It looks like I need to reference those project in a test project if I want them to show up, but I am not sure if ther is a better way to handle it.

**Comment by sawilde** [comment]
You are correct only assemblies actually loaded by the runtime will show up in your coverage reports - this is intentional.

The best way is, as you say, to reference them to a test project and do something to force the runtme to load them i.e. a single test per assembly should suffice.
