### ISSUE TITLE
Failing test that relies on CurrentUICulture

### ISSUE THREAD

**Issue by BennyTordrupVisma** [OpenCover/opencover#301]
I have a test that relies on setting the CurrentUICulture in order to have a resource manager load language specific strings during the test.

The test succeeds in Visual Studio, but when running it using OpenCover, it fails.

I suspect the problem to be that the Resources directory containing the language files is not copied to the Out folder in the TestResults sub folder - and hence, the files cannot be found by the resource manager.

Is there a way to circumvent this until a fix is ready?

**Comment by sawilde** [comment]
Have you tested this just using the test utility on the command line without OpenCover?

**Comment by BennyTordrupVisma** [comment]
I'm running the tests in Visual Studio, and there they succeed.
How can I test it on command line without OpenCover?

**Comment by sawilde** [comment]
How do you run it with OpenCover?

**Comment by BennyTordrupVisma** [comment]
This is the command issued:


.\packages\OpenCover.4.5.3207\OpenCover.Console.exe -target:"C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\MSTest.exe"  -targetargs:/testcontainer:AOUnitTests\bin\Debug\AOUnitTests.dll /nologo  -register:user -mergebyhash  -filter:"+[DocumentImport*]* +[Visma.AccountingOffice*]*" 
 -excludebyfile:*\*Designer.cs;*\*.g.cs;*\*.g.i.cs 


It seems like a directory is created in the TestResults folder for each run from OpenCover. The folder contains my user name, machine name and time of execution. In that folder, there is an Out folder where all the binaries are copied - including the AOUnitTests.dll referenced in the command line.

But the tests will look for a folder named Resources containing two xml files with translations. They are not present in the Out folder, and I think that is the cause of failure for these tests.

**Comment by sawilde** [comment]
Okay - it could be a difference in the test runner in Visual Studio vs the one command line runner.

**Comment by BennyTordrupVisma** [comment]
Closed by accident :-(

Is there a way to force usage of the same test session using OpenCover? In that case, I could just copy the Resources directory into the test session directory - they are not often changed.

**Comment by BennyTordrupVisma** [comment]
Changed the command line to Visual Studio 12 version of MSTest - no change.

**Comment by molnargab** [comment]
Have you tried running the tests with only MSTest? E.g. by `C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\MSTest.exe /testcontainer:AOUnitTests\bin\Debug\AOUnitTests.dll`

There could be differences to what you would expect from the Visual Studio run.
Once I had some issues with MSTest due to files missing from the [deployment](https://msdn.microsoft.com/en-us/library/ms182475.aspx). By default only a couple of files (mostly referenced assemblies) are copied for a test run.

**Comment by BennyTordrupVisma** [comment]
Gives a different result as when executing from Visual Studio, i.e. have the same failing tests as when using OpenCover

**Comment by BennyTordrupVisma** [comment]
Found a solution from this thread: http://stackoverflow.com/questions/17907884/running-mstest-from-the-command-line-with-a-custom-assembly-base-directory

Changed my command line to use the vstest.console.exe instead of MSText.exe

**Comment by BennyTordrupVisma** [comment]
My command now looks like this:

.\packages\OpenCover.4.5.3207\OpenCover.Console.exe ^
 -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" ^
 -targetargs:AOUnitTests\bin\Debug\AOUnitTests.dll /Framework:Framework45 /Platform:x86 ^
 -register:user ^
 -mergebyhash ^
 -filter:"+[DocumentImport*]* +[Visma.AccountingOffice*]*" ^
 -excludebyfile:*\*Designer.cs;*\*.g.cs;*\*.g.i.cs 

This causes the same tests to succeed in command line as in Visual Studio.

**Comment by sawilde** [comment]
awesome :)
