### ISSUE TITLE
NUnit TestCases are not recognized as Tracked Methods

### ISSUE THREAD

**Issue by leemorris** [OpenCover/opencover#303]
Recommend changing the GetTrackedMethod as follows:

 public IEnumerable<TrackedMethod> GetTrackedMethods(IEnumerable<TypeDefinition> typeDefinitions)
        {
            return (from typeDefinition in typeDefinitions
                    from methodDefinition in typeDefinition.Methods
                    from customAttribute in methodDefinition.CustomAttributes
                    where customAttribute.AttributeType.FullName == "NUnit.Framework.TestAttribute" 
                          || customAttribute.AttributeType.FullName == "NUnit.Framework.TestCaseAttribute"
                    select new TrackedMethod()
                    {
                        MetadataToken = methodDefinition.MetadataToken.ToInt32(),
                        Name = methodDefinition.FullName,
                        Strategy = "NUnitTest"
                    }).Distinct();
        }

**Comment by sawilde** [comment]
Thanks @leemorris, looks like a great idea

**Comment by molnargab** [comment]
Good point. Looking at the NUnit docs, I think we should add support for a couple of more, such as [`Theory`](http://www.nunit.org/index.php?p=theory&r=2.5) or [`Repeat`](http://www.nunit.org/index.php?p=repeat&r=2.5) (not sure on the usage for `Repeat` though).

It seems NUnit has a [`TestCaseBuilderAttribute`](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestCaseBuilderAttribute.cs) base class for these attributes. Also the attributes have interfaces, such as `ITestBuilder` and `ISimpleTestBuilder`. Perhaps we could have something more general this way.

**Comment by molnargab** [comment]
@leemorris, could you check if [this build](https://ci.appveyor.com/api/buildjobs/97spo0yoijcj0cmj/artifacts/main/bin/zip/opencover.4.5.4030.zip) works for your test attributes?

**Comment by sawilde** [comment]
try this - https://www.nuget.org/packages/OpenCover/4.5.4212-rc137

**Comment by sawilde** [comment]
https://github.com/OpenCover/opencover/releases/tag/4.6.166
