### ISSUE TITLE
Enhancement: Ability to set OpenCover's timeout length when waiting for another program to start

### ISSUE THREAD

**Issue by SECogan** [OpenCover/opencover#304]
I have a Windows service I'm trying to cover with OpenCover. This service takes a significant amount of time to startup. During this time, OpenCover times out, and the service finishes starting after OpenCover has closed. 

I would like a way to somehow configure OpenCover to wait longer during this step, either as a command-line switch or configuration option. I feel that this is something that would not only be useful to this specific instance, but could be used for many other programs as well.

Thank you, and let me know if you need any further information.

**Comment by molnargab** [comment]
@SECogan, could you check [this build](https://ci.appveyor.com/api/buildjobs/39ic8wq62599r9tp/artifacts/main/bin/zip/opencover.4.5.4111.zip)? It has a new option -servicestarttimeout.

**Comment by SECogan** [comment]
@molnargab I'll give that a shot and let you know how it works. Thanks!

**Comment by sawilde** [comment]
try this - https://www.nuget.org/packages/OpenCover/4.5.4212-rc137

**Comment by sawilde** [comment]
https://github.com/OpenCover/opencover/releases/tag/4.6.166
