### ISSUE TITLE
Cannot skip method from being reported

### ISSUE THREAD

**Issue by sanastasiou** [OpenCover/opencover#306]
Hi,

I need to hide following method from the report

`System.Windows.Freezable RTextNppPlugin.Utilities.BindingProxy::CreateInstanceCore()`

Said method is protected and also has the attribute 

`[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]`

My command line:

-excludebyattribute:"\*.ExcludeFromCodeCoverage\*" -skipautoprops -hideskipped:All

Can you tell me what am I doing wrong?

**Comment by sawilde** [comment]
Nothing looks obviously wrong - have you opened the assembly in ILSpy and examined what attributes are associated with the method?

**Comment by sanastasiou** [comment]
I just did,

![image](https://cloud.githubusercontent.com/assets/2955627/7782718/c97d2d56-0125-11e5-9414-beaf1c8b4be6.png)

Seems ok to me..

**Comment by sanastasiou** [comment]
Issue fixed. I was using the fully qualified name of the attribute, but after seeing IL I changed it to use only the "short" name. Then it worked. Sorry for the time.

**Comment by sawilde** [comment]
:)
