### ISSUE TITLE
Uncovered branches in C# iterators

### ISSUE THREAD

**Issue by ulrichb** [OpenCover/opencover#310]
```C#
public static class Iterator
{
    public static IEnumerable<string> Go()
    {
        yield return "one";
        yield return "two";
        yield return "three";
    }
}

[TestFixture]
public class IteratorTest
{
    [Test]
    public void FirstTest()
    {
        Assert.That(Iterator.Go(), Is.EqualTo(new[] {"one", "two", "three"}));
    }
}
```

When running the test listed above with OpenCover, I get one uncovered branch in `Iterator.Go()`.

```
$ packages\OpenCover.4.5.3723\OpenCover.Console.exe -target:packages\NUnit.Runners.2.6.4\tools\nunit-console.exe -targetargs:"OpenCoverIterator\bin\Debug\OpenCoverIterator.dll /nologo /noshadow /framework=net-4.0 /domain=Multiple" -register:user
ProcessModel: Default    DomainUsage: Multiple
Execution Runtime: net-4.0
.
Tests run: 1, Errors: 0, Failures: 0, Inconclusive: 0, Time: 0,295387005119281 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Committing...
Visited Classes 2 of 2 (100)
Visited Methods 2 of 2 (100)
Visited Points 8 of 8 (100)
Visited Branches 6 of 7 (85.71)
```
![screen](https://cloud.githubusercontent.com/assets/388796/7920892/fb87dc28-08a1-11e5-8f0b-6198eba12c56.png)

Is this uncovered branch reported on purpose, or is this a missing implicit exclusion for internal iterator branches?

**Comment by sawilde** [comment]
OpenCover deals with IL only and it looks like there is a branch at this point of the IL - have a look in the XML produced as to where branch is and then using ILSpy perhaps and see what the IL looks like.

**Comment by ulrichb** [comment]
This is the snippet of the `result.xml`:
```
<Method visited="true" cyclomaticComplexity="6" sequenceCoverage="100" branchCoverage="83.33" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
  <Summary numSequencePoints="5" visitedSequencePoints="5" numBranchPoints="6" visitedBranchPoints="5" sequenceCoverage="100" branchCoverage="83.33" maxCyclomaticComplexity="6" minCyclomaticComplexity="6" />
  <MetadataToken>100663303</MetadataToken>
  <Name>System.Boolean OpenCoverIterator.Iterator/&lt;Go&gt;d__0::MoveNext()</Name>
  <FileRef uid="1" />
  <SequencePoints>
[...]
  </SequencePoints>
  <BranchPoints>
    <BranchPoint vc="0" uspid="12" ordinal="0" offset="8" sl="13" path="0" offsetchain="29 39" offsetend="137" fileid="1" />
    <BranchPoint vc="1" uspid="13" ordinal="1" offset="8" sl="13" path="1" offsetchain="37" offsetend="41" fileid="1" />
    <BranchPoint vc="1" uspid="14" ordinal="2" offset="8" sl="13" path="2" offsetchain="31" offsetend="71" fileid="1" />
    <BranchPoint vc="1" uspid="15" ordinal="3" offset="8" sl="13" path="3" offsetchain="33" offsetend="100" fileid="1" />
    <BranchPoint vc="1" uspid="16" ordinal="4" offset="8" sl="13" path="4" offsetchain="35" offsetend="129" fileid="1" />
  </BranchPoints>
  <MethodPoint vc="4" uspid="17" ordinal="0" offset="0" />
</Method>
```
... and the IL code of `MoveNext()`:
```
.method private final hidebysig newslot virtual 
	instance bool MoveNext () cil managed 
{
	.override method instance bool [mscorlib]System.Collections.IEnumerator::MoveNext()
	.maxstack 2
	.locals init (
		[0] bool,
		[1] int32
	)

	IL_0000: ldarg.0
	IL_0001: ldfld int32 OpenCoverIterator.Iterator/'<Go>d__0'::'<>1__state'
	IL_0006: stloc.1
	IL_0007: ldloc.1
	IL_0008: switch (IL_0025, IL_001f, IL_0021, IL_0023)

	IL_001d: br.s IL_0027
	IL_001f: br.s IL_0047
	IL_0021: br.s IL_0064
	IL_0023: br.s IL_0081
	IL_0025: br.s IL_0029
	IL_0027: br.s IL_0089

	IL_0029: ldarg.0
	IL_002a: ldc.i4.m1
	IL_002b: stfld int32 OpenCoverIterator.Iterator/'<Go>d__0'::'<>1__state'
	IL_0030: nop
	IL_0031: ldarg.0
	IL_0032: ldstr "one"
	IL_0037: stfld string OpenCoverIterator.Iterator/'<Go>d__0'::'<>2__current'
	IL_003c: ldarg.0
	IL_003d: ldc.i4.1
	IL_003e: stfld int32 OpenCoverIterator.Iterator/'<Go>d__0'::'<>1__state'
	IL_0043: ldc.i4.1
	IL_0044: stloc.0
	IL_0045: br.s IL_008d

[... branches for "two" and "three" ... ]

	IL_0081: ldarg.0
	IL_0082: ldc.i4.m1
	IL_0083: stfld int32 OpenCoverIterator.Iterator/'<Go>d__0'::'<>1__state'
	IL_0088: nop

	IL_0089: ldc.i4.0
	IL_008a: stloc.0
	IL_008b: br.s IL_008d

	IL_008d: ldloc.0
	IL_008e: ret
} // end of method '<Go>d__0'::MoveNext
```

... so the problem seems to be the fall-through branch at `IL_001d` (which then jumps to `IL_0027`), which corresponds to the `vc=0` "branch point" with `offsetchain="29 39"`.

The problem is that a caller of the iterator method normally doesn't reach the fall-through, and therefore, IMO, this should be excluded implicitly by OpenCover.

BTW: The following code reaches the fall-through by using reflection to set "state" to -100 and therefore leads to 100% branch coverage.

```C#
[Test]
public void SetState()
{
    var enumerator = Iterator.Go().GetEnumerator();

    var type = enumerator.GetType();
    var fieldInfo = type.GetField("<>1__state", BindingFlags.Instance | BindingFlags.NonPublic);
    fieldInfo.SetValue(enumerator, -100);

    enumerator.MoveNext();

    Assert.That(enumerator.Current, Is.EqualTo(null));
}
```

**Comment by molnargab** [comment]
You could also trigger this case by calling `MoveNext` 2 times, after you've reached the end of the enumerator.

It would be good to handle this case, it also has line number `0xFEEFEE` in the PDB.
I think we would need to exclude all branches from compiler generated code in order to resolve this, unlike `using` blocks, where we could limit the scope for generated try-catch blocks.

**Comment by sawilde** [comment]
I'm looking at seeing if I should just ignore branches in MoveNext methods that follow certain patterns; but keep those branches that seem to encapsulate a sequence point. I've started on something similar for #302 and I think it may apply here.

It may need some testing however and quiet a few samples to see if it feasible.

**Comment by sawilde** [comment]
First step is to just to ignore the initial switch outright if we are in a generated MoveNext

**Comment by ulrichb** [comment]
@sawilde Firstly, big thanks for implementing this filter.

During testing this, I found one issue with the iterators generated by Roslyn 1.0 in VS 2015. If the iterator contains only one `yield return`, the compiler will emit two branches instead of a `switch`, which is not detected by your filter. See the following snippets.

```C#
public static IEnumerable<string> SingleItem()
{
    yield return "single item";
}
```

Generated IL of Roslyn 1.0:
<pre>
.method private hidebysig newslot virtual final instance bool MoveNext() cil managed
{
    .override [mscorlib]System.Collections.IEnumerator::MoveNext
    .maxstack 2
    .locals init (
        [0] int32 num)
    L_0000: ldarg.0 
    L_0001: ldfld int32 OpenCoverIterator.Iterator/<SingleString>d__1::<>1__state
    L_0006: stloc.0 
    L_0007: ldloc.0 
<b>    L_0008: brfalse.s L_0012
    L_000a: br.s L_000c
    L_000c: ldloc.0 
    L_000d: ldc.i4.1 
    L_000e: beq.s L_0014
    L_0010: br.s L_0016
    L_0012: br.s L_0018
    L_0014: br.s L_0034
    L_0016: ldc.i4.0 
    L_0017: ret</b>
    L_0018: ldarg.0 
    L_0019: ldc.i4.m1 
    L_001a: stfld int32 OpenCoverIterator.Iterator/<SingleString>d__1::<>1__state
    L_001f: nop 
    L_0020: ldarg.0 
    L_0021: ldstr "single"
    L_0026: stfld string OpenCoverIterator.Iterator/<SingleString>d__1::<>2__current
    L_002b: ldarg.0 
    L_002c: ldc.i4.1 
    L_002d: stfld int32 OpenCoverIterator.Iterator/<SingleString>d__1::<>1__state
    L_0032: ldc.i4.1 
    L_0033: ret 
    L_0034: ldarg.0 
    L_0035: ldc.i4.m1 
    L_0036: stfld int32 OpenCoverIterator.Iterator/<SingleString>d__1::<>1__state
    L_003b: ldc.i4.0 
    L_003c: ret 
}
</pre>

In comparison to generated IL of `csc.exe` of VS 2013:
<pre>
.method private hidebysig newslot virtual final instance bool MoveNext() cil managed
{
    .override [mscorlib]System.Collections.IEnumerator::MoveNext
    .maxstack 2
    .locals init (
        [0] bool flag,
        [1] int32 num)
    L_0000: ldarg.0 
    L_0001: ldfld int32 OpenCoverIterator.Iterator/<SingleString>d__3::<>1__state
    L_0006: stloc.1 
    L_0007: ldloc.1 
<b>    L_0008: switch (L_0019, L_0017)
    L_0015: br.s L_001b
    L_0017: br.s L_003b
    L_0019: br.s L_001d
    L_001b: br.s L_0043</b>
    L_001d: ldarg.0 
    L_001e: ldc.i4.m1 
    L_001f: stfld int32 OpenCoverIterator.Iterator/<SingleString>d__3::<>1__state
    L_0024: nop 
    L_0025: ldarg.0 
    L_0026: ldstr "single"
    L_002b: stfld string OpenCoverIterator.Iterator/<SingleString>d__3::<>2__current
    L_0030: ldarg.0 
    L_0031: ldc.i4.1 
    L_0032: stfld int32 OpenCoverIterator.Iterator/<SingleString>d__3::<>1__state
    L_0037: ldc.i4.1 
    L_0038: stloc.0 
    L_0039: br.s L_0047
    L_003b: ldarg.0 
    L_003c: ldc.i4.m1 
    L_003d: stfld int32 OpenCoverIterator.Iterator/<SingleString>d__3::<>1__state
    L_0042: nop 
    L_0043: ldc.i4.0 
    L_0044: stloc.0 
    L_0045: br.s L_0047
    L_0047: ldloc.0 
    L_0048: ret 
}
</pre>

**Comment by sawilde** [comment]
Thanks - I've not been working on VS2015 in anger yet - I tried upgrading OpenCover to use the new Community Edition and had so many issues I decided to leave it a while.

**Comment by ulrichb** [comment]
Oh ... :fearful:

**Comment by sawilde** [comment]
it was the C++ stuff that caused issues as I was looking to update the supported interfaces - now i've knocked a few big issues off though I can get back to it

**Comment by ddur** [comment]
I'm investigating similar case too. Maybe is a bug.

**Comment by ddur** [comment]
"{" is not branch statement. There should not be any branch under "{" SequencePoint.
Recent releases remove all (compiler generated) branches under  "{" and "}" SequencePoints, where possible due to compiler rewriting.
