### ISSUE TITLE
Methods reporting as not visited when they are

### ISSUE THREAD

**Issue by DAndreChampagne** [OpenCover/opencover#312]
I have an abstract C# class that exposes virtual methods. When I inherit the class, the virtual methods are called and executed appropriately, however, OpenCover seems to not register them as being visited.

I'm using OpenCover.4.5.3723 and ReportGenerator.2.1.4.0, both obtained from Nuget.

![new bitmap image](https://cloud.githubusercontent.com/assets/2564427/7986319/dfdaf050-0aa4-11e5-8026-306f8c8606b5.png)

This is the unit test that successfully calls the SaveChanges() method:

    namespace Dac.Tests.Framework.DAL {

        [TestClass]
        public class RepositoryBaseTests {
            TestUser _User;
            IRepository<TestUser> _Repository;

            // shim class for testing abstract class methods
            public class RepositoryBaseShim : RepositoryBase<TestUser> {
                public RepositoryBaseShim() : base(new TestDbContainer1()) { }
            }

            [TestInitialize]
            public void Initialize() {
                _Repository = new RepositoryBaseShim();
                _User = new TestUser {
                    Name = "Bob Dole",
                };
            }

            [TestMethod]
            public void SaveChanges() {
                DbEntityValidationException exception = null;

                try {
                    _Repository.SaveChanges(); // calls the virtual method just fine
                } catch (DbEntityValidationException ex) {
                    exception = ex;
                }

                Assert.IsNull(exception);
            }
        }
    }

This is the class class:

    namespace Dac.Framework.DAL {

        public abstract class RepositoryBase<T> : IRepository<T> where T : class, IEntity {
            protected internal DbContext Context { get; set; }
            protected internal DbSet<T> DbSet { get; set; }

            public static PluralizationService PluralizationService { get; protected internal set; }

            static RepositoryBase() {
                RepositoryBase<T>.PluralizationService = PluralizationService.CreateService(new CultureInfo("en-us"));
            }

            public RepositoryBase(DbContext context) {
                this.Context = context;
                this.DbSet = Context.Set<T>();
            }

            // edited for brevity...

            public virtual void SaveChanges() {
                try {
                    this.Context.SaveChanges();
                } catch (DbEntityValidationException ex) {
                    foreach (var ve in ex.EntityValidationErrors) {
                        foreach (var v in ve.ValidationErrors) {
                            Debug.WriteLine("property: '{0}', message: '{1}'", v.PropertyName, v.ErrorMessage);
                        }
                    }
                    throw;
                }
            }
        }
    }

In looking at the XML output from OpenCover, it looks like (if I'm reading this correctly) the visited count is never being incremented. Even though there are multiple calls to this function throughout the application.

            <Method visited="false" cyclomaticComplexity="5" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="21" visitedSequencePoints="0" numBranchPoints="5" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="5" minCyclomaticComplexity="5" />
              <MetadataToken>100663387</MetadataToken>
              <Name>System.Void Dac.Framework.DAL.RepositoryBase`1::SaveChanges()</Name>
              <FileRef uid="11" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="203" ordinal="0" offset="0" sl="51" sc="43" el="51" ec="44" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="204" ordinal="1" offset="1" sl="52" sc="17" el="52" ec="18" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="205" ordinal="2" offset="2" sl="53" sc="17" el="53" ec="44" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="206" ordinal="3" offset="14" sl="54" sc="13" el="54" ec="14" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="207" ordinal="4" offset="20" sl="54" sc="15" el="54" ec="53" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="208" ordinal="5" offset="21" sl="54" sc="54" el="54" ec="55" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="209" ordinal="6" offset="22" sl="55" sc="17" el="55" ec="24" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="210" ordinal="7" offset="23" sl="55" sc="36" el="55" ec="61" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="211" ordinal="8" offset="37" sl="55" sc="26" el="55" ec="32" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="212" ordinal="9" offset="44" sl="55" sc="63" el="55" ec="64" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="213" ordinal="10" offset="45" sl="56" sc="21" el="56" ec="28" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="214" ordinal="11" offset="46" sl="56" sc="39" el="56" ec="58" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="215" ordinal="12" offset="61" sl="56" sc="30" el="56" ec="35" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="216" ordinal="13" offset="69" sl="56" sc="60" el="56" ec="61" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="217" ordinal="14" offset="70" sl="57" sc="25" el="57" ec="108" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="218" ordinal="15" offset="111" sl="58" sc="21" el="58" ec="22" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="219" ordinal="16" offset="112" sl="56" sc="36" el="56" ec="38" bec="2" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="220" ordinal="17" offset="148" sl="59" sc="17" el="59" ec="18" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="221" ordinal="18" offset="149" sl="55" sc="33" el="55" ec="35" bec="2" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="222" ordinal="19" offset="182" sl="60" sc="17" el="60" ec="23" bec="0" bev="0" fileid="11" />
                <SequencePoint vc="0" uspid="223" ordinal="20" offset="185" sl="62" sc="9" el="62" ec="10" bec="0" bev="0" fileid="11" />
              </SequencePoints>
              <BranchPoints>
                <BranchPoint vc="0" uspid="224" ordinal="0" offset="123" sl="56" path="0" offsetend="125" fileid="11" />
                <BranchPoint vc="0" uspid="225" ordinal="1" offset="123" sl="56" path="1" offsetend="61" fileid="11" />
                <BranchPoint vc="0" uspid="226" ordinal="2" offset="159" sl="55" path="0" offsetend="161" fileid="11" />
                <BranchPoint vc="0" uspid="227" ordinal="3" offset="159" sl="55" path="1" offsetend="37" fileid="11" />
              </BranchPoints>
              <MethodPoint xsi:type="SequencePoint" vc="0" uspid="203" ordinal="0" offset="0" sl="51" sc="43" el="51" ec="44" bec="0" bev="0" fileid="11" />
            </Method>

The best part about this is that I tried taking out this code and putting it into a standalone application, and there it worked fine and the function calls were successfully counted. So I'm not sure if this is because of a setting within Visual Studio that I can change, or if maybe this one project needs to be recreated.

Any thoughts?

**Comment by molnargab** [comment]
Strange enough. Any chance you're excluding the test assemblies? How do you call OpenCover?

**Comment by DAndreChampagne** [comment]
I tried removing the filter however that didn't change the report. This is the batch file I'm using. There are 5 test assemblies total, the shim class is in Dac.Tests.dll.

    .\packages\OpenCover.4.5.3723\OpenCover.Console.exe^
     -output:"Coverage\coverage.xml"^
     -mergebyhash^
     -target:"C:\Program Files (x86)\Microsoft visual Studio 10.0\Common7\IDE\mstest.exe"^
     -targetargs:"/testcontainer:\"C:\Users\champad\Documents\Projects\OIA FMS\OIAFMS\OIAFMS.BLL.Tests\bin\Debug\OIAFMS.BLL.Tests.dll\" /testcontainer:\"C:\Users\champad\Documents\Projects\OIA FMS\OIAFMS\OIAFMS.Common.Tests\bin\Debug\OIAFMS.Common.Tests.dll\" /testcontainer:\"C:\Users\champad\Documents\Projects\OIA FMS\OIAFMS\OIAFMS.DAL.Tests\bin\Debug\OIAFMS.DAL.Tests.dll\" /testcontainer:\"C:\Users\champad\Documents\Projects\OIA FMS\OIAFMS\OIAFMS.Presentation.Win.Tests\bin\Debug\OIAFMS.Presentation.Win.Tests.dll\" /testcontainer:\"C:\Users\champad\Documents\Projects\Dac\Dac.Tests\bin\Debug\Dac.Tests.dll\""^
     -filter:"+[*]* -[*Tests]*"^
     -register:user

    .\packages\ReportGenerator.2.1.4.0\ReportGenerator.exe^
     -reporttypes:"Html"^
     -reports:"C:\Users\champad\Documents\Projects\OIA FMS\OIAFMS\Coverage\coverage.xml"^
     -targetdir:"C:\Users\champad\Documents\Projects\OIA FMS\OIAFMS\Coverage"^
     -historydir:"C:\Users\champad\Documents\Projects\OIA FMS\OIAFMS\Coverage\History"

    pause

**Comment by sawilde** [comment]
Very unusual and nothing looks obvious as to the cause - do you have a repeatable sample that we can use to investigate further?

What version of .NET are you using by the way?

**Comment by DAndreChampagne** [comment]
Sadly, I don't. The code I'm using is at work.

If this helps, today I switched from using MSTest to NUnit as my test software, and now those functions are showing as visited. This was the only change I made.

**Comment by DAndreChampagne** [comment]
Also, I'm targetting .NET 4.0.

**Comment by sawilde** [comment]
no repeat and developer has resolved issue through other means
