### ISSUE TITLE
Problem installing package with VS 2015 RC

### ISSUE THREAD

**Issue by giggio** [OpenCover/opencover#315]
If you try to install OpenCover to a project on VS 2015 RC (latest available at the moment) using nuget you get this error message:

````
Could not install package 'OpenCover 4.5.4107-rc122'. You are trying to install this package into a project that targets '.NETFramework, Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
````

I think there might be a problem on the way the nuget pkg is structured. Maybe you need a tools folder?

Some references:
https://docs.nuget.org/create/enforced-package-conventions
https://docs.nuget.org/create/creating-and-publishing-a-package

**Comment by sawilde** [comment]
Are you adding it a project package or a solution package?

If the latter what happens when you add it is a solution package on VS2015RC?

Thanks, probably will need to change the structure to keep up with the times.

**Comment by giggio** [comment]
I was managing nuget pkgs for a project.
But you can't add it as a solution package using Nuget 3.0 interface from VS 2015 RC.
See below when I tried to manage packages for solution, I have to select at least one project, and if I do that error happens. :(

![opencover](https://cloud.githubusercontent.com/assets/334958/8075118/53fcf124-0f12-11e5-80fe-0fdf325f9453.png)

**Comment by sawilde** [comment]
awesome info thanks

**Comment by nkanani** [comment]
I had similar problem - a workaround i used was to modify packages.config to add:

<package id="opencover" version="4.5.3723" targetFramework="net452" />

**Comment by giggio** [comment]
@nkanani Yes, that is how I am working around it at this time as well.

**Comment by danielpalme** [comment]
I have the same problem with ReportGenerator(see [#19](https://github.com/danielpalme/ReportGenerator/issues/19)).
Probably we have to place the files in the ```tools``` subfolder of our packages.

**Comment by sawilde** [comment]
@danielpalme: yup - we are soooo.... yesterday. :)

**Comment by danielpalme** [comment]
The tests are finally working again.
You might want to change the directory structure in the ZIP file accordingly.

**Comment by giggio** [comment]
Cool, is it up on nuget already?

**Comment by sawilde** [comment]
not yet - just pulled the code

**Comment by giggio** [comment]
Would you please update nuget so we can update our VS 2015 projects? :)

**Comment by sawilde** [comment]
try this - https://www.nuget.org/packages/OpenCover/4.5.4212-rc137

**Comment by sawilde** [comment]
https://github.com/OpenCover/opencover/releases/tag/4.6.166

**Comment by giggio** [comment]
I just tried the latest release on VS 2015 RTM, and it installed perfectly. Thanks!

**Comment by sawilde** [comment]
:+1:
