### ISSUE TITLE
Multiple vs project coverage

### ISSUE THREAD

**Issue by vigneshwarvijayaraghavan** [OpenCover/opencover#317]
What if there are 2 vs solutions and one is for test project and the other one is the code for which the coverage needs to be done??

**Comment by sawilde** [comment]
The use the filters (see [wiki](https://github.com/OpenCover/opencover/wiki/Usage)) to exclude the test assemblies.

**Comment by vigneshwarvijayaraghavan** [comment]
My question is, I have an automation suite ( say C:\Test\Test.dll ) with Nunit framework and I have a web appln for which I need coverage when I run the automation suite resides in another folder ( say D:\Source\Source.dll ) . When I say target is nunit.exe and targetargs as test.dll, it gets coverage for test.dll, but i need the coverage for source.dll.

Could you kindly help me to do that??

**Comment by sawilde** [comment]
Sure - What have you tried so far?

From what you have described you are trying to get coverage using an integration test where you are running the profiler on one application, say `nunit-console.exe`, but trying to get coverage of another application? How are you launching the web application, what have you tried in the [documentation](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) that comes with OpenCover, that isn't working for you?

**Comment by vigneshwarvijayaraghavan** [comment]
.\packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -target:C:\Windows\System32\inetsrv\w3wp.exe -targetargs:-debug 
-targetdir:C:\Inetpub\wwwwoot\MyWebApp\bin\ -filter:+[*]*

.\packages\ReportGenerator.2.1.4.0\ReportGenerator.exe "-reports:results.xml" "-targetdir:.\coverage"

pause

**Comment by sawilde** [comment]
What does it say in the OpenCover output xml?
