### ISSUE TITLE
VS2015 .NET 4.0 assemblies: No PDB could be loaded

### ISSUE THREAD

**Issue by Sam13** [OpenCover/opencover#319]
When compiling my .NET 4.0 solution with VS2015 RC1 (still under .NET 4.0) I'm not able to run OpenCover anymore. For all assemblies the following message is shown in the output:
*Cannot instrument C:\Users\TestUserName\AppData\Local\Temp\nunit20\ShadowCop
yCache\9732_635712476997605454\Tests_5181666\assembly\dl3\a5254cd4\1cd770a8_f3b2
d001\SomeAssembly.dll as no PDB/MDB could be loaded*

PDB does not exist on the shadow copy location only in the original location which is supplied as working copy path to OpenCover and NUnit.
When compiling under VS2010 the same procedure works...

Any ideas how to analyze this error?

**Comment by sawilde** [comment]
What is your actual command line? Have you used the `-targetdir:` [option](https://github.com/OpenCover/opencover/wiki/Usage)?

**Comment by Sam13** [comment]
Here is an anonymized version of my command line:
```
D:\Test\vendor\opencover\bin\OpenCover.Console.exe -register:user -target:"D:\Test\vendor\NUnit\bin\nunit-x86.exe" -targetdir:"D:\Test\bin\x86\Debug" -targetargs:"" -output:"C:\Users\Test\AppData\Local\Temp\output.xml" -filter:"+[*]* -[log4net*]* -[*nunit*]* -[msvcm*]* -[Rhino.Mocks*]* -[NLog*]* -[*UnitTest]*" -log:Error -returntargetcode -threshold:100)
```

The process *OpenCover.Console.exe* has also the same working directory than specified in *-targetdir*.

For some assemblies it works for some it doesn't. By changing nothing just using the VS2010 compiler it works for all assemblies...

**Comment by sawilde** [comment]
Does the PDB exist in the `targetdir` folder? Was it built at the same time as the DLL? Have you tried the `/noshadow` option with nunit?

**Comment by Sam13** [comment]
1) PDBs exist in *targetdir*, verfied them by debugging, able to load them so must be ok
2) Yes

but still no success

**Comment by sawilde** [comment]
Sorry then I don't know, new one to me, I'll have to spend some time replicating it. Which version of OpenCover are you using? The latest one is in nuget.

**Comment by Sam13** [comment]
I was using the latest binaries from GitHub: 4.5.3522.
But with the new version from NuGet 4.5.3723 it works.

**Comment by molnargab** [comment]
Since the upgrade worked, the issue must have been the same as #248.

**Comment by sawilde** [comment]
@sam13 - sorry my bad I forgot to upload the latest images to github - most people use nuget nowadays.

**Comment by Sam13** [comment]
I'm planning to do so ;-)

**Comment by sawilde** [comment]
@Sam13 nothing I have done intentionally - I don't have an XP image and support from MS expired April 2014. 

What is the error? And is anything in the Event logs?

**Comment by Sam13** [comment]
Yes I'm aware of that but that's out of my control...

Nothing in the event logs but a callstack (sorry for being lazy and not posting it toghether with the question):
`An exception occured: Failed to register(user:True,register:True,is64:False):3 the profiler assembly; you may want to look into permissions or using the -register:user option instead. C:\WINDOWS\system32\regsvr32.exe /s  /n /i:user "D:\Project\vendor\opencover\bin\x86\OpenCover.Profiler.dll"
stack:    at OpenCover.Framework.ProfilerRegistration.ExecuteRegsvr32(Boolean userRegistration, Boolean register, Boolean is64) in c:\projects\opencover\main\OpenCover.Framework\ProfilerRegistration.cs:line 66
		  at OpenCover.Console.Program.Main(String[] args) in c:\projects\opencover\main\OpenCover.Console\Program.cs:line 104`

Command line:
`D:\Project\vendor\opencover\bin\OpenCover.Console.exe -register:user -target:"D:\project\Vendor\NUnit\bin\nunit-x86.exe" -targetdir:"D:\Project\bin\x86\Debug" -targetargs:"" -output:"output.xml" -filter:"+[*]* -[log4net*]* -[*nunit*]* -[msvcm*]* -[Rhino.Mocks*]* -[NLog*]* -[*UnitTest]*" -log:Error -returntargetcode -threshold:100`
Working dir: `D:\Project\bin\x86\Debug`

With 4.5.3522 this works without any changes...

**Comment by molnargab** [comment]
Try running the command manually without `/s`, e.g. `C:\WINDOWS\system32\regsvr32.exe /n /i:user `.
It will open up a message box with the exact error message.

**Comment by Sam13** [comment]
@molnargab Thanks for the hint.
The error message is the following:
*LoadLibrary("...\x86\OpenCover.Profiler.dll") failed - The specified procedure could not be found*
Same command line works for 4.5.3522.

When comparing the OpenCover.Profiler.dll of version 4.5.3522 and 4.5.3723 in DependencyWalker I can see that in 4.5.3723 there is an additional function called *LoadOpenCoverSupportAssembly*. This does not exist in 4.5.3522

**Comment by sawilde** [comment]
*LoadOpenCoverSupportAssembly* is not used in the registration process; it is used when interacting with Microsoft.Fakes.

We did however change from VS2012 to VS2013 and that changed the toolset which may be a candidate - https://tedwvc.wordpress.com/2014/01/01/how-to-target-xp-with-vc2012-or-vc2013-and-continue-to-use-the-windows-8-x-sdk/

**Comment by Sam13** [comment]
Yes that might be the reason. Anyway I'll stick with the 4.3522 and if I move to VS 2015 completely I'll grab the latest one. Then I have to drop XP support anyway ;-)

**Comment by sawilde** [comment]
You won't be alone, MS dropped XP support last year and more recently have announced no more MS Essentials support; okay not a biggy as AV goes but the other vendors will probably start to follow as XP drops down in usage ([~11%](http://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0))
