### ISSUE TITLE
OpenCover not finding some PDBs

### ISSUE THREAD

**Issue by AndrueC** [OpenCover/opencover#320]
We have a new vs2015 solution and after setting up a Jenkins CI job for it we've found that some PDBs are being reported as 'missing' when they aren't. Eg;

* Good *
    <Module hash="47-11-15-0C-37-48-B4-90-3C-76-1B-5B-C4-CF-28-25-3A-C3-B9-59">
      <Summary numSequencePoints="62" visitedSequencePoints="30" numBranchPoints="62" visitedBranchPoints="30" sequenceCoverage="48.39" branchCoverage="48.39" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" />
      <FullName>c:\JenkinsWorkspace\ConnectSR\CI\_Build\Lexacom.ConnectSR.Client.dll</FullName>
      <ModuleName>Lexacom.ConnectSR.Client</ModuleName>

* Bad *
    <Module skippedDueTo="MissingPdb" hash="19-6E-93-C8-B4-0E-2B-52-8B-12-06-F7-9A-95-81-4E-FD-F5-70-68">
      <FullName>c:\JenkinsWorkspace\ConnectSR\CI\_Build\Lexacom.Connect.Core.dll</FullName>
      <ModuleName>Lexacom.Connect.Core</ModuleName>

I've used sysinternals to monitor activity and it shows opencover.exe opening and reading from the DLL it supposedly didn't find.

This is with the latest preview but also with 4.5.3723.

**Comment by sawilde** [comment]
What does it say in the XML for the assembly it didn't profile?

**Comment by AndrueC** [comment]
Sorry, I didn't notice it had stripped out the XML.

    < Module skippedDueTo="MissingPdb" hash="08-7C-50-99-B0-F2-78-BA-CE-D2-57-21-40-11-DD-30-2F-6C-24-19">
      < FullName>c:\JenkinsWorkspace\ConnectSR\CI\_Build\Lexacom.Connect.Core.dll</FullName>
      < ModuleName>Lexacom.Connect.Core</ModuleName>
      < Classes />
    < /Module>

The log file says:

Cannot instrument c:\JenkinsWorkspace\ConnectSR\CI\_Build\Lexacom.Connect.Core.dll as no PDB/MDB could be loaded

**Comment by sawilde** [comment]
And the PDB was in the same location?

I am using a 3rd party `mono.cecil` to load an interrogate PDBs so it may be having trouble with the new PDB format being produced by VS2015. 

Obviously I don't see it with my VS2015 builds so it may be something specific to your code (i.e. it is producing a PDB that the version of `mono.cecil` I am using can't cope with. Are you able to give me your compiled assemblies so I can investigate further - there is a later version so I may also try packaging a new release?

**Comment by sawilde** [comment]
try this - https://www.nuget.org/packages/OpenCover/4.5.4212-rc137

**Comment by AndrueC** [comment]
That version of OpenCover works, thanks!

**Comment by sawilde** [comment]
https://github.com/OpenCover/opencover/releases/tag/4.6.166
