### ISSUE TITLE
Have AppVeyor to upload releases to GitHub

### ISSUE THREAD

**Issue by molnargab** [OpenCover/opencover#323]
AFAIK GitHub releases are uploaded manually. With [this feature](http://www.appveyor.com/docs/deployment/github) of AppVeyor this could be automated, just like NuGet.

We could even have rc releases to be marked as pre-release.

**Comment by sawilde** [comment]
sweet - definitely should look into this one - automation FTW.

**Comment by sawilde** [comment]
Oops - it would seem that when ApppVeyor created and tagged a release this caused a webhook message to be set to  caused AppVeyor to create a new build which then caused a ... you can see where this goes :) - now disabled the send on Create (branch, or tag)

**Comment by sawilde** [comment]
https://github.com/OpenCover/opencover/releases/tag/4.6.166
