### ISSUE TITLE
Support for code coverage for ASP.NET 5 projects.

### ISSUE THREAD

**Issue by anuraj** [OpenCover/opencover#327]
Support for code coverage for ASP.NET 5 projects.

We can run the test in ASP.NET 5 using `dnx . test` command, where . is the current directory, where we require the project.json file. So I am the command like this.

```
OpenCover.Console.exe -target:C:\Users\Anuraj.P\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnx.exe -targetargs:" . test" -output:coverage.xml
```

![coverage](https://cloud.githubusercontent.com/assets/276411/8774132/824161c2-2ef8-11e5-9efc-9411fe081149.PNG)

You can find the source code and test project - https://github.com/anuraj/ASPNET5CIDemo

If you want to configure DNX, please check the appveyor.yml or .travis.yml

**Comment by sawilde** [comment]
Thanks, what version of OpenCover are you using? The latest release can be found here https://github.com/OpenCover/opencover/releases if you need it.

In the meantime what does it say in the XML about where it loaded the assembly from and why it didn't  instrument it?

**Comment by scotroach** [comment]
I too have the same problem.
The projects are the new ASP.NET 5 - XProj.  When built there are no .pdb...
In the xml says it was skipped because no pdb.
<Module skippedDueTo="MissingPdb" hash="">
      <FullName>OS.Core.dll</FullName>
      <ModuleName>OS.Core</ModuleName>
      <Classes />
    </Module>

**Comment by gBritz** [comment]
I am also having the same problem, using dnx-clr-win-x86.1.0.0-beta6.
Output file says it was skippedDueTo="MissingPdb" in dlls of project and hash attribute is empty.
There is another way to inform the path of the pdb file?

**Comment by sawilde** [comment]
`-targetdir:` may work for you 

the original OP did not respond to my query so I have not pushed on the support

**Comment by gBritz** [comment]
Thanks for your suggestion.
I tried to use the ```-targetdir:```, but i had another error.
[You can check here](https://ci.appveyor.com/project/Britz/accounts/build/1.0.19#L3424)
You have any sample project with dnx to base me?

**Comment by sawilde** [comment]
> Have you any sample project with dnx to base me?

Sorry I don't, what you could try is using the full path to the targetdirectory.

**Comment by anuraj** [comment]
It tried the latest version. opencover.4.6.192.msi, XML says skippedDueTo="MissingPdb".

**Comment by Cobster** [comment]
I was experiencing the same issue as reported.  But it appears to be working after registering the profiler.  See the Build system integration section of the manual.

**Comment by Cobster** [comment]
I think I got it figured out.  Specify the --lib argument with the dnx command that targets the folder containing PDB of the assembly being covered.

For instance here is my command:

OpenCover.Console.exe -target:C:\users\jbruun\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6\bin\dnx.exe -targetargs:"--lib c:\projects\cpip\src\website\bin\debug\dnx451 c:\projects\cpip\te
st\Website.Tests\. test" -output:coverage.xml -filter:+[Website]*

**Comment by gBritz** [comment]
Great awesome.
Thanks, your suggestion really works.
[Build with coverage here](https://ci.appveyor.com/project/Britz/accounts/build/1.0.21#L3481)

**Comment by anuraj** [comment]
It is working for me, but the results include XUnit assemblies as well. If I include filter option the report is not getting generated.

**Comment by sawilde** [comment]
@Cobster thanks - I'll add it to the wiki and documentation

**Comment by Cobster** [comment]
@sawilde - Your welcome, glad this could get figured out without requiring new bits.
@anuraj - Does the lib folder you are targeting contain the PDB? I've had to use the **dnu build** from the command line to get the dll and pdb created, a simple build in visual studio doesn't seem to generate the artifacts.

**Comment by anuraj** [comment]
Yes. I have the DLL and PDB. But I didn't understand why filter option is not working. If I apply filter:"-[XUnit*]*" - It is not generating the report :(

**Comment by Cobster** [comment]
@anuraj - Not sure if its case sensitive, but if it is the **XU** in XUnit should be lowercase to match the assembly name. Are you adding the asterisk wildcard after [xunit] to it will filter the types?

I've had better luck using the inclusion filter to specify my own assemblies.

**Comment by sawilde** [comment]
@anuraj  add `+[*]*` opencover filters have a default set but when you supply your own then it is exclusive by default this is so we don't bring in coverage for 3rd party assemblies and the runtime, which may skew your results and make it very, very slow.

as @Cobster mentions the inclusive way is much easier and you are much more in control e.g.

    -filter:"+[MyCompanyName*]* -[*Tests]*"

which you include all the assemblies beginning with MyCompanyName but exclude any that have Tests at the end.

All of this is in the wiki [usage guide](https://github.com/OpenCover/opencover/wiki/Usage#understanding-filters)

**Comment by sawilde** [comment]
Added wiki entry https://github.com/OpenCover/opencover/wiki/DNX-Support

**Comment by sgopimca7** [comment]
When the code reads the value from configuration file such as scenarios like reading connection string from database, then it always throws null exception and all test methods are fail.

**Comment by sawilde** [comment]
@sgopimca7 Please open a new issue with a repeatable scenario

**Comment by abhimanyuk453** [comment]
i am facing similar issue where for my project .net framework 4.6.2 hosted in iis ,i am unable to generate xml file for my project.
Command used is : OpenCover.Console.exe -target:C:\Windows\System32\inetsrv\w3wp.exe -targetargs:-debug -targetdir:C:\inetpub\wwwroot\coverage\bin\ -register:user
could you please help me with this issue. @sawilde 
<img width="960" alt="opencoverissue" src="https://user-images.githubusercontent.com/19637799/117292271-a104cc00-ae8d-11eb-88e3-5c32a5354558.PNG">
