### ISSUE TITLE
Samples in nuget package can be harmful

### ISSUE THREAD

**Issue by wyand** [OpenCover/opencover#331]
The sample solutions should not be included in the nuget package.

Builds that depend on finding information based on file name conventions can very easily identify the sample solution, and artifacts in them such as packages.config files, as actual code. I'm trying to use open cover with an project that I don't have control of the build files on, and I can't build unless I manually delete the samples after a package restore.

Samples aren't really packaged content -- they should be distributed separately.

**Comment by sawilde** [comment]
The samples have been there for some time and this is this is the first I have heard of a an issue. 

You'll have to give me an idea on how it causes problems (really detailed) - I don't know of any build that does what you say above and may be particular to you rather than a general issue.

If the build is automatically picking up the solution under and building it then it needs to stop - put in an exclusion and move on.

**Comment by wyand** [comment]
yep, you are right... spent too long banging my head on something that really is the build system's fault. 

part of my concern was that .net vNext will be much more based on just matching ** pattern (which is a good thing), but then the packages won't be in with the solution anyways, so its a moot point. Sorry for the silly issue.

**Comment by sawilde** [comment]
no worries, I was thinking I might just zip them up anyway - if it can happen once it can happen again, time is more the issue, it's quicker for you to exclude rather than wait on me to release a new package.

**Comment by Jacob-McKay** [comment]
My project is running on VSTS build system, and before I introduced OpenCover, our MSBuild config was using this: **\*.sln to find and build the solutions(s).  After including the OpenCover nuget package, my builds started to fail.

Having read this issue I followed your advice and excluded the solution that failed to build by specifying: **\*.sln;-:**\OpenCover.*\** as my solution path for MsBuild.

I don't know how common this is, but it could hurt the adoption of your nuget package.  I can tell you that example/test code in what I expect to be only a library/dll is a smell to me.  Including an exclusion in my build configuration(s) just for one nuget package increases the complexity of my build, which I'm also not a fan of.  And if something fails my build when I use it like I use every other nuget package, I'm more likely to ditch it.

I like this tool and prefer it to the paid alternatives, and would like to see it do well.  I don't mean to come off negative or aggressive, just wanna vent my concerns in the hopes that you'll improve the tool if you feel it's necessary.

**Comment by Jacob-McKay** [comment]
This is what was causing the build to fail FYI: 

```
PROJECT\packages\OpenCover.4.6.519\SampleSln\BomTest\BomManagerTests.cs (8, 7)
The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)
PROJECT\packages\OpenCover.4.6.519\SampleSln\BomTest\BomManagerTests.cs (12, 6)
The type or namespace name 'TestFixtureAttribute' could not be found (are you missing a using directive or an assembly reference?)
PROJECT\packages\OpenCover.4.6.519\SampleSln\BomTest\BomManagerTests.cs (12, 6)
The type or namespace name 'TestFixture' could not be found (are you missing a using directive or an assembly reference?)
PROJECT\packages\OpenCover.4.6.519\SampleSln\BomTest\BomManagerTests.cs (15, 10)
The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)
PROJECT\packages\OpenCover.4.6.519\SampleSln\BomTest\BomManagerTests.cs (15, 10)
The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)
PROJECT\packages\OpenCover.4.6.519\SampleSln\BomTest\BomManagerTests.cs (22, 10)
The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)
PROJECT\packages\OpenCover.4.6.519\SampleSln\BomTest\BomManagerTests.cs (22, 10)
The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)
PROJECT\packages\OpenCover.4.6.519\SampleSln\BomTest\BomManagerTests.cs (23, 10)
The type or namespace name 'TestCaseAttribute' could not be found (are you missing a using directive or an assembly reference?)
PROJECT\packages\OpenCover.4.6.519\SampleSln\BomTest\BomManagerTests.cs (23, 10)
The type or namespace name 'TestCase' could not be found (are you missing a using directive or an assembly reference?)
PROJECT\packages\OpenCover.4.6.519\SampleSln\BomTest\BomManagerTests.cs (24, 10)
The type or namespace name 'TestCaseAttribute' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by sawilde** [comment]
okay I'll raise it as a feature #587

**Comment by marcelbeeker** [comment]
Can you exclude your samples from the NuGet package? They broke my DevOps build as Jacob mentioned. It's unnessary code in my solution!
