### ISSUE TITLE
Bundled adware?

### ISSUE THREAD

**Issue by nickbabcock** [OpenCover/opencover#332]
Downloading the opencover nuget package results in my antivirus (webroot) complaining of infection. Here is what the antivirus logs:

```
packages\opencover\x86\opencover.profiler.dll [MD5: 3473C31EF0AA74E6D6B1ACAC5592F12C] [3/00080000] [Pua.Adware.Crossrider]
```

Any ideas why it would do this?

**Comment by sawilde** [comment]
I suspect a false positive rather than a real virus - the code (I am assuming you pulled the latest nuget pckage) is built from source code using [AppVeyor and then after packaging is pushed to nuget](https://ci.appveyor.com/project/sawilde/opencover/build/4.6.166).

I'll submit the DLLs to other AV vendors and see what comes back.

**Comment by sawilde** [comment]
I can't see where to test the file against webroot online without installing so I tried a few meta scanners.

No detections from [VirusTotal](https://www.virustotal.com/en/file/fc435594a237c628a1ca3ff5fa691873883d36b4da7f75af8c9f40bee1a394e0/analysis/1438328801/), a heuristic hit from [Metascan](https://www.metascan-online.com/en/scanresult/file/12330df7674243b6bbe717bbebd0f87b) and nothing on [Jotti](https://virusscan.jotti.org/en-US/filescanjob/2x4tmab2bx)

I'll carry on looking into it but still probably a false positive though - you can see if the assembly you have gets different results just in case the infection is localised to you.

**Comment by nickbabcock** [comment]
I've opened a false positive ticket on webroot's site, so hopefully they can get back with more details.

**Comment by nickbabcock** [comment]
Wow, so Webroot responded almost immediately indicating that it was a false positive and pushed out the change. Everything works now. :smile:

**Comment by sawilde** [comment]
sweet :+1: - though I may look into pushing such assemblies to these AV vendors as part of the build pipeline - more for piece of mind in case the build servers get compromised.
