### ISSUE TITLE
StackOverflowException with Visual Studio 2015 and OC 4.6.166

### ISSUE THREAD

**Issue by Birgos** [OpenCover/opencover#334]
Hello,

after switching from VS 2013 to VS 2015 and OC 4.5.3723 to OC 4.6.166
I can not use OC any longer. Everytime I try to run OC  I get this error message:
```
Process is terminated due to StackOverflowException.
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
```

So I removed the /s parameter from the argumentlist of the ExecuteRegsvr32 method@ ProfileRegistration.cs. But the dll's are registered probably.

Then I took the "old" files from the 4.5.3723 version and copied them into the extracted tools directory under my packages folder (including x86/x64 folder). After that, I was able to run OC as usual.

I tried to debug the solution and it seems to me that
```
        SetProfilerAttributesOnDictionary(...)
        {
            dictionary[@"OpenCover_Profiler_Key"] = profilerKey;
        ....
```
**dictionary[@"OpenCover_Profiler_Key"]** throws a **Nullreference-Exception**.

I hope you can give me the decisive tip.

btw, here are my call parameters:
```
-register:user -target:"<path>\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"<targetdlls>" /noshadow /nologo" -filter:"<filterSettings>" -output:"<path>\OpenCoverReport.xml"
```

**Comment by sawilde** [comment]
Thanks - there seems to be a few teething problems with VS2015 builds that I am not able to reproduce locally - it you are able to provide the code/assemblies to help diagnose this issue further that would be great otherwise you'll have to wait until I work out how to re-create the same issue you are seeing.

**Comment by sawilde** [comment]
> I tried to debug the solution and it seems to me that
>
>        SetProfilerAttributesOnDictionary(...)
>        {
>            dictionary[@"OpenCover_Profiler_Key"] = profilerKey;
>        ....
> dictionary[@"OpenCover_Profiler_Key"] throws a Nullreference-Exception.

> I hope you can give me the decisive tip.

I don't think that is the case, the only time that method is called is from [here](https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Framework/Manager/ProfilerManager.cs#L97) and as you can see it is protected.

**Comment by sawilde** [comment]
> Process is terminated due to StackOverflowException.

I suspect this is your process failing as OpenCover itself is still running otherwise it wouldn't have been able to print its messages.

**Comment by sawilde** [comment]
have you got any more information for me?

**Comment by Birgos** [comment]
Sorry for my late response. But I needed some time for further testing.

Meanwhile i was able to isolate the problem a little bit.
Here is what my actual call looks like:
 ```
"<PathToPackage>\OpenCover.Console.exe" -register:user -target:"<PathToPackage>\nunit-console.exe" -targetargs:"<targetdlls>" /noshadow /nologo" -filter:"<filterSettings>" -output:"<path>\OpenCoverReport.xml"
```

**But** when i call the x86 version of nunit-console (nunit-console-x86.exe) everything works fine.
I'm using a Visual Studio 2015 64Bit Command Prompt but it also happens with a Visual Studio 2013 32Bit Command Prompt.

So the working call looks like:
 ```
"<PathToPackage>\OpenCover.Console.exe" -register:user -target:"<PathToPackage>\nunit-console-x86.exe" -targetargs:"<targetdlls>" /noshadow /nologo" -filter:"<filterSettings>" -output:"<path>\OpenCoverReport.xml"
```

I think it could be due to my Visual Studio installation, because even the OpenCoverUI Plugin in Visual Studio 2015 only works with the x86 version. But at the moment I have no idea how to solve this.

But I wanted to announce at least one possible solution to this issue if anyone else encounter similar problems. So maybe I can save someone else a day-long search for the cause of this issue.
