### ISSUE TITLE
[4.6.166] 0 visitedSequencePoint while this is obviously false

### ISSUE THREAD

**Issue by Greybird** [OpenCover/opencover#335]
Hi,

On my software factory, I get quite consistenly 0 visitedSequencePoint, hence 0% coverage, which is wrong, as even the passed tests are considered unvisited.

I did try -register:user, pregesister using regsvr32 (and I can confirm keys in the registry are present in HKLM).

I run the opencovers in parallel on separate assemblies under jenkins, using the following command line:

````
D:/Jenkins/Tools/OpenCover-4.6.166/OpenCover.Console.exe 
  -hideskipped:All 
  -mergebyhash 
  -skipautoprops 
  -threshold:1 
  -target:D:/Jenkins/Tools/NUnit/bin/nunit-console-x86.exe 
  -targetargs:-framework:net-4.0 -nologo -noshadow -labels -work=D:\Jenkins\workspace\SONAR-Coverage\NUnit-report -result=TestAssembly-1.xml -include:-GUI-nonreg TestAssembly.dll 
  -output:D:\Jenkins\workspace\SONAR-Coverage\OpenCover-report\TestAssembly-1.xml
````

I tried to make the jenkins account admin of the machine, but it did not change.

On the 200+ jobs running in parallel (at around 20 max at the same time), around 70% of them are getting 0% coverage.
When trying to run only a single assembly at once, I also get 0% coverage.

When I run the coverage on a single assembly alone on my dev pc, I get a coverage without issue.

Could you please help in figuring out what happens ? Do I miss a config ? Should you need a debug version of opencover to get more info, I can totally install it and provide you logs.

Thanks in advance

Arnaud

**Comment by sawilde** [comment]
What information is in the XML file regarding the assemblies?

**Comment by Greybird** [comment]
Hi,

File starts like this:
`
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Summary numSequencePoints="419525" visitedSequencePoints="0" numBranchPoints="202070" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="419" minCyclomaticComplexity="1" visitedClasses="0" numClasses="7429" visitedMethods="0" numMethods="70522" />
  <Modules>
    <Module hash="07-0C-D8-5F-DB-CC-EB-88-B4-E2-2D-F1-6B-B8-5C-A6-6E-8A-9E-0D">
      <Summary numSequencePoints="956" visitedSequencePoints="0" numBranchPoints="183" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="14" minCyclomaticComplexity="1" visitedClasses="0" numClasses="10" visitedMethods="0" numMethods="99" />
      <FullName>D:\Jenkins\workspace\SONAR-Coverage\src\bin\Tests\Debug\TestAssembly.dll</FullName>
      <ModuleName>TestAssembly</ModuleName>
      <Files>
`

**Comment by sawilde** [comment]
I think you haven't passed the arguments to OpenCover/Nunit correctly. You need to escape wrap all the arguments to NUnit (aka passed via targetargs) with quotes e.g.

    "-targetargs:-framework:net-4.0 -nologo -noshadow -labels -work=D:\Jenkins\workspace\SONAR-Coverage\NUnit-report -result=TestAssembly-1.xml -include:-GUI-nonreg TestAssembly.dll"

I have made an update to OpenCover itself to be more strict on arguments it does not recognise

**Comment by Greybird** [comment]
Thanks a lot for your interest in my issue!

I checked on another chain (as the one I encounter the problem is not available for the night), and we seem to run with the adequate quotes.

However, you change cannot do any harm from my point of view.

I will check tomorrow on the problematic chain to make sure, and let you know my findings.

I cannot share code as explained, but I think I may probably get permission to export test results and coverage report if needed.
Also I could be able to export some kind of procmon activity log if this could be of help ?.

Feel free to tell me if this would be of interest, as well as any other info you would need.
In this case, I would check with our legal department what is doable.

Arnaud

**Comment by Greybird** [comment]
Hi,

Sorry for the delay.

I was able to check, and found that arguments are correctly passed.

I was wondering if the fact that I use opencover to monitor x86 nunit console process which can in turn launch some x86 or x64 processes could be a problem ?

When I launch a unitary assembly of a x86 console running a x64 executable, both of them are covered correctly.But could there be an issue with this way of doing ?
Meanwhile, I'll try to make both nunit and all ran processes x64 to see if something changes.

Arnaud

**Comment by sawilde** [comment]
OpenCover should be able to handle both 32 and 64 bit processes at the same, each profiler instance, one per .NET process, should create its own shared memory buffers with the host process. The issue may be the number of buffers being allocated at any one time but you say you have seen the issue even when just one test run is in action so I doubt think this is why you getting 0% coverage.

> Also I could be able to export some kind of procmon activity log if this could be of help ?.

I am not sure what is in such a log to know whether it would be of any use but I doubt it would capture any internal behaviour e.g. instrumentation.

For a single test run that produces 0% it would be interesting to see the coverage report XML - what would be nice is to give me a copy of a repeatable sample (DLLs/PDBs) of code and tests, this may be possible with a small subset of code that has low value but still repeats the problem. I don't know what your product is to know if this is possible.

**Comment by Greybird** [comment]
Hi,

I'll try to find a repeatable use case then, and will let you know if i achieve this.

Thanks !

Arnaud

**Comment by sawilde** [comment]
I think I have found a race condition that may account for your issue - I'll be pushing out a release candidate hopefully in a few days - I'll let you know more

**Comment by Greybird** [comment]
Thanks a lot !

This is great news as I didn't manage to create a repro yet.
I'll test you RC once you will provide it.

**Comment by sawilde** [comment]
A build is available on AppVeyor - it's part of a issue resolution for another defect - https://ci.appveyor.com/project/sawilde/opencover/build/artifacts

**Comment by sawilde** [comment]
Have you tried the latest build yet?

**Comment by bigmat** [comment]
Hi
Arnaud is on holidays but i tried your version. The issue is still the same but with your version i now can reproduce the same issue locally.
I also saw that if i add a filter on some specific assemblies i have the result expecting (at least on the little part i tested).
I will speak with Arnaud to see how we can provide a example to reproduce or what we will do as it's complicated to send outside some part of codes.
He is coming back tomorrow. We will revert to you asap.
Thanks again for your help.

Mathieu

**Comment by sawilde** [comment]
Hi bigmat can you confirm which version you are using?

**Comment by bigmat** [comment]
Version 4.6.202
i see a version 4.6.205, is there some modification that can help ?

**Comment by sawilde** [comment]
potentially

**Comment by bigmat** [comment]
ok i will try it tomorrow and let you know

**Comment by Greybird** [comment]
Hi,

Just an update to let you know where we stand.

By added some filter, @bigmat managed to get it working at some point.
Upon investigation, we found that the filter used was ignoring some assemblies from the directory (we have several hundreds involved).
When we included all of them using +[A*]*...+[Z*]*, we get 0 vc again.

We'll work on finding the culprit(s) tomorrow, and will see if something can be determined from them (.net version, x86/x64, large adress aware, ... ?).
We'll let you know our findings asap.

Thanks again for your help.

**Comment by Greybird** [comment]
Hi @sawilde !

We finally tracked it down with @bigmat, even if we don't know the exact root cause.
Our culprit assembly is a 11 795 Kb assembly, with its 27 028 KB PDB.

Using DebugView, I found that the first SendVisit trace was the following:
00000171	44.11119843	[4208] OpenCover: ProfilerCommunication::SendVisitPoints() => Communication (Results channel) with host has failed (0x102, 10000)	

Pushing the timeout to 60000 solved completely the issue.

As this seems not to be the first issue related to a timeout issue, would you consider making them configurable ? A multiplicative factor could be enough if you need to keep SHORT and LONG timeout with same relation factor....
I don't know the exact implications of this however, so I leave this decision to your expertise on the subject :sweat_smile: 

Also, now that we know how to get the traces, if you feel like you need more information on the run to find a more elegant solution, we'll be gad to help by running your builds against our assembly to provide you with the logs.

Arnaud

**Comment by sawilde** [comment]
thanks - I'll probably add a timeout value (use at your own risk)

**Comment by sawilde** [comment]
Can you try this release to see if it corrects your issue
https://www.nuget.org/packages/OpenCover/4.6.247-rc 
https://github.com/OpenCover/opencover/releases/tag/4.6.247-rc

**Comment by sawilde** [comment]
https://www.nuget.org/packages/OpenCover/4.6.515-rc

**Comment by sawilde** [comment]
This issue is starting to drift from the original

We have published the release at https://www.nuget.org/packages/OpenCover/4.6.519 and https://github.com/OpenCover/opencover/releases/tag/4.6.519
