### ISSUE TITLE
-excludebyattribute not working

### ISSUE THREAD

**Issue by BDDCloud** [OpenCover/opencover#340]
Hi, the -excludebyattribute is not working for me. This is probably my usage. I've tried a bunch of variations with and without quotes / wild cards.

Sample usage of the attribute in code:
    [CoverageExclude]
    public class CredentialLoginResult

The usage is below, any ideas?

-register:user -excludebyattribute:System.CoverageExcludeAttribute -hideskipped:all -excludebyfile:"*\*.xaml.cs;*\*.xaml;*\*.g.cs"  -filter:"+[Foo]* -[Foo]Bar
Widgets.ActiveReports.*" -target:"packages\NUnit.Runners.2.6.3\tools\nunit-console-x86.exe" -targetargs:"/noshadow Tests.Foo\bin\Debug\Tests.Foo.dll" -output:build\Open
CoverTests.xml

**Comment by sawilde** [comment]
What is the namespace of your attribute? NOTE: Normally there is no `CoverageExcludeAttribute` under the `System` namespace; `System` is normally reserved for classes provided by the .NET framework. 

try

    -excludebyattribute:*.CoverageExclude*

**Comment by BDDCloud** [comment]
Bah that was it. Thanks! CoverageExclude had no namespace. So even *.CoverageExclude* wasn't working.
