### ISSUE TITLE
IIS - "no results"

### ISSUE THREAD

**Issue by wewedgeworth** [OpenCover/opencover#343]
Hi,

I am trying to use OpenCover with an application I have deployed over IIS at my Default Web Site. I have been referencing this issue: https://github.com/OpenCover/opencover/issues/234

First I run:
net stop w3svc /y

Then:
OpenCover.Console.exe -service -target:w3svc -output:C:\tmp\coverage.xml -targetdir:C:\Inetpub\wwwroot\bin

Once I do this, I get the following:
Stopping svchost with pid '1080'
svchost with pid '1080' was stopped succcesfully
New svchost for w3svc with pid '6756' was started
Service started 'w3svc'

Then I run my application and test cases. Then close the service and get the following:
Service stopped 'w3svc'
Stopping svchost to clean up environment variables for w3svc
Please note that 'w3svc' service many automatically start
Stopping svchost with pid '3584'
svchost with pid '2264' was started
Committing...
No results, this could be for a number of reasons. The most common reasons are:
1) missing PDBs for the assemblies that match the filter please review the output file and refer to the Usage guide (Usage.rtf) about filters.
2) the profiler may not be registered correctly, please refer to the Usage guide and the -register switch.

(I have tried using the -register switch and it does the same thing, I am running as an administrator)

The output in my generated .xml file is as follows:
<?xml version="1.0" encoding="utf-8"?>
< CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  < Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  < Modules />
</ CoverageSession>

Does anyone know what is causing my issue? Am I doing something wrong?

Thanks,

**Comment by sawilde** [comment]
Are the PDB files in the `bin` folder?

What filters are you using?

Have you preregistered the profilers (both of them) using `regsvr32` or just used the plain `-register` switch?

IIS is notoriously tricky and I recommend people use IISExpress in a test/instrumenting environment.

**Comment by wewedgeworth** [comment]
Thanks for the reply.

Yes all of the PDB files from my Visual Studio solution are in C:\Inetpub\wwwroot\bin

I am not using any filters

I tried using both -register and regsvr32 x86\OpenCover.Profiler.dll, regsvr32 x64\OpenCover.Profiler.dll, to set the profilers. It still does not work, just generating the same .xml as above.

**Comment by wewedgeworth** [comment]
I now have OpenCover working properly using IIS Express.

However, I am still trying to get it to work over IIS, as our continuous integration will need to be run via IIS. Is there anything else I can try to get it to work?

Also, is there any IIS configuration that should be enabled or configured in a different way that might be the cause of my issue?

Thanks,

**Comment by sawilde** [comment]
I updated the wiki - https://github.com/OpenCover/opencover/wiki/IIS-Support

You need to look at using `-debug` mode of the w3wp process

This info was in the pdf/rtf file that was in the downloads but not in the wiki itself.
