### ISSUE TITLE
Just a clarification - Using FunctionEnter2 handler

### ISSUE THREAD

**Issue by vaidhy** [OpenCover/opencover#344]
I am trying to add an extension for deeper test metrics. I would like to hook on to FunctionEnter2 in coverage_callback.cpp, but it looks like those functions are never called. Any trace point I set in there seem to be ignored. 

Are those function deprecated in favor of the coverage_cuckoo instrumentation?

**Comment by sawilde** [comment]
The function callbacks are only called when `COR_PRF_MONITOR_ENTERLEAVE` is set and that only happens during the `-coverbytest` feature to track which test is currently being executed.

> I am trying to add an extension for deeper test metrics. 

What is the change you are proposing?

**Comment by vaidhy** [comment]
I am trying to capture unit tests outputs for Nunit, XUnit and VSTest without making changes to any of the build scripts. I had achieved that in the past by registering a profiler and looking for specific methods. However, now I am trying to add coverage metrics and realized that my previous approach will not work.. nor can I chain profilers since FunctionEnter/LEave callbacks cannot be chained. 

I also spent one more day with the code now and I am changing my approach to plugging my code into the framework as opposed to the profiler. It is easier to monitor when the C# code is called.

**Comment by vaidhy** [comment]
I found out the reason for why FunctionEnter2 was not getting called.. In FunctionIDMapper, there is an undocumented param *pbHook.. If it is set to false, Enter and Leave functions will not be called.

**Comment by sawilde** [comment]
> I found out the reason for why FunctionEnter2 was not getting called.. In FunctionIDMapper, there is an undocumented param *pbHook.. If it is set to false, Enter and Leave functions will not be called.

That is how that [function](https://msdn.microsoft.com/en-us/library/aa964957(v=vs.110).aspx) works
