### ISSUE TITLE
Possibility to pass multiple targetdirs when starting a process

### ISSUE THREAD

**Issue by philippjenni** [OpenCover/opencover#348]
Hi,

It's possible to pass multiple targetdirs when starting opencover.

I have a web application which requires 2 different applications (Management and User) with a shared business and datalayer. I will cover the code usage over the complete application (Management and User).

I start iisexpress from opencover, but i can only cover the complete code from 1 application, which i define over the targetdirs parameter. The coverage from business layer and datalayer works over the 2 applications, but i missing the application specific coverage from the second application

**Comment by sawilde** [comment]
I'll probably implement a `-searchdirs:` switch as `targetdir` is quite specific.

In the meantime ensure that the PDBs are available alongside the DLLs to be profiled or alternatively try copying all the PDBs into the targetdir location even if the DLL isn't there.

**Comment by philippjenni** [comment]
A searchdirs parameter it also a good idea and should work for my requirement
