### ISSUE TITLE
OpenCover Console uses 1 CPU to 100%

### ISSUE THREAD

**Issue by philippjenni** [OpenCover/opencover#349]
Hi,

On my Build Server (Win 2012) uses the opencover alway a cpu to 100%. I have 2 CPU in the server and the opencover.console process uses 50% of cpu load. A second opencover process uses also 50% cpu. 

Any idees?

**Comment by sawilde** [comment]
That is expected as there is a lot of information flowing from the profiler to the host. If you are not bothered about accurate visit counts then you can use the `-threshold;` option see [wiki](https://github.com/OpenCover/opencover/wiki/Usage)

**Comment by philippjenni** [comment]
I have set the threshold parameter to 1, but i doesn't have an impact to the cpu load of the opencover.console process.

**Comment by sawilde** [comment]
Oh it has an impact as it will not be processing as much data you just can't see it.

Unfortunately that is the way it works - it has a Thread.Yield() in a loop whilst checking to see if any new messages have come in - if any other process wants the CPU they should get it.

https://msdn.microsoft.com/en-us/library/system.threading.thread.yield(v=vs.110).aspx

**Comment by philippjenni** [comment]
The problem is, that build server which covers the code is running on a virtual environment. On each code covering cycle risies the environment an high cpu alert.

**Comment by sawilde** [comment]
There may be something that could be done but I don't want to drop performance as that has been an issue in the past.

**Comment by molnargab** [comment]
`Yield` returns a bool. How about we added a sleep if yield was unsuccessful (which we think it was)?

Since we're already busy-waiting for data being consumed, it shouldn't hurt performance that much, though it would reduce CPU utilization.

**Comment by sawilde** [comment]
@molnargab yup, that was my thinking as well

**Comment by molnargab** [comment]
@philippjenni, could you check the CPU utilization with [CI build 4.6.234](https://ci.appveyor.com/project/sawilde/opencover/build/4.6.234/artifacts)?

**Comment by ddur** [comment]
[AppVeyor](https://ci.appveyor.com/) is free build server

**Comment by philippjenni** [comment]
Yes i will try this

**Comment by sawilde** [comment]
It worked well for me CPU usage hardly ever entered double figures when running dogfood tests whereas before it was running >30% for most of the time

**Comment by philippjenni** [comment]
Hi,

I have tested in my Build Envrionment. Now it looks very nice.

Thanks for your support ...
