### ISSUE TITLE
Tool for counting Visual Studio Tasks

### ISSUE THREAD

**Issue by uesrname** [OpenCover/opencover#351]
Hello,
I am looking for a .NET code coverage tool which is able to count the amount of Visual Studio tasks, e.g. TODO or HACK, in the code. In particular I would like to count user specified tasks, so I want to add my own tasks to the VS Task List and want to count how much of each tasks are in my code.

Is it possible to do this with opencover?

**Comment by sawilde** [comment]
No, code coverage is for executing code i.e. the IL after compilation.
