### ISSUE TITLE
OpenCover causes System.Runtime.Remoting Exception

### ISSUE THREAD

**Issue by SECogan** [OpenCover/opencover#353]
When attempting to run a program with OpenCover, the program crashes on launch and throws this exception:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	
  Problem Signature 02:	
  Problem Signature 03:	5507252c
  Problem Signature 04:	System.Runtime.Remoting
  Problem Signature 05:	4.6.81.0
  Problem Signature 06:	5584e616
  Problem Signature 07:	2c2
  Problem Signature 08:	9d
  Problem Signature 09:	System.Runtime.Remoting.Remoting
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

This exception is never thrown when running the program without OpenCover. I spoke with one of the developers of the program in question, and he said that at this point, the program is using a .NET remoting API to phyiscally attach to the corresponding service and access data from the service. I've got our service running properly (as evidenced by being able to start the program without OpenCover), but is there some sort of problem where OpenCover would interfere with this communication?

**Comment by sawilde** [comment]
It's possible but sounds like you are running OpenCover in an integration environment rather than via test runners like nunit, xunit so unless you are able to provide repeat steps I'll not be able to look into it further..

**Comment by SECogan** [comment]
Hi Shaun,

Thanks for getting back to use, but unfortunately we won't be able to give you our software to troubleshoot, so we'll have to work around this ourselves.

**Comment by sawilde** [comment]
I don't need your code but if you can repeat it as a separate code sample if possible
