### ISSUE TITLE
getting cover results for external dll's; VS2015, W8.1, MSTest

### ISSUE THREAD

**Issue by JoeAtGit** [OpenCover/opencover#356]
OpenCover.Console.exe -register:user "-target:C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\ide\MSTest.exe" -mergebyhash "-targetargs:/testcontainer:\E:\Work\GitStaging\RiskModel.Test\bin\Debug\RiskModel.Test.dll" "-output:e:\tmp\JoeCover.xml" "-targetdir:E:\Work\GitStaging\RiskModel.Test\bin\Debug\"

getting an error from windows saying " this app cannot run on your pc."

then cmd window reports- "Access is denied"

would appreciate any suggestion

Best
J

**Comment by sawilde** [comment]
Have you looked in the windows event logs?

**Comment by JoeAtGit** [comment]
Thank you Shaun

Issue was with  VSTTExecution and permissions - sorted now.

Thanks again for the advice

J.

**Comment by JoeAtGit** [comment]
OpenCover output:
96/96 test(s) Passed

Summary
-------
Test Run Completed.
  Passed  96
  ----------
  Total   96
Results file:  E:\Work\GitStaging\RiskModel.Test\bin\Debug\TestResults\Joe_name 2015-10-15 13_59_18.trx
Test Settings: Default Test Settings
Committing...
Visited Classes 0 of 30 (0)
Visited Methods 0 of 143 (0)
Visited Points 0 of 1185 (0)
Visited Branches 829 of 5110 (16.22)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 159 of 482 (32.99)
Alternative Visited Methods 732 of 3341 (21.91)

result file shows all tests passed, but xml output shows coverage results for 2 external dll's only: 
EntityFramework.BulkInsert.dll  and moq.dll

**Comment by sawilde** [comment]
What reason does it give for not profiling the other assemblies?

**Comment by JoeAtGit** [comment]
Thank you Shaun

new command line:
OpenCover.Console.exe 
-register:user 
"-target:C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\ide\MSTest.exe" 
/mergebyhash 
"-targetargs:/testcontainer:RiskModel.Test.dll /noisolation" 
"-output:e:\tmp\testCover\JoeCover.xml" 
"-targetdir:E:\Work\GitStaging\RiskModel.Test\bin\Debug" 
-filter:"+[RiskModel.Test]RiskModel.Test* "

the reason is **"skippedDueTo="MissingPdb"**, this reported 4 times for the same hash in the XML output

Have checked and pdb is in the folder. - not sure why its not found.

As MSTest moves files around during tests, tried adding a second /testcontainer to the args
which resulted in a warning message:
**Warning: In loading [testName] 
from e:\work\gitstaging\riskmodel.test\bin\debug\testresults\x\out\riskmodel.test.dll, 
it is detected that its id collides with [testName] 
from E:\Work\GitStaging\RiskModel.Test\bin\Debug\riskmodel.test.dll. 
[testName] 
from E:\Work\GitStaging\RiskModel.Test\bin\Debug\riskmodel.test.dll will be kept.**

**Comment by JoeAtGit** [comment]
Hi Shaun

Any advice or suggestions please?

Thanks
Joe

**Comment by molnargab** [comment]
> As MSTest moves files around during tests,

Are you using the deployment feature of MSTest? If so, PDBs should be deployed (copied over) as well  for each test run. AFAIK they are not deployed, but can be added with: https://msdn.microsoft.com/en-us/library/ms182475.aspx?f=255&MSPPError=-2147217396.

I think the [testsetting](https://msdn.microsoft.com/en-us/library/ms182475.aspx?f=255&MSPPError=-2147217396#Anchor_3) file is the most appropriate in this use-case.

**Comment by JoeAtGit** [comment]
Thank you Molnargab for your suggestion

Tried adding a testsetting file, tried invoking VsTest and MsTest like so:

 opencover.console.exe -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" "-targetargs:/testcontainer:"E:\Work\Staging\TestProjectName\bin\Debug\TestProjectName.dll\"  /Logger:trx /Settings:"E:\Work\Staging\LastTry.testsettings\"" -output:"E:\Work\Staging\OpenCover\coverResult.xml" -register:user -filter:"+[TestProjectName*]* -[*.Spec]*"  -mergebyhash
 
  -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"\"E:\Work\Staging\TestProjectName\bin\Debug\TestProjectName.dll\"  /Logger:trx /Settings:\"E:\Work\Staging\LastTry.testsettings\"" -output:"E:\Work\Staging\OpenCover\coverResult.xml" -register:user -filter:"+[TestProjectName*]* -[*.Spec]*"  -mergebyhash

Both communicate: "<Module skippedDueTo="MissingPdb" hash="CA">"

Best
Joe

**Comment by sawilde** [comment]
@JoeAtGit - are you still having issues?

**Comment by arturokunder** [comment]
@sawilde I have the same problem.
I'm testing an ASP MVC 5 app with Visual Studio Unit testing (VS2015)

**Comment by JoeAtGit** [comment]
Yes sir.

Less critical as our automated build server (Jenkins) is able to still run
OpenCover.
Alas, we have to check into master in order to get cover results
