### ISSUE TITLE
How do I use the -register argument?

### ISSUE THREAD

**Issue by gCurtisCT** [OpenCover/opencover#357]
When I run this command: `OpenCover.Console -target:"Conv tests.csproj" -register[:Path64]`

I get this error message:

`The argument register[ is not recognised`

If `Path64` is supposed to be a variable and not literal, what is it supposed to be a variable for?

**Comment by ddur** [comment]
[] means optional, use -register:user or -register:Path64 or  -register:Path32

**Comment by gCurtisCT** [comment]
Okay. thanks. Now I'm not sure that I'm pointing it towards the right target. What should I point it at? The compiled `.exe`? When I do that, correctly specifying the register, it just runs my executable as if I double-clicked on it.

**Comment by ddur** [comment]
OpenCover target is usually NUnit console that runs the tests that runs over your "target" code :)

https://github.com/opencover/opencover/wiki/Usage
https://github.com/OpenCover/opencover/raw/master/main/OpenCover.Documentation/Usage.pdf

Exmple from first link above:
```bat
OpenCover.Console.exe -target:"C:\Program Files (x86)\NUnit 2.6\bin\nunit-console.exe" 
  -targetargs:"/nologo /noshadow C:\AUT\Ihavethetests.dll" -filter:"+[*]* -[Ihavethetests*]*" -register:user
```

**Comment by gCurtisCT** [comment]
Thanks a lot! I was able to get everything working. Except now it's telling me that 2/14 tests pass, whereas if I run the tests through Visual Studio it says all the tests pass.
