### ISSUE TITLE
Build with installed VS2013/Community, fails on OpenCover.UITest 

### ISSUE THREAD

**Issue by ddur** [OpenCover/opencover#358]
Error CS0234: The type or namespace name 'UITesting' does not exist in the namespace 'Microsoft.VisualStudio.TestTools' (are you missing an assembly reference?)

Error CS0246: The type or namespace name 'CodedUITest' could not be found (are you missing a using directive or an assembly reference?)

Error CS0246: The type or namespace name 'CodedUITestAttribute' could not be found (are you missing a using directive or an assembly reference?)

**Comment by sawilde** [comment]
It's also now affecting the build server so need to pull it from the solution and fix any build issues.

**Comment by sawilde** [comment]
https://ci.appveyor.com/project/sawilde/opencover/build/4.6.219

**Comment by ddur** [comment]
https://github.com/OpenCover/opencover/pull/377
