### ISSUE TITLE
SharpDevelop integration

### ISSUE THREAD

**Issue by ddur** [OpenCover/opencover#359]
So far it was possible just to drop new binaries in Sharp Develop \bin\tools\OpenCover\[x86|x64].
It does not apply any more. 

When I copy `Release` binaries and run, `coverage.xml` is empty, no error messages.
```<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>```

Running `Debug` binaries reports message:
`Committing...`
`No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.`

Sharp Develop generated command:
`"[......]\SharpDevelop\bin\Tools\OpenCover\OpenCover.Console.exe" -register:user -mergebyhash -target:"[......]\bin\Tools\NUnit\nunit-console-x86.exe" -targetdir:"[......]\Source\Test\Project\bin\Debug" -targetargs:"\"[......]\bin\Debug\Project.dll\" /xml=\"[......]\Source\Test\Project\bin\Debug\Project-TestResult.xml\" /pipe=\"df535cbf-c30c-4549-ba92-4a67d2bc53e7\" /run=\"ProjectTest\"" -output:"[......]\Source\Test\Project\OpenCover\coverage.xml" -filter:"+[Solution]Namespace1* +[Solution]Namespace2* "`

I do not know what is changed in OpenCover (profiler?) after 4.5.2506.1
Maybe problem has to do with `/pipe=\"df535cbf-c30c-4549-ba92-4a67d2bc53e7\"` option used in command?

**Comment by ddur** [comment]
I tried all releases from and including 4.5.2506
https://github.com/OpenCover/opencover/releases/tag/4.5.2506
https://github.com/OpenCover/opencover/releases/tag/4.5.3207
https://github.com/OpenCover/opencover/releases/tag/4.5.3427
https://github.com/OpenCover/opencover/releases/tag/4.6.166
https://github.com/OpenCover/opencover/releases/tag/4.6.181-rc
https://github.com/OpenCover/opencover/releases/tag/4.6.192-rc

All above works as expected except most recent one:
https://github.com/OpenCover/opencover/releases/tag/4.6.210-rc

**Comment by sawilde** [comment]
What is the `pipe` option? A throwback from the PartCover days? 

The command line parser should fail if an unrecognized parameter is supplied.

**Comment by ddur** [comment]
1) No, is not 'pipe'.  It works same when 'pipe' removed.
2) It is not command line parser. If command line parser fails, OpenCover would stop immediately with exception. Here everything looks fine, tests are performed, until end, when coverage.xml is empty.

**Comment by ddur** [comment]
@sawilde 
AFAIK, SharpDevelop runs OpenCover as child process.
Maybe problem is here https://github.com/OpenCover/opencover/issues/282

**Comment by molnargab** [comment]
@ddur, could you also check a CI build before 4.6.210? [This one (4.6.206)](https://ci.appveyor.com/project/sawilde/opencover/build/4.6.206/artifacts) is right before merging the feature you suspect, and [this](https://ci.appveyor.com/project/sawilde/opencover/build/4.6.207/artifacts]) is a build with the changes.

**Comment by ddur** [comment]
Thanks @molnargab
Build https://ci.appveyor.com/project/sawilde/opencover/build/4.6.205 works
Build https://ci.appveyor.com/project/sawilde/opencover/build/4.6.206 not
Problem is somewhere here https://github.com/opencover/opencover/pull/345

**Comment by ddur** [comment]
Well, looks like builds after 4.6.205 do not work outside build environment. 
No single one Zip distribution package (after 4.6.205) contains CrashReporter.NET.dll
Latest MSI distribution (just installed and tested), contains CrashReporter.NET.dll, but it does not work too.

This is not only SharpDevelop issue!

**Comment by ddur** [comment]
@sawilde 
Fund :sunglasses:
Versions after build 4.6.205 have changed something about filters. 
Command option -filter: argument that worked in older versions, now returns nothing!

**Comment by ddur** [comment]
Assembly name filter does not pass
[assembly_name]namespace* - empty result
[*]namespace* - OK

**Comment by sawilde** [comment]
does the `assembly_name` match what is in the XML i.e. compare it with what you get when you have `*`

**Comment by ddur** [comment]
When I use ```[*]``` reported module name is OK. 
Same as ```assembly_name``` (```<ModuleName>DBCL</ModuleName>```)

**Comment by molnargab** [comment]
I did some debugging on this. If one provides both an assembly and a class filter, then none of the processes would be included, due to a bug in `Filter.InstrumentProcess`.

**Comment by ddur** [comment]
My test assembly is DBCL.dll, namespace DD.Collections, class BitSetArray
Filter was +[DBCL]DD.Collections.BitSetArray*
No, it does not work with filter above.

**Comment by ddur** [comment]
@molnargab 
If you want to test
Repository https://github.com/ddur/DBCL
Clone, restore packages, check if ok and run test-coverage.bat
First two tests should have same coverage result

**Comment by molnargab** [comment]
Just grabbed the latest version, it does produce 100% for both cases.
Though, I had to point the script to my built version of OpenCover, not to the installed one.

**Comment by ddur** [comment]
I'm not sure that I understand what you want to say. What produces what?
I installed latest OpenCover MSI installer from AppVeyor
https://ci.appveyor.com/project/sawilde/opencover/build/4.6.252/artifacts

![untitled](https://cloud.githubusercontent.com/assets/3501612/11998553/2fc63fa8-aaa4-11e5-8b14-f12b0537b773.png)

**Comment by ddur** [comment]
I'm not sure, but on the first glimpse, I guess problem is here
Arguments are process name and assembly name but exclusion filter that is checked is class name.
I think it should be a assembly name exclusion filter. 
Looks like copy/paste error.
```
        /// <summary>
        /// Decides whether an assembly should be included in the instrumentation
        /// </summary>
        /// <param name="processName">The name of the process being profiled</param>
        /// <param name="assemblyName">the name of the assembly under profile</param>
        /// <remarks>All assemblies matching either the inclusion or exclusion filter should be included 
        /// as it is the class that is being filtered within these unless the class filter is *</remarks>
        public bool UseAssembly(string processName, string assemblyName)
        {
            processName = Path.GetFileNameWithoutExtension(processName);
            var matchingExclusionFilters = ExclusionFilters.GetMatchingFiltersForAssemblyName(assemblyName);
            if (matchingExclusionFilters.Any(exclusionFilter => exclusionFilter.ClassName == ".*" && exclusionFilter.IsMatchingProcessName(processName)))
            {
                return false;
            }

            if (matchingExclusionFilters.Any(exclusionFilter => exclusionFilter.ClassName != ".*"))
            {
                return true;
            }

            var matchingInclusionFilters = InclusionFilters.GetMatchingFiltersForAssemblyName(assemblyName);
            if (matchingInclusionFilters.Any())
            {
                return true;
            }

            return false;
        }
```

**Comment by ddur** [comment]
I found some old version of UseAssembly
```
        public bool UseAssembly(string assemblyName)
        {
            if (ExclusionFilter.Any(keyValuePair => Regex.Match(assemblyName, keyValuePair.Key.WrapWithAnchors()).Success && keyValuePair.Value == ".*"))
            {
                return false;
            }

            if (ExclusionFilter.Any(keyValuePair => Regex.Match(assemblyName, keyValuePair.Key.WrapWithAnchors()).Success && keyValuePair.Value != ".*"))
            {
                return true;
            }

            if (InclusionFilter.Any(keyValuePair => Regex.Match(assemblyName, keyValuePair.Key.WrapWithAnchors()).Success))
            {
                return true;
            }

            return false;
        }
```

**Comment by molnargab** [comment]
On my machine it is:
![image](https://cloud.githubusercontent.com/assets/3465869/12002587/edd1b092-ab01-11e5-90a4-852d3ed1f9cd.png)

I think `UseAssembly` is correct:

1. Exclude an assembly if all of its classes are excluded for the given process,
1. Include the assembly if only some classes are excluded.

`assemblyName` is taken into part when selecting the matching filters, i.e. the part from the old code when `keyValuePair.Key` was used.

**Comment by ddur** [comment]
@molnargab 
So, you cannot reproduce?

**Comment by ddur** [comment]
When I use  +[DBCL]Anything*, command-line parser parses OK,   ```AddFilter (string assemblyClassName)``` is invoked and ```AssemblyAndClassFilter``` is created
But ```UseAssembly``` and ```InstrumentClass``` are never invoked!

**Comment by ddur** [comment]
Cannot find in documentation anything about {process} filter.
Sometime is path, sometime GUID?

**Comment by molnargab** [comment]
@ddur, yes, I can not reproduce your issue with 4.6.252 (though I'm able to with 4.6.210-rc). Also both of those methods are called in my case.

Could you check you're indeed running 4.6.252 (e.g. adding another call with `-version` option to your script)?

**Comment by ddur** [comment]
I have found it :+1: Came to same fix then I realize 2) then 1) 
1) I installed 4.6.252 from link above, but version returned is 4.6.222 :smiling_imp: 
2) Your fix/change is not merged into my local repository or branch :smile:

**Comment by sawilde** [comment]
:+1:
