### ISSUE TITLE
OpenCover.Console.exe does not return 1 error code when target returns 1

### ISSUE THREAD

**Issue by marcelmunarolo** [OpenCover/opencover#361]
Dear Colleagues, 

As described in issue #333 , even using the att -returntargetcode, it is not working.
Any options so far?

Thanks,
Marcel

**Comment by sawilde** [comment]
What do you mean by not working? Perhaps a few more details will help

**Comment by marcelmunarolo** [comment]
False alarm,
Actually, it was a problem in my bat file, and the -returntargetcode is working properly.

My apologies,
Marcel
