### ISSUE TITLE
Feature Request: Please measure and report method NPath complexity

### ISSUE THREAD

**Issue by NigelThorne** [OpenCover/opencover#363]
NPath counts the number of (non-looping) paths through a method. This matches the number of unit tests you would have to write to fully exercise every path through that method. This is helpful when working in a mentoring role, to help show how good design needs less testing.  I'd love to be able to also report "this method should have 12 tests, it has 2".

NPath grows exponentially, so is typically a much larger number than the Cyclomatic Complexity.

http://modess.io/2013/05/19/cyclomatic-and-npath-complexity-explained/

**Comment by ddur** [comment]
NPath complexity (as explained in your link) can be computed from &lt;BranchPoint&gt; tags in report. 
Maybe can be done in ReportGenerator too. Are you using it?
https://github.com/danielpalme/ReportGenerator

**Comment by sawilde** [comment]
@NigelThorne - have you looked at the <BranchReport/> data, does it have what you need? The branches are IL branches however and so may not directly correlate with code and so the npath calculation may be a bit awry; we are looking at trimming out the auto generated branches (when we get round to identifing them)

**Comment by ddur** [comment]
https://github.com/OpenCover/opencover/pull/391

**Comment by sawilde** [comment]
Keeping it open until we release
