### ISSUE TITLE
VsPerfCmd Keeps on running after opencover and build are finished.

### ISSUE THREAD

**Issue by joshidp** [OpenCover/opencover#367]
Hi,

VsPerfCmd.exe keeps running even after build including open cover run has competed. iIt locks some of the files in workspace.

I tried it to shutdown, but VsPerfCmd gives me error that " VSP1306: Profile Monitor does not appear to be running. "

Please suggest some solution.

Thanks!

**Comment by sawilde** [comment]
I am not sure how this relates to OpenCover.
