### ISSUE TITLE
Empty code coverage with xunit.vsix (VS integration tests)

### ISSUE THREAD

**Issue by kzu** [OpenCover/opencover#368]
Hi there!

[xunit.vsix](https://www.nuget.org/packages/xunit.vsix) provides an Xunit-based VS integration testing library, by launching VS, connecting to it and generally doing everything MSTest + [HostType("VS IDE")] does for VS extensibility authors. Everything is working great except for collecting code coverage numbers :(.

I've tried all the instructions on #109, [StackOverflow](http://stackoverflow.com/questions/27278266/using-opencover-to-run-coded-ui-tests-not-collecting-application-code) and everything in-between with no luck. (including reading on how you got Moles/Fakes to work). I also tried -register:user, -register:path32, manually regsvr32 x86\OpenCover.Profiler.dll, creating the registry entries manually and even restarting Windows.

I've created the [bare minimum VSIX extension](https://www.dropbox.com/s/vi37epcvh6l37k8/MyExtension.7z?dl=0) and its integration tests solution to reproduce the issue with minimal noise.

You only need to run the build.cmd script from a developer command prompt, and it will install the Xunit/OpenCover/ReportGenerator nuget packages, build the solution, and run the single integration test, which just invokes a single method in a MEF-exported VS service. The batch script sets the recommended envvars too.

The xunit.vsix nuget package includes the full source under the `src` folder, so you can also just run with the debugger attached and set breakpoints in that source and it will all work. Source also available here in [github](https://github.com/kzu/xunit.vsix). The code that propagates the profiler-related environment variables to the ProcessStartInfo before launching it is in the [VsClient](https://github.com/kzu/xunit.vsix/blob/master/src/Xunit.Vsix/VsClient.cs#L298) class. 

Just to make sure that all the vars are where I expect them to be, the integration test I created will just dump all envvars in the current process, which is the VS instance started to run it.

I'm at a complete loss as to why it doesn't work, any help would be immensely appreciated!

**Comment by kzu** [comment]
Thanks in advance @sawilde for an amazing tool and hopefully some help on this ;)

**Comment by sawilde** [comment]
OpenCover has two parts the `.exe` host and the `.dll` profiler(s). You need both running for OpenCover to work correctly as the profiler needs to talk to the host that launched the application that the profiler is attached to (hope that makes sense).

There is a project called [OpenCover.UI](https://github.com/OpenCoverUI/OpenCover.UI) that could be extended/completed to handle [xunit](https://github.com/OpenCoverUI/OpenCover.UI/pull/69) - this might be an alternative starting point.

**Comment by kzu** [comment]
Cool, gonna take a look. Thanks!

**Comment by kzu** [comment]
Hmm... but the repro I provided, invokes the OpenCover.exe to run the xunit runner, so unless you're referring to another .exe, it obviously is running by the time the xunit extension I created runs, starts VS and executes the code.

**Comment by sawilde** [comment]
> but the repro I provided

I wasn't in a position to look at the repro as I couldn't open it on my phone from dropbox. 

What are the envvars for? OpenCover supplies all the envvars it needs when it launches to target process.

**Comment by kzu** [comment]
I just wanted to ensure that all teh envvars were in place (they are).

The way it works is: opencover.exe -> xunit.console.x86.exe -> devenv.exe

It seems at some point, between xunit console and devenv.exe, that coverage stops happening.

**Comment by ddur** [comment]
@kzu 
What is your OpenCover version number?

**Comment by kzu** [comment]
Hey @ddur, I finally came to the obvious conclusion that a zip in dropbox isn't very useful to peek into a repro :)

So here it is in its entirety: https://github.com/kzu/OpenCoverVsixTests

The version I'm using right now is [4.6.166](https://github.com/kzu/OpenCoverVsixTests/blob/master/packages.config#L4)

**Comment by kzu** [comment]
I would appreciate any help on this, I'm dead in the water without coverage for VS integration tests :(

**Comment by ddur** [comment]
@kzu 
First, your sample does not work, test fails.
Second, I do not see where OpenCover is invoked in your build.cmd

Take look at my https://github.com/ddur/DBCL/blob/master/coveragetest.bat

```@".\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe" -register:user -mergebyhash ^```
```-output:".\artifacts\OpenCover.BitSetArray.xml" ^```
```-filter:"+[DBCL]DD.Collections.BitSetArray*" ^```
```-target:".\packages\NUnit.Runners.Net4.2.6.4\tools\nunit-console-x86.exe" ^```
```-targetdir:".\Source\Test\NUnit.BitSetArray\bin\Debug" ^```
```-targetargs:"\"NUnit.BitSetArray.dll\" /labels /xml=\"TestResult.xml\" "```

Fix first row path to point where your OpenCover is installed
Change second row where you want coverage report to be saved
Remove filter row (change later if required)
Change 
```-target:"path\to\your\xunit\runner.exe" ^```
```-targetdir:"\path\to\dir\where\xunit\runner\will\run\" ^```
```-targetargs:"arguments for xunit runner (escape quote \"within\" targetargs)"```

Note: ^ character is line continuation

When you get ```-output:coverage.xml``` then use Report Generator to display coverage as html
Report Generator sample is at the bottom of coveragetest.bat

**Comment by kzu** [comment]
Hey @ddur thanks for taking the time to look into this. 

When you run build.cmd, that runs msbuild for build.proj, which runs the Build target [which invokes OpenCover](https://github.com/kzu/OpenCoverVsixTests/blob/master/build.proj#L45).

I've [gisted the output](https://gist.github.com/kzu/ed7c4eae471e9284bbb2#file-opencoverbuildoutput) where you can see that xunit is [properly being invoked](https://gist.github.com/kzu/ed7c4eae471e9284bbb2#file-opencoverbuildoutput-L7) and even the [test output string foo](https://gist.github.com/kzu/ed7c4eae471e9284bbb2#file-opencoverbuildoutput-L114) is even rendered, from a [call form the test to a service](https://github.com/kzu/OpenCoverVsixTests/blob/master/src/MyExtension.IntegrationTests/MyServiceSpec.cs#L37) that is hosted in the running [Visual Studio MEF custom service](https://github.com/kzu/OpenCoverVsixTests/blob/master/src/MyExtension/MyService.cs#L19).

But the [visited classes](https://gist.github.com/kzu/ed7c4eae471e9284bbb2#file-opencoverbuildoutput-L120) remains zero, even if the code did actually run, and [the environment variables](https://gist.github.com/kzu/ed7c4eae471e9284bbb2#file-opencoverbuildoutput-L24) on the running VS process clearly have the proper (I think?) profiling values.

Does it make sense?

**Comment by kzu** [comment]
I should have noticed that you of course need to run `build.cmd` from a VS developer command prompt, since it invokes `msbuild`... The test [passes without errors if you do so](https://gist.github.com/kzu/ed7c4eae471e9284bbb2#file-opencoverbuildoutput-L118) (just did a clean repo clone).

**Comment by ddur** [comment]
Unfortunately something is wrong with my VSSDK installation.
But after I changed ```-register:user``` and  removed filter and '^' after ```-excludebyattribute:*.ExcludeFromCodeCoverage*^``` I got some result. Hope it helps.

```
         E:\GitHub\OpenCoverVsixTests\build\packages\OpenCover\tools\OpenCover.Console.exe  -output:out\test.coverage.x
         ml -register:user -returntargetcode -excludebyattribute:*.ExcludeFromCodeCoverage* -skipautoprops -hideskipped
         :All -threshold:1 -mergebyhash -target:E:\GitHub\OpenCoverVsixTests\build\packages\xunit.runner.console\tools\
         xunit.console.x86.exe -targetargs:"E:\GitHub\OpenCoverVsixTests\src\MyExtension.IntegrationTests\bin\Debug\MyE
         xtension.IntegrationTests.dll  -html out\test.html -xml out\test.xml -parallel all -noshadow"
         ?Executing: E:\GitHub\OpenCoverVsixTests\build\packages\xunit.runner.console\tools\xunit.console.x86.exe
         xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
           Discovering: MyExtension.IntegrationTests
           Discovered:  MyExtension.IntegrationTests
           Starting:    MyExtension.IntegrationTests
             MyExtension.IntegrationTests.MyServiceSpec.when_invoking_service_then_succeeds [FAIL]
               System.InvalidOperationException : Cannot execute test for specified VisualStudioVersions=14.0 because t
         here is no VSSDK installed for that version.
           Finished:    MyExtension.IntegrationTests
         === TEST EXECUTION SUMMARY ===
            MyExtension.IntegrationTests  Total: 0
         Committing...
         Visited Classes 145 of 378 (38.36)
         Visited Methods 332 of 1234 (26.9)
         Visited Points 1262 of 5751 (21.94)
         Visited Branches 751 of 3892 (19.30)

         ==== Alternative Results (includes all methods including those without corresponding source) ====
         Alternative Visited Classes 164 of 402 (40.8)
         Alternative Visited Methods 438 of 1576 (27.79)
```

**Comment by kzu** [comment]
Yeah, the problem with removing the filters is that then running tests takes forever and the resulting coverage report is gigantic since it includes every single assembly that runs within VS, which is like a TON :)

`OpenCover.Console.exe  -output:out\test.coverage.xml -register:user -returntargetcode -filter:"+[MyExtension]* +[MyExtension.IntegrationTests]* -[Microsoft.*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -skipautoprops -hideskipped:All -threshold:1 -mergebyhash -target:C:\Code\Personal\OpenCoverVsixTests\build\packages\xunit.runner.console\tools\xunit.console.x86.exe -targetargs:"C:\Code\Personal\OpenCoverVsixTests\src\MyExtension.IntegrationTests\bin\Debug\MyExtension.IntegrationTests.dll  -html out\test.html -xml out\test.xml -parallel all -noshadow"`

I've removed the `^` you mentioned, and copied the resulting command line above. I can't find what's wrong with the filter expression :(

**Comment by kzu** [comment]
> Note that the quotes must be around the -filter: part, too

From [SO](http://stackoverflow.com/questions/6829792/how-to-add-filters-to-opencover-tool-to-skip-some-of-the-classes-in-a-namespace), argh!

**Comment by kzu** [comment]
btw, @ddur the error you see is because you don't seem to have installed the VSSDK for 2015 (it's now a checkbox in the main installer) at all :(. So the results you're getting aren't also the interesting ones, since those are from the test runner and test classes, rather than the extension under test. 

I've tried all combinations possible. Yes, if I set no filter at all, I get a humongous coverage xml, but it still says that MyExtension.MyService wasn't covered, even if the only integration test there invokes it and its output is clearly in the console output. Adding just my assembly filter didn't work either:

`C:\Code\Personal\OpenCoverVsixTests\build\packages\OpenCover\tools\OpenCover.Console.exe  -output:out\test.coverage.xml -register:user -returntargetcode -filter:+[MyExtension]* -skipautoprops -hideskipped:All -mergebyhash -target:C:\Code\Personal\OpenCoverVsixTests\build\packages\xunit.runn
er.console\tools\xunit.console.x86.exe -targetargs:"C:\Code\Personal\OpenCoverVsixTests\src\MyExtension.IntegrationTests\bin\Debug\MyExtension.IntegrationTests.dll  -htm
l out\test.html -xml out\test.xml -parallel all -noshadow"`

I've removed pretty much everything from the call, and the [new output](https://gist.github.com/kzu/f63dab258b1e2fe2d009#file-opencoverbuildoutput2-L2) from that call still results in [zero visited classes](https://gist.github.com/kzu/f63dab258b1e2fe2d009#file-opencoverbuildoutput2-L111) even if the [foo string right above](https://gist.github.com/kzu/f63dab258b1e2fe2d009#file-opencoverbuildoutput2-L105) comes from the [service writing to Debug](https://github.com/kzu/OpenCoverVsixTests/blob/master/src/MyExtension/MyService.cs#L19) the 'foo' string passed in [by the running test](https://github.com/kzu/OpenCoverVsixTests/blob/master/src/MyExtension.IntegrationTests/MyServiceSpec.cs#L37). :confused:

**Comment by ddur** [comment]
I had some warnings when VS is installed. 
Reinstalled VS2015, VSSDK is now OK.
MyExtension.MyService::Run is instrumented and present in test.coverage.xml, no visits.
```
    <Module hash="E3-C0-AF-CF-F2-1C-D9-9B-A4-B4-9A-80-32-F4-79-41-67-BD-B5-17">
      <Summary numSequencePoints="5" visitedSequencePoints="0" numBranchPoints="3" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="1" visitedClasses="0" numClasses="1" visitedMethods="0" numMethods="1" />
      <FullName>C:\USERS\DDUR\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0EXP\EXTENSIONS\KZU\MYEXTENSION\1.0\MyExtension.dll</FullName>
      <ModuleName>MyExtension</ModuleName>
      <Files>
        <File uid="5" fullPath="E:\GitHub\OpenCoverVsixTests\src\MyExtension\MyService.cs" />
      </Files>
      <Classes>
        <Class>
          <Summary numSequencePoints="5" visitedSequencePoints="0" numBranchPoints="3" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="1" visitedClasses="0" numClasses="1" visitedMethods="0" numMethods="1" />
          <FullName>MyExtension.MyService</FullName>
          <Methods>
            <Method visited="false" cyclomaticComplexity="2" sequenceCoverage="0" branchCoverage="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="5" visitedSequencePoints="0" numBranchPoints="3" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="2" minCyclomaticComplexity="2" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="1" />
              <MetadataToken>100663297</MetadataToken>
              <Name>System.Void MyExtension.MyService::Run(System.String)</Name>
              <FileRef uid="5" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="24" ordinal="0" offset="0" sl="15" sc="3" el="15" ec="4" bec="0" bev="0" fileid="5" />
                <SequencePoint vc="0" uspid="25" ordinal="1" offset="1" sl="16" sc="4" el="16" ec="39" bec="2" bev="0" fileid="5" />
                <SequencePoint vc="0" uspid="26" ordinal="2" offset="11" sl="17" sc="5" el="17" ec="45" bec="0" bev="0" fileid="5" />
                <SequencePoint vc="0" uspid="27" ordinal="3" offset="22" sl="19" sc="4" el="19" ec="30" bec="0" bev="0" fileid="5" />
                <SequencePoint vc="0" uspid="28" ordinal="4" offset="29" sl="20" sc="3" el="20" ec="4" bec="0" bev="0" fileid="5" />
              </SequencePoints>
              <BranchPoints>
                <BranchPoint vc="0" uspid="29" ordinal="0" offset="9" sl="16" path="0" offsetend="11" fileid="5" />
                <BranchPoint vc="0" uspid="30" ordinal="1" offset="9" sl="16" path="1" offsetend="22" fileid="5" />
              </BranchPoints>
              <MethodPoint xsi:type="SequencePoint" vc="0" uspid="24" ordinal="0" offset="0" sl="15" sc="3" el="15" ec="4" bec="0" bev="0" fileid="5" />
            </Method>
            <Method visited="false" cyclomaticComplexity="1" sequenceCoverage="0" branchCoverage="0" isConstructor="true" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
              <MetadataToken>100663298</MetadataToken>
              <Name>System.Void MyExtension.MyService::.ctor()</Name>
              <SequencePoints />
              <BranchPoints />
              <MethodPoint vc="0" uspid="31" ordinal="0" offset="0" />
            </Method>
          </Methods>
        </Class>
      </Classes>
    </Module>
```
As far as I understand, test starts new instance of Visual Studio in another process. 
Maybe that is problem?
Have you tried to do the same tests with NUnit 2.6.4?
@sawilde ?

**Comment by kzu** [comment]
Yeah, that's precisely my repro and what it does. It's no different than
MSTest CodedUI tests though, so it should just work :(

**Comment by ddur** [comment]
I think that your extension is part of new instance of VS, not the current one. 
Can you install your extension into VS and then run the tests within same VS without starting new one?

**Comment by kzu** [comment]
That doesn't make a lot of sense. When you create integration tests for an extension, you build the extension, that deploys the VSIX binaries (and symbols) to the VS experimental instance, which at that point has the same binaries installed as your integration test project, and then the integration test runs in the context of the launched VS. This is exactly what MSTest HostType("VS IDE") attribute does, and is exactly what I replicated (and improved along the say) with xunit.vsix nuget (since MSTest isn't very flexible for what we need).

Without starting a new IDE instance, you can't control what version of the IDE the test runs, what "hive" (Experimental or normal), etc. You can't also recycle VS if a test corrupts the environment so that others can continue to run, and so on.

Again, the scenario I'm running is exactly the same as a CodedUI test: you don't expect the CodedUI test to automate the IDE you're running the test from, right? You always launch a new process, and automate that one instead.

So, if the test is indeed running, calling the right code (as shown in the output), and the envvars are properly configured to profile, I still can't imagine why the classes show as non visited :(

**Comment by ddur** [comment]
I think that new IDE instance has installed vsix binaries that are not the same as instrumented binaries.
Reported binary is:
``` Users\User\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0EXP\EXTENSIONS\KZU\MYEXTENSION\1.0\MyExtension.dll</FullName> ```

OpenCover instrumented.dll usually has different path, like:
``` Users\user\AppData\Local\Temp\nunit20\ShadowCopyCache\9312_635859770746869398\Tests_79857515\assembly\dl3\82953d30\a06c294c_5f37d101\DBCL.dll ```
... and I think that not-instrumented original binary from project \Debug or \Release is installed as vsix extension. Not instrumented binary from "ShadowCopyCache".

However, I can be wrong.

**Comment by ddur** [comment]
On my PC, 
``` C:\Users\User\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0EXP\EXTENSIONS\KZU\MYEXTENSION\1.0\MyExtension.dll ```
has exact same size as 
``` E:\GitHub\OpenCoverVsixTests\src\MyExtension\bin\Debug\MyExtension.dll ```

AFAIK, Instrumented.dll must have larger size than original.

**Comment by molnargab** [comment]
@kzu, could you check if you can run a VS instance with your extensions from OpenCover directly? 

Your toolchain is quite complex, it would be good to know if we're able to produce the results at all. Then we could investigate why it's not working the expected way.

**Comment by kzu** [comment]
I don't follow. What do you mean by "my extension"? The VS extension?
That's just a dummy service. Invoking the service must be done from a that
spins up a new VS, it can't be called "in process". As far as "run from
OpenCover directly" I'm lost too. Doesn't it just call the rest runner that
exercises the code?

Also, I thought OpenCover used the clr profiling APIs directly and didn't
rewrite any assemblies, is that a wing assumption on my part?

**Comment by ddur** [comment]
As far as I can remember, OpenCover rewrites assemblies. I think it does it in memory.
I'm afraid that I can't help any you more with my limited knowledge and time.

**Comment by kzu** [comment]
If it rewrites it in memory, then the physical file size wouldn't be different from the ones built by VS in bin\Debug|Release, right? 

I've striped everything out of the [build script](https://github.com/kzu/OpenCoverVsixTests/blob/master/build.proj), which is now a simple holder of config for the calls to open cover (and doing the nuget restore). 

I've also added the exact same test but using MSTest, to make sure it's not my xunit.vsix nuget doing something weird. 

Running build.cmd will just do msbuild build.proj /t:mstest, which just [invokes OpenCover with MSTest as a target](https://github.com/kzu/OpenCoverVsixTests/blob/master/build.proj#L39).

I got the same results as before: zero visited classes. I wonder if @AArnott uses OpenCover for MS's own integration tests and code coverage?

**Comment by AArnott** [comment]
AFAIK no one in VS uses OpenCover or xunit.vsix. But now that I know xunit.vsix exists, I hope to find time soon to look at it. I was working on a similar idea early this year but never finished it.

**Comment by ddur** [comment]
What I was trying to say is that OpenCover does not copy instrumented dll into temporary installed VS extension. You have two identical binaries in two places and maybe, one is instrumented and another is run. If you are willing to try tests as I earlier suggested, you will quick find out if that is true or not.

**Comment by ddur** [comment]
@AArnott 
https://github.com/dotnet/buildtools/blob/25decb2fe02edd3b7ab32a325e2281c2a2df9ea9/src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets

**Comment by AArnott** [comment]
@ddur: that's cool. But I don't think we build VS with that. .NET may build parts of itself with it, but that's a separate code base and system.

**Comment by ddur** [comment]
@AArnott: Sure, I can imagine that you all at VS have at least VS Enterprise ;)

**Comment by AArnott** [comment]
I wish. Actually most of VS builds with a rather old build system. We're working to bring it up to par with what we ship to customers, but it's a very big job.

**Comment by sawilde** [comment]
OpenCover doesn't rewrite assemblies, what it does is intercept the JIT of a method by the runtime and then gives the runtime an updated method with the instrumentation points inserted. No modification is made to anything on the disk.

**Comment by ddur** [comment]
@sawilde this put into another simpler words: "it rewrites assembly method by method, in memory"?

**Comment by kzu** [comment]
Any guesses as to why it would successfully show static analysis of the
relevant assemblies but have none of them visited in this case when the
test launches a second process? (Using MSTest in my latest repro)

**Comment by ddur** [comment]
@kzu
It is not what i guessed earlier. 
I referenced installed vsix binaries from xunit test project and result is same.

I do not know, but maybe, maybe because vsix assembly is not directly run by test, maybe because it is loaded (again?) into VS (out of OpenCover instrumentation chain?) and exposed via service interface.

I'm not sure what you mean under "static analysis", maybe Code Contracts with "Static contract checking" can help?

**Comment by kzu** [comment]
I meant that cyclomatic complexity is reported for the assembly I want
coverage reported ;)

Supposedly, as long as the envvars are set, it doesn't matter who and when
starts the child processes, since that's how it works for CodedUI tests
too, as far as I could gather from the web ;)

**Comment by ddur** [comment]
@kzu, I don't know what you mean by CodedUI.
This? https://msdn.microsoft.com/en-us/library/dd286726.aspx#VerifyingCodeUsingCUITCreate

Allegedly, Visual Studio Enterprise has its own Code Coverage tool. 
I'm strongly convinced that such tool will cover VS extensions. ;)

**Comment by kzu** [comment]
Don't have enterprise ;)

MSTest VS integration tests don't require enterprise and do the same
basically, launch a child process and code is exercised. Is it possible I'm
the first to try to use OpenCover for this? :o)

**Comment by ddur** [comment]
@kzu 
It is possible.

I made small modification, added 2 lines above service call
```
            IMyService iMyExtensionService = new MyExtension.MyService();
            iMyExtensionService.Run ("bar");

            var components = GlobalServices.GetService<SComponentModel, IComponentModel>();
			var service = components.GetService<IMyService>();
			service.Run ("foo");

```
It is not covered. 
I can only conclude that vsix extension is loaded an JIT-ed at VS startup, before tests starts, so OpenCover can detect, but cannot instrument that assembly.

What you think?

**Comment by ddur** [comment]
If is possible to start new [VS instance](https://msdn.microsoft.com/en-us/library/bb166560.aspx) as part of the OpenCover&test suite, I guess, vsix will be covered?

**Comment by ddur** [comment]
@kzu 
Profiler registered before build with regsvr32, no change.

@AArnott 
Maybe VS at startup compiles vsix extensions to native?

**Comment by AArnott** [comment]
@ddur: No, VS does *not* compile vsix extensions to native code. The CLR JIT does the normal thing.

**Comment by ddur** [comment]
Thanks @AArnott !

**Comment by ddur** [comment]
@kzu I did not realize earlier that [xUnit.vsix](https://www.nuget.org/packages/xunit.vsix) is your project (on top of xUnit).

It seems that coverage problem has nothing to do with VisualStudio.

To your first sample solution I added standard C# library project NoExtension.NoService.Run() (Same as MyExtension but not VS extension) and extended OpenCover -filter to cover  ```[*]Extension.IntegrationTests*```.
Result: **Nothing is visited!** 
```
         Finished:    MyExtension.IntegrationTests
         === TEST EXECUTION SUMMARY ===
         MyExtension.IntegrationTests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 32,410s
         Committing...
         Visited Classes 0 of 5 (0)
         Visited Methods 0 of 7 (0)
         Visited Points 0 of 30 (0)
         Visited Branches 0 of 23 (0)
```
Possible cause?:
Test cases in xUnit.vsix ar run by VsRemoteRunner
Remote profiling is not supported by CLR profiling API (https://msdn.microsoft.com/en-us/library/bb384493%28v=vs.110%29.aspx#support)
Yet, I'm not sure if those two "remote" describe same concept

Test to do:
Run any coverage tests with xUnit only. 
xUnit.vsix sits on top of xUnit, and If nothing is visited under xUnit, then there is nothing to fix in your xUnit.vsix project.

**Comment by kzu** [comment]
The "remoteness" is on the local machine (from .net remoting), with the
same envvars, so wouldn't the CLR connect to the same registered profiler
started already by OpenCover?

**Comment by ddur** [comment]
Looks like it does not connects for instrumentation or for collecting visit events

https://msdn.microsoft.com/en-us/library/bb384493(v=vs.110).aspx
```
Unsupported Functionality
Remote profiling, which is not supported for the following reasons:

    Remote profiling extends execution time. When you use the profiling interfaces, you must minimize execution time so that profiling results will not be unduly affected. This is especially true when execution performance is being monitored. However, remote profiling is not a limitation when the profiling interfaces are used to monitor memory usage or to obtain run-time information about stack frames, objects, and so on.

    The CLR code profiler must register one or more callback interfaces with the runtime on the local computer on which the profiled application is running. This limits the ability to create a remote code profiler.
```
I guess CLR profiling API with .net remoting makes no difference if remote is on local computer or somewhere else.
https://msdn.microsoft.com/en-us/library/kwdt6w2k%28v=vs.71%29.ASPX
```
.NET remoting enables you to build widely distributed applications easily, whether application components are all on one computer or spread out across the entire world. You can build client applications that use objects in other processes on the same computer or on any other computer that is reachable over its network.
``` 
It looks like that this picture shows that profiling works only within same process
![Profiling Architecture](https://i-msdn.sec.s-msft.com/dynimg/IC13527.jpeg)

**Comment by ddur** [comment]
If you run CodeCover together with test-runner, "remotely" in single process, I think that will work.

**Comment by kzu** [comment]
Hm, so, launch OpenCover to launch VS instead of the xunit.vsix test
runner? Ok, will give that a try and report back

**Comment by ddur** [comment]
What I meant is: launch "remotely" OpenCover AND test-runner for each discovered test. 
Go step by step. First make at least something visited, add one "control" project to solution that is not vsix special case and that is always visited.

I guess, VS is launched as separated process and ```GlobalServices.GetService<SComponentModel, IComponentModel>().GetService<IMyService>() ``` returns IPC (Inter Process Communication) service.
If that is true, coverage of vsix-extension project on VS server side (behind interface) will be missing.
That will require to start OpenCover and VS as "runner" to cover vsix-extension server side.

However, I make mistakes.

**Comment by ddur** [comment]
I think, VS is not only .Net, there must be plenty of C++ code. Do not know what happens when OpenCover runs VS as "test-runner". I'm sure it will be slower :)

**Comment by kzu** [comment]
don't care much for slowness, since this is for acceptance tests suite.

I think this whole thing would vanish if OpenCover supported instrumented
entire assemblies in place like the MS coverage tool does :).

I think I'll push for that instead.

**Comment by sawilde** [comment]
> I think I'll push for that instead.

Push for what?

**Comment by UlyssesAlves** [comment]
Like [SebastianStehle said,](https://github.com/OpenCover/opencover/issues/544#issuecomment-183362748) you need to use xUnit's parameter -noshadow to solve the problem of zero coverage in OpenCover report.
