### ISSUE TITLE
Issue with -returntargetcode arg

### ISSUE THREAD

**Issue by koektudis** [OpenCover/opencover#369]
Hello,

In my continuous chain I've Jankins launching a batch that run OpenCover to retrieve code coverage.
OpenCover launch Nunit via a batch file : 
"C:\Program Files (x86)\OpenCover\OpenCover.Console.exe" -returntargetcode -target:"NUnit.bat" -targetargs:"%varExtraArgrs%" -output:"./OpenCoverResults.xml" -register -targetdir:".\bin" -coverbytest:*.dll 

The Nunit.bat launch Nunit, print %errrorlevel% and returns the result throw %errorlevel%.
(ex : echo ErrorLevel after calling Nunit is: %errorlevel%)

In my case I've 5 tests that failed. The Nunit.bat show me this result in the console, and print : 

ErrorLevel after calling Nunit is: 5

But when returning in the OpenCover.bat I've "ErrorLevel after calling OpenCover is: 0"

The problem is that Jenkins does not break the build because the result is 0.

In few words we have : Jenkins -> OpenCover.bat -> Nunit.bat

I try the -returntargetcode arg, but it does not work. How can I retreive the expected result ?

**Comment by sawilde** [comment]
please provide the batch files so we can replicate your issue and start the path to finding a solution for you.

**Comment by koektudis** [comment]
Hi,

Please find bat in attachment with .txt extension.

[OpenCover.txt](https://github.com/OpenCover/opencover/files/45512/OpenCover.txt)
[NUnit.txt](https://github.com/OpenCover/opencover/files/45511/NUnit.txt)

Thanks in advance,

**Comment by koektudis** [comment]
Hi Shawn,

Have you found something with thoses batchs files ? 
Do you have any clue ? 

Thanks in advance

**Comment by sawilde** [comment]
I believe the issue is in your NUnit.bat file 

Even though nunit is returning with an errorcode your batch file is returning is returning 0 which is what OpenCover is returning.

try adding 

    EXIT /B %errorlevel%

to the end of your batch file - https://technet.microsoft.com/en-au/library/bb490902.aspx
