### ISSUE TITLE
OpenCover is missing \build\Version\Version.cs files

### ISSUE THREAD

**Issue by leemorris** [OpenCover/opencover#371]
from the following projects.
OpenCover.MSBuild
OpenCover.Framework
OpenCover.Extensions
OpenCover.Console
OpenCover.Test

**Comment by sawilde** [comment]
build opencover from the command line and it should create them

**Comment by sawilde** [comment]
https://github.com/OpenCover/opencover/blob/master/build/version.build#L21

**Comment by dermotKirk** [comment]
Thanks for this!!

**Comment by JesusROviedo** [comment]
Hi,
I am trying to build opencover, but I find a error: "CS 2001 is missing ...\build\version\version.cs. I am building opencover from the command line with the command: msbuild ....\opencover.sln, Although the problem persists

**Comment by molnargab** [comment]
Are you running `Build.bat`? It should create the version file.

**Comment by JesusROviedo** [comment]
No, because I ran build.bat and the progam was closed by an error.
