### ISSUE TITLE
Microsoft Windows SDK for Windows 7 and .NET Framework

### ISSUE THREAD

**Issue by trivalik** [OpenCover/opencover#372]
In list of "Building", "What you need" in readme.md is missing:

Microsoft Windows SDK for Windows 7 and .NET Framework

This comes out if you run build.bat
```
NAnt 0.91 (Build 0.91.3881.0; alpha2; 17.08.2010)
Copyright (C) 2001-2010 Gerry Shaw
http://nant.sourceforge.net

Buildfile: file:///C:/Users/tester/Downloads/opencover-master/opencover-master/default.build
Target framework: Microsoft .NET Framework 4.0
Target(s) specified: rebuild


get-os-version:

     [echo] Microsoft Windows NT 6.1.7601 Service Pack 1 => 6.1.7601.65536

netfx.tools:


BUILD FAILED

Please install 'Microsoft Windows SDK for Windows 7 and .NET Framework'

Total time: 0.1 seconds.
```

Edit:

I found out that in default.build the path for this is specified to
netfx.tools.folder as ${program.files.x86}/Microsoft SDKs\Windows\v8.0A\Bin\NETFX 4.0 Tools

As you can see, there is Version 8.0a. So the error message is confusing!
Wikipedia means this version is it:
https://msdn.microsoft.com/en-US/windows/desktop/hh852363.aspx

**Comment by sawilde** [comment]
thanks

**Comment by trivalik** [comment]
Additional info, I was able to build all projects except all test project with Microsoft SDKs\Windows\v7.0A\Bin\NETFX 4.0.
Not sure whats causing not build the test project. Anyway, I didn't need to test.

But the main problem for me were the DLLs of gendarme.

I got:

```
1>------ Rebuild All started: Project: gendarmTest, Configuration: Debug Any CPU ------
1>c:\users\trivalik\documents\visual studio 2015\Projects\gendarmTest\gendarmTest\Program.cs(13,68,13,91): error CS0012: The type 'Rule' is defined in an assembly that is not referenced. You must add a reference to assembly 'Gendarme.Framework, Version=2.11.0.0, Culture=neutral, PublicKeyToken=b07ccf3a9f1ab3c9'.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```
I fixed this by recompile gendarme by my self (both files have now version 0.0.0.0). Also sign both files (with my own key) was not making the problem again. 
Any idea from your side? I checked the original gendarme and cecil DLLs with ILSpy, but versions are all ok.

To test this, I was creating a new C# project with reference on Gendarme.Framework.dll (2.11.0.0) and Gendarme.Rules.Maintainability.dll (2.11.0.0) and add code:
```C#
        public static void GetCyclomaticComplexityForToken(int token, ref int complexity)
        {
            Gendarme.Rules.Maintainability.AvoidComplexMethodsRule.GetCyclomaticComplexity(null);
        }
```
I attached a word document with the 2 DLLs inside :-)

[Doc1.docx](https://github.com/OpenCover/opencover/files/48375/Doc1.docx)

**Comment by sawilde** [comment]
Thanks. 

The issue with gendarme is probably local to you as I don't have the issue and nor does the build server, I will however keep it in mind in case the problem creeps.
