### ISSUE TITLE
portable PDB emitted by DNU on Linux being ignored

### ISSUE THREAD

**Issue by aggieben** [OpenCover/opencover#379]
I have set up some xUnit tests with an ASP.NET 5 (rc1) project, and I am successfully generating coverage reports using OpenCover on Windows.  I had to essentially treat the DNX application host like I might an IIS server; all the assemblies being profiled needed to be copied to a directory that I could then use as the parameter to `targetdir`.  I named this directory `targetbin\Debug\dnx451` and copied my assemblies to it.

I invoked opencover.exe like this: `opencover.console.exe -target:$(gcm dnx) -targetargs:"-p $(pwd) test" -targetdir:"$(pwd\targetbin\Debug\dnx451"`.

I have tried to to replicate this exact setup on Linux, using mono 4.2.1.  According to https://github.com/aspnet/dnx/pull/2609, DNU on linux will emit a portable PDB when `DNX_BUILD_PORTABLE_PDB` is used.  I used `dnu build` on Linux to create the pdbs and copied them to my `targetdir` as before.

The tests run fine, as expected, but no coverage report is created.  Here's the contents of report.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>
```

Here's the console output (top 2 lines are from my project, obvs):
```
=== TEST EXECUTION SUMMARY ===
   Cm.Core.Tests  Total: 76, Errors: 0, Failed: 0, Skipped: 0, Time: 1.726s
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
```

It appears that OpenCover ignores the PDBs, although I don't have a great way to figure out for sure what's going on.

P.S. - The `ColoredConsoleAppender` in the default `log4net.config` fails on mono.  Please see this issue: https://issues.apache.org/jira/browse/LOG4NET-453.  In order to get console output I had to change it to `ManagedColoredConsoleAppender` and comment out the color mappings.

**Comment by sawilde** [comment]
We use mono.cecil to read PDBs and I know we've had to upgrade to latest to handle some issues in changed PDB format. 

P.S. OpenCover only supports windows .net as mono does not have the same hooks when it comes to a profiler API especially when it comes rewriting a method with new IL.

**Comment by ddur** [comment]
Question is about running OpenCover under Linux OS.
Recent ASP.NET 5 (&.Net) is ported to Linux.
http://docs.asp.net/en/latest/getting-started/installing-on-linux.html
I doubt that profiler part of OpenCover, written in C++(Windows) will soon or ever work under Linux.
Maybe, if is possible to rewrite profiler in C#?
I'm not sure why this is still open?

**Comment by sawilde** [comment]
I agree
