### ISSUE TITLE
Process Filter Syntax

### ISSUE THREAD

**Issue by ddur** [OpenCover/opencover#395]
@sawilde 
"<>" characters are forbidden in file name but "[ ] { }" is not.
{something}[else] is perfectly legal file name.
Shall we change from {process} to ```<process>``` while this feature is still undocumented?

**Comment by sawilde** [comment]
Might as well - thanks.

**Comment by ddur** [comment]
@sawilde 
Term "Process" is for me a little bit confusing (with OS "Process"). 
Can you invent better term? 
Something that will describe root-assembly or root-assembly-call-tree or  ?

**Comment by sawilde** [comment]
It is the OS process, or as I understand it, we are using [GetModuleFileName](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683197(v=vs.85).aspx) to get this name.  I didn't want to use the name assembly as it is I didn't want to confuse it with .NET assemblies (it is possible that process is not .NET based). We also need to use a name that most people will understand 'process' was the closest name that works.

**Comment by ddur** [comment]
OK
