### ISSUE TITLE
Outputpath OpenCover.Extensions

### ISSUE THREAD

**Issue by trivalik** [OpenCover/opencover#401]
The outputpath of OpenCover.Extensions project has target bin\Release instead of ..\bin\Release
the same for the debug configuration.

**Comment by ddur** [comment]
https://github.com/OpenCover/opencover/wiki/Continuous-Integration

**Comment by sawilde** [comment]
It's actually dragged in by the tests so if you did modify it and compile it would not copy into the right location - I am going to change it
