### ISSUE TITLE
Coverage dropping

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#416]
@ddur, @molnargab - you may have noticed that coverage has dropped quite dramatically in the past month - it was in the 90+% (highest 94%) region but has now just hit 85%. Now I don't mind not testing code if it has no value but we seem to adding code without any supporting tests at all or we have a lot of unused code. I am going to start by removing unused code and then look at adding tests to valuable code.

**Comment by ddur** [comment]
Sequence points are equal by reference and by value only if both have same fileID.

**Comment by ddur** [comment]
In the search for uncovered "corner cases" I used https://github.com/ddur/DBCL
I found one case where same SequencePoint is tripled, and one copy was unvisited.
Also found at least one case (enumerator for KeyValuePair) where one or two last "}" sequence points are moved to generated "MoveNext" method and left unvisited.

**Comment by ddur** [comment]
Just found exceptional case with compiler generated branches in "in" keyword

**Comment by ddur** [comment]
Can we run OpenCover that runs OpenCover that runs tests over non trivial assembly? :)

**Comment by sawilde** [comment]
> Can we run OpenCover that runs OpenCover that runs tests over non trivial assembly? :)

sure - that's what the dogfood tests do so it would be simple to repeat the pattern

**Comment by ddur** [comment]
Not exactly, I imagined running another OpenCover in place of NUnit.Console.Runner, but I think I see what you mean:
We can run OpenCover with test that will cover another OpenCover, like dogfood, but only test will be to start running another test suite over third assembly :+1:  :)

**Comment by ddur** [comment]
In both cases, I do not know if two registered profilers will work or conflict.

**Comment by sawilde** [comment]
It shouldn't be an issue, each instance of OpenCover host uses a identifier/key to only talk to profilers it lanuched but this can be overridden by another OpenCover host further down the line - this is what pedigree.cmd does; [pedigree chum](http://www.pedigree.com.au/dog-food/) is a type of dogfood.

**Comment by ddur** [comment]
I have only cats now. :)
By the way, coverage dropped to 9% by last two builds.
Please visit https://github.com/OpenCover/opencover/issues/410

**Comment by sawilde** [comment]
> By the way, coverage dropped to 9% by last two builds.

yeah it seems to happen when it fails so we only get the coverage of the ui tests

**Comment by ddur** [comment]
Coverage is green again, almost 93%

**Comment by ddur** [comment]
Build 144 	master 	94.34%

**Comment by ddur** [comment]
![coverage 416](https://cloud.githubusercontent.com/assets/3501612/12217812/6987a91a-b70c-11e5-8bd8-8ab96e7f6369.png)

**Comment by sawilde** [comment]
Good work everyone
