### ISSUE TITLE
Coverity

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#417]
@ddur - I can't access the coverity report is it possible to make them public?

**Comment by ddur** [comment]
I do not know, it is set to be viewable by public.
Maybe I have to invite you? Then I need your email.
![coverity projectsettings](https://cloud.githubusercontent.com/assets/3501612/12183473/5a65762a-b58f-11e5-95b8-ec0a9aa23208.png)

**Comment by ddur** [comment]
![coverity mustwait](https://cloud.githubusercontent.com/assets/3501612/12183577/db5f9dbe-b58f-11e5-84b6-b7789067ad7b.png)

**Comment by sawilde** [comment]
I still can't see your project can you invite me `shaun_wilde(at)hotmail.com`? 

Also should we run this off the main opencover repo rather than your private one?

**Comment by sawilde** [comment]
I also wonder if we need two projects, one for C# and one for C++?

**Comment by sawilde** [comment]
Just noticed that coverity has a version of OpenCover inside it :smiley:

**Comment by sawilde** [comment]
I note my project is open to all https://scan.coverity.com/projects/opencover-opencover (I set this up a long time ago) so I am pushing to there for testing. Need to configure the appveyor specifics

**Comment by sawilde** [comment]
I think I am done here 

@ddur and @molnargab please invite yourself to the project and I'll make you mods (if you want)

**Comment by ddur** [comment]
>I still can't see your project can you invite me? 

You are invited

**Comment by ddur** [comment]
>Also should we run this off the main opencover repo rather than your private one?

Sure, that was only sample how to do it.

**Comment by ddur** [comment]
> I also wonder if we need two projects, one for C# and one for C++?

No, there is second language to set.

**Comment by ddur** [comment]
>Just noticed that coverity has a version of OpenCover inside it :smiley:

:smiley: :+1:

**Comment by ddur** [comment]
> @ddur and @molnargab please invite yourself to the project and I'll make you mods (if you want)

done

**Comment by sawilde** [comment]
> No, there is a secondary language to set.

I saw that after I submitted my first scan - though it has c++ as primary and c# secondary - I can live with that

**Comment by ddur** [comment]
>I saw that after I submitted my first scan - though it has c++ as primary and c# secondary - I can live with that

I did the same. So, you didn't saw my post [here](https://github.com/OpenCover/opencover/issues/242) on time :)

**Comment by sawilde** [comment]
looks like we are ready for another coverity build - I can trigger this from github

**Comment by ddur** [comment]
OK, I have one more, wait for second

**Comment by sawilde** [comment]
> OK, I have one more, wait for build

I cancelled the last on - it is very busy at the moment

let me know when done

**Comment by sawilde** [comment]
I've extended the script to allow a scheduled build to run coverity build and configured the appveyor portal to run it at 18:00 Mon and Thu I hope I have the cron syntax right for that, I assume it will be UTC time but time will tell; no pun intended.

**Comment by sawilde** [comment]
Now if only I understood the summary project page as the different panels seem out of sink.

**Comment by ddur** [comment]
>I've extended the script

:+1: 

>Now if only I understood the summary project page as the different panels seem out of sink.

I don't understand what you want to say. Which panels? Out of sink?

All about Coverity is delayed. Current status:
>Last Build Status: In-queue. Your build is in the queue to be analyzed. There are 74 builds ahead of it.

**Comment by sawilde** [comment]
> Which panels? Out of sink?

The panels seemed out of sync of the defect report when I viewed them. I now think it may be due to when I cancelled a build and pushed another for analysis

**Comment by sawilde** [comment]
> I've extended the script to allow a scheduled build

the scheduled build ran but failed to upload as the other scan was in progress but at least now we will have a automatic build i.e. I assume this will help us catch any new issues they add detectors for.

**Comment by ddur** [comment]
:+1: Closed?

**Comment by sawilde** [comment]
one more merge to coverity branch to push the last few defects through then we should be at 0 - great work everyone @ddur, @molnargab.

**Comment by sawilde** [comment]
Note to self - don't run coverity during the week... 

*Last Build Status: In-queue. Your build is in the queue to be analyzed. There are 98 builds ahead of it.*

and that is from a build we pushed 9 hours ago (it started at 177)

https://ci.appveyor.com/project/sawilde/opencover/build/4.6.370

**Comment by ddur** [comment]
```
 Due to high levels of activity, the number of weekly builds per project are as follows:

    Up to 12 builds per week, with a maximum of 3 builds per day, for projects with fewer than 100K lines of code
    Up to   8 builds per week, with a maximum of 2 builds per day, for projects with 100K to 500K lines of code
    Up to   4 builds per week, with a maximum of 1 build per day, for projects with 500K to 1 million lines of code
    Up to   2 builds per week, with a maximum of 1 build per day, for projects with more than 1 million lines of code

Once a project reaches the maximum builds per week, additional build requests will be rejected. You will be able to re-submit the build request the following week.
```

**Comment by sawilde** [comment]
Well it's taking about 24 hours to do a scan at the moment - I suppose OS projects are bumped for commercial ones so not surprised.

**Comment by ddur** [comment]
Referenced wrong issue. Coverity, Codecov, Coverals ..... :)

**Comment by sawilde** [comment]
![image](https://cloud.githubusercontent.com/assets/297165/12338238/d6fd5e18-bb62-11e5-8a3d-71dc264e84cd.png)

Yeah we are 0  `coverity` defects

Thanks to @ddur, @molnargab and @SteveGilham 

I've moved the schedule to `0 23 * * Sun` which is late enough to cover any weekend work - we still have the coverity branch for any fast tracking of any serious defects found and fixed.
