### ISSUE TITLE
Coverage, AppVeyor, Test: not AdminOnly ?

### ISSUE THREAD

**Issue by ddur** [OpenCover/opencover#449]
@sawilde 
Will ```AdminOnly``` test fail on AppVeyor build?

**Comment by sawilde** [comment]
I am not sure what permissions the build agent has - we can always try it!

**Comment by ddur** [comment]
I will try it.

**Comment by ddur** [comment]
It works. 
AppVeyor environment must be checked.
I'm not familiar with Nant and I do not want to be familiar with it.
There are 14 *.cmd files with ```/exclude:AdminOnly```, not sure what to do with it.
I will cancel my temporary test changes.
