### ISSUE TITLE
DrDump

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#455]
Hi @ddur and @molnargab 

I've added you both to the drdump account (if you don't wish this then let me know). The drdump is where all the 'crashes' are sent and accumulated.

https://drdump.com/AppVersion.aspx?AppVersionID=1669
 
Shaun

**Comment by ddur** [comment]
OK. BTW, I can login as guest.

**Comment by sawilde** [comment]
> OK. BTW, I can login as guest.

The site said it sent you an invite (spam folder perhaps - I used the same email as seen in coverity)

**Comment by ddur** [comment]
I received invite.

**Comment by sawilde** [comment]
It's a bit chaotic in there with a few duplicates so I am being quite harsh on the RC code that generated defects if I think it has since been addressed by our recent development work.

**Comment by sawilde** [comment]
I have tinkered in drdump and disabled (removed from support) the catchall [Release Candidate](https://drdump.com/AppVersion.aspx?AppVersionID=1669) and added two new entries.

[OpenCover 4.6.401.*](https://drdump.com/AppVersion.aspx?AppVersionID=2088) - for the latest release candidate, and,
[Developer Build 4.6](https://drdump.com/AppVersion.aspx?AppVersionID=2078) - to consume any reports generated by our development efforts.

I am not sure if DrDump has an API that will allow us to create entries during the rc/release builds but for now it will have to be manual.
