### ISSUE TITLE
OpenCover process never end

### ISSUE THREAD

**Issue by desoindx** [OpenCover/opencover#460]
Hello,

i'm using OpenCover version 4.5.3522 in combination with JustMock and MSTest :
OpenCover.Console.exe -target:"D:\Program Files (x86)\Telerik\JustMock\Libraries\JustMockRunner.exe" -targetargs:"\"D:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\mstest.exe\" /testcontainer:\"Test.dll\" /category:\"ExecAutomated\" /testsettings:Local.testsettings /resultsfile:\"TestResult\Test.trx" -output:CodeCoverage\Test.xml"

and often (2 out of 3 times) the process never ends. The task manager shows that the process use a lot of CPU and the log shows that the test are over and the trx file is correctly created but not the code coverage one.

Summary
-------
Test Run Completed.
  Passed  328
  -----------
  Total   328
Results file:  D:\Sonar\Sonar\TestResult\Test.trx
Test Settings: Local

I tried to attach a debugger to the OpenCover.exe and it seems that the process is stuck in the ProcessManager.RunProcess method.

This is the only test dll that cause an issue. The only difference that i see is that those tests takes a long time to run (approximately 3 hours).

Could you please help me ?

Thanks a lot.
Regards

**Comment by sawilde** [comment]
Please use the latest release of OpenCover as 4.5.3522 is over a year old

try [4.6.166](https://www.nuget.org/packages/OpenCover/4.6.166) (latest supported nuget) or the latest release from appveyor [4.6.382](https://ci.appveyor.com/project/sawilde/opencover/build/4.6.382)

**Comment by desoindx** [comment]
i just installed the 4.6.382 version and will run some test. As i said the test takes a long time to run and the problem does not happen all the time so i might take some time. I will post an update as soon as possible.

Thanks for your quick answer.

**Comment by sawilde** [comment]
let us know how you go - if we don't hear from you we will close the issue as resolved

**Comment by desoindx** [comment]
All of the run finished succesfully yesterday so it's already better.
You can close the task and i'll reopen if needed.

Thanks for your help,
Regards.
