### ISSUE TITLE
Integrate SonarQube as part of the OpenCover build pipeline

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#481]
https://github.com/OpenCover/opencover/issues/242#issuecomment-169134931

By using SonarQube alongside Coverity we can only make the code better.

*Questions*
As there a SaaS for this? 
Is it free?

**Comment by ddur** [comment]
There is a [free service announcement](http://www.sonarqube.org/nemo-public-demo-of-sonar/)
Link in above announcement is obsolete 
[Free SonarQube service for Open Source - Nemo](http://nemo.sonarqube.org/)
Software is free, released under GPL license.

**Comment by ddur** [comment]
http://www.sonarqube.org/easy-analysis-of-visual-studio-solutions-with-the-sonarqube-scanner-for-msbuild/

**Comment by ddur** [comment]
http://blogs.msdn.com/b/visualstudioalm/archive/2015/09/29/quickstart-analyzing-net-projects-with-sonarqube-msbuild-or-visual-studio-online-and-third-party-analyzers-stylecop-resharper.aspx

**Comment by ddur** [comment]
Cannot find sign-up. Service is free but not freely available? :)

**Comment by sawilde** [comment]
Raised issue on forum - https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/sonarqube/DPeFf1RoVis

**Comment by sawilde** [comment]
It appears that SonarQube cannot build windows projects but are in the process of allowing "self-service" but dates not finalized. Will need to review at a later date.

Task: Review [SonarQube](http://www.sonarqube.org/) and [Nemo](http://nemo.sonarqube.org/) for self-service functionality and act accordingly.

**Comment by sawilde** [comment]
Installation Steps:
- download and unpack sonarqube-5.3
- download and unpack sonar-csharp-plugin-4.4.jar and place in extensions
- download and unpack MSBuild.SonarQube.Runner-1.1.zip

* you may need to 'unblock' the zip files before extraction

to run 
- run sonarqube-5.3\bin\windows-x86-32\startsonar,bat
- open Visual Studio Developer Prompt 2013
- \Projects\sonarqube-runner\MSBuild.SonarQube.Runner.exe begin /k:"opencover" /n:"opencover" /v:"0.0.0.1"
- msbuild main\OpenCover.sln /t:rebuild
- \Projects\sonarqube-runner\MSBuild.SonarQube.Runner.exe end

view results
- access site http://localhost:9000 using admin/admin

not only have c# analysis so far - can't find c++ plugin (licence?)

**Comment by sawilde** [comment]
![image](https://cloud.githubusercontent.com/assets/297165/12417296/2f4b7dc0-befb-11e5-9fa1-b2af430af9cd.png)

Some interesting thoughts to improve on code - I just need a place to push results to for shared access and review.

**Comment by sawilde** [comment]
![image](https://cloud.githubusercontent.com/assets/297165/12417867/452d8026-beff-11e5-8626-698551b9e8e6.png)

All of the criticals are OWASP related and the Console.WriteLine statements - will try to remove/ignore these

**Comment by sawilde** [comment]
@SteveGilham does this data look like your results? Did you manage to get the c++ plug-in working?

**Comment by ddur** [comment]
https://github.com/SonarOpenCommunity/sonar-cxx

**Comment by ddur** [comment]
info http://baptiste-wicht.com/posts/2014/10/sonarqube-inspections-for-cpp-projects.html

**Comment by SteveGilham** [comment]
The results look to be in the same ballpark

![sonarqube](https://cloud.githubusercontent.com/assets/7460854/12431139/9d2f2644-beeb-11e5-9962-804ae82d444d.png)

This was just using the built-in C# rules plugin in default mode; I just saw the standard C/C++ ruleset was commercially licensed and went no further.  This was all done in the rather dead time in the office on Christmas Eve, and I've not had chance to do any more with the framework and what it can do apart from inspect C# code since.

**Comment by sawilde** [comment]
@ddur - yes I cam across that project as well (it was where I saw the issuestats badges that I added to our readme) I might pull it in to my setup and see if it works locally.

@SteveGilham you version of sonarqube looks different to mine - I have a lot more minor issues; usually to do with code should be put on multiple lines.

I am going to look into hosting this somewhere - hopefully free.

**Comment by sawilde** [comment]
It'll probably have to be on ubuntu somewhere (I doubt I'd get free) - this guide may help if we find a hosting provider.

http://dev.mamikon.net/installing-sonarqube-on-ubuntu/

**Comment by sawilde** [comment]
I have a server up and running 

http://sonar.many-monkeys.com:9000/

I've hosted it in Azure as I have some free MSDN minutes and I might as well use them.

**Comment by sawilde** [comment]
It's now part of the build - just push to the sonar branch

Will fix/comment on some issues and do regular pushes to sonar and then I may add it to the scheduled build we use for coverity.

**Comment by sawilde** [comment]
Oh and @ddur, @molnargab , @SteveGilham you can sign up and I can add you to the appropriate groups if you wish.

**Comment by sawilde** [comment]
@ddur most of the remaining sonar issues are CyclomaticComplexity level around a lot of the work you have been doing recently with branch points so I left them :)

**Comment by ddur** [comment]
OK. I have many null checks duplicated.

**Comment by ddur** [comment]
I see only login. Where do I signup?

**Comment by sawilde** [comment]
> I see only login. Where do I signup?

there should be a signup on the login screen

once registered I'll set you up with admin privs

**Comment by sawilde** [comment]
damn server keeps crashing - will have to look into this later

**Comment by sawilde** [comment]
it doesn't break the build (thankfully) becuse of where I placed it int the pipeline but it is annoying

**Comment by ddur** [comment]
>there should be a signup on the login screen

Where?
![sonarcubesignup](https://cloud.githubusercontent.com/assets/3501612/12571816/4aed9b78-c3e5-11e5-89a7-961f139dcfff.png)

**Comment by sawilde** [comment]
I had to switch a flag

![image](https://cloud.githubusercontent.com/assets/297165/12577798/f4215a14-c470-11e5-9256-b0e591bba175.png)

assuming the server doesn't go bang you should see a sign up link on the login page

**Comment by ddur** [comment]
I'm signed up, please authorize me.

**Comment by sawilde** [comment]
#ddur - done

**Comment by sawilde** [comment]
The community sonar-cxx is failing to parse the files - I have raised an issue with the project

https://github.com/SonarOpenCommunity/sonar-cxx/issues/769

**Comment by sawilde** [comment]
done
