### ISSUE TITLE
Problem 182391: OpenCover.Framework.Communication.CommunicationManager.HandleMemoryBlock

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#482]
https://drdump.com/Problem.aspx?ProblemID=182391

````
System.OverflowException
 at OpenCover.Framework.Communication.CommunicationManager.HandleMemoryBlock(IManagedMemoryBlock mmb) in CommunicationManager.cs:90
 at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass31.<ProcessBlock>b__2f(Object state) in ProfilerManager.cs:325
 at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()
 at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
````

**Comment by ddur** [comment]
Maybe is here?
```
} while (mmb.StreamAccessorResults.Read(mmb.Buffer, 0, mmb.BufferSize) != mmb.BufferSize);
```
Should be ```<``` or ```<=```?
```
} while (mmb.StreamAccessorResults.Read(mmb.Buffer, 0, mmb.BufferSize) <= mmb.BufferSize);
```
If first uint contains number larger than ```mmb.BufferSize```
then ```Buffer.BlockCopy(mmb.Buffer, 0, newData, 0, dataSize);``` will throw ```System.OverflowException```

**Comment by ddur** [comment]
```
            do
            {
                mmb.StreamAccessorResults.Seek(0, SeekOrigin.Begin);
            } while (mmb.StreamAccessorResults.Read(mmb.Buffer, 0, mmb.BufferSize) != mmb.BufferSize);
```
What if sent/received data block is shorter or longer than ```mmb.BufferSize```?
Will it loop forever if shorter, or throw exception if it is longer?

**Comment by ddur** [comment]
I don't know if it has anything to do with this issue, but some message sizes are recently changed here
https://github.com/sawilde/opencover/commit/ed114a11acc5ffb0d26cae88df620d57614a2e67

**Comment by sawilde** [comment]
> What if sent/received data block is shorter or longer than

it's a memory mapped buffer it is always the same size; it is not sent/received as it it never moves, but we do need to make sure who is reading/writing, hence the events etc

> but some message sizes are recently changed here

no that was coverity complaining about clearing more that the size of a `MSG_Union` object but I created a memory buffer larger than that i.e. 64K

**Comment by ddur** [comment]
>it's a memory mapped buffer it is always the same size; it is not sent/received as it it never moves, but we do need to make sure who is reading/writing, hence the events etc

OK, buffer is same size, but is the message of same size? Message size is in first 4 bytes of buffer.

**Comment by ddur** [comment]
```
		[SecuritySafeCritical]
		public unsafe override int Read([In] [Out] byte[] buffer, int offset, int count)
		{
			if (buffer == null) {
				throw new ArgumentNullException("buffer", Environment.GetResourceString("ArgumentNull_Buffer"));
			}
			if (offset < 0) {
				throw new ArgumentOutOfRangeException("offset", Environment.GetResourceString("ArgumentOutOfRange_NeedNonNegNum"));
			}
			if (count < 0) {
				throw new ArgumentOutOfRangeException("count", Environment.GetResourceString("ArgumentOutOfRange_NeedNonNegNum"));
			}
			if (buffer.Length - offset < count) {
				throw new ArgumentException(Environment.GetResourceString("Argument_InvalidOffLen"));
			}
			if (!this._isOpen) {
				__Error.StreamIsClosed();
			}
			if (!this.CanRead) {
				__Error.ReadNotSupported();
			}
			long num = Interlocked.Read(ref this._position);
			long num2 = Interlocked.Read(ref this._length) - num;
											------------
			if (num2 > (long)count) {
				num2 = (long)count;
			}
```
There is another length of "message"

**Comment by ddur** [comment]
Maybe I do not understand, this looks unusual to me because in other code I saw (and wrote), message is of unknown size, it is transferred in blocks via buffer, so message can be shorter or longer than buffer.

**Comment by ddur** [comment]
if "message" is always same, why do you calculate dataSize here?
```
            var nCount = (int)BitConverter.ToUInt32(mmb.Buffer, 0);
            var dataSize = (nCount + 1)*sizeof (UInt32);
            var newData = new byte[dataSize];
            Buffer.BlockCopy(mmb.Buffer, 0, newData, 0, dataSize);
```
If dataSize can be shorter than buffer, maybe it can be longer to?

**Comment by ddur** [comment]
Exception is allegedly thrown on line 90
```90: var newData = new byte[dataSize];```
```int dataSize``` is successfully casted from ```uint```, it cannot be negative.
Must be next line or later throwing exception.

```91: Buffer.BlockCopy(mmb.Buffer, 0, newData, 0, dataSize);``` 
```newData.Length == dataSize```, so ```Buffer.BlockCopy``` will throw only if ```dataSize``` is larger than ```mmb.Buffer.Length```?

**Comment by sawilde** [comment]
> "Message" size is in first 4 bytes of buffer.

no, it is the number of valid visit points populated in the buffer

>  it is transferred in blocks via short fixed size buffer, so message can be shorter or longer than buffer.

that is the communication buffer, this is the visit points buffer it has different behaviour - it is only written to by the profiler and read by the host.

> if "message" is always same, why do you calculate dataSize here?

The buffer is reused over and over, and for performance reasons it is not cleared after reading but only updated. So there could be stale data in the other elements, hence we only allocate a buffer block required to store the valid populated data for that transfer. 

> If dataSize can be shorter than buffer, maybe it can be longer too?

The data is only sent when 
- the buffer reaches 64000 elements (see ProfilerCommunication::AddVisitPointToThreadBuffer)
- the process is shutting down

You need to look at the profiler side of the communication channel.

These are the sizes of the buffer and the structures they contain
- Buffer 65536
- Union 64008
- Visit 64004

I used a 64K buffer as it was the nearest multiple of 4K - I had tinkered with many buffer sizes and found this size to be optimal for most purposes.  

> Buffer.BlockCopy(mmb.Buffer, 0, newData, 0, dataSize);

throws other exceptions - https://drdump.com/Problem.aspx?ProblemID=182870 and are correctly recorded.

There is obviously something odd happening but it will be only identified by looking at both sides of the communication channel and not the side affected. Timeout perhaps?

**Comment by sawilde** [comment]
made a small change to set the count in the buffer is set to 0 on all paths

**Comment by sawilde** [comment]
will need another rc build to see if the issue goes away
