### ISSUE TITLE
Update usage for powershell

### ISSUE THREAD

**Issue by TimMurphy** [OpenCover/opencover#49]
The way to handle arguments with spaces in PowerShell is different from DOS. 

In DOS either of the following **-targetargs:"arg1 arg2"** or **"-targetargs:arg1 arg2"** is valid.

However in  PowerShell only  **"-targetargs:arg1 arg2"** is valid. 

https://github.com/sawilde/opencover/wiki/Usage has been updated accordingly. CommandLineParser.Usage needs updating.

As there is one format that works in DOS and PowerShell I recommend that only that method appears in the wiki and CommandLineParser.Usage.

I'm happy to be assigned this issue.

**Comment by jmbeach** [comment]
I still can't get this format to work in powershell. I am trying to run `dotnet test test-project-path`. I have tried many different combinations of quotes, but I can't get anything to work. It works if I run `dotnet test test-project` outside of opencover to be clear.

Running:

```
.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe" "-targetargs:test test-project"
```

Returns:

```
Executing: C:\Program Files\dotnet\dotnet.exe
Couldn't find a project to run test from. Ensure a project exists in D:\Code\GitHub\<my-project-path>.
Or pass the path to the project
```
