### ISSUE TITLE
Q1 Release

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#497]
Okay we have [4.6.434](https://www.nuget.org/packages/OpenCover/4.6.434-rc) as a release candidate and a number of downloads happening.

If we get no significant reports of issues affecting a large number of users then I think we should consider a release this weekend.

Thoughts?

**Comment by ddur** [comment]
Looks good so far. :+1:

**Comment by sawilde** [comment]
I feel like I need a 'n' days before the last work place incident type counter!

![image](https://cloud.githubusercontent.com/assets/297165/12462296/97e5d09e-c011-11e5-89ca-05ef70c8d5d7.png)

**Comment by sawilde** [comment]
![image](https://cloud.githubusercontent.com/assets/297165/12526441/8f1d13a8-c1c1-11e5-8575-1d52bba3ced5.png)

**Comment by ddur** [comment]
:smiley: 
It is only one. 
![137181-throwout-brearing-highlander 1](https://cloud.githubusercontent.com/assets/3501612/12527411/97a46414-c17a-11e5-94a0-85e826e55e8e.jpg)

**Comment by ddur** [comment]
We have more than two months before Q1 expires. 
Coverity can't find more bugs, we cant find more bugs, 
so, let's have release Q1-1 Q1-2 Q1-3?
Only release will reach wide usage. ;)

Have you been bored before Crash-Reporter and Doctor-Dump?
That must have been like stone-age, or like pre-mobile age. Blessed ignorance.
I do not know how could I leave the home and return without android mobile. :D

**Comment by ddur** [comment]
http://faculty.salisbury.edu/~xswang/Research/Papers/SERelated/no-silver-bullet.pdf
https://vimeo.com/133325995

**Comment by sawilde** [comment]
I agree - if we think we have this last one nailed then I say another RC perhaps and then a release?

I am not sure how your fix for the last one fixes the crash presented as the location of the crash and the fix submitted seem so disconnected.

**Comment by ddur** [comment]
>I am not sure how your fix for the last one fixes the crash presented as the location of the crash and the fix submitted seem so disconnected.

Two methods that begin with exact same line are called before failing method.
```
                if (methods.Any()) {
                    var sourceRepository = new SourceRepository(); // module sources
                    // keep transformations in this order!
                    TransformSequences_Initialize (methods);
                    TransformSequences_JoinWithBranches (methods);
                    TransformSequences_AddSources (module.Files, methods, sourceRepository);
                    TransformSequences_RemoveCompilerGeneratedBranches  (methods, sourceRepository);
```
```
        static void TransformSequences_Initialize (IEnumerable<Method> methods)
        {
            foreach (var method in methods) {
```
```
        private static void TransformSequences_JoinWithBranches (IEnumerable<Method> methods)
        {
            foreach (var method in methods) {
```
```
        private static void TransformSequences_RemoveCompilerGeneratedBranches (IEnumerable<Method> methods, SourceRepository sourceRepository)
        {
            foreach (var method in methods) { // Line 637
```
It cannot be line 637
Line fixed is only point of failure I could find so far. Same exception can be thrown at that line.
Did Coverity found anything?

**Comment by ddur** [comment]
Can we have a false doctor dump for each start? Release candidate only.
Number of downloads does not reflect real usage.
Number of runs compared with number of crashes will help us to determine bug severity.

**Comment by ddur** [comment]
@sawilde #498

**Comment by sawilde** [comment]
> Did Coverity found anything?

Its due to run in the next 24 hours (23:00 UTC on a Sunday)

> Can we have a false doctor dump for each start?

I'd rather not.

> Number of runs compared with number of crashes will help us to determine bug severity.

perhaps not but since even with a small number of downloads somebody found it easy to crash OpenCover at that point it seems important, as this is new code we should try to address it before release.

> @sawilde #498

it looks like you found the issue and have a fix after all?

**Comment by ddur** [comment]
>it looks like you found the issue and have a fix after all?
Fix was immediately done OK. I recreated crash to have fix confirmation.

Last pull request is adding extra message for the user testing coverage changes without recompile. In other words, user is changing file between compile and coverage test. 

Message is based on empty sequence point. It would be better if I had time-stamp of module file to compare with source file time-stamp.

**Comment by sawilde** [comment]
> Message is based on empty sequence point. It would be better if I had time-stamp of module file to compare with source file time-stamp.

There is created/modified/accessed on .EXE/.DLL but it isn't perfect, on my machine I can find assemblies that have created dates later than the modified dates; this is a known issue on windows machines.

**Comment by ddur** [comment]
I will double check, on modified time and on empty SequencePoint. 
File copy changes creation time but preserves modified time, at least on my PC.

**Comment by sawilde** [comment]
> File copy changes creation time but preserves modified time, at least on my PC.

yup - I see same behaviour - I do remember reading a post about why but I forget the reasons now.

**Comment by sawilde** [comment]
Okay we now have safe mode and will produce a new release candidate on an acceptable coverity report later today

**Comment by sawilde** [comment]
We have published the release at https://www.nuget.org/packages/OpenCover/4.6.519 and https://github.com/OpenCover/opencover/releases/tag/4.6.519
