### ISSUE TITLE
Problem 184061: OpenCover.Framework.Persistance.BasePersistance.TransformSequences_RemoveCompilerGeneratedBranches

### ISSUE THREAD

**Issue by ddur** [OpenCover/opencover#498]
https://drdump.com/Problem.aspx?ProblemID=184061

Reported line makes no sense.

**Comment by ddur** [comment]
SequencePoint source/text can be empty if source file is changed between compilation and OpenCover coverage test. 

Debug symbols file (*.pdb) stores position of SequencePoints within source file. Therefore, changed or missing source file will have impact on removing compiler-generated-branches.

**Comment by ddur** [comment]
#497

**Comment by sawilde** [comment]
It could be the app has been optimized and some functions inlined (this is why OpenCover disables that for any process that it launches).

We could add a `.ini` file to help that https://msdn.microsoft.com/en-us/library/9dd8z24x(v=vs.110).aspx

````
[.NET Framework Debugging Control] 
GenerateTrackingInfo=1 
AllowOptimize=0
````

**Comment by ddur** [comment]
@sawilde 
https://drdump.com/DumpGroup.aspx?DumpGroupID=452943
One user 5 times, and two others once.

Can we get more info from .pdb about source file? Time-stamp or size?
If yes, we can warn user that file is changed after .pdb is created (after compilation).

**Comment by ddur** [comment]
If I'm right, this should be reproducible at 4.6.434-rc by 
1) compile
2) clear one source file to empty
3) run coverage test

**Comment by ddur** [comment]
In .pdb I see only source file names.
Can we have module file time-stamp?

**Comment by ddur** [comment]
Reproduced by adding one line at the top of source file
![issue498](https://cloud.githubusercontent.com/assets/3501612/12531128/a9f2e4aa-c1f3-11e5-9048-03e48a85c3bc.png)

**Comment by ddur** [comment]
Working on last modification time

**Comment by ddur** [comment]
#497
