### ISSUE TITLE
OpenCover now launches as a 32 bit process

### ISSUE THREAD

**Issue by lanfeust69** [OpenCover/opencover#500]
Following PR #430 (I think), OpenCover.Console.exe is now generated with the 32BITPREF CLR flag set to 1. This means that it will normally run as a 32 bit process, which is likely to fail with an OutOfMemoryException for any "big" run.

**Comment by sawilde** [comment]
It's possible not something I can check right now but sometimes the tolling does change the odd defaults.

You can use CorFlags.exe to switch it off and I'll look into the setting and either using that tool in the build to test the flag is set correctly before we package.
