### ISSUE TITLE
Add excludedpath(s) option to exclude processes/assemblies in named folders

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#521]
Rather than add path support to filters (making it overly complex) we should instead remove the path support from filters (introduced to support Smocks #364) which had a knock on affect and introduced defect #512, now resolved by reverting part (but not all) of the change for Smocks.

Tasks: 
- remove path support from filters (reverting)
- add new arg `-excludedpaths:path[;path][;path]` (same syntax as `-searchdirs`)
- integrate excludedpaths into ProfilerCommunication::TrackAssembly using the supplied modulePath to check against (startswith?)
- we should also add and use a new skip reason (ExcludedFolder?) and ensure it is processed in BasePersistence::ProcessSkippedAction (similar to MissingPdb behaviour)
- update docs

**Comment by ddur** [comment]
Removing path-matching is high priority but issue #364 is medium and Smocks framework is experimental and in alpha status. I think that new feature can wait after Q1 release.
