### ISSUE TITLE
Spike: Implement data transfer before profiler shutdown

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#528]
Occasionally (and unpredictably) the runtime shutsdown the profiler without calling `::Shutdown` leading to a loss of data in the thread based buffers. 

Investigate a way of transferring data during other events that we might receive before ::Shutdown that we can use to transfer data earlier and mitigate the issue. 

First we need to create a scenario that repeats the issue to reliably test against.

**Comment by sawilde** [comment]
Alternatively we could implement `-safemode` which only uses shared memory buffers and so is not subject to data loss but may have poor performance depending on the make-up of the tests - caveat emptor.

**Comment by molnargab** [comment]
The [atexit function](http://www.cplusplus.com/reference/cstdlib/atexit/) may also be worth to check (hopefully the runtime lets the profiler finish). Though I also found some [caveats](https://www.ibm.com/developerworks/community/blogs/5894415f-be62-4bc0-81c5-3956e82276f3/entry/be_careful_when_using_the_atexit_routine_with_static_objects?lang=en).

**Comment by Fortnox** [comment]
("Jansky" from StackOverflow here.)  One thing that confuses me is that we weren't (unless we hadn't noticed, it only occurs occasionally) having these problems before updating. Having read through the release notes though I can't see anything that appears relevant to me, can you think of any changes that might have caused this?

As for recreating a scenario, the build machines have 2 cores and the problems always seem to surround asynchronous code. We tend to use Moq in our tests. Not sure how to recreate it as it happens unpredictably. I can catch it the next time it happens and gather some more information

**Comment by sawilde** [comment]
> Having read through the release notes though I can't see anything that appears relevant to me, can you think of any changes that might have caused this?

From where did you update from?

**Comment by sawilde** [comment]
@molnargab - interesting not sure if that applies to .NET exes (worth looking into). 

I was more thinking about any app-domain unload events etc that the profiler may see that we could react to. Another alternative is to look at specific test execution processes and hook into the `TestFixture` complete events or equivalent.

**Comment by Fortnox** [comment]
@sawilde I think it was version 4.5.1313.6. I say "I think" because the copy in our repo didn't have any mention of the version number and the executable didn't have the --version command added later. But it occurred to me just now to check the metadata on the executable which, in the old executable, lists "File version" as "4.5.1313.6"

**Comment by sawilde** [comment]
@Fortnox - that's over 2 years oldm - a lot has changed (but obviously no always for the better).

The approach may need to be both an alternative way of triggering the buffer dump and perhaps a `-safemode`

**Comment by sawilde** [comment]
I've gone for safe mode option; we use the the same 'mode' when we have track by test on.

**Comment by Fortnox** [comment]
Hey Shaun just to say, the problem doesn't appear to have recurred since we deployed the fix last Wednesday. Thanks for all your help we really appreciate it.

**Comment by sawilde** [comment]
We have published the release at https://www.nuget.org/packages/OpenCover/4.6.519 and https://github.com/OpenCover/opencover/releases/tag/4.6.519
