### ISSUE TITLE
Fixed statement branch coverage

### ISSUE THREAD

**Issue by hughbe** [OpenCover/opencover#529]
The following code

```
unsafe 
{
    fixed (char* sourcePtr = aStringValue) // 1/2 branch coverage *here*
    {
        DoSomething();
     }
}
```

reports 1/2 branch coverage. Is this a bug with OpenCover, or do I need to test this code differently?

Thanks!

**Comment by molnargab** [comment]
There's a branch in the generated IL code, to check if `aStringValue` is null. If it can be null in your code, then you'll need to have a test for that (for 100% branch coverage).

Though, I just simply replaced it with an empty string, and had the branch generated...

OpenCover already ignores some IL branches, though I'm not sure this can be something we ignore; if `aStringValue` would be a parameter, I'd wanted to be notified if I missed to test the null case.

**Comment by ddur** [comment]
```fixed``` is not branch statement like ```if```. 
If sequence point with generated IL branch begins at keyword ```fixed```, branch can be removed.

**Comment by ddur** [comment]
If ```aStringValue``` is checked for null value before assignment, ```fixed``` never gets null value and that branch will never be covered.

**Comment by hughbe** [comment]
8s there a way that OpenCover can detect this?

**Comment by hughbe** [comment]
...and report full coverage

**Comment by ddur** [comment]
Maybe.

**Comment by sawilde** [comment]
as @molngab suggested, you could write another test to test the other part of the branch.

The risk with getting OpenCover to ignore it is that what happens if the `aStringValue` is null i.e. the scenario you have not tested for; and remember you situation may not be everyone else's situation.

**Comment by ddur** [comment]
If I remember good, it is similar to (```foreach```) ```in``` created branch where IEnumerable is checked for null and exception thrown. If null is checked, that branch will never be covered. Keyword ```in``` is not branch keyword. IMHO, it is programmers job to prevent that exception.

**Comment by ddur** [comment]
If null is checked before ```fixed```, test will never cover that branch, but it will cover null check branch.

**Comment by sawilde** [comment]
I agree we need to be careful of removing branches and showing complete coverage when doing so may lead to the user becoming overconfident in the completeness of their testing. If the user can write a test that exercises that path then they should do so, as they need to know they can handle that scenario, and if of course in `their` scenario it cannot happen because other code already deals with the check then they can dismiss it as a false positive. 

I am always wary of the 100% code/branch rule as it leads to overconfidence and event well tested code can have defects. The best thing about well tested code IMO is that you can refactor that code knowing that you haven't broken any existing test what you can't do is know if any refactoring brings in new bugs; but this si why coding is so interesting :).

**Comment by ddur** [comment]
We can warn users that OpenCover does not cover missing code that should be written :)

**Comment by ddur** [comment]
Afaik, this branch is last known compiler generated branch that is not removed.
That branch becomes not coverable after null check is properly implemented in code.

```fixed``` keyword is language construct, like ```await```, in my opinion it does not differ from any system (mscorlib) library omitted by default filter. Almost every Net system method has branches that can throw an exception, and yet we do not see them. Every method call on null instance object reference has null reference check branch, and yet, we do not show that branch uncovered.

Shall we document semantic of that branch or let and expect from user to decompile IL code to find out meaning of that branch and why is uncovered? Or we wait until someone from MS OS projects team complain about, like in ```await``` issue #352?

I think that decision can be easy resolved by simple principle/question:
Did user created that branch in code or someone else (MS/Mono compiler writer)?

**Comment by ddur** [comment]
After all, removal of not-by-user-created-branches can be made optional.

**Comment by ddur** [comment]
How do we know what is "user" code and what is not?
User is in possession of (*.pdb debug) source code.

**Comment by sawilde** [comment]
@ddur are you in a position to resolve this based o your previous experience in this area?

**Comment by ddur** [comment]
I guess I can resolve this issue. I was not quite sure if I have project owner blessing or not. :)

**Comment by sawilde** [comment]
> I was not quite sure do I have project owner blessing or not.

Sure you do; I am just making sure that we are not excluding branches that the user should cover because by hiding them we hide a defect by not forcing them to have a test that exercises that path

**Comment by ddur** [comment]
Unfortunately, keyword fixed does not generate sequence-point.
I could read whole line, try to match fixed keyword, but that would be slow and unreliable because C# syntax allows new-line everywhere.

![issue 529 fixed keyword](https://cloud.githubusercontent.com/assets/3501612/13024643/62bf415e-d1f8-11e5-89e2-4bc01b6240a3.png)

**Comment by ddur** [comment]
We cannot rely on pointer type assignment because it can appear outside fixed-statement.
But, I think, no pointer type assignment sequence-point should have branches.

**Comment by ddur** [comment]
Actually, assignment can be conditional. 
```var a = b == 0? c : b;```
We cannot remove branches from all assignments. That is too much for regex.

**Comment by ddur** [comment]
Any idea?
Or we can close this issue?

**Comment by ddur** [comment]
In the future we can think about integrating Roslyn into OpenCover :)
Or moving branch removal functionality into OpenCover UI VS Extension where Roslyn is available?

**Comment by sawilde** [comment]
I'd say leave it for now

**Comment by ddur** [comment]
@sawilde 
[ILSpy](https://github.com/icsharpcode/ILSpy) recognizes ```fixed``` block. 
It must be a pattern in IL code.
Looks like first branch within the block should be skipped.
That is your area of expertise :)

https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/ILAst/PeepholeTransform.cs#L787

**Comment by sawilde** [comment]
> That is your area of expertise :)

okay

**Comment by hughbe** [comment]
Just to bring this back up again:
This code:
```
unsafe 
{
    if (string.IsNullOrEmpty(aStringValue))
    {
        return aStringValuea;
    }
    fixed (char* sourcePtr = aStringValue) // 1/2 branch coverage *here*
    {
        return DoSomething();
     }
}
```
reports 1/2 branch coverage, but the 2nd branch is impossible to cover.
Is this a problem with the C# compiler generating dead code, the JIT not doing its job properly, or OpenCover reporting things incorrectly.

I think it might be the former - do you think it would be a good idea to post this as an issue in the roslyn repo?

**Comment by sawilde** [comment]
@hughbe there is a probably a branch in the IL - look there first to see if the logic makes sense - may also give you an idea of how to exercise it.
