### ISSUE TITLE
OpenCover - Should it fail?

### ISSUE THREAD

**Issue by SavaNDragos** [OpenCover/opencover#531]
Tests run: 2422, Errors: 7, Failures: 4, Inconclusive: 0, Time: 167.628490492507 seconds
  Not run: 251, Invalid: 0, Ignored: 251, Skipped: 0

Errors and Failures:
1) Test Error : ... (this is an error from the nunit tests)

After displaying this message OpenCover finishes with 0, after it generates the report.
Shouldn't  it had failed?

**Comment by sawilde** [comment]
OpenCover itself has not failed but your target executable has - for this this scenario we have a switch `-returntargetcode[:offest]` and is described in the [wiki -  Usage](https://github.com/OpenCover/opencover/wiki/Usage) as this:

> Return the target process return code instead of the OpenCover console return code. Use the offset to return the OpenCover console at a value outside the range returned by the target process.
