### ISSUE TITLE
Version information log out

### ISSUE THREAD

**Issue by trivalik** [OpenCover/opencover#540]
Since sawilde told me that I was using a different version. It comes to my mind to check console logs of jenkins, but there was no version logged out. Using the parameter -version does log out the version but not executing anything.

Is it possible to run openconsole normal when -version is used in case of more than one argument?

**Comment by ddur** [comment]
I ran OpenCover once with -version, and then again for coverage test.

**Comment by sawilde** [comment]
> I ran OpenCover once with -version, and then again for coverage test.

That's a good workaround and we could add this to the next release (not this one).

**Comment by ddur** [comment]
It would be nice to see OpenCover version in output *. XML file too.
