### ISSUE TITLE
Cannot instrument RefEmit_InMemoryManifestModule as no PDB/MDB could be loaded

### ISSUE THREAD

**Issue by dcorriveau-omniscient** [OpenCover/opencover#543]
I've been struggling with this for a while now so I'm hoping you guys can help me figure out what's wrong with my command.

I'm using VS2015, Windows 10.
I have a solution with 3 projects:
- FW.WebAPI.Plugins (main library)
- Build (project that contains PowerShell scripts, I'm using psake)
- FW.WebAPI.Plugins.Tests (XUnit Tests)

My build scripts compiles the solution, then copies the files (using targets) to a directory (_PublishedXUnit\FW.WebAPI.Plugins.Tests), then I run the command to launch opencover with the xunit runner.

The command looks like this (although I changed the actual path values and the quotes might not be correct since this is normally run from a powershell script):
`OpenCover.Console.exe "-target:C:\packages\xunit.runner.console\Tools\xunit.console.exe" "-targetargs:C:\_PublishedXUnit\FW.WebAPI.Plugins.Tests\FW.WebAPI.Plugins.Tests.dll -xml C:\TestResults\XUnit\xUnit.xml -nologo -noshadow" "-output:C:\TestCoverage\OpenCover.xml" "-filter:+[*]* -[*Tests]* -[*xunit*]*" "-excludebyattribute:System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" "-excludebyfile:*\*Designer.cs;*\*.g.cs;*\*.g.i.cs" -skipautoprops -mergebyhash -mergeoutput -hideskipped:All -returntargetcode -register:user -log:All`

I'm getting this output:
```
---------- Executing TestXUnit Task ----------
1 XUnit project has been found:
FW.WebAPI.Plugins.Tests
Creating test directory located at  C:\TestResults\XUnit
Creating test coverage directory located at  C:\TestCoverage
testAssemblies ""C:\_PublishedXUnit\FW.WebAPI.Plugins.Tests\FW.WebAPI.Plugins.Tests.dll""
Running Tests
Executing: C:\packages\xunit.runner.console\Tools\xunit.console.exe
Cannot instrument RefEmit_InMemoryManifestModule as no PDB/MDB could be loaded
  Discovering: FW.WebAPI.Plugins.Tests
  Discovered:  FW.WebAPI.Plugins.Tests
  Starting:    FW.WebAPI.Plugins.Tests
  Finished:    FW.WebAPI.Plugins.Tests
=== TEST EXECUTION SUMMARY ===
   FW.WebAPI.Plugins.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.226s
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.


---------- Executing Clean Task ----------
Executed Clean!


---------- Executing Test Task ----------

Generating HTML test coverage report
Loading report 'C:\TestCoverage\OpenCover.xml'
 Preprocessing report
 Initiating parser for OpenCover
Initializing report builders for report types: Html
Analyzing 0 classes
 Creating summary
Report generation took 0.3 seconds

Build Succeeded!

----------------------------------------------------------------------
Build Time Report
----------------------------------------------------------------------
Name       Duration        
----       --------        
Init       00:00:00.0516159
Compile    00:00:02.5371417
TestMSTest 00:00:00        
TestXUnit  00:00:03.8161776
Clean      00:00:00.0035463
Test       00:00:00.7297226
Total:     00:00:07.1944530
Build exit code: 0
```

So as you can see there is the `Cannot instrument RefEmit_InMemoryManifestModule as no PDB/MDB could be loaded` error that is weird, and also my actual main project isn't discovered. Even if I remove the filters to include all the projects it's still not discovered. The .pdb files are there next to the assemblies. I also tried to manually register the profiler, in case that would be related to that, but it doesn't change anything.

If a don't use any filters, the test project is actually found and I get a report (test coverage) for the test project, which obviously isn't what I want, but it does show that it partially works, it's just that it cannot find my actual main project.

How can I debug this to determine what's wrong ?

Thanks.

**Comment by sawilde** [comment]
Which version of OpenCover are you running?

When you run without filters how does the module appear in the XML?

At which point, when adding filters, does the module disappear from the results?

**Comment by dcorriveau-omniscient** [comment]
I'm using the Nuget package version 4.6.519.
The actual program module only appears when I add it to the list of "test dlls", which I assume isn't the correct way of doing things. Otherwise, if I use the filter `+[*]*` and I only list the test assemblies in the params, I get coverage for the Test assembly and 3 xunit assemblies `xunit.core` etc...

**Comment by sawilde** [comment]
> The actual program module only appears when I add it to the list of "test dlls", 

I think this will trick xunit runner to load the module, in order to look for tests, which will allow OpenCover to locate the .pdb.

I assume `RefEmit_InMemoryManifestModule` has a pdb file, if so where is it in relation to the assembly when you are running your nunit tests? You could possibly try using the `-targetdir` option to execute OpenCover from the location where it can find the pdbs or you can use the -searchdirs` option to select several locations where pdbs may be found.

see the [Usage](https://github.com/OpenCover/opencover/wiki/Usage) wiki or pdf.

**Comment by dcorriveau-omniscient** [comment]
I have no idea what `RefEmit_InMemoryManifestModule` is, it's not something I coded and I cannot find a file named like that.

**Comment by dcorriveau-omniscient** [comment]
The `FW.WebAPI.Plugins.dll` and `FW.WebAPI.Plugins.pdb` are right next to the `FW.WebAPI.Plugins.Tests.dll` and `FW.WebAPI.Plugins.Tests.pdb` files, which is weird because OpenCover sees the tests assembly but not the main program assembly ?

**Comment by dcorriveau-omniscient** [comment]
Oh wait I'm probably a dummy. Does the test need at least one line of code that uses the main assembly to find it (being a project reference would not be enough) ? Because I commented most of my tests for the moment so I don't think I have any of them left that are actually calling the main assembly, so do you think it wouldn't include that assembly in the report if that's the case ?

**Comment by dcorriveau-omniscient** [comment]
Confirmed, it's working if at least one test is using the main assembly.
The errors kind of threw me off a little, but it may be because I have pdb in there that shouldn't be there or something like that. At least if it's working the errors are less of an issue.

**Comment by dcorriveau-omniscient** [comment]
I tried to clean up the assemblies / pdb in the directory, for example by removing the xunit.* ones but the error about RefEmit_InMemoryManifestModule still remains. I am not sure where it's coming from, it's a module that is loaded, maybe OpenCover does something like GetExecutingAssembly at some point and that grabs it. In any case my main issue is fixed. Thanks for your help.

**Comment by sawilde** [comment]
> I have no idea what RefEmit_InMemoryManifestModule is

According to a brief bit of gooling I think you are using ikvm and it is a dynamically generated assembly - just add it to your filters and it will go away `-[RefEmit_*]*` perhaps? Have a look in the xml outputted by opencover for the name to exclude.

> Does the test need at least one line of code that uses the main assembly to find it

Yes, a reference won't be enough as the runtime will not load unused assemblies.

> by removing the xunit.* ones

they look like they should be excluded by your filters

> In any case my main issue is fixed.

:+1:

**Comment by dcorriveau-omniscient** [comment]
The module name is "Anonymously Hosted DynamicMethods Assembly", _I should have guessed it_. Thanks.
