### ISSUE TITLE
0% code coverage with XUnit and portable class library.

### ISSUE THREAD

**Issue by SebastianStehle** [OpenCover/opencover#544]
Hello together, 

I am developing a UWP app. To improve the testability and moved the most code to portable class libraries (UWP tests sucks). But when I run open cover I have a code coverage of 0%, which is definitly not correct (I tested NCover some weeks ago).

I have a batch for running OpenCover:

	"%~dp0\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe" ^
	-register:user ^
	-target:"%~dp0\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" ^
	-targetargs:"Tests\bin\Debug\Tests.dll" ^
	-filter:"+[GP*]* +[Hercules*]*" ^
	-skipautoprops ^
	-output:"%~dp0\GeneratedReports\Minapp.xml"
	exit /b %errorlevel%

	:RunReportGeneratorOutput
	"%~dp0packages\ReportGenerator.2.4.2.0\tools\ReportGenerator.exe" ^
	-reports:"%~dp0\GeneratedReports\Minapp.xml" ^
	-targetdir:"%~dp0\GeneratedReports\Output"
	exit /b %errorlevel%

and my tests are running fine. 

![consoleout](https://cloud.githubusercontent.com/assets/1236435/13006721/27671be4-d18b-11e5-82e8-dca33c031564.png)

But the results look strange:

[GeneratedReports.zip](https://github.com/OpenCover/opencover/files/127967/GeneratedReports.zip)

**Comment by SebastianStehle** [comment]
Solved. Have to use -noshadow parameter.

**Comment by sawilde** [comment]
you could've also use the opencover switches `-targetdir` and `-searchdirs` depending on circumstances

**Comment by vival30** [comment]
Thanks  @SebastianStehle  I also had the same Issue now i got the coverage value in the report...

**Comment by UlyssesAlves** [comment]
That's it, @SebastianStehle ! -noshadow was the missing piece to get my coverage report working too. Thanks a lot!
