### ISSUE TITLE
Incomplete branch coverage of switch statements without the default branch.

### ISSUE THREAD

**Issue by jwaliszko** [OpenCover/opencover#545]
I'm using Visual Studio 2015 Update 1. When I use OpenCover (4.6.519) to analyze code coverage, I see incomplete branch coverage of some parts, for assembly compiled in both RELEASE and DEBUG modes (despite the fact I've visited all the branches in the visible C# code). 

Screenshots of the reports generated by ReportGenerator (2.4.2) are shown below:

RELEASE (3 of 4 branches are covered):
![image](https://cloud.githubusercontent.com/assets/1596462/13009337/2a7122e2-d19c-11e5-8d69-f423e2dac050.png)

DEBUG (3 of 4 branches are covered):
![image](https://cloud.githubusercontent.com/assets/1596462/13009340/2e7cb3ba-d19c-11e5-9886-601b43feb024.png)

To reproduce this issue: 
* download the minimalist archive: [sample.zip](https://github.com/OpenCover/opencover/files/128922/sample.zip), 
* extract it (to directory which does not contain whitespaces in its path, e.g. `D:\`),
* execute `run.ps1` PowerShell script (report will be generated and opened for you). 

----
The second question I'd like to ask, is not related to the branch coverage. It's about the OpenCover command construction in PowerShell, when you have whitespaces in both target, and target arguments.

The command I'm using now is following (see mentioned `run.ps1`): 
```
& $opencover -register:user -hideskipped:All -mergebyhash -target:$xunit "-targetargs:$testdll -noshadow" -filter:+[sample]* -output:coverage.xml -returntargetcode
```
Assume that all these variables: `$opencover`, `$xunit`, `$testdll`, do not contain whitespaces - working scenario. Now, how to properly construct the same command, when the values of these mentioned variables do have whitespaces? 

I've seen [the usage documentation](https://github.com/OpenCover/opencover/wiki/Usage#notes-on-spaces-in-arguments). I've tried a couple of approaches, but failed every single time to do it right (to test it, just extract the same [sample.zip](https://github.com/OpenCover/opencover/files/128922/sample.zip) to directory containing whitespaces in its path, e.g. `C:\Users\You\Documents\Visual Studio 2015\Projects\`, execute `run.ps1` script to see the crash, and try to fix the quotes).

**Comment by ddur** [comment]
@jwaliszko 
With ```enum Order``` you cannot test default branch
![issue545-1](https://cloud.githubusercontent.com/assets/3501612/13016011/86b767bc-d1bc-11e5-9a64-d5c1514af0d1.png)
![issue545-2](https://cloud.githubusercontent.com/assets/3501612/13016025/913b7638-d1bc-11e5-9f7f-6f1a28c5c3b7.png)

**Comment by jwaliszko** [comment]
I know that default execution path is impossible in my code (i.e. in real scenario it is a private function, and the input is validated earlier, so no execution flow will ever cause other switch branches to be invoked, despite these denoted explicitly). 

In other words, I do not want to include this `default` branch because it is not testable:
```
private string Stringify(Order order)
{
    Debug.Assert(ordet == Order.First || order == Order.Second);
    switch (order)
    {
        case Order.First:
            return "1st";
        case Order.Second:
            return "2nd";
        default:
            throw new ArgumentOutOfRangeException(); // never gets here
    }
}
```
`if {} else {}` is not an option as well because there is much more branches in real scenario.

**Comment by ddur** [comment]
Then use last value as ```default:``` instead of ```case:```

**Comment by ddur** [comment]
```[switch] default``` branch is equal to ```[if] else``` branch. 
If code does not exercise ```else``` branch, coverage is incomplete. 
Above statement holds for ```default:``` branch.
```switch``` is compiled to sequence of IL branch conditions (if/then/else)

**Comment by jwaliszko** [comment]
Thanks. I've been considering replacement of the last known branch with the `default` statement as well but didn't like it. After all I've decided to post here, and clarify that case, especially after I've seen the results generated by the native Visual Studio coverage tool (see that DEBUG code is entirely covered):

RELEASE:
![image](https://cloud.githubusercontent.com/assets/1596462/13018943/d35644de-d1cc-11e5-871b-fd4eaae1e9aa.png)
![image](https://cloud.githubusercontent.com/assets/1596462/13018961/e777a8a4-d1cc-11e5-80c2-db41eee466c5.png)

DEBUG:
![image](https://cloud.githubusercontent.com/assets/1596462/13018999/0d2f5fc4-d1cd-11e5-8882-efcd4814594d.png)
![image](https://cloud.githubusercontent.com/assets/1596462/13019009/1959ba7e-d1cd-11e5-93a5-3f95615ad9ed.png)

After seeing that, I started to wonder of what the correct approach should be:
 * relay on the programmer, and measure the visible C# code paths, only for the statements which were executed, based on the given set of tests, 
 * or alternatively, investigate all the paths generated by the internal language implementation. 

Obviously I have no any experience in this matter whatsoever, and that's only my lame thought.

**Comment by ddur** [comment]
In release mode there is no connection to source available, so VS shows same results as OpenCover.
I guess that VS in debug mode explores all possible paths using source-analysis.
OpenCover does not exercise any kind of source-analysis.

**Comment by sawilde** [comment]
Because the compiler always adds a `default:` to all switches if you don't add one yourself and OpenCover will instrument it. Now in the case of enums you'd think that if you had them all covered then there should be no need for the default but... an `enum` variable isn't limited to what is in it's declaration e.g.

````
enum Order
{
 First,
 Second,
};

void Main()
{
	Order order = (Order) Enum.Parse(typeof(Order), "5");
	string result;
	switch (order)
	{
	case Order.First:
		result = "1st";
		break;
	case Order.Second:
		result = "2nd";
		break;
	default:
	    throw new InvalidOperationException(string.Format("Invalid value for Order {0}", order));
	}
	result.Dump();
}
````

will throw the exception (tested in LinqPad). 

Now if you MUST get 100% branch coverage move this conversion to a separate utility-like class and then test the default branch like I have shown above (or something similar) otherwise ignore it.

**Comment by sawilde** [comment]
In powershell you may need to escape your quotes e.g.

````
& "`"$opencover`"" -register:user -hideskipped:All -mergebyhash "`"-target:$xunit`"" "`"-targetargs:$testdll -noshadow`"" -filter:+[sample]* -output:coverage.xml -returntargetcode
````

**Comment by jwaliszko** [comment]
I'll probably end up with this:
```
private string Stringify(Order order)
{
    switch (order)
    {
        case Order.First:
            return "1st";
        default:
            Debug.Assert(ordet == Order.Second);
            return "2nd";
    }
}
```
It may look weird, but is descriptive enough and did not require strained tests.

**Comment by jwaliszko** [comment]
The command below:
```
& "`"$opencover`"" -register:user -hideskipped:All -mergebyhash "`"-target:$xunit`"" "`"-targetargs:$testdll -noshadow`"" -filter:+[sample]* -output:coverage.xml -returntargetcode
```
throws following exception:
![image](https://cloud.githubusercontent.com/assets/1596462/13024241/523ced82-d1f2-11e5-98d5-a38315f8a39f.png)

I've tried multiple various constructs (including alternative form of commands execution like `Invoke-Expression`) without success. 

I'm using the following PowerShell version (if it matters):
![image](https://cloud.githubusercontent.com/assets/1596462/13024274/9bea78dc-d1f2-11e5-8c78-cf54291ae7e6.png)

**Comment by sawilde** [comment]
You may just have to try a combination of quotes

```
& "'$opencover'"
```

powershell and quotes/spaces is always a pain and not just limited to OpenCover

**Comment by jwaliszko** [comment]
PowerShell and quotes/spaces is nothing more than problems. I wasn't able to find a correct way to solve it. The workaround for me so far - operate on paths without spaces (at least without spaces in these all 3 parts: entry, target and targetargs, at once).

**Comment by sawilde** [comment]
I had a look at how I've done it on one of my pipelines

```
exec { & $opencover_exe `
  '-register:user' `
  "-filter:$coverage_filters" `
  "-target:$nunit_exe" `
  "-targetargs:/noshadow $test_dlls"  }
```

Perhaps it will help.

**Comment by jwaliszko** [comment]
It doesn't help - if your `$test_dlls` variable contains whitespaces, command crashes. It's very quick to verify it using `run.ps1` script in the [sample.zip](https://github.com/OpenCover/opencover/files/128922/sample.zip), I've provided in the first post of this thread.

Maybe you could accept a fix, where the `-targetargs` parameters are separated by semicolons? It would simplify the impossible-to-do quotes escaping constructions from inside PowerShell. 

The fix I'm thinking of is a minor change to the [`CommandLineParser.cs#L212`](https://github.com/OpenCover/opencover/blob/8aff26800824a8f46a4329eeca4f77e8b65e87c9/main/OpenCover.Framework/CommandLineParser.cs#L212), mainly:
```
case "targetargs":
    TargetArgs = string.Join(" ",
        GetArgumentValue("targetargs")
            .Split(';')
            .Select(_ => _.Length > 1 ? $"\"{_.Trim()}\"" : _));
    break;
```
Assuming that current usage cases don't contain semicolons, this logic preserves backward compatibility, enabling additional way of providing arguments, i.e. `"-targetargs:$testdll;-noshadow"`.

**Comment by ddur** [comment]
How about moving the critical part into simple batch file and call it from Power Shell?

**Comment by ddur** [comment]
More about else/default branch
```else/default``` is always present in source-code semantic, compiler generates it because he must to.
```else/default``` is implicit path and can be coded as explicit
```
if (x) {
    doSomething();
} else if (y) {
    doSomethingElse()
}
```
```
switch (condition) {
    case x: doSomething(); break;
    case y: doSomethingElse(); break;
}
```
```
                        | // code before condition
                        |\___ // if / switch&case branch
                        |    \
 else/default branch -> |     | // doSomething or doSomethingElse
                        |____/
                        |
```

**Comment by jwaliszko** [comment]
Thanks for further clarification. 
I haven't tried batch running from PS for that case, perhaps it can be done, but isn't it somewhat contrived?

**Comment by ddur** [comment]
I thought you have problem with PS

**Comment by jwaliszko** [comment]
There are ways. I can even switch to Cygwin and use Bash. But under Windows PS in general is most powerful, or at least more than an old batch scripts, so switching to older technology, just to workaround certain operations, in my opinion, shouldn't be considered as the right thing (for me it is the last resort). 

Nevertheless, if my problem is that uncommon, we can consider the issue as closed. I'm not forced to use whitespaces myself for all my arguments. I've picked this case up, because I believed it may be an issue for certain cases.

**Comment by sawilde** [comment]
Frankly I am confused about what comment refers to what now :)

dynamically creating and calling a batch script (as @ddur is suggesting) and then executing that batch from your powershell will definitely get you there quicker if you can't work out how to build your exec in powershell.  

As you say powershell is very powerful and has ways for you to deal with spaces so even if we created a variation that helped you work with opencover in powershell it still won't help for other scenarios you will encounter so working out how to escape would probably benefit you in the long term - try using backticks `` ` `` or other powershell escaping `\`

```
exec { & $opencover_exe `
  '-register:user' `
  "-filter:$coverage_filters" `
  "`"-target:$nunit_exe`"" `
  "`"-targetargs:/noshadow $test_dlls`""  }
```

I use psake at work for my scripts (don't have access at the weekend) and solved the spaces issue then and from memory it looks something like the above.

Now using `;` as separators may make sense in your case until you try to execute a program that needs an argument that requires passing a `;` so then we have to build our own escaping mechanism to deal with `;` e.g. `;;` or `\;` which could lead to `\\\;`

**Comment by sawilde** [comment]
okay I had a tinker and came up with the following all args exes and dlls had spaces in path and I used cvpa to expand them out to ensure what I was passing to `exec` had spaces.

As you can see I had to use `` `" `` to create a single `"` and where necessary `` `"`" `` to create a `""` to escape double quotes when necessary when the OS executes the command.

```
task default -depends RunOpenCover

properties {
  $opencover_version = '4.6.519'
  $nunit_version = '3.0.1'
  
  $opencover_exe = cvpa -literalpath "packages\OpenCover.$opencover_version\tools\OpenCover.Console.exe"  
  $nunit_exe = cvpa -literalpath "packages\NUnit.Console.$nunit_version\tools\nunit3-console.exe"  
}

task RunOpenCover {
  echo $opencover_exe
  echo $nunit_exe
  
  $test_dll1 = cvpa -literalpath "bin\Debug\TestMe.dll"
  $test_dll2 = cvpa -literalpath "..\TestMe2\bin\Debug\TestMe2.dll"
  $test_dlls = "`"`"$test_dll1`"`" `"`"$test_dll2`"`""
  
  exec { & $opencover_exe `
    -register:user `
    -target:$nunit_exe `
    "`"-targetargs:$test_dlls`"" }
}
```

which produces the following output

```
C:\Projects\opencover.git\issues\spaces 545\TestMe>build.cmd
psake version 4.5.0
Copyright (c) 2010-2014 James Kovacs & Contributors

Executing RunOpenCover
C:\Projects\opencover.git\issues\spaces 545\TestMe\packages\OpenCover.4.6.519\to
ols\OpenCover.Console.exe
C:\Projects\opencover.git\issues\spaces 545\TestMe\packages\NUnit.Console.3.0.1\
tools\nunit3-console.exe
Executing: C:\Projects\opencover.git\issues\spaces 545\TestMe\packages\NUnit.Con
sole.3.0.1\tools\nunit3-console.exe
NUnit Console Runner 3.0.5813
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10586.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\Projects\opencover.git\issues\spaces 545\TestMe\bin\Debug\TestMe.dll
    C:\Projects\opencover.git\issues\spaces 545\TestMe2\bin\Debug\TestMe2.dll


Run Settings
    WorkDirectory: C:\Projects\opencover.git\issues\spaces 545\TestMe
    RuntimeFramework: net-4.0
    NumberOfTestWorkers: 4

Test Run Summary
    Overall result: Passed
   Tests run: 2, Passed: 2, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2016-02-14 02:32:51Z
    End time: 2016-02-14 02:32:52Z
    Duration: 0.321 seconds

Results (nunit3) saved as TestResult.xml
Committing...
Visited Classes 2 of 2 (100)
Visited Methods 2 of 2 (100)
Visited Points 6 of 6 (100)
Visited Branches 2 of 2 (100)

==== Alternative Results (includes all methods including those without correspon
ding source) ====
Alternative Visited Classes 2 of 2 (100)
Alternative Visited Methods 4 of 4 (100)

Build Succeeded!

----------------------------------------------------------------------
Build Time Report
----------------------------------------------------------------------
Name         Duration
----         --------
RunOpenCover 00:00:11.0948814
Total:       00:00:11.3305222
```
