### ISSUE TITLE
mergeoutput is not recognised

### ISSUE THREAD

**Issue by bartap** [OpenCover/opencover#547]
When I try use mergeoutput argument the opencover give me error.
The mergeoutput is not listed in help. Was the argument removed? Is there still option to put results into one file?

Error:
Incorrect Arguments: The argument mergeoutput is not recognised
opencover.4.5.3207

Thanks

**Comment by sawilde** [comment]
According to the [release notes](https://github.com/OpenCover/opencover/blob/master/ReleaseNotes.tmp) `-mergeoutput` was first available in 4.5.3427. 

Please upgrade to latest and try again.

**Comment by bartap** [comment]
Oh Thank you, I'm new in Opencover and I didn't realized that I just hit version before the feature was implemented.

Thanks
