### ISSUE TITLE
cla signing and review ninja

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#555]
Hi @ddur @molnargab @danielpalme 

Just to let you know I've added a couple more integrations 
1. CLA signing - will request that the contributor agrees to certain rules around submission
2. Review Ninja - to help with the code submission review.

**Comment by ddur** [comment]
CLA signed. 
About Review Ninja: I do not like that agreement with SAP.

**Comment by sawilde** [comment]
> CLA signed (twice) but it does not count on badge?
I am not convinced I have set the badge up properly or it may not be dynamically generated and so we need to wait for a refresh

> About Review Ninja: I do not like that agreement with SAP.
What don't you like?

**Comment by ddur** [comment]
>What don't you like?

As far as I understand, it applies not only on me, but on all my current and future employers. 
If I have to introduce that agreement to all may potential future employers, only I can say is F#C# SAP.

**Comment by sawilde** [comment]
> As far as I understand, it applies not only on me, but on all my current and future employers. 

Can you highlight the piece in the agreement?

**Comment by ddur** [comment]
I do not have that text anymore and do not remember exact words. I remember mentioning company where other party works. Consequently, as long as agreement is not terminated it applies to the future companies/employers.

**Comment by sawilde** [comment]
The only piece that applies to employers I can find is where you are acting on behalf of them which is different to working on behalf of yourself.

**Comment by ddur** [comment]
I will read it again

**Comment by sawilde** [comment]
I assume anyone who wants to read it has :)
