### ISSUE TITLE
register failed

### ISSUE THREAD

**Issue by trivalik** [OpenCover/opencover#557]
Today I got a random shot of:

Failed to register(user:True,register:True,is64:True):5 the profiler assembly; you may want to look into permissions or using the -register:user option instead. C:\Windows\system32\regsvr32.exe /s  /n /i:user "D:\Program Files\opencover\x64\OpenCover.Profiler.dll"
If you are unable to resolve the issue please contact the OpenCover development team
see https://www.github.com/opencover/opencover/issues

I am not sure how this happens, because the run happens every day a few times. I was changing today 2 project nearly at the same time so that both fail with this error.
I was then executing manually on cmd prompt the "C:\Windows\system32\regsvr32.exe /s  /n /i:user "D:\Program Files\opencover\x64\OpenCover.Profiler.dll"" without problem. The next build run as before without any problems.

The Domain user has also local admin rights. The OS is Server 2008 R2 Datacenter. UAC is switched off.

**Comment by sawilde** [comment]
Not sure what we can do - it's an external utility we are are running to register the DLL's.

Do you have any information in your event logs (eventvwr.msc) that may give an indication as to why it may have happened when it did?

**Comment by molnargab** [comment]
@trivalik , if you omit `/s` you should get a popup with the error message.

**Comment by trivalik** [comment]
Executing the command without ```/s``` is always successful. Nothing special in log visible.
Maybe can you log out the return value of regsvr32?

```C++
#define FAIL_ARGS   1 // Invalid Argument
#define FAIL_OLE    2 // OleInitialize Failed
#define FAIL_LOAD   3 // LoadLibrary Failed
#define FAIL_ENTRY  4 // GetProcAddress failed
#define FAIL_REG    5 // DllRegisterServer or DllUnregisterServer failed.
```

source: http://stackoverflow.com/questions/22094309/regsvr32-exit-codes-documentation

**Comment by sawilde** [comment]
not sure what we can do sometimes things just don't work and then they do again - we could look to have a retry perhaps but how long to wait etc etc.

**Comment by sawilde** [comment]
> Maybe can you log out the return value of regsvr32.

Yup, we can add that to the error message I suspect

**Comment by trivalik** [comment]
I have now a guess what is happen. Since 2 jobs run simultanousely that regsrv32 cannot handly this. The only thing what is against this is that both jobs fail.

**Comment by sawilde** [comment]
Ah, probably - normally I'd say just register manually (regsvr32) and drop the `-register` switch

**Comment by trivalik** [comment]
That's the point. So you mean there is no chance to fix it by code change? i.e. global lock within filesystem

**Comment by sawilde** [comment]
If you know you are only profiling 32 or 64 bit then you can use the registry free loading approach `-register:path32` or `-register:path64`.

**Comment by trivalik** [comment]
I changed it now for all jobs to ```-register:path32```.

**Comment by sawilde** [comment]
:+1:

**Comment by sawilde** [comment]
report output of regsvr32 action when it fails

**Comment by timotei** [comment]
Hello. It seems I get the same issue on Windows Containers (Windows Server 2016 Technical Preview 5 docker container). If I use `-register:path32` it seems to work. Which is super weird, cause the original failure **is** the 32bit one: `Failed to register(user:True,register:True,is64:False):5 the profiler assembly; you may want to look into permissions or using the -register:user option instead. `

Initially, I thought it's a regsvr32 issue (https://github.com/Microsoft/Virtualization-Documentation/issues/315), but it seems not always, and it must be something from the .NET FWK, which returns 5.

**Comment by sawilde** [comment]
Perhaps you don't have access to the registry as a user - you could true just `-register` or use regsvr32 to preregister the profilers

> As I understand it, that's for the .NET FW, which theoretically shouldn't care about the C++ part of the profiler, no?

No the .NET FW cares very much about what profiler to load (the c++ part), profilers cannot be written in .NET e.g. so commonly we use c++ or pascal.

**Comment by timotei** [comment]
Well, I **did** use the the `register:user` switch which translates into: (` C:\Windows\system32\regsvr32.exe /s  /n /i:user "C:\Users\ContainerAdministrator\.gradle\caches\opencover\opencover-4.6.166\x86\OpenCover.Profiler.dll"`

**Comment by sawilde** [comment]
Yes but sometimes it depends on the permissions of the account making the regsvr32 call.

4.6.166 is quite old - I did see that someone created a chocolaty package but didn't keep it up to date and is now on my todo list - where did you get your version from?

**Comment by timotei** [comment]
Well, the version from Github. I remember I tried with the latest and I got the same issue. 

The account is administrator, so it shouldn't have problems. The issue I have with `-register:path32` is that *nothing* is generated in the report, just like no profiler would be registered. Should I open another issue for that?

**Comment by sawilde** [comment]
> Should I open another issue for that?

Since I have no issues with any of the options and is purely to do with your environment, you will have to supply repeat steps. The easier you make it to repeat, the more likely someone will look at it.

**Comment by mcartoixa** [comment]
The conflict might occur regularly in a Continuous Integration scenario based on a per-project NuGet deployment of OpenCover : multiple instances trying to analyze different projects at the same time.

A global lock (e.g. using a semaphore) could prove very useful in this case. Or get rid of the NuGet deployment system.

**Comment by sawilde** [comment]
@mcartoixa that is a definite possibility, however many instances of opencover can run in parrallel but to do so you have to either

1. use regsvr32 to register the profilers and not use the `-register` or `-register:user` related switches
2. use `-register:path32` or `-register:path64`

So I am not sure I want a global mutex in there - that would also stop the pedigree tests where opencover analyses opencover running nunit executing its tests

**Comment by mcartoixa** [comment]
The first option defeats the purpose of a NuGet deployment IMHO, because in effect it requires you to manually install the tool.

And the second option cannot currently be handled by the MSBuild task (it does `-register:user` or nothing). So I guess another PR is called for. Shall I create another issue for that?

**Comment by sawilde** [comment]
> The first option defeats the purpose of a NuGet deployment IMHO, because in effect it requires you to manually install the tool.

we have installers and zip packages for those not wanting to use nuget

> And the second option cannot currently be handled by the MSBuild task....

yes that would be good - thanks

I am probably going to close this issue as the OP is no longer enagaged.

**Comment by trivalik** [comment]
The issue is not happen again, so. Maybe create a new ticket if it comes again.

**Comment by sawilde** [comment]
@trivalik - we are still intending on updating the code to provide a reason

**Comment by reyou** [comment]
I just downloaded latest version and running following command on windows 10 machine.

OpenCover.Console.exe -output:"C:\Temp\opencover.xml" -register:user 
-target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" 
-targetargs:"C:\Temp\SonarQubeTests.dll"

And I am getting same error. Is there anything I am doing wrong?

I also run the command below, but nothing changed.

`regsvr32.exe /s  /n /i:user "C:\Programs2\opencover-master\main\bin\Debug\x86\OpenCover.Profiler.dll`

**Comment by reyou** [comment]
Sorry when I use "register:path32" flag it worked.

**Comment by juanmanuelst** [comment]
fuck everybody

**Comment by juanmanuelst** [comment]
TRUMP SUCKS
