### ISSUE TITLE
Argument to fix a minimum percentage coverage?

### ISSUE THREAD

**Issue by labilbe** [OpenCover/opencover#558]
Hi,

I am looking for a way to specify something like:
- If my total coverage is less than 80% then the build should fail.

Is it possible to do that with OpenCover?
Can't figure out how.

Thanks!

**Comment by sawilde** [comment]
You can get the overall coverage value from the output xml file and then fail the build based on that value.

**Comment by molnargab** [comment]
[danielpalme/OpenCoverToCoberturaConverter](https://github.com/danielpalme/OpenCoverToCoberturaConverter) may also help. Assuming your CI supports Cobertura reports.

**Comment by labilbe** [comment]
Hi Shaun,
I ended up with something like

`  <Target Name="RunTests">
    <OpenCover ToolPath="$(OpenCoverPath)" Target="$(NUnitPath)\nunit3-console.exe" Output="$(CoverageFile)"
               TargetArgs="$(TestAssemblies) /result=&quot;$(TempPath)\nunit.xml;format=nunit2&quot;"
               Filter="$(CoverageFilters)" />
    
    <MSBuild.ExtensionPack.Xml.XmlFile TaskAction="ReadAttribute" File="$(CoverageFile)" XPath="/CoverageSession/Summary/@sequenceCoverage">
      <Output TaskParameter="Value" PropertyName="SequenceCoverage" />
    </MSBuild.ExtensionPack.Xml.XmlFile>
    <Error Text="Current coverage results ($(SequenceCoverage)%) does not meet minimal coverage expectations ($(MinimalCoverageExpectation)%)" Condition="'$(SequenceCoverage)' &lt; '$(MinimalCoverageExpectation)'" />
    <ReportGenerator ReportFiles="$(CoverageFile)" TargetDirectory="$(TempPath)\coverage" ReportTypes="Html;Latex" VerbosityLevel="Verbose" />
  </Target>`

So thank you for your hint.
The only problem I have is I don't have same percentage that OpenCover report.
I don't know how OpenCover can return "81.6%" from report if my opencover.xml report displays

`<Summary numSequencePoints="22458" visitedSequencePoints="11612" numBranchPoints="19141" visitedBranchPoints="9264" sequenceCoverage="51.71" branchCoverage="48.40" maxCyclomaticComplexity="72" minCyclomaticComplexity="0" visitedClasses="1042" numClasses="1822" visitedMethods="6687" numMethods="12138" />`

How did you end up with a percentage of approxim. +30% ?

**Comment by sawilde** [comment]
> PS : I understand that 81.6% is obtained doing ([Covered lines]/[Coverable lines]). So my real question is how do you do to get these two numbers from opencover.xml?

You would have to repeat the same process that [ReportGenerator](https://github.com/danielpalme/ReportGenerator) uses.

It is suspicious that you have 52% sequence coverage and 82% line coverage i.e. you still have a lot of uncovered code; without seeing your code I would guess the code would be behind branches on the same line e.g.

    if (condition) action();

where the `condition` is hit but the `action` is not but because they are on the same line it is considered covered just not 100% covered; this is why OpenCover counts sequence points and not lines.

**Comment by labilbe** [comment]
> You would have to repeat the same process that ReportGenerator uses.
I will check that thanks!

>  I would guess the code would be behind branches on the same line
No, I use condition+action on two lines except for ternary styles.

`var result = test1 ? result1 : result2;`

Attached another coverage result (generated with Visual Studio Code Coverage tool)
![sshot-1](https://cloud.githubusercontent.com/assets/54315/13488828/dbf8222c-e123-11e5-82d4-39aed51746ac.png)

**Comment by sawilde** [comment]
You are comparing apples with pears, we instrument differently and so will have different measures. VS uses source code and instruments you code whereas OpenCover works against your assemblies and uses sequence points as derived from the PDB files.

**Comment by labilbe** [comment]
Thank you for your time.

**Comment by labilbe** [comment]
I think I found the origin of differences.

`public MyProp {get; set;}`

Same line and different sequence points.
In my tests I omitted to check the get method, relying only on mock expectations.

**Comment by sawilde** [comment]
You can ignore auto-properties with OpenCover using `-skipautoprops`; of course you may want to know if you use them so you may decide not to.

**Comment by labilbe** [comment]
Ok, interesting tip! Thanks!
