### ISSUE TITLE
OpenCover targetargs -> How to have multiple arguments in one bat file?

### ISSUE THREAD

**Issue by catmiawmiaw** [OpenCover/opencover#559]
Hi guys,
Would like to ask how to insert multiple values into this argument?
-targetargs:<target arguments> - Arguments to be passed to the target process.

A sample would be great.

Thanks in advance,
Catherine

**Comment by sawilde** [comment]
You'll need to use quotes

    -targetargs:"-arg1 -arg2"

The [wiki](https://github.com/OpenCover/opencover/wiki/Usage#notes-on-spaces-in-arguments) provides examples.

**Comment by catmiawmiaw** [comment]
Thank you!
