### ISSUE TITLE
Running opencover against a nuget package

### ISSUE THREAD

**Issue by vigneshwar-v** [OpenCover/opencover#560]
I have a nuget repository which contains pdbs/dlls/source code and my site is hosted in a different machine. So Can I run opencover by pointing to the url against nuget repo while running my automation suite??

**Comment by sawilde** [comment]
If I understand you correctly, no.

OpenCover has to run on the same machine you are running the application you intend to instrument.

**Comment by vigneshwar-v** [comment]
oh thanks!
