### ISSUE TITLE
How to start a solution in VS2015?

### ISSUE THREAD

**Issue by Yefimov** [OpenCover/opencover#561]
When i try to start opencover (on VS2015) i see this error 
![image](https://cloud.githubusercontent.com/assets/16087064/14068314/c5676b90-f487-11e5-8225-c46755c6590c.png)
after launchung installutil.exe it shows and close
![image](https://cloud.githubusercontent.com/assets/16087064/14068317/ca91c566-f487-11e5-811c-dbc2030cb77f.png)

How i can start opencover correctly?

**Comment by kveretennicov** [comment]
Are you running `OpenCover.Console.exe`? Have you checked [Usage](https://github.com/OpenCover/opencover/wiki/Usage)?

**Comment by Yefimov** [comment]
**pver**'s answer:

> to start (and debug) OpenCover.UI in VS2015, you need to change the startup arguments of the project.
> If you open the OpenCover.UI.VS2015.sln, you can set OpenCover.UI.VS2013 as startup project
> Right click the project file and open the project properties
> in tab 'Debug', change C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe
> to C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
> (so change the 12 into 14)
> that way you should be able to run and debug OpenCover.UI
