### ISSUE TITLE
Coverage misses complete classes

### ISSUE THREAD

**Issue by tzachshabtay** [OpenCover/opencover#563]
Hi, my project is here: https://github.com/tzachshabtay/MonoAGS
Coverall page is here: https://coveralls.io/github/tzachshabtay/MonoAGS
OpenCover is called during the build from AppVeyor, the AppVeyor.yml is in the root of the project.

The coverage worked fine up until a few days ago when I made changes.
You can see where it started going wrong, in build 58 where the coverage dropped from 45% to 21%.
If you sort by missed lines, the highest number of missed lines is in AGSCharacter.generated.cs.
It looks like this class is not accessed at all during the tests. But if you debug the tests and put a breakpoint in the constructor, you'll see that the class is accessed during the tests.

That class is auto-generated by a T4 template, but it was generated manually before the build, so it shouldn't be any different from other classes in OpenCover's eyes.
It's a partial class where the other partial implementation is another folder, I thought this might be the problem, so I tried building with the two partial classes in the same folder, but that didn't work.
I tried upgrading OpenCover (from 4.6.166 to 4.6.519) but that didn't work either.

Please help, thanks.

**Comment by sawilde** [comment]
What does it say in the output file about why the class was skipped?

**Comment by tzachshabtay** [comment]
Hmm, weird, apparently it went back to normal a few commits later. I don't have older output files, so I guess this can be closed. I'll re-open with an output file if it reproduces.
Thanks.
