### ISSUE TITLE
Getting paid...

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#566]
Not 100% convinced there is any value in a donate button but I see they are becoming more popular so perhaps there is a shift where people will voluntary contribute money to a project they use rather than time... 

Personally I have no need for cash as I try to use anything that is free, but, as I mentioned recently on twitter, an occasional cup of coffee (skinny latte, large) would be nice.

I see chocolatey are using gratipay so I have started the process with them to see what the process is like but still not sure whether putting a button on the site would work (or just be depressing).

Thoughts?

**Comment by kveretennicov** [comment]
It has certain potential to discourage non-paid contributions, depending on how it is organized with respect to community. But i'm sure it can also be a very interesting experiment to try. Also, even if you don't need cash, you can re-donate it, assign bounties for own or upstream bugs, etc. Transparency will be key to whether it will be perceived as depressing or the opposite.

**Comment by sawilde** [comment]
@kveretennicov That is my worry as I would like to encourage more people to contribute especially as I start to do less; don't worry not abandon but I want to try other things.

Also I find cash too *icky*.

**Comment by sawilde** [comment]
some options

https://ko-fi.com/ - buy a coffee 
https://gratipay.com/ - donate and take a split
http://backerpass.com/ - in beta - trying to create a personal relationship
https://www.patreon.com/ - more for artists and creatives; aren't developers considered creatives as well?

and then there are ones where people offer money to fix things...

The more I look into this, the more I am starting to talk myself out of going down this path :)

**Comment by Yefimov** [comment]
I think this is a fair decision. Even Twitch/YouTube-streamers have donate buttons.

**Comment by sawilde** [comment]
will we are approved for gratipay - https://github.com/gratipay/team-review/issues/195#event-625886573

Also added a contributing.md file which also shows up when someone hits the new issue button

![image](https://cloud.githubusercontent.com/assets/297165/14512247/b9fd61d2-0220-11e6-954d-6066c21df736.png)

so a  bonus

**Comment by ddur** [comment]
@sawilde Maybe you could offer commercial support.

>Personally I have no need for cash ...

Personally I do have need for cash (or job). All contributions are welcome. :)
