### ISSUE TITLE
Target's return code isn't being returned

### ISSUE THREAD

**Issue by pherelad** [OpenCover/opencover#567]
Hi there,

First of all, nice project! While introducing OpenCover to our CI pipeline, we noticed that the return code from nunit wasn't being returned from OpenCover. We are using the -targetreturncode flag when invoking OpenCover.Console.exe as well. I've tried executing NUnit by itself and it seems to return the correct return code.

```
c:\b\project\debug\build\Tools\ThirdParty\opencover-4.6.261\OpenCover.Console.exe -returntargetcode -target:c:\nunit-3.0.0-beta-4\bin\nunit3-console.exe "-targetargs:--result=c:\b\project\debug\build\AllTests.nunit.xml c:\b\project\debug\build\AllTests.nunit" -output:c:\b\project\debug\build\AllTestsCoverage\AllTestsCoverage.xml -filter:+[*]* -register:user
```

The final result is below:
```
5) Failed : Namespace.Blah.Blah.TestCase
  Expected: 3
  But was:  2
at Namespace.Blah.Blah.Class.Method1() in c:\b\project\debug\build\Namespace.Blah.Blah\Class1.cs:line 84

Test Run Summary
    Overall result: Failed
   Tests run: 289, Passed: 284, Errors: 3, Failures: 2, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2016-04-07 18:55:18Z
    End time: 2016-04-07 18:57:41Z
    Duration: 143.135 seconds

Results (nunit3) saved as c:\b\project\debug\build\AllTests.nunit.xml
program finished with exit code 0
```
The return code from OpenCover always seems to be zero, even if NUnit is quite obviously failing with a non-zero return code. I've also looked through other bug reports of this happening where people are using batch files, but forgetting to set the exit code, but in this case we are executing NUnit directly.

Thanks for any assistance you can offer; I'd be happy to try any suggestions you may have. :smile:

**Comment by pherelad** [comment]
Bump. If anyone needs more information on what's going on here please let me know. I'd be happy to provide any information needed.

**Comment by pherelad** [comment]
Hi @kveretennicov, yeah, that's our python script that runs the unit tests. It's just echoing the exit code we get after spawning opencover.

**Comment by pherelad** [comment]
Sorry, actually that's not true; I just checked the actual code and it's from buildbot :D But a python script is what buildbot executes, which in turn executes OpenCover.

**Comment by kveretennicov** [comment]
Well, obviously next question is, does the Python script call `sys.exit(...)` to report subprocess's exit code to buildbot?

**Comment by sawilde** [comment]
I just tested that the target code is being returned as expected. 

```
@echo off
..\working\main\packages\NUnit.Runners.2.6.4\tools\nunit-console-x86.exe target.dll
echo Orig: %errorlevel%
..\working\main\bin\Release\OpenCover.Console.exe -target:..\working\main\packages\NUnit.Runners.2.6.4\tools\nunit-console-x86.exe -targetargs:target.dll -register:user
echo Open1: %errorlevel%
..\working\main\bin\Release\OpenCover.Console.exe -returntargetcode -target:..\working\main\packages\NUnit.Runners.2.6.4\tools\nunit-console-x86.exe -targetargs:target.dll -register:user
echo Open2: %errorlevel%
```

and I get the following output i.e. when I use the `-returntargetcode` option it works as expected

```
Orig: -2
Open1: 0
Open2: -2
```

**Comment by pherelad** [comment]
Yes, it's calling sys.exit(). Please see the code below:

`
  import sys.exit
  # ...
  # Execute the generated unit test application
  params = [
    kOpenCoverPath,
    '-returntargetcode:10000',
    '-target:' + kNUnitConsolePath,
    '-targetargs:--result=' + kTestFileName.strip() + '.xml ' +
      kTestFileName.strip(),
    '-output:' + kCoverageXmlPath,
    '-filter:+[*]*',
    '-register:user'
  ]
  print 'Executing: ' + ' '.join(params)
  result = subprocess.call(params)

  # Generate coverage report
  params = [
    kReportGeneratorPath,
    '-reports:' + kCoverageXmlPath,
    '-targetdir:' + kCoveragePath
  ]
  print 'Executing: ' + ' '.join(params)
  subprocess.call(params)

  params = [
    kNUnitConsolePath,
    '--result=' + kTestFileName.strip() + '.xml',
    kTestFileName.strip()
  ]
  print 'Executing: ' + ' '.join(params)
  result = subprocess.call(params)

  if result != 0:
    print 'Failed to run "' + kTestFileName + '"\nCommand: ' + \
      ' '.join(params)
    exit(result)

  exit(result)
`

**Comment by sawilde** [comment]
> I have also tried with -returntargetcode:10000

This will only offset any OpenCover error numbers to that value to separate them from any target error code.

Since I have tested that OpenCover is doing the right thing I can only assume your issue is in the python script. Have you since resolved the issue or do you require more help?

**Comment by sawilde** [comment]
I also rewrote my test in python and got the expected result so I cannot explain why you are having the issues you are experiencing

```
import subprocess
#
# Execute the generated unit test application
params = [
  '../working/main/bin/debug/OpenCover.Console.exe',
  '-returntargetcode',
  '-target:../working/main/packages/NUnit.Runners.2.6.4/tools/nunit-console-x86.exe',
  '-targetargs:target.dll',
  '-register:user'
]

print 'Executing: ' + ' '.join(params)
result = subprocess.call(params)
print(result)
```

**Comment by kveretennicov** [comment]
@pherelad, to add to @sawilde's efforts above - there is also a problem that the Python script you've shown is obviously different from the one you actually run: first line `import sys.exit` is not working Python, neither 2.x nor 3.x. I can only guess what other (relevant) differences remain hidden.

**Comment by pherelad** [comment]
Hey guys,

I'm afraid I did have to prune back the Python script a bit since this is a work related effort. You're right, I did omit the 'import sys' line, but can assure you that it's there in the script. The script that @sawilde provided matches pretty closely with what we're doing, minus some wrapper functions that we use to abstract away some of the nitty gritty.

Well, thanks for taking a look guys. I'll make sure that our Python scripts matches as closely as possible to your working solution @sawilde and then make sure I can get things to work on the shell without the Python script. That's something I haven't tried yet actually. Again, thanks for taking a look at this!

I'll report back once I learn more :+1:

**Comment by pherelad** [comment]
Regarding

> first line import sys.exit is not working Python, neither 2.x nor 3.x. I can only guess what other (relevant) differences remain hidden.

You're right, I messed up the source code when I was editing my reply there. It's actually `import sys`. My fault! I'll update it so it doesn't confuse anyone else.

**Comment by sawilde** [comment]
@pherelad thanks for the update - we'll keep this open for a while and close in a few weeks - if you have further questions you can reopen it (if closed) or start a new ticket referencing this one.
