### ISSUE TITLE
OpenCover -> NCover -> Bamboo

### ISSUE THREAD

**Issue by theSmallerFish** [OpenCover/opencover#568]
I'm being forced to move from TFS to Bamboo and am trying to get similar code coverage results, or at least a fair representation.  I've seen numerous threads around the internet about taking OpenCover results and transforming them to NCover compatible results.  Most use a xslt transform that they say that they got here.  It doesn't seem to be here anymore.  I got OpenCover integrated into a build plan and then do the transform on it based on the xslt that they re-shared.  Unfortunately after wiring Bamboo up to try to pull the Ncover results in, it doesn't present any results.  I don't know if I'm doing something wrong, or if Ncover has been changed enough that this "trick" no longer works.  I figured you would at least be able to tell me if it no longer can work.  I am guessing that may be the case since the xslt isn't hosted here anymore.  Any advice is appreciated.

**Comment by sawilde** [comment]
We don't use Bamboo anymore and so we pulled the page; I found the following in the deleted wiki pages (which I think I pulled from somewhere else)

    <?xml version="1.0" encoding="UTF-8"?>
    <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
      <xsl:output method="xml" indent="yes" standalone="yes"/>
      <xsl:template match="/CoverageSession/Modules">
        <coverage>
          <xsl:for-each select="Module[not(@skippedDueTo)]">
            <module name="{ModuleName}">
              <xsl:for-each select="Classes/Class">
                <xsl:if test="count(Methods/Method) &gt; 0">
                  <class name="{FullName}">
                    <xsl:variable name="className" select="FullName" />
                    <xsl:for-each select="Methods/Method">
                      <method class="{$className}">
                        <xsl:for-each select="SequencePoints/SequencePoint">
                          <seqpnt visitcount="{@vc}" />
                        </xsl:for-each>
                       </method>
                    </xsl:for-each>
                  </class>
                </xsl:if>
              </xsl:for-each>
            </module>
          </xsl:for-each>
        </coverage>
      </xsl:template>
    </xsl:stylesheet>

But it is to convert to an old NCover output and as you say this may no longer be supported.

You could:
1. create a new transform to convert to a compatible format,
2. request that Bamboo support OpenCover - https://jira.atlassian.com/browse/BAM-11470 
3. ask them to bring back the old NCover support.
4. build your own plug-in for bamboo (or get someone else to)

**Comment by theSmallerFish** [comment]
Thanks for the feedback.  I may try to change up the xslt and see what happens.  I did a trial of NCover to get an updated xml file to compare against.  If I come up with a new one, I will probably come back here and share it.

**Comment by coldacid** [comment]
@theSmallerFish: Any luck?

**Comment by theSmallerFish** [comment]
I was able to get it partially working.  Being new to Bamboo, I was looking in the wrong place for some of it.  The XSLT does work, however I find it increases code coverage with each build of that day.  A bit odd.  I haven't had time to figure out that part.  I'm also playing with the XSLT to get block coverage similar to what Visual Studio provides by default, rather than line coverage.  I do plan to post back when I get it all worked out, that could be a while though due to the limited amount of time I have to spend on this.  More to follow, I hope.

**Comment by Bheesma** [comment]
@theSmallerFish Can you share your xslt? I am using the xslt given above, and the NCover shows a blank graph only. I'm not sure how to proceed.

**Comment by theSmallerFish** [comment]
@Bheesma 
I will give you what I have.  I stopped trying eventually.  It doesn't give the same results as Visual Studio/TFS, but its something.

```<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="xml" indent="yes" standalone="yes"/>
    <xsl:template match="/CoverageSession/Modules">
        <coverage>
            <xsl:for-each select="Module[not(@skippedDueTo)]">
                <module name="{ModuleName}">
                    <xsl:for-each select="Classes/Class">
                        <xsl:if test="count(Methods/Method) &gt; 0">
                            <class name="{FullName}">
                                <xsl:variable name="className" select="FullName" />
                                <xsl:for-each select="Methods/Method">
                                    <xsl:variable name="methodName" select="Name" />
                                    <xsl:variable name="methodSignature" select="Name" />
                                    <xsl:variable name="visitedMethods" select="Summary/@visitedMethods" />
                                    <method name="{$methodName}" signature="{$methodSignature}">
                                         <seqpnt visitcount="{$visitedMethods}" />
                                    </method>
                                </xsl:for-each>
                            </class>
                        </xsl:if>
                    </xsl:for-each>
                </module>
            </xsl:for-each>
        </coverage>
    </xsl:template>
</xsl:stylesheet>
```

Here is the batch script I am running as a bamboo step.  There are two sections in `<>` that you would need to replace.  The XsltConvert.exe is a simple c# app that runs a transform (see code below).
```
rmdir /s /q "TestResults\"

md TestResults
cd TestResults
md ncover
cd ..

"./packages/OpenCover.4.6.519/tools/OpenCover.Console.exe" -target:"%PROGRAMFILES(X86)%\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"\"./<path to test dll>\" /inIsolation /Logger:trx" -output:"./TestResults/results.xml" -register:path32 -filter:"+[<include filter>*]* -[*.Tests*]*" -mergebyhash -hideskipped:Filter -returntargetcode

"./XsltConvert.exe" "./opencover_to_ncover.xslt" "./TestResults/results.xml" "./TestResults/ncover/Coverage.xml"
```

XsltConvert Code:
```
        static void Main(string[] args)
        {
            if (args.Length != 3)
                return;

            var xslDoc = new System.Xml.Xsl.XslCompiledTransform();
            xslDoc.Load(args[0]);
            xslDoc.Transform(args[1], args[2]);
        }
```
