### ISSUE TITLE
Let user choose installation path

### ISSUE THREAD

**Issue by mubed** [OpenCover/opencover#569]
Why isn't it possible to select the installation path when using the MSI installer? I need the program to be installed somewhere, all users can access it, but it's automatically installed under %appdata%, which is a folder, only current user can see!

**Comment by sawilde** [comment]
Have you tried installing it elevated?

**Comment by mubed** [comment]
Running an MSI elevated is a bit tricky (start cmd as Administrator --> run msi in cmd), but I tried it: no change.
But I found the solution myself: On the first screen there is an "Advanced" button. Clicking on that, you can set the installation folder (see figures).

Besides, I think, as the installation is a "copy deployment", you can move the folder after installation AND actually you don't need the MSI, because you can instead 
extract files from the ZIP file directly into the folder you want.

![2016-04-11 09_09_39-opencover setup](https://cloud.githubusercontent.com/assets/694738/14421523/65e5ade8-ffd2-11e5-81e2-9a18b5ebcdb9.png)
![2016-04-11 09_16_52-opencover setup](https://cloud.githubusercontent.com/assets/694738/14421655/1a14ac6a-ffd3-11e5-8010-d6a5f0aece4f.png)

**Comment by sawilde** [comment]
I forgot all about that; I don't actually use the installer myself as I always install via nuget.
