### ISSUE TITLE
Cannot get working with DNX & Appveyor

### ISSUE THREAD

**Issue by shederman** [OpenCover/opencover#573]
I have tried so many permutations and attempts, and I just cannot get OpenCover working with DNX and Appveyor. The project is at https://github.com/palantirza/Numeric/tree/develop, and it just always states that there's no results.

At wits end. Have read PDF, StackOverflow, wiki, DNX wiki entry, AppVeyor articles. Not having any joy.

**Comment by sawilde** [comment]
As far as I can tell the dnx platform is dead (retired) (https://github.com/aspnet/dnx) and so I don't feel there is much need to try and support this.

I also can't see how you have tested this locally, as that would be the expected approach before pushing it up to a build-server. If you don't have a windows environment and can only attempt to run coverage through AppVeyor then you should look to capture the `coverage.xml` as an artifact file as that carries a lot of information about what was loaded and the reasons for not instrumenting an assembly.
