### ISSUE TITLE
OpenCover Does not get executed with msbuild file

### ISSUE THREAD

**Issue by varun7447** [OpenCover/opencover#575]
OpenCover Does not get executed with msbuild file.

Issue: Opencover works fine if executed using the batch file. Same command from batch file in msbuild file takes forever to execute.

**Comment by sawilde** [comment]
please provide an example of it not working for you

**Comment by varun7447** [comment]
".\packages\OpenCover.4.5.3723\OpenCover.Console.exe" ^

-register:Administrator ^

-output:"coverage.xml" ^

-returntargetcode ^

-target:".\packages\xunit.runner.console.2.0.0\tools\xunit.console.exe" ^

-targetargs:"Moodys.ERS.RO.Core.Tests.dll -noshadow -xml xunit-results.xml"
^

-targetdir:"Moodys.ERS.RO.Core.Tests\bin\Debug" ^

-filter:"+[Moodys*]* -[Moodys.*.Tests*]* -[Moodys.*.Domain.State]*
-[*DataAccess*]* -[*Automation*]*" ^

-log:All

This works fine.. If i run the same in msbuild file it does not run the
unit tests.


<Target Name="CodeCoverage">

    <CreateItem Include="**\Bin\Debug\Company.ERS.RO.Core.Tests.dll">

      <Output TaskParameter="Include" ItemName="TestAssemblies" />

    </CreateItem>

    <PropertyGroup>

      <OpenCoverCommand>&quot;$(OpenCoverExe)&quot; -register:Administrator
&quot;-target:&quot;$(XUnitExe)&quot;&quot;
&quot;-targetargs:&quot;@(TestAssemblies,
'&quot; &quot;')&quot; -noshadow -debug -xml $(XUnitReportFile)&quot;
&quot;-filter:$(OpenCoverFilter)&quot;
&quot;-output:&quot;$(OpenCoverOutputFile)&quot;&quot;
&quot;-log:all&quot;</OpenCoverCommand>

    </PropertyGroup>

    <Message Importance="high" Text="Running code coverage with this
command: $(OpenCoverCommand)"/>

    <Exec Command="$(OpenCoverCommand)" />

  </Target>


Thanks,


Varun

**Comment by sawilde** [comment]
Hi @varun7447, we only support the latest build, please upgrade to latest and try again.

**Comment by kveretennicov** [comment]
@varun7447, amount of quotes around `-target` looks strange to me. Could you check the actual command that gets executed? For instance, with `<Message Text="$(OpenCoverCommand)" />`.

**Comment by varun7447** [comment]
Running the same command in batch file is fine..

**Comment by sawilde** [comment]
update markdown on some posts

**Comment by sawilde** [comment]
Now I can see the XML, I now may be able to help you with _your_ MSBUILD script; I am not a big user of msbuild so there may be issues in the below.

First you need to register the profiler (there is no `-register:Administrator` - hint:this will not work in the latest version) i.e. if you are doing per-user registration then you should use `-register:user` (recommended) otherwise you can use `-register` or for registry free usage `-register:path32` or `-register:path64`.

Next you only need quotes when dealing spaces in arguments and you also have too many it looks like `&quot;-target:&quot;$(XUnitExe)&quot;&quot;` should be `&quot;-target:$(XUnitExe)&quot;`.

This one makes my head hurt

    &quot;-targetargs:&quot;@(TestAssemblies,'&quot; &quot;')&quot; -noshadow -debug -xml $(XUnitReportFile)&quot;

but I believe that it should look like this assuming the entries in `TestAssemblies` and `XUnitReportFile` have no spaces

    &quot;-targetargs:@(TestAssemblies,' ') -noshadow -debug -xml $(XUnitReportFile)&quot;

Now I believe you should only need to use &quot; when trying to escape a " but I don't see any reason for you to do so e.g.

    <OpenCoverCommand>"$(OpenCoverExe)" -register:user "-target:"$(XUnitExe)" "-targetargs:@(TestAssemblies), ' ') -noshadow -debug -xml $(XUnitReportFile)" "-filter:$(OpenCoverFilter)" "-output:$(OpenCoverOutputFile)" -log:all</OpenCoverCommand>

As @kveretennicov has suggested what you should also do is dump your output and try running it manually on the command line.

**Comment by varun7447** [comment]
Thanks for your email Shaun.

Do you recommend using any other way other than msbuild? I am trying to figure out the best way to maintain. I can use batch files but trying to see if there is any other way.

**Comment by sawilde** [comment]
> Do you recommend using any other way other than msbuild?

Anything that can execute a command line - I have seen build scripts written in msbuild, nant, powershell (psake), nodejs and ruby (rake) - it is personal preference. OpenCover uses nant but that is quite old now and nowadays I use use psake on windows.

**Comment by MaceWindu** [comment]
We use OpenCover from MSBUILD for a long time. Looking at your command - you use too much quotes. Code like
```
&quot;-target:&quot;$(XUnitExe)&quot;&quot;
```
should be replaced with
```
&quot;-target:$(XUnitExe)&quot;
```
And as **kveretennicov** mentioned - look for resulting command in MSBUILD output to see where you made a mistake

**Comment by MaceWindu** [comment]
BTW, why don't you use MSBUILD OpenCover task (OpenCover.MSBuild.dll) - it is much easier to configure OpenCover using specialized task.

**Comment by varun7447** [comment]
Thanks for getting back. I am not aware of open over msbuild task. Can you guide me to any references?

**Comment by MaceWindu** [comment]
You can download latest release zip https://github.com/OpenCover/opencover/releases/tag/4.6.519
and find it in MSBuild folder (also included into OpenCover nuget package).
Attach it to your build using provided .targets file or just add line like that:
```
<UsingTask AssemblyFile="PUT_YOUR_PATH_HERE\OpenCover.MSBuild.dll" TaskName="OpenCover.MSBuild.OpenCover" />
```
 to your msbuild file.

I don't see any documentation on this task in usage.rtf/wiki, so check list of available properties here:
https://github.com/OpenCover/opencover/blob/master/main/OpenCover.MSBuild/OpenCover.cs

**Comment by sawilde** [comment]
@MaceWindu - I forgot about that task - I don't actually use it myself it was an external contribution which probably accounts for the lack of documentation - do you have any to hand we can add?

**Comment by MaceWindu** [comment]
Nope, but I could write it somewhere this week.

**Comment by sawilde** [comment]
Please do - better it is written by someone how uses it - thanks

**Comment by MaceWindu** [comment]
Please check it https://github.com/OpenCover/opencover/wiki/MsBuild-Support
Feel free to edit it as I'm not native speaker and could write something strange :)

**Comment by kveretennicov** [comment]
@MaceWindu, nice write-up. I'm not a native speaker neither, so I just changed "MsBuild" to canonical "MSBuild". Nothing else caught my eye.

**Comment by sawilde** [comment]
@MaceWindu - thanks - as I was reading the parameters piece I was thinking I hadn't thought about extending it to include some of the newer ones but I see you covered that at the end :) - I think on demand would be best as you say as I don't really know how many people use the task itself.
