### ISSUE TITLE
OpenCover suddenly reports 0% everywhere

### ISSUE THREAD

**Issue by erik-am** [OpenCover/opencover#576]
Hi,

We have a lot of different code repositories and in our CI process we use different build agents. Suddenly, since yesterday, all our build servers report 0% code coverage with OpenCover for all repositories, even for repositories where we didn't change anything.
I tried upgrading OpenCover to the latest version, that didn't help. I also tried to re-register the profiler globally, also didn't help.

In the output it says `Visited Classes 0 of X` where X is the number of test classes only, not the actual code! No coverage is reported over the actual code under test.

The strange thing is that the problem started out of the blue, without us knowingly changing any configuration. OpenCover has worked on our build agents for several months succesfully.

So now I wonder if it might be caused by a Windows Update. Therefore I'm opening this issue to find out if more people suddenly experience issues or not?

**Comment by bnm22** [comment]
I had this same issue and upgraded my OpenCover to the latest version, 4.6.519, and it seems to resolved my issues for most of my projects but one. One of my project is throwing this error: " System.InvalidProgramException : Common Language Runtime detected an invalid program." 

We are running .NET 4.6.1 and NUnit 2.6.3. I know this is only a comment but wanted to let you know.

**Comment by sawilde** [comment]
What does it say in the output file? i..e the xml file carries a lot of information.

**Comment by erik-am** [comment]
I had a look at the XML files. The only modules that are listed are Microsoft DLL's and our own Test DLL. But our application DLLs (code under test) is missing in the XML.

**Comment by sawilde** [comment]
Do you have a something I can reproduce against?

**Comment by erik-am** [comment]
I tried to create the simplest solution to trigger the behaviour, and while doing so, I think I found the root cause.

OpenCover does not seem to work when there are Fakes, generated by [Microsoft Fakes](https://msdn.microsoft.com/en-us/library/hh549175.aspx), next to the test DLLs!

Please [download this test solution](https://dl.dropboxusercontent.com/u/12332161/OpenCoverTest.zip) to see it.

* There already is a generated `coverage.xml` in the zip file. Here you can see that `Application.dll` is missing in the xml.
* You can run the powershell script `.\RunOpenCover.ps1` to run OpenCover and see the output yourself.

If you remove the Fakes from the test project _and_ manually clean up the bin\Debug folder, then it will work and report coverage.

The strange is that we've been using Microsoft Fakes for a while already, and never had problems before. I'm not sure what suddently introduced these issues. I hope that at least you can reproduce it.

**Comment by jcgillespie** [comment]
I think I'm running into the same thing.  I'm wondering if it is related to Visual Studio/TFS 2015 Update 2 (which we are using).  

From the [Update 2 Release Notes](https://msdn.microsoft.com/en-US/library/5d9d229c-b97e-47b2-9a60-947477f90211): 
>**Issue:** Code Coverage data collection for .NET code has these known limitations:
> * You cannot navigate to code when Code Coverage data collection is done together with tools that do IL rewriting (for example: Code Contracts).
> * Code Coverage data collection for .NET code cannot be used together with Fakes.

**Comment by sawilde** [comment]
Ah possibly - fakes also uses a profiler to do the faking thing and pushes OpenCover out of the way - we'll need to find out if what they are doing is different to before and see if I can intercept and hook OpenCover in again.

https://github.com/OpenCover/opencover/blob/0f406744660456ec67e4aa3a6d77d2e28a8788ee/main/OpenCover.Support/Fakes/FakesHelper.cs

**Comment by erik-am** [comment]
It's fixed in Visual Studio 2015 Update 3.

**Comment by sawilde** [comment]
awesome and I did nothing :)
