### ISSUE TITLE
OpenCover version 4.6.519 throwing System.NotSupportedException

### ISSUE THREAD

**Issue by alexsgithub** [OpenCover/opencover#577]
I am running the following command to create test coverage on my build:

D:\tfs\0Source\WAM\Dev\SOAP\Source\Iag.Wam.Asecr>C:\OpenCover\OpenCover.Console.exe -output:"%CD%\op
encover.xml" -register:user -target:"%VSINSTALLDIR%\Common7\IDE\CommonExtensions\Microsoft\TestWindo
w\vstest.console.exe" -targetargs:"Iag.Wam.Asecr.Tests\bin\Debug\Iag.Wam.Asecr.Tests.dll"

The results are below:

"At: Program.Main
An System.NotSupportedException occured: The given path's format is not supported.
stack:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights,
Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAt
trs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at OpenCover.Framework.Persistance.FilePersistance.<>c__DisplayClass1.<Initialise>b__0() in c:\pr
ojects\opencover\main\OpenCover.Framework\Persistance\FilePersistance.cs:line 50
   at OpenCover.Framework.Persistance.FilePersistance.HandleFileAccess(Action loadFile, String fileN
ame) in c:\projects\opencover\main\OpenCover.Framework\Persistance\FilePersistance.cs:line 59
   at OpenCover.Console.Program.Main(String[] args) in c:\projects\opencover\main\OpenCover.Console\
Program.cs:line 67
A report has been sent to the OpenCover development team.
If you are unable to resolve the issue please contact the OpenCover development team
see https://www.github.com/opencover/opencover/issues
Failed to send crash report :( "

Thank you for your help!

**Comment by sawilde** [comment]
There is a drdump report on this just recently 90% coming from one user.

Tested that the issue is not related to environment variable expansion - well it works locally.

Changing output to publish the received path as part of the exception handling
