### ISSUE TITLE
No coverage reported when running tests via xUnit console

### ISSUE THREAD

**Issue by jdhuntington** [OpenCover/opencover#581]
I suspect I may be making an error configuring opencover, but I'm unable to determine where.

### Goal
Run xUnit tests with `xunit.runner.console` and generate accurate coverage report.

### Expected
In the project https://github.com/jdhuntington/upgraded-garbanzo , running `.\Run-Coverage.ps1` in the root of the project (after building) should show some coverage details for both invocations of `OpenCover.Console.exe`.

### Actual
The first invocation of `OpenCover.Console.exe` (which runs a simple program `CoverageInvestigation.exe`) shows accurate results.

    Committing...
    Visited Classes 1 of 1 (100)
    Visited Methods 4 of 5 (80)
    Visited Points 18 of 24 (75)
    Visited Branches 5 of 7 (71.43)
    
    ==== Alternative Results (includes all methods including those without corresponding source) ====
    Alternative Visited Classes 1 of 1 (100)
    Alternative Visited Methods 4 of 5 (80)

The second invocation (which runs xUnit) shows no methods have been called.

    Committing...
    Visited Classes 0 of 1 (0)
    Visited Methods 0 of 1 (0)
    Visited Points 0 of 4 (0)
    Visited Branches 0 of 1 (0)
    
    ==== Alternative Results (includes all methods including those without corresponding source) ====
    Alternative Visited Classes 0 of 1 (0)
    Alternative Visited Methods 0 of 2 (0)

I'd like to know if I'm simply incorrect in invoking `OpenCover` with the following command, or if there are issues when running opencover and xUnit together.

    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"CoverageInvestigation.Test\bin\Debug\CoverageInvestigation.Test.dll" -output:"nocoverage.xml"

**Comment by sawilde** [comment]
What does it say in the XML as to why the dll was 'skipped'?

**Comment by jdhuntington** [comment]
Ah-ha, it was missing the information on the PDB location. Thank you - somehow I missed searching for the right property in the XML. I will close this issue; thanks very much for the help!

For reference, here are the two XML files that were generated:
https://gist.github.com/jdhuntington/1646a4c172b63a85c6a80663dbf53b48

And the fix for my test harness is:
https://github.com/jdhuntington/upgraded-garbanzo/commit/d4f00bd8d716117d3332d5de75305a457d2bbecd

**Comment by UlyssesAlves** [comment]
Like [SebastianStehle said](https://github.com/OpenCover/opencover/issues/544#issuecomment-183362748), you need to use xUnit's parameter -noshadow to solve the problem of zero coverage in OpenCover report.

**Comment by gouraharidas** [comment]
Thanks @UlyssesAlves.
-noshadow argument in xunit helped me to get correct coverage.
