### ISSUE TITLE
Mono in VS2015

### ISSUE THREAD

**Issue by Yefimov** [OpenCover/opencover#583]
How i can add Mono.Cecil? I see it in \opencover-master\tools\, but don't know, how to solve the problem when my VS2015 "can't find type or name from namespace Mono"

![image](https://cloud.githubusercontent.com/assets/16087064/14915362/0873ef06-0e1b-11e6-9aef-4a052d76ce59.png)

I can't find the solution of this problem in **Usage**.

**Comment by sawilde** [comment]
Are you looking to build OpenCover or just use it?

For building OpenCover you should use the instructions in the [readme](https://github.com/OpenCover/opencover#building)

To use OpenCover then you can use one of the packages e.g. [nuget](https://www.nuget.org/packages/opencover) or from the [releases](https://github.com/OpenCover/opencover/releases)

**Comment by sawilde** [comment]
Hi - do you need any more information?

**Comment by sawilde** [comment]
I was going to say surely that is just add reference but I realised that it can't be something so trivial - I am currently working on upgrading the VS2015 and came across the same issue - not matter what I tried I couldn't get it to load properly in VS2015. I have a workaround and I will push once I have resolved some of the other issues I encountered whilst retooling - until then VS2013 is probably the best choice.

**Comment by Yefimov** [comment]
I tried to reinstall or to restore VS2015 and some tools from **usage**.  I asked my friends, but they have this issue too. 

> I will push once I have resolved some of the other issues I encountered whilst retooling - until then VS2013

I think that's a good idea.

**Comment by sawilde** [comment]
The code is now building in VS2015
