### ISSUE TITLE
Coverage results generated by Visual Studio is different than OpenCover one

### ISSUE THREAD

**Issue by shanishiri** [OpenCover/opencover#584]
Hi,
I’m having issue with OpenCover. I'm using the code coverage xml for SonarQube analysis and i can see large differences between OpenCover results (14.66%) and VS2012 coveragexml (85.85%).  
_The command line I’m using is:_
 C:\OpenCover\OpenCover.Console.exe -register:user -output:"{Bin}\..\Source\opencover.xml" -target:"C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\MSTest.exe" /nologo /usestderr -mergebyhash -targetargs:"/testSettings:{Bin}\..\Source\Local.testsettings /resultsfileroot:{Bin}\..\..\TestResults /testcontainer:{Bin}\..\TestingTools\FlowBuilderTest\FlowBuilderTest\bin\Release\FlowBuilderTest.dll

Any idea what I’m doing wrong here?

**Comment by sawilde** [comment]
First you need to visualize your results - I use [ReportGenerator](https://www.nuget.org/packages/ReportGenerator) for this.

Then you can see what assemblies are being covered and which are not. 

If an assembly is not being covered that you expect you can look in the xml as to the reason the assembly was skipped; most common reasons are _filters_ or _missingpdb_.

If _filters_ then you need to loo into adding/removing filters using the _-filters:_ argument. If missingpdb then you can look into adding more search locations either through _-targetdir:_ or _-searchdirs:_ arguments.

**Comment by shanishiri** [comment]
Hi,
I download ReportGenerator and use it as you recommended and also used -filters: argument. OpenCover's results seems better now, just that on the ReportGenerator i get 33%, but SonarQube keeps showing 8.6%. Is it SonarQube issue?

**Comment by shanishiri** [comment]
I can see that OpenCover report include the unit test dll's for summary coverage, while in SonarQube it does'nt.

**Comment by sawilde** [comment]
All depends on your filters, its quite common to exclude test assemblies from coverage reports.

**Comment by shanishiri** [comment]
o.k, so now I exclude test assemblies and I still see differences with VS analysis. There are methods that on openCover xml I can see that was not been visited ( visited="false") and mark with 0% for coverage, but on VS the same methods has coverage percentage. Do you know why is that?

**Comment by sawilde** [comment]
no I don't 

I don't know what your code or tests looks like and I don't use the visual studio coverage, you 'll have to investigate this one yourself.

**Comment by shanishiri** [comment]
Hi Shaun,
I solved the issue with using  /noisolation switch and edit my .testsettings file so it will not include code coverage diagnostic. 
Thanks for your help :)

**Comment by sawilde** [comment]
:+1: - I'll try and keep that in mind and add it to some notes for the next person

**Comment by prakashorton** [comment]
hi 

need your in resolving below issue

[https://github.com/OpenCover/opencover/issues/901](Opencover Issue)
