### ISSUE TITLE
Exclude ExcludeFromCodeCoverageAttribute by default?

### ISSUE THREAD

**Issue by pontusi** [OpenCover/opencover#585]
The `excludebyattribute` flag is very useful, but I also like when command line tools require as few arguments as possible to give good default results. I suggest adding a default attribute filter for the `System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute` attribute, when the `nodefaultfilters` flag is not set.

I admit that this will not help those projects that have their own custom `ExcludeFromCodeCoverageAttribute`. Maybe filter out any attribute named `ExcludeFromCodeCoverageAttribute` regardless of namespace, but that is a bit bolder.

This will also break backwards compatibility, but not in a horrible way: I don't think many users rely on members decorated with `System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute` to be included in coverage analysis.

**Comment by sawilde** [comment]
I like the idea but I'd like to hear if there is any feedback on any potential issues on this change before enacting it.

**Comment by sawilde** [comment]
I am still not convinced this is a good idea as I would then have to supply a way to re-include code excluded by default; this is so that people can get an idea of raw coverage vs coverage (w/ excluded).

**Comment by zabulus** [comment]
IMHO, it is better to add to manual a sample about adding ExcludeFromCodeCoverageAttribute to exclude in command line (in case it is not there yet) and leave everything as is.
I'm using ExcludeFromCodeCoverageAttribute, but I haven't experienced any problems with figuring out how to add it to filter.

**Comment by sawilde** [comment]
I've decided it's not really needed as the work to turn it off outweighs the gains
