### ISSUE TITLE
MSBuild task forces to register openCover in registry

### ISSUE THREAD

**Issue by hkoestin** [OpenCover/opencover#588]
Dear all

When running the MSBuild task of openCover from the Nuget folder, I get the error, that I have to install openCover and register it within the registry. Why is this enforced?

Is there a way around this, to run the MSBuild task without having to install openCover on the machine or registering it with the reg-edit?

I am using the task like this:
```xml
<UsingTask AssemblyFile="$(Nuget_OpenCover)\MSBuild\OpenCover.MSBuild.dll" TaskName="OpenCover.MSBuild.OpenCover" />
```

Running it later on produces the error:

> error : Could not find OpenCover installation registry key. Please install OpenCover or repair installation.

Thanks for any advice!

Harald

**Comment by sawilde** [comment]
have a look at the register option in https://github.com/OpenCover/opencover/wiki/MsBuild-Support

**Comment by hkoestin** [comment]
@sawilde already tried this. does not work either. you can have a look at the OpenCover MSBuild Task implementation. The Register flag does not change anything in the behavior of the method `GenerateFullPathToTool`. It will still throw. Is this behavior the intended one?

compare the following 

```c#
RegistryKey key=null;

string[] keyNames=new string[] { _OpenCoverRegKey, _OpenCoverRegKeyWow6432 };
foreach (string kn in keyNames)
{
     key=Registry.CurrentUser.OpenSubKey(kn);
     if (key!=null)
           break;

    key=Registry.LocalMachine.OpenSubKey(kn);
    if (key!=null)
           break;
}

if (key==null)
{
     Log.LogError("Could not find OpenCover installation registry key. Please install OpenCover or repair installation.");
     return null;
}
```

**Comment by sawilde** [comment]
As I understand it if you are not going to register the dll so it can be discovered via the registry then you need to provide the path yourself using ToolPath and ToolExe

**Comment by sawilde** [comment]
Do you still require any help?
