### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by sawilde** [OpenCover/opencover#595]
https://github.com/dotnet/corefx/issues/8880

> @sawilde, does OpenCover have a hard dependency on mscorlib.dll being named "mscorlib"? The core library has been renamed for .NET Core from "mscorlib" to "System.Private.Corelib", and I'm wondering if that change explains why OpenCover is reporting 0 hits on everything.

So we need to add hooks for that assembly name in [CuckooSupportCompilation](https://github.com/OpenCover/opencover/blob/0f406744660456ec67e4aa3a6d77d2e28a8788ee/main/OpenCover.Profiler/CodeCoverage_Cuckoo.cpp#L211).

**Comment by sawilde** [comment]
They are currently using the `-oldstyle` switch - which seems to be working for them

**Comment by joemcbride** [comment]
Question on this - is the .NET Core support going to be only Windows, or also support macOS, Linux, etc.?  Thanks!

**Comment by sawilde** [comment]
@joemcbride currently it is windows only because we really on the profiling API which is COM based (an ancient technology in modern IT terms that I cut my teeth on in my youth). 

There is this thread on the .net core clr repo regarding the [Profiling API]( https://github.com/dotnet/coreclr/issues/445) that I am keeping my eye on but until they release it xplat (the release keeps shifting) I am unable to do anything with that.

**Comment by joemcbride** [comment]
Drats, well here's to hoping.  Thanks!

**Comment by JSkimming** [comment]
> an ancient technology in modern IT terms that I cut my teeth on in my youth

@sawilde Stop it, you're making me nostalgic for those days back in Henley-on-Thames 😃

**Comment by psibernetic** [comment]
@sawilde https://github.com/dotnet/coreclr/issues/15136 and https://github.com/noahfalk/coreclr/blob/master/Documentation/project-docs/profiling-api-status.md now list Linux as working, so might you might check that.

**Comment by sawilde** [comment]
@psibernetic I have been looking at it - the windows one took months of part-time development - so don't expect anything soon - it isn't a simple port.

**Comment by jp7677** [comment]
Hi there. I'm using an appveyor build of OpenCover with a Mono.Cecil beta that works pretty well for Netcore with portable debug symbols. I can fully understand though that you prefer to wait for a final release of Mono.Cecil before doing a release for OpenCover again. That said I'm not sure anymore that Mono.Cecil will ever come out of beta. Is there an alternative in that case?

**Comment by sawilde** [comment]
@jp7677 I don't have one as yet - I've been looking at starting again using the new profiler APIs that come with .net core but I just don't have the time at the moment.

**Comment by sharwell** [comment]
@sawilde Mono.Cecil 0.10 was just released with support for portable PDB formats. 😄

**Comment by danmosemsft** [comment]
In the .NET Core repos, we are eager to move to an OpenCover that supported portable PDB

**Comment by sawilde** [comment]
YES! I've sort of stopped looking!

@sharwell hopefully both - though I may need to tinker with how I use mono.cecil - got easter break coming up so will hopefully find a few days over that period - pray for rainy weather!

**Comment by danmosemsft** [comment]
Any luck over Easter @sawilde ?

**Comment by sawilde** [comment]
We can handle .net core but the support has been patchy with what looks like the PDBs changing format.

Portable and Embedded works with .net 2.2  using the -oldstyle switch - I suspect this is because the Cuckoos aren't loading

**Comment by sawilde** [comment]
We get coverage from .net core 2.2 and .net core 3.1 using the -oldstyle switch and .net 5.0 with or without that switch

Try the release candidate 4.7.1137-rc or a later build
