### ISSUE TITLE
OpenCover not working with VSTest.console.exe when using runsettings

### ISSUE THREAD

**Issue by a2kcollett** [OpenCover/opencover#597]
Hello,

I am having an issue getting OpenCover to report the correct coverage when using runsettings.

If I run OpenCover with VStest it works fine however it reports coverage against everything.

If I use /Settings:example.runsettings it then reports that nothing is covered.

The main difference I see is when I run without runsetting there is no mention of a .coverage file being created however when using runsettings it says a .coverage file was created in TestResults/

The end result is I am trying to upload these into SonarQube. I am unsure if I need to add something special in runsettings to make this work with OpenCover but has anyone been able to get OpenCover working with VSTest and using runsettings not testsettings?

**Comment by sawilde** [comment]
When using OpenCover you need to disable any other coverage utility as they will not play nicely with each other; if you have the ability to get vstest producing coverage data then you probably don't need OpenCover.

**Comment by sawilde** [comment]
@a2kcollett - do you require any further help?

**Comment by reyou** [comment]
Hello @sawilde.
I am following this documentation https://docs.sonarqube.org/pages/viewpage.action?pageId=6389770 and as it was mentioned, .coverage file does not show anything.

I am getting following output;

> Executing: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\
> Microsoft\TestWindow\vstest.console.exe
> Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> Passed   DoWorkTest
> Passed   GiveLenghtTest
> Passed   GiveLenghtTestFails
> 
> Total tests: 3. Passed: 3. Failed: 0. Skipped: 0.
> Test Run Successful.
> Test execution time: 0.2960 Seconds
> Committing...
> No results, this could be for a number of reasons. The most common reasons are:
>     1) missing PDBs for the assemblies that match the filter please review the
>     output file and refer to the Usage guide (Usage.rtf) about filters.
>     2) the profiler may not be registered correctly, please refer to the Usage
>     guide and the -register switch.

Do you have any clue on this?

**Comment by reyou** [comment]
I am running program from visual studio, it looks like ProfileManager.cs/SaveVisitData() method does not collect data from vstest.console.exe.

When I check folder inside 

> C:\Programs2\opencover-master\main\bin\Debug\TestResults 

I can see generated folders and .coverage file. This coverage file is a valid file for VS 2015, I can open and see the results. But converted .xml file is empty like below;

```
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="4.6.0.0">
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" maxCrapScore="0" minCrapScore="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>
```

I can confirm also ProfilerRegistration.cs/ExecuteRegsvr32() works fine with me (profile user for 64 bit). Because process results as 0 (success).

Not sure how far I can go ahead, or supply more information. I will try to debug more, hope will find more useful information.

**Comment by sawilde** [comment]
If you are on a build box then you should look to either pre-registering the profilers (see wiki/docs) or using  `-register:path32` or `-register:path64` as appropriate.

If I can't repeat it then I can't help but guess.

**Comment by reyou** [comment]
Thanks @sawilde. I tried many ways, from command prompt (as admin) from powershell ise (as admin) and directly running the console app from Visual Studio passing main[] parameters manually. For all of them I registered Profiler binary before I run. I also checked ExecuteRegsvr32() runs before codecoverage begins, and it is successfully registering the profiler.

I will try to attach sample project for you to download. For now I have following specs;

1- Windows 10 machine (64 bit)
2- VS 2015 enterprise (ide version 14)
3- Target app is Console App / Unit Tests with framework 4.5
4- .coverage binary file generates good (VS 15 can open) but generated report.xml is empty.
5- Sample project will be attached.

**Comment by reyou** [comment]
Hello @sawilde,
Please see this sample project;
https://github.com/reyou/OCoverSampleCons

If you just run following powershell script;
https://github.com/reyou/OCoverSampleCons/blob/master/powershell/OpenCover.ps1

(Please only change $projectRoot parameter to point root of the project)

You might be getting same error as I am getting as below;

![image](https://cloud.githubusercontent.com/assets/6571483/24371876/426f4978-12fa-11e7-8c3d-95593c21191a.png)

Could you please suggest if I am missing something? 

Output xml I am getting at "C:\Temp\OCoverSampleCons\opencover-output"

`<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="4.6.0.0">
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" maxCrapScore="0" minCrapScore="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>`
