### ISSUE TITLE
Coverage is not being generated on CI server

### ISSUE THREAD

**Issue by Haythem** [OpenCover/opencover#602]
**Hello,**

I have an Azure Virtual Machine that I've set up as a build server. The machine is a Windows Server 2012 R2 Datacenter. I've installed OpenCover and added it to the `PATH`.

On the other hand I have a [gitlab-runner](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner) installed as a windows service on my virtual machine and running with the `Local System Account`.

The gitlab-ci.yaml contains a job that should restore dependencies using `dotnet restore` (dotnet core RC2 project) and calculate the coverage using the following command :

`opencover.console -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test test/MyProject.Test" -output:"coverage.xml"`

Once triggered, I got the following :
`Committing...
No results, this could be for a number of reasons. The most common reasons are:  
    1) missing PDBs for the assemblies that match the filter please review the output file and refer to the Usage guide (Usage.rtf) about filters.  
    2) the profiler may not be registered correctly, please refer to the Usage guide and the -register switch.`

I tried adding `-searchdirs:"test/MyProject.Test/bin/Debug/netcoreapp1.0` but with no luck.

Trying to figure out why it's behaving like that, I cloned the project on the same virtual machine and ran the same command from above and my coverage was generated.

Any ideas please ? :smile: 

Thanks in advance

**Comment by Haythem** [comment]
**Hi again,**

The problem is now solved. It appeared that the `gitlab-runner` Windows service running under the `Local System Account` was causing the problem. I changed the user and the problem just vanished.

I'm closing this down and I'll blog about mounting a minimal CI server with open cover for private projects.

**Comment by sawilde** [comment]
:+1:
