### ISSUE TITLE
Outdated chocolatey package

### ISSUE THREAD

**Issue by Roemer** [OpenCover/opencover#603]
Hello
Your chocolatey package (https://chocolatey.org/packages/OpenCover) is outdated. Do you plan on updating it? Since it is outdated, I created an updated portable package for it (https://chocolatey.org/packages/opencover.portable). If you want, I could also take over the OpenCover chocolatey package as additional maintainer and keep it updated. If that would be ok for you, can you add me as maintainer on chocolatey?
Thanks

**Comment by sawilde** [comment]
Thanks - I actually didn't create that package and only recently got myself added to it so I could maintain it with the rest of the releases to try and avoid these situations.

That would be awesome if you want o be involved and help me get this all automated like we do with the nuget package(s)

**Comment by Roemer** [comment]
I have already created the packages here: https://github.com/Roemer/Chocolatey-Packages
So either just add me as maintainer on chocolatey or add my package to opencover source (and maybe grant me push rights). I'll keep it updated then.

**Comment by sawilde** [comment]
> So either just add me as maintainer on chocolatey or add my package to opencover source

To submit to OpenCover initially we take things as pull requests 

To add this so it is dynamic we would need to parameterize the powershell scripts before we packaged it and then use the build to update the script.

The build can then push to chocolatey during a release cycle

**Comment by Roemer** [comment]
I found a blog where someone more or less does it: https://gripdev.wordpress.com/2015/04/08/appveyor-github-and-chocolatey-automatically-build-your-project-and-publish-updates-it-to-chocolatey/

There are also plenty of other projects which already do this (googling "appveyor choco pack" finds those). A good example seems to be: https://github.com/RaYell/choco-sim/blob/master/appveyor.yml

Will you have a look at it or should I investigate further? Would be great to have that package updated soon.

**Comment by sawilde** [comment]
It all depends on your timescales

**Comment by sawilde** [comment]
we have out first package - https://ci.appveyor.com/project/sawilde/opencover/build/4.6.576/artifacts

unfortunately we don't have a matching msi to go with it yet - will need to wait until we make a new release

**Comment by Roemer** [comment]
Will you also add the "portable" version (see https://chocolatey.org/packages/opencover.portable)? I could add you as maintainer then on chocolatey so you can directly reuse this package.

**Comment by sawilde** [comment]
Okay, but why would I use one over the other? Sorry not a big chocolatey user.

**Comment by Roemer** [comment]
The portable one does get installed directly into the chocolatey data directory and not into the program files. Therefore it can be easier to install (needs less rights) and also to remove (only this folder inside chocolatey needs to be removed).

**Comment by sawilde** [comment]
okay, should be simple enough to do.

**Comment by Roemer** [comment]
I added you as maintainer for opencover.portable on chocolatey. You can remove me as maintainer if you want.

**Comment by sawilde** [comment]
see build - https://ci.appveyor.com/project/sawilde/opencover/build/4.6.581
