### ISSUE TITLE
Common language runtime issue when injecting endjointpoint before the return instructions

### ISSUE THREAD

**Issue by Anbu2388** [OpenCover/opencover#611]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [X] .NET 2
- [X] .NET 3.5
- [X] .NET 4
- [X] .NET 4.5
- [X] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [X] Windows 8
- [X] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [x] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

When the method has try-catch I'm getting this problem.
End joint point will be the managed method call. It should be called when the instrumented method call happen.

### Actual Behavior

Common language runtime found invalid program error.

### Steps to reproduce the problem:

Create a method with try-catch. For example as follows,

    public void GetSalaryTemp()
        {
            try
            {
                if (Request.QueryString["id"] != null)
                {
                    string id = Request.QueryString["id"].ToString();
                    if (id == "1")
                    {
                        Response.Write("ID = 1");
                        return;
                    }
                    else if (id == "2")
                    {
                        Response.Write("ID = 2");
                        return;
                    }
                }
            }
            catch
            {
            }
        }

I'm using Method.cpp class for injecting the end instruction before return instructions. When injecting the endjoint point with last return instruction, I'm getting this error.

Note: The method I'm using : InsertSequenceInstructionsAtOffset(long offset, InstructionList &instructions)

Please let me know if need any clarifications.

**Comment by sawilde** [comment]
It looks like you are having problems with code you have taken from OpenCover to do your own custom instrumentation, so you will need to: 

1. describe more about what you are trying to do
2. what the IL looks like before you instrument it
3. what the IL you are trying to introduce does and what it looks like
4. what the IL looks like after instrumentation

**Comment by sawilde** [comment]
Hi, do you still need any help with this?

**Comment by Anbu2388** [comment]
Sorry for the delay response.

My own custom instrumentation is like adding our managed method call reference into starting and ending of a method by IL injection.

1. Using your Method.cpp methods I will read the IL instructions.
2. Then add my own start IL instructions at offset 0 and end IL instructions at before return(ret) instructions.
3. Then using the SetILFunctionBody I'll rewrite the IL code.

Before the instrumentation the IL code for my method is,
===============================================================
.method public hidebysig 
	instance void GetSalaryTemp () cil managed 
{
	// Method begins at RVA 0x28e0
	// Code size 28 (0x1c)
	.maxstack 2

	.try
	{
		IL_0000: ldarg.0
		IL_0001: call instance class [System.Web]System.Web.HttpResponse [System.Web]System.Web.UI.Page::get_Response()
		IL_0006: ldstr "test test test GetSalaryTemp"
		IL_000b: callvirt instance void [System.Web]System.Web.HttpResponse::Write(string)
		IL_0010: leave.s IL_0015
	} // end .try
	catch [mscorlib]System.Object
	{
		IL_0012: pop
		IL_0013: leave.s IL_0015
	} // end handler

	IL_0015: ldsfld string [mscorlib]System.String::Empty
	IL_001a: pop
	IL_001b: ret
} // end of method _Default::GetSalaryTemp
============================================================
After instrumentation, the IL code is as follows,

IL_0000 ldarg.0                       //1. this object to be paased in first param of my method

IL_0001 ldstr (70)000104        //2. method name to be paased in second param of my method

IL_0006 ldstr (70)000142        //3. my own string to be paased in third param of my method

IL_000B call (0A)000020         //4. My start method call

IL_0010 ldarg.0

IL_0011 call (0A)000016

IL_0016 ldstr (70)0000C7

IL_001B callvirt (0A)000017

IL_0020 leave IL_002B

IL_0025 pop

IL_0026 leave IL_002B

IL_002B nop                           //5. Adding nop before end method call

IL_002C call (0A)000021        //6. My end method call added before return

IL_0031 ret

The following static methods are in C# managed dll loaded in GAC.
MethodTrackerFactory.StartPoint(object thisObj, object methodName, object context)
MethodTrackerFactory.EndPoint()


The same method is working for 32 bit process. 
Getting "Common Language Runtime detected an invalid program." for 64 bit process.

I suspect is there any pointer related issue. Or What could be the reason when it is working for 32 bit and not working for 64 bit.

Thanks in advance.

**Comment by sawilde** [comment]
What do the the exception handler entries look like after the IL has been inserted?

**Comment by Anbu2388** [comment]
-----------------------------------------------------------------------------------
BEFORE INSTRUMENTATION,
IL_0000 ldarg.0
IL_0001 call (0A)0000DF
IL_0006 ldstr (70)0008D8
IL_000B callvirt (0A)0000E0
IL_0010 leave IL_001B
IL_0015 pop
IL_0016 leave IL_001B
IL_001B ret
Section 0: 0 0000 0015 0015 001B 0000 01000014            //Exception handler list 
-------------------------------------------------------------------------------------------
AFTER INSTRUMENTATION
IL_0000 ldarg.0                                                    //Newly added ins
IL_0001 ldstr (70)003B6C                                     //Newly added ins
IL_0006 ldstr (70)003B5E                                     //Newly added ins
IL_000B call (0A)00034A                                      //Newly added ins
IL_0010 ldarg.0
IL_0011 call (0A)0000DF
IL_0016 ldstr (70)0008D8
IL_001B callvirt (0A)0000E0
IL_0020 leave IL_002B
IL_0025 pop
IL_0026 leave IL_002B
IL_002B nop                                                 //Newly added ins
IL_002C call (0A)00034B                              //Newly added ins
IL_0031 ret
Section 0: 0 0000 0025 0025 0031 0000 01000014                                      //Exception handler list
--------------------------------------------------------------------------------------------------

The line section is got from DumpIL method in method.cpp file.
The syntax is Section 0: handlerType tryStart tryEnd handlerStart handlerEnd filterStart m_token

Please assist me what will be the issue.

**Comment by sawilde** [comment]
Okay I think the catch handler is incorrect, I think it should be

    Section 0: 0 0000 0025 0025 002B 0000 01000014 //Exception handler list

You may need to work with the code taken from OpenCover to get it to produce the IL you need.

**Comment by Anbu2388** [comment]
Awesome @sawilde. It works... Thanks a lot.

**Comment by sawilde** [comment]
What did you do to change the code to make it work?

**Comment by Anbu2388** [comment]
I have set the newly added instruction nop(IL_002B ) to tryHandlerEnd instruction. Then it is solved. 

Although I'm getting "Common language runtime error" and "JIT Compiler encountered an internal limitation" for many framework(Ex: All methods in System.Data.SqlClient) related methods. I think this injection on return statements will not be feasible.

I have an idea like adding try-finally block in all the methods, and adding the new end method call instruction in finally block. I think this can be possible via adding exception handler instruction in a method IL.

What about your thought on this? Or Do you have any other idea to achieve this?

@sawilde

**Comment by sawilde** [comment]
okay
