### ISSUE TITLE
NUnit 3.4.1 Where functionality not working

### ISSUE THREAD

**Issue by sflanders** [OpenCover/opencover#614]
It appears open cover has issues with the syntax used for the where clause in NUnit 3.4.1.   I will only work properly with a few very simple variations.   Once you introduce anything with spaces it will break even when using the delimiters ask for.   I'm hoping there is an escape character i can apply to the string to make sure opencover doesn't trip over it.

https://github.com/nunit/docs/wiki/Test-Selection-Language

works
--where="cat!='Category1'"

doesn't work
--where="cat != 'Category1'"
--where="cat!='Category 1'"
--where="cat != 'Category1' && cat != 'Category3'"
--where="cat != 'Category 1' && cat != 'Category3'"
...

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [X] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [X] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

It should be taking that where text and filtering the tests accordingly

### Actual Behavior

It appears its incorrectly parsing my arguments for nunit 3.4.1 and causing it to break

Here's the kind of errors you will see:

c:\Projects\DevOps\Build.Scripts\Source>"C:\Projects\DevOps\Build.Scripts\Source
\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe" -returntargetcode -outp
ut:"C:\Projects\DevOps\Build.Scripts\Source\Tests\nunittestrunnertestoutput\Open
CoverResult.xml" -register:user -filter:"" -excludebyattribute:*.ExcludeFromCode
Coverage* -target:"C:\Projects\DevOps\Build.Scripts\Source\packages\NUnit.Consol
eRunner.3.4.1\tools\nunit3-console.exe" -targetargs:""C:\Projects\DevOps\Build.S
cripts\Source\Tests\nunittestrunnertestoutput\_PublishedApplications\SonarQubeDu
mmyNUnit2Test\SonarQubeDummyNUnit2Test.dll"  --where="cat != 'Category1'"  --fra
mework="net-4.5" --process=Multiple --dispose-runners --result="C:\Projects\DevO
ps\Build.Scripts\Source\Tests\nunittestrunnertestoutput\NUnitResult.xml""

Incorrect Arguments: The argument '!=' is not recognised

Usage:
    ["]-target:<target application>["]
    [["]-targetdir:<target directory>["]]
    [["]-searchdirs:<additional PDB directory>[;<additional PDB directory>][;<ad
ditional PDB directory>]["]]

### Steps to reproduce the problem:

"OpenCover.Console.exe" -returntargetcode -output:"C:\yourpath\OpenCoverResult.xml" -register:user -filter:"" -excludebyattribute:*.ExcludeFromCodeCoverage* -target:"nunit3-console.exe" -targetargs:""C:\yourpath\SonarQubeDummyNUnit2Test.dll" --where="cat != 'Category1'"  --framework="net-4.5" --process=Multiple --dispose-runners --result="C:\yourpath\NUnitResult.xml""

**Comment by sawilde** [comment]
> [x] reviewed the usage guide and usage document.

If you read the usage wiki `usage.pdf` you will see that we do support `\"` as an escape sequence

**Comment by sflanders** [comment]
I had tried using that several different ways but it never seemed to help.   I even tried escaping every character within the --where="?"

**Comment by sawilde** [comment]
try

    "-targetargs:\"C:\yourpath\SonarQubeDummyNUnit2Test.dll\" --where=\"cat != 'Category1'\" --framework=\"net-4.5\" --process=Multiple --dispose-runners --result=\"C:\yourpath\NUnitResult.xml\""

or even

    "-targetargs:C:\yourpath\SonarQubeDummyNUnit2Test.dll --where=cat!=Category1 --framework=net-4.5 --process=Multiple --dispose-runners --result=C:\yourpath\NUnitResult.xml"

**Comment by sflanders** [comment]
So i decided to debug against open cover source directly.   Guess that needs two sets of double quotes for the string[] args thing to parse it properly.   so: --where=""blah blah"", instead of: --where="blah blah", or --where=\"blah blah\".   i think i've ran into that before but its hard to know thats the problem.   Is there a flag that can be turned on that will dump out the received args?

**Comment by sawilde** [comment]
I wouldn't debug against source directly, I would instead [write a test](https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Test/Framework/CommandLineParserTests.cs) and then debug/resolve using that.

**Comment by sflanders** [comment]
I just meant i pulled the source down to see how parameters are parsed.   The data was already bad before it even gets to your command parser.   Needless to say my issue is resolved, just took a little digging.  Thanks for the suggestions.

**Comment by sawilde** [comment]
And your solution was for the benefit of anyone else who might have the same issue?

Is there a way we could improve the documentation perhaps?

**Comment by sflanders** [comment]
Yes.  So this is one of those weird things with how the "**Main([string] args)**" parameter parses out each parameter.   Without the 2 sets of double quotes those expressions will cause them to be parsed out as separate parameters, which basically breaks the execution.  Thats why i mentioned it would be cool if the program dumped out what it detected as the raw params.  Its hard sometimes to tell without spinning up a dummy console app to see the issue.
