### ISSUE TITLE
Asynchronous Threading problem when injecting IL of System.Web.Mvc.Controller.BeginExecute method

### ISSUE THREAD

**Issue by Anbu2388** [OpenCover/opencover#616]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [X] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

The instrumented begin method and end method will be called.

### Actual Behavior

Page getting crashed with the error "A single instance of controller 'System.Web.Mvc.Controller+<>c__DisplayClass19' cannot be used to handle multiple requests. If a custom controller factory is in use, make sure that it creates a new instance of the controller for each request."

### Steps to reproduce the problem:

Inject the method "System.Web.Mvc.Controller.BeginExecute" by adding start method call in beginning of method and endjointpoint at before return instructions. It works for all the method in this controller class except this one.

The injected method IL has been given below,

IL_0000 ldarg.0	<--------------------------------Newly Added

IL_0001 ldstr (70)005BF3		                                                       <--------------------------------Newly Added

IL_0006 ldstr (70)000896		                                                      <--------------------------------Newly Added

IL_000B call (0A)000848			                                              <--------------------------------Newly Added

IL_0010 ldnull

IL_0011 stloc.3

IL_0012 newobj (06)000F38

IL_0017 stloc.s 04

IL_0019 ldloc.s 04

IL_001B ldarg.1

IL_001C stfld 040004AA

IL_0021 ldloc.s 04

IL_0023 ldarg.0

IL_0024 stfld 040004A9

IL_0029 ldarg.0

IL_002A callvirt (06)00054B

IL_002F brfalse IL_005E

IL_0034 ldloc.3

IL_0035 brtrue IL_0048

IL_003A ldloc.s 04

IL_003C ldftn (06)000F39

IL_0042 newobj (0A)000077

IL_0047 stloc.3

IL_0048 ldloc.3

IL_0049 stloc.0

IL_004A ldarg.2

IL_004B ldarg.3

IL_004C ldloc.0

IL_004D ldsfld 040001A2

IL_0052 call (06)00050C

IL_0057 nop					                                      <--------------------------------Newly Added

IL_0058 call (0A)000849				                             <--------------------------------Newly Added

IL_005D ret

IL_005E ldloc.s 04

IL_0060 ldfld 040004AA

IL_0065 brtrue IL_0075

IL_006A ldstr (70)0005E8

IL_006F newobj (0A)00005D

IL_0074 throw

IL_0075 ldarg.0

IL_0076 ldarg.0

IL_0077 ldloc.s 04

IL_0079 call (06)00053F

IL_007E ldfld 040004AA

IL_0083 callvirt (06)00053E

IL_0088 ldsfld 040001AC

IL_008D brtrue IL_00A3

IL_0092 ldnull

IL_0093 ldftn (06)0005CF

IL_0099 newobj (0A)0004C2

IL_009E stsfld 040001AC

IL_00A3 ldsfld 040001AC

IL_00A8 stloc.1

IL_00A9 ldsfld 040001AD

IL_00AE brtrue IL_00C4

IL_00B3 ldnull

IL_00B4 ldftn (06)0005D0

IL_00BA newobj (0A)0004C3

IL_00BF stsfld 040001AD

IL_00C4 ldsfld 040001AD

IL_00C9 stloc.2

IL_00CA ldarg.2

IL_00CB ldarg.3

IL_00CC ldloc.1

IL_00CD ldloc.2

IL_00CE ldarg.0

IL_00CF ldsfld 040001A2

IL_00D4 ldc.i4.m1

IL_00D5 ldnull

IL_00D6 call (2B)0000C8

IL_00DB nop                                     	                                 <--------------------------------Newly Added

IL_00DC call (0A)000849				                                 <--------------------------------Newly Added

IL_00E1 ret

Note: If the instructions not being added in the first return instruction, it works fine.

System.Web.Mvc version is 5.0.0.0. Also there is no exception handler in this method.

Please help me on this. @sawilde

**Comment by sawilde** [comment]
@Anbu2388 sorry I don't know where to start since I have no way to replicate your issue nor the time to do so though I suspect you are affecting the stack in some manner that is then affecting the return parameter. If you have a reproducible sample then I or someone else may be able to help you. However your issue is not with OpenCover itself but you are instead looking for support on some code that you have taken from OpenCover and using it for similar purpose.

**Comment by Anbu2388** [comment]
Thanks @sawilde

**Comment by Anbu2388** [comment]
1. I wanna get return type of a method.
2. I wanna insert a local variable in LocalVarSigTok in method header.

Please help me on this... @sawilde

**Comment by sawilde** [comment]
> I wanna get return type of a method.

I use mono.cecil to get the metadata but you'll not be able to use that from the profiler directly so you'll have to use the profiler API.

[PartCover](https://github.com/sawilde/partcover.net4) has some code that may be of use to you.

May I also suggest you do some reading around the subject such as [David Broman's blog](https://blogs.msdn.microsoft.com/davbr/) and the MSDN [forums](https://social.msdn.microsoft.com/Forums/en-US/home?forum=netfxtoolsdev) but you are entering rarely uncharted territory.

> I wanna insert a local variable in LocalVarSigTok in method header.

I don't recall ever having the need to do that so I know as little about that as you do.
