### ISSUE TITLE
MSBuild task cannot be used as is when OpenCover is deployed with NuGet

### ISSUE THREAD

**Issue by mcartoixa** [OpenCover/opencover#617]
### My Framework
- [ ] .NET 2
- [ ] .NET 3.5
- [X] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else
### My Environment
- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016
### I have already...
- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.
### My issue is related to (check only those which apply):
- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request
### Expected Behavior

I am deploying OpenCover with NuGet (as opposed to installling it). If I somehow `<Import "OpenCover.targets" />` I should be able to use the MSBuild OpenCover task directly.
### Actual Behavior

The `<Import />` directive fails. The MSBuild task is looking for OpenCover in the registry, assuming that it has been installed whan it has not.
### Steps to reproduce the problem:

Just try. My guess is that not that many people use this deployment method :-)
I'll provide a PR shortly.

**Comment by sawilde** [comment]
@mcartoixa thanks 
ps what do you think of the new flow [good|bad|room for improvement]?

**Comment by mcartoixa** [comment]
I think it's ~~fine~~good.

For future reference, the right syntax to import the targets file when deployed with NuGet is `<Import Project="$(MSBuildProjectDirectory)\packages\OpenCover.*\MSBuild\OpenCover.targets" />` (note the wildcard to replace the version number).

**Comment by sawilde** [comment]
> note the wildcard to replace the version number

do you mean we need to script the version number change or that it will iterate through all matches?

**Comment by mcartoixa** [comment]
No. That's for users who want to import the OpenCover task in their MSBuild script:
* when OpenCover has been installed you do `<Import Project="$(MSBuildExtensionsPath32)\OpenCover\OpenCover.targets" />`.
* when deployed with NuGet you do `<Import Project="$(MSBuildProjectDirectory)\packages\OpenCover.*\MSBuild\OpenCover.targets" />`. The star takes care of the version number (cf. the _Wildcards_ section in https://msdn.microsoft.com/en-us/library/92x05xfs.aspx).

**Comment by sawilde** [comment]
nice :)
