### ISSUE TITLE
Replace source directory information when run tests on not same machine as libraries were built on

### ISSUE THREAD

**Issue by zabulus** [OpenCover/opencover#619]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [X] .NET 4.5.2
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior

I have multiple step CI build. Libraries are built in one job "Build libraries", and used in "Run tests" and in "Build installation" jobs. In "Run tests" job following errors are occurred in log:
```
build	07-Aug-2016 13:46:41	Total tests: 387. Passed: 183. Failed: 201. Skipped: 3.
error	07-Aug-2016 13:46:41	Test Run Failed.
build	07-Aug-2016 13:46:41	Test execution time: 12.6819 Minutes
build	07-Aug-2016 13:46:41	Committing...
build	07-Aug-2016 13:46:42	An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\bamboo\xml-data\build-dir\<Path to library source file placed in  job "Build libraries">'. 
```
I'd like to have possibility to override source folder used by OpenCover to use current job source folder.

**Comment by sawilde** [comment]
Sorry I don't understand. where is the exception coming from?

Note: I don't use bamboo so you'll need to explain in terms that can be repeated outside that environment.

**Comment by zabulus** [comment]
I'll explain it in other terms.
1. Clone project sources in two different folders. In my case it is two different PCs.
2. Build all assemblies in first folder.
3. Move built assemblies into second folder to same paths.
4. Completely delete first folder.
5. Run tests in the second folder.

**Comment by sawilde** [comment]
And what is the problem with that?

**Comment by zabulus** [comment]
Not a problem. Feature request.
I'd like to replace paths in resulting file to be used from second folder not the folder assemblies built in.

**Comment by sawilde** [comment]
You'll need to show/describe which file paths you are talking about.

The assembly files should be from where they were first loaded from during the execution run.
The source file paths come from the PDB themselves.

So which file paths?

> Not a problem. Feature request.

First we need to decide if it is necessary or if you can do what you want without a code change to opencover. I say this as I have never had issues - and I use build systems that do exactly that pattern you describe.

**Comment by zabulus** [comment]
Sure.
I'm talking about source paths from PDB.
After test run results.xml filled with paths from PDB.
I don't know what I'm doing wrong, but I can't get sources in my coverage reports, only names of classes and methods.
If I run build and tests from same folder everything works great.

**Comment by sawilde** [comment]
can you show the commands you are using?

**Comment by sawilde** [comment]
What are you using to generate coverage reports?

**Comment by zabulus** [comment]
```..\..\..\..\src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"%VS110COMNTOOLS%..\Ide\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"SharpDatabase.Tests.dll /TestCaseFilter:TestCategory!=Nightly /inIsolation /Logger:trx /Platform:x64 /TestAdapterPath:..\..\..\..\src\packages\xunit.runner.visualstudio.2.0.1\build\_common" -excludebyattribute:*.ExcludeFromCodeCoverage* -filter:+[WcfService*]* -register:user```
I'm using ReportGenerator. It have sourcedirs parameters, but it doesn't do what I want:
```
..\..\..\..\src\packages\ReportGenerator.2.4.5.0\tools\ReportGenerator.exe "-reports:.\results.xml" "-targetdir:..\..\..\..\Report" "-sourcedirs:%SolutionDir%"
```

**Comment by sawilde** [comment]
> I'm using ReportGenerator. It have sourcedirs parameters, but it doesn't do what I want, or it doesn't work as needed. 

Why don't you create you own utility to do a string replacement in the XML and then you have full control? You'll get what you want a lot quicker as OpenCover isn't going to be released until we have updated libraries from the mono.cecil project.

**Comment by zabulus** [comment]
Yep, I considered this. But to implement replace I need to know _previous_ folder path. For now I know it, but it is not flexible, if prev path will change in future.
OK, if you think this issue gives a little gain with too much effort, I'll make my replace with PS one-liner PS, and will fix it in future, you can close the issue.

**Comment by sawilde** [comment]
>  But to implement replace I need to know previous folder path

but you'd need that to send arguments to OpenCover - there could be a scenario where one set of PDBs is built in folder A and another in folder B but all being executed from folder C or even D (in the case of multiple processes) - this is why I am not seeing the value of the request as it is too situation specific.
