### ISSUE TITLE
CRAP score feature

### ISSUE THREAD

**Issue by TraGicCode** [OpenCover/opencover#620]
Any thoughts on implementing the calculation of CRAP (Change Risk Anti-Patterns) metric?  I think this would be helpful especially since the data needed for this calculation is already provided by Open Cover.

**Comment by sawilde** [comment]
Are you on about this metric?

> crap(m) = comp(m)^2 * (1-cov(m)/100)^3 + comp(m)

Never thought of it; the comp(m) shown by OpenCover is actually at the IL level not source code.

What is it's value?

**Comment by TraGicCode** [comment]
The CRAP metric is a great metric to be used along with code coverage since.

Generally speaking,  Crappy methods exhibit the following characteristics
1.) High Cyclomatic complexity
2.) Low code coverage

Its usually challenging to write tests for complex code.  Therefore code without tests are signs of crappy code ( hence lack of code coverage ).  Having some code coverage indicates some degree of thought about testability and implementation.

The value of this metric is to help mitigate/reduce risk by uncovering the possible presence of crappy code.  The code can
1.) Have Tests added
2.) Be refactored ( preferable )

The common practices is a CRAP score of 30 or less is considered acceptable and generally anything higher should be looked at.  This is really a team decision on this threshold.

**Comment by sawilde** [comment]
> The common practices is a CRAP score of 30 or less is considered acceptable and generally anything higher should be looked at. This is really a team decision on this threshold.

Okay I can see how it can be useful - once done we'll need to work with @danielpalme to see if we can get a visualisation of this data in his awesome reporting tool.

**Comment by danielpalme** [comment]
I created an issue for ReportGenerator:
https://github.com/danielpalme/ReportGenerator/issues/57

Just let me know when you are done,

**Comment by TraGicCode** [comment]
@danielpalme done.

**Comment by danielpalme** [comment]
@TraGicCode 
Great.

You could try this beta release: https://www.nuget.org/packages/ReportGenerator/2.4.6-beta3
Does it work for you?

**Comment by TraGicCode** [comment]
is working for me and looks good!
:+1:

**Comment by TraGicCode** [comment]
What are the next steps taken in order for this to make it to the next release?

**Comment by sawilde** [comment]
I leave them pending so I can update the release notes

**Comment by TraGicCode** [comment]
Any estimate on when the next release might be?

**Comment by sawilde** [comment]
nope - sorry - still waiting on the mono.cecil dependancy.

**Comment by akamud** [comment]
Any update on this? I am using version OpenCover.4.6.519 but I guess this is not available yet.

**Comment by sawilde** [comment]
@akamud sorry not had a lot of time of late to work on a release - I've been waiting on another package but it seems to never want to release - I may look to make a beta release that uses the beta package I am dependant on but I am reluctant to create a release as of yet.

**Comment by akamud** [comment]
I understand, no need to rush, I guess.
