### ISSUE TITLE
Nested ternary statements have incorrect coverage reported

### ISSUE THREAD

**Issue by hughbe** [OpenCover/opencover#621]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [x] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Full coverage is reported.

### Actual Behavior

6/8 branches are reported as being covered.

### Steps to reproduce the problem:

The following code:
```
return (h >= '0' && h <= '9') ? h - '0' :
 	(h >= 'a' && h <= 'f') ? h - 'a' + 10 :
 	(h >= 'A' && h <= 'F') ? h - 'A' + 10 :
 	 -1;
```
reports 6/8 branches as being covered in my unit tests. However, if I break it down into if statements, e.g.
```
if (h >= '0' && 'h' <= '9')
    return h - '0';
else if (h >= 'a' && h <= 'f')
    return h - 'a' + 10;
else if (h >= 'A' && h <= 'F')
    return h - 'A' + 10;
else
   return -1;
```
then full coverage is reported.

I assume this is because of nested ternary statements

**Comment by sawilde** [comment]
> I assume this is because of nested ternary statements

OpenCover uses the generated IL to generate the branch statement coverage - if your tests are unable to cover all the IL branches then there is nothing I can do. You also should ask yourself which code is easier to read, I would say the latter. 

This reads even easier

````
if (h >= '0' && 'h' <= '9')
    return h - '0';
if (h >= 'a' && h <= 'f')
    return h - 'a' + 10;
if (h >= 'A' && h <= 'F')
    return h - 'A' + 10;
return -1;
````

**Comment by sawilde** [comment]
By the way it looks like you are creating a hexidecimal string to int convertor - may I suggest you avoid such trivialities and use [Convert.ToInt32](https://msdn.microsoft.com/en-us/library/1k20k614(v=vs.110).aspx) e.g.

> Convert.ToInt32("3A", 16)
