### ISSUE TITLE
Opencover.exe fails when execute from Jenkins for sonar analysis

### ISSUE THREAD

**Issue by sreekanthmg** [OpenCover/opencover#623]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5 --> .Net 4.5.2
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior

When i try to execute below command directly in cmd, it works fine

.\opencover.4.6.519\OpenCover.Console.exe -target:"C:\Tools\NUnit-3.4.1\nunit3-console.exe" -targetargs:"*\UnitTestProject1\bin\Release\UnitTestProject1.dll" -output:"*\opencover.xml" -register:user

But it fails when I execute it from Jenkins sonar integration.
Following error, I am getting
**Results (nunit3) saved as TestResult.xml
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.** 

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by sawilde** [comment]
The issue will probably be related to the permissions of your user account used to run Jenkins. 

Have you tried the options in the guides especially around either using the `-register` switch or using the `regsvr32` utility?

**Comment by sreekanthmg** [comment]
I am using local user account with admin privileges to run Jenkins. By using the same local account only, I have logged into system and executed successfully in command line.

I tried with regsvr32, but still no help

**.\opencover.4.6.519\OpenCover.Console.exe -target:"C:\Tools\NUnit-3.4.1\nunit3-console.exe" -targetargs:"\UnitTestProject1\bin\Release\UnitTestProject1.dll" -output:"\opencover.xml" -register:regsvr32**

Is above syntax is right ?

I am getting below error when I tried using regsvr32

**Failed to register(user:False,register:True,is64:False):5 the profiler assembly; you may want to look into permissions or using the -register:user option instead. C:\Windows\system32\regsvr32.exe /s   "*\Downloads\opencover.4.6.519\x86\OpenCover.Profiler.dll"**

**Comment by sawilde** [comment]
May I refer you to the documentation [Usage.pdf](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) (which I assumed you have read as you checked the box) and that the only *additional* options supported by `-register` are *user*, *path32* or *path64*. You may of course forgo the `-register` switch if you use the `regsvr32.exe` utility as detailed in the **Build system integration** and **FAQ**.

**Comment by sreekanthmg** [comment]
Thanks for your support. The issue is been resolved

I just replaced -register:user to **-register:path32**

**Comment by sawilde** [comment]
yup - but be aware it'll only cover 32 bit apps that way
