### ISSUE TITLE
Line coverage is not shown correctly, only part of a method is shown as covered 

### ISSUE THREAD

**Issue by soundaryasamala** [OpenCover/opencover#624]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior
Code coverage should be shown as covered for all the lines in a method 
Fill me in...

### Actual Behavior
Only few lines are shown as covered even though there are no conditional statements

Fill me in...

### Steps to reproduce the problem:

Fill me in...
![report](https://cloud.githubusercontent.com/assets/6280591/18051594/2cfd58b4-6e13-11e6-8ccb-b69b23bba2b3.PNG)

**Comment by sawilde** [comment]
Sorry the above does not help me reproduce the problem you are having you will need to provide more information i.e. sample code that exhibits the behaviour you describe.
