### ISSUE TITLE
Including results from projects that are not tested at all

### ISSUE THREAD

**Issue by ceddlyburge** [OpenCover/opencover#626]
Hi there

I have a xamarin project that wasn't tested at all from the test projects.

Is there a way to get this included in the test results?

I have tried copying the dll in to the same place as all the others, which didn't work.

I tried adding a reference to the xamaring project from the test project (a minor hack) and this didn't work either.

Then I added a dummy test to the xamarin project and then all was good, but it seems like there would be a better way.

Thanks

Cedd

Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [X] .NET 4.6.2
- [] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by sawilde** [comment]
> Then I added a dummy test to the xamarin project and then all was good, but it seems like there would be a better way.

nope this is how it works - the assembly has to be loaded for the profiler to instrument it.

If you don't want to execute any code until you have proper tests then you could possibly use reflection to force the assembly to be loaded.
