### ISSUE TITLE
While trying to cover a test with OpenCover, a message box pops up saying "An exception occured: Could not find a part of the path 'C:\<blah>\OpenCover\<someGuid>\TestResults. Please refer to output window for more details.

### ISSUE THREAD

**Issue by sm38098** [OpenCover/opencover#627]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 4.5

### My Environment

- [ ] Windows 10

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded

### Expected Behavior

Coverage should be recorded

### Actual Behavior

Exception thrown

### Steps to reproduce the problem:

Using VS 2015 professional, ran a simple unit test but it failed to provide coverage. Moreover I'm using resharper on my machine. Not sure if it's something to do with that.

**Comment by sawilde** [comment]
How are you running OpenCover?

**Comment by damonachey** [comment]
Install OpenCover from Visual Studio extensions site.
Create new project
Add public class named Foo
Add public function to Foo named Bar with no parameters and a void return
Right click in Bar and use default VS menu to "Create unit tests"
Use defaults from wizard
Run test from OpenCover Test Explorer via right click
Get failure below...


1 tests found
-target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"\"c:\users\damon\documents\visual studio 2015\Projects\ConsoleApplication1Tests\bin\Debug\ConsoleApplication1Tests.dll\" /Tests:ConsoleApplication1.Tests.FooTests.BarTest /Logger:trx" -output:"c:\users\damon\documents\visual studio 2015\Projects\ConsoleApplication1\OpenCover\494abf5c-444b-4a3a-86b1-443a7e61ff01\7d469a1e-99e5-48b1-8c9a-f3d57d292903.xml" -hideskipped:All -register:user
The given path's format is not supported.

Could not find a part of the path 'c:\users\damon\documents\visual studio 2015\Projects\ConsoleApplication1\OpenCover\494abf5c-444b-4a3a-86b1-443a7e61ff01\TestResults'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at OpenCover.UI.Processors.MSTestExecutor.UpdateTestResultsFile()
   at OpenCover.UI.Processors.MSTestExecutor.ReadTestResults()
   at OpenCover.UI.Processors.TestExecutor.Execute()
   at OpenCover.UI.Commands.ExecuteSelectedTestsCommand.<RunOpenCover>b__1()
1 tests found

**Comment by Qevlarr** [comment]
I had this same problem. Look at the OpenCover output: in VS, in the output window (View > Output), select "OpenCover" in the "Show output from:" dropdown. In my case, it said 

> Error:
> None of the provided test containers match the Platform Architecture and .Net Framework settings for the test run. Platform: X86  .Net Framework: Framework45. Go to http://go.microsoft.com/fwlink/?LinkID=330428 for more details on managing these settings.

Rebuilding for that configuration fixed the problem.
