### ISSUE TITLE
MissingPdb when pdbs is in different location than dlls

### ISSUE THREAD

**Issue by kalimera8764** [OpenCover/opencover#628]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`
### My Framework
- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else
### My Environment
- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [X] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016
### I have already...
- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.
### My issue is related to (check only those which apply):
- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request
### Expected Behavior

I have some nunit tests (dlls), that i call to execute using nunit-console. The corresponding pdbs are in a different location. I tried using "-targetdir" or "-searchdirs" to solve the issue.
The dlls and pdbs are produced from the same build in VS2013. When they are together, it works fine, when i try to read them from different locations it does not.
That dll is ": skippedDueTo="MissingPdb""
I have attached the bat file i am using to execute. (i have tried different combinations of filters/targets)
[openCoverExecution.txt](https://github.com/OpenCover/opencover/files/484948/openCoverExecution.txt)

Any other ideas on how i could get coverage when i have different locations of dlls and pdbs?

**Comment by sawilde** [comment]
It looks as I would expect - do you have a sample project that I can repeat this on?

**Comment by kalimera8764** [comment]
Hello Shaun,

I have made a smaller, sample project, that i could replicate the issue.

I have included the solution and the structure of the folders/files.
[testApp.zip](https://github.com/OpenCover/opencover/files/486771/testApp.zip)

Let me know if i missed something.

**Comment by kalimera8764** [comment]
Did you have any time to look at the issue? Did you manage to replicate it? Let me know, if there is any more information you would like from my part.

**Comment by sawilde** [comment]
I don't know if you resolved this yourself but when opencover looks for the pdbs in other folders it also expects to find the assemblies there as well - I'll see what I can do to change this but I may be limited by the 3rd party library we use.
