### ISSUE TITLE
Test coverage for several test projects

### ISSUE THREAD

**Issue by mayconbeserra** [OpenCover/opencover#629]
Hi,

This is a question :)

How could I run the test coverage in dotnet core but for several test projects?

I'm able to do that with one, but more than one, I haven't been able yet.

Cheers,

**Comment by sawilde** [comment]
What tool are you using to run your test projects? Most tools have an ability to run one or more test projects but if not you can use the `-mergeoutput` switch as detailed in the wiki (see [Usage](https://github.com/OpenCover/opencover/wiki/Usage))

**Comment by mayconbeserra** [comment]
Hi @sawilde ,

I'm using xunit ("testRunner": "xunit").

Is there any other option for dotnet core?

Cheers,

**Comment by sawilde** [comment]
then `-mergeoutput` is probably you best choice as I recall from my usage of xunit

**Comment by mayconbeserra** [comment]
great, thanks @sawilde 

Do you have an example to help me how to use it?

cheers

**Comment by sawilde** [comment]
Have you had a chance to look at the [wiki](https://github.com/OpenCover/opencover/wiki/Usage)?
