### ISSUE TITLE
OpenCover sometimes hangs with mstest

### ISSUE THREAD

**Issue by MartinDemberger** [OpenCover/opencover#630]
Our daily tests hangs about every second day with only saying "Staring execution..." as last message. When I attached the debuggger to the hanging mstest-process I saw that the test has already starting and is hanging in CCoideCoverage::JITCompilerStarted. It's hanging in the line "if (m_allowModules[modulePath])". 
It looks to me like m_allowModules is corrupted because if I look at it in VS2015 I see a size of 70 but inside there are only two elements and a lot of errors.
### My Framework
- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [X] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else
### My Environment
- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016
### I have already...
- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.
### My issue is related to (check only those which apply):
- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request
### Expected Behavior

The test should proceed.
### Actual Behavior

The test hangs and doesn't come to an end even after 12 hours.
### Steps to reproduce the problem:

Start the tests several times on our server and sometimes it hangs... :-(

**Comment by sawilde** [comment]
Do you have a reproducible sample?

**Comment by MartinDemberger** [comment]
Sorry, but this only happens on our build server and even there only about one of three fails. The server has VS2015 installed so I'm able to connect to the hanging process.

**Comment by hughbe** [comment]
I can provide a repro for hanging with xunit:
1. Clone https://github.com/hughbe/html-generator
2. Open `runtests.bat`
3. Modify the `user_name` property and `user_path` property if necessary
4. Open `cmd` in the cloned directory
5. Run `runtests.bat`

The xunit tests take about 0.6 seconds on my PC, but opencover hangs up to 30s

**Comment by sawilde** [comment]
Does the xunit process shutdown? OpenCover only closes when all the child process it launched shutdowns or it stops getting notifications but it waits some time before deciding to end the run.
