### ISSUE TITLE
Coverage detail for CI/CD

### ISSUE THREAD

**Issue by wahmedswl** [OpenCover/opencover#631]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [X] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

Hi, is there anyway i can get Coverage Detail on Console? Currently, i am using gitlab with their internal CI/CD runner. I am using xUnit for coverage and i want to integrate opencover for code coverage details. Gitlab uses reges to parse coverage information. So, it would be great to have output generate to stdout rather generating result.xml and also, if coverage been shown in a regex friendly manner. Gitlab has following mentions for other tools

```
Below are examples of regex for existing tools:

Simplecov (Ruby) - \(\d+.\d+\%\) covered
pytest-cov (Python) - \d+\%\s*$
phpunit --coverage-text --colors=never (PHP) - ^\s*Lines:\s*\d+.\d+\%
gcovr (C/C++) - ^TOTAL.*\s+(\d+\%)$
tap --coverage-report=text-summary (Node.js) - ^Statements\s*:\s*([^%]+)
```

Thanks

**Comment by sawilde** [comment]
Output is published to the console so why can't you get it from there?

**Comment by wahmedswl** [comment]
Hi, this is the output generated to console
```
Committing...
Source file is modified: E:\Development\Production-WS\Infrastructure\TestAndPerf\Test\TestSequelSql.cs
Empty sequence-point at line: 260 column: 29
Source file: E:\Development\Production-WS\Infrastructure\Logging\Logger.cs
Visited Classes 64 of 149 (42.95)
Visited Methods 371 of 919 (40.37)
Visited Points 3415 of 8195 (41.67)
Visited Branches 1034 of 2630 (39.32)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 80 of 160 (50)
Alternative Visited Methods 440 of 1065 (41.31)
```

What is the source to get Code coverage in %? like 25% etc

Thanks

**Comment by sawilde** [comment]
This is the one you are probably after as this is the number of covered sequence points - however you if you want to turn this into lines you will have to process the XML yourself like the UI tools such as ReportGenerator do.

> Visited Points 3415 of 8195 (41.67)

**Comment by wahmedswl** [comment]
Thanks

**Comment by wahmedswl** [comment]
Sorry but it would be great if coverage information be available in % cuz i have used following regex to get this information and its not showing up nicely
```
Visited Points .+ \(\d+.\d+\)
```

I have following output
```
Committing...
Visited Classes 66 of 168 (39.29)
Visited Methods 391 of 986 (39.66)
Visited Points 2431 of 5980 (40.65)
Visited Branches 1422 of 3874 (36.71)
```

And its showing up like this in gitlab

![image](https://cloud.githubusercontent.com/assets/15020561/22783210/95b13718-eeec-11e6-813e-32297b6acbe1.png)

It would be great to get coverage information just like other main-stream are providing
```
Below are examples of regex for existing tools:

Simplecov (Ruby) - \(\d+.\d+\%\) covered
pytest-cov (Python) - \d+\%\s*$
phpunit --coverage-text --colors=never (PHP) - ^\s*Lines:\s*\d+.\d+\%
gcovr (C/C++) - ^TOTAL.*\s+(\d+\%)$
tap --coverage-report=text-summary (NodeJS) - ^Statements\s*:\s*([^%]+)
excoveralls (Elixir) - \[TOTAL\]\s+(\d+\.\d+)%
```

Thanks

**Comment by sawilde** [comment]
you can pull the information from the xml file

**Comment by wahmedswl** [comment]
yes, you are right. But, it would be great if that information is also part of 

```
Committing...
Visited Classes 66 of 168 (39.29)
Visited Methods 391 of 986 (39.66)
Visited Points 2431 of 5980 (40.65)
Visited Branches 1422 of 3874 (36.71)
```

because GitLab computes Coverage from build output, i can pull up that information from xml but it would be great to have that information part of it to be used as ready to go solution.

Thanks

**Comment by sawilde** [comment]
Then why not do a regex on this line `Visited Points 2431 of 5980 (40.65)`? Since that is most likely the number you want (the number in brackets is the the %)

**Comment by wahmedswl** [comment]
Yeah, i already had regex to extract but current one i am using, it extract full line. Yes, you are right I only want to extract (40.65)

**Comment by wahmedswl** [comment]
```(Visited Points).*\((.*)\)``` did the magic, @gep13 helped in that.

**Comment by Jenan** [comment]
Hello - @wahmedswl  - can you please share - how did you configure your piplene on GitLab for running opencover? Thank you.

**Comment by wahmedswl** [comment]
I am using ```Cake``` for build orchestration, following snippet will help

```
#tool "nuget:?package=xunit.runner.console"
#tool "nuget:?package=OpenCover"
#tool "nuget:?package=ReportGenerator"

Task("Run-Unit-Tests").Does(() =>
{
    MSBuild("./TestAndPerf/TestAndPerf.csproj", settings => 
    {
        settings.SetConfiguration(configuration).SetPlatformTarget(PlatformTarget.MSIL);
        settings.WithProperty("OutDir", buildDir + "/32+64bit/TestAndPerf");
    });
    EnsureDirectoryExists("./build/32+64bit/OpenCover/");
    OpenCover(tool => {
        tool.XUnit2("./build/32+64bit/TestAndPerf/**/TestAndPerf.dll", new XUnit2Settings {
            Parallelism = ParallelismOption.Collections,
            ShadowCopy = false
        });
    },
    "./build/32+64bit/OpenCover/OpenCover.xml",
    new OpenCoverSettings { ReturnTargetCodeOffset = 0, Register = "Path64" }
        .WithFilter("+[SequelMed*]*")
        .WithFilter("-[*]xunit.*"));

    // TODO: Need to think about how to bring this out in a generic way for all Test Frameworks
    ReportGenerator("./build/32+64bit/OpenCover/OpenCover.xml", "./build/32+64bit/OpenCover");
});


```

**Comment by Jenan** [comment]
Are you using this code on GitLab.com or on your own GitLab instance? Thx

**Comment by wahmedswl** [comment]
@Jenan this is not gitlab.com, its our own gitlab-CE instance. I don't know if gitlab.com provide window machines

**Comment by Jenan** [comment]
You are absolutely right, there is probable only linux. I have to waiting for linux support of OpenCover. I appreciate your reply. :) @sawilde - Where will be able to using OpenCover on linux? Thx,

**Comment by sawilde** [comment]
@Jenan 

> Where will be able to using OpenCover on linux? Thx,

that is a long way off I'm afraid

**Comment by OggyMishra** [comment]
@sawilde You can create your project specific runner on windows box. Checkout this link https://docs.gitlab.com/ce/ci/runners/

**Comment by sawilde** [comment]
@OggyMishra interesting but I have no need for such a thing

**Comment by doctorlard** [comment]
Hi, I don't wish to reopen this issue, but for posterity and prosperity, or in case anyone is stuck in a time machine, or has spent hours tediously fiddling with regex and comes looking for this information, this will parse out the correct number (the third number, in parentheses):

`Visited Points.*\((\d+\.\d+)`

I had some horrible combination of Perl vs. Ruby regex library compatibility, Windows non-UTF8 locales, interference from ANSI-coded coloured output, and possibly the positions of the moon, sun and planets. I managed this setting with normal (coloured) OpenCover output, without using anything to filter out ANSI (I think GitLab job output does that anyway), and with a self-hosted GitLab 13.4 (EE Premium, Omnibus) running on Ubuntu 18.04.
