### ISSUE TITLE
Method Not Covered

### ISSUE THREAD

**Issue by jregnier** [OpenCover/opencover#633]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

The following method should be fully tested by the test below.
```CS
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            List<List<string>> result = new List<List<string>>();

            var array = JArray.Load(reader);

            foreach (var item in array)
            {
                if (item is JArray)
                {
                    result.Add(((JArray)item).ToObject<List<string>>());
                }
                else if (item is JValue)
                {
                    result.Add(new List<string>() { ((JValue)item).Value.ToString() });
                }
            }

            return result;
        }
```
and this is what the test looks like. Its testing the method indirectly with a TestObject which has the attribute on one of its properties and also directly by calling the method from the test.
```CS
        [TestMethod]
        public void ReadJsonTest()
        {
            var json = File.ReadAllText("Dto\\BoosterCustomConverterData.json");

            var result = JsonConvert.DeserializeObject<RootSetDto>(json);

            Assert.IsNotNull(result.Set.Booster);
            Assert.AreEqual(16, result.Set.Booster.Count);

            JsonTextReader jsonReader = new JsonTextReader(new StringReader("[[\"rare\",\"mythic rare\"],\"uncommon\",\"uncommon\",\"uncommon\",\"common\",\"common\",\"common\",\"common\",\"common\",\"common\",\"common\",\"common\",\"common\",\"common\",\"land\",\"marketing\"]"));

            BoosterCustomConverter converter = new BoosterCustomConverter();
            var result2 = converter.ReadJson(jsonReader, typeof(List<List<string>>), null, null) as List<List<string>>;
            Assert.IsNotNull(result2);
            Assert.AreEqual(16, result2.Count);
        }
```
### Actual Behavior

The method is reporting 0 coverage.

### Steps to reproduce the problem:

Run OpenCover with following command
```.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"J:\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\MtgApiManager.Lib.Test\bin\Debug\MtgApiManager.Lib.Test.dll" -filter:"+[MtgApiManager.Lib]*  -[MtgApiManager.Lib]MtgApiManager.Lib.Properties.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\MtgApiManager.Lib_coverage.xml```

**Comment by sawilde** [comment]
Please provide a working sample (not code snippets) so I can replicate your issue exactly.

**Comment by jregnier** [comment]
Thanks for the reply. Last night I decided to refactor my code and ended up not needing the method causing the issue so indirectly fixing my issue. Thanks
