### ISSUE TITLE
The result TRX file is already exists

### ISSUE THREAD

**Issue by MrOm1214** [OpenCover/opencover#634]
I am new to Code Coverage and this Open Cover tool but I take a reference from the following link 

http://www.allenconway.net/2015/06/using-opencover-and-reportgenerator-to.html

and create two separate bat files. But when I am running GenerateUnitTestMatrix.bat I am getting the error like as shown in Image Please help me to resolve this error :

**Error : The result trx file is already exists. Please specify a different results file or verify the existing file is no longer needed or delete it.** 

Thank You Very Much In Advance

![myerror](https://cloud.githubusercontent.com/assets/8445429/19891820/d8befaa0-a067-11e6-9bf4-7f767da3ef9b.png)

**Comment by sawilde** [comment]
.trx files are to do with mstest - not opencover
