### ISSUE TITLE
-excludebyattribute for opencover command line is not working

### ISSUE THREAD

**Issue by vijaypnet** [OpenCover/opencover#635]
lease provide the following information when submitting an issue, where appropriate replace the [ ] with a [X]

My Framework

 .NET 2
 .NET 3.5
 .NET 4
 .**NET 4.5**
 .NET 4.6
 .NET 4.6.1
 .NET 4.6.2
 .NET Core 1.0.0
 Something else
My Environment

 Windows 7 or below (not truly supported due to EOL)
 Windows 8
 **Windows 8.1**
 Windows 10
 Windows 10 IoT Core
 Windows Server 2012
 Windows Server 2012 R2
 Windows Server 2016

We are using Opencover command line tool to push code coverage data to Sonarcube as part of build script in team city. We have added excludebyattribute as an argument to open cover so that we can exclude certain .net classes from code coverage report.

-excludebyattribute: "System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute"

But it seems that the classes marked with ExcludeFromCodeCoverage attribute still included in code coverage report. Please let us know if we are using correct argument.

**Comment by sawilde** [comment]
May I refer you to the wiki - [Understanding filters](https://github.com/OpenCover/opencover/wiki/Usage#understanding-filters)
