### ISSUE TITLE
OpenCover won't process C# source codes

### ISSUE THREAD

**Issue by AdamOrHd123** [OpenCover/opencover#637]
### My Framework

- [X] .NET 4.5
### My Environment

- [X] Windows 7 or below (not truly supported due to EOL)

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I expects OpenCover to produce an xml output for C# source codes that does not complain on missing pdb file.

### Actual Behavior
I have a problem where C# code is not being covered.
In contrast, C++ code is being covered.
In the output file there are a lot of tags indicating with an attribute of skippedDueTo="MissingPdb"
The command-line I use is as follows:
C:\Projects\opencover.4.5.3207>OpenCover.Console.exe -target:"C:\Projects\Accura
cy_With_Pdb\Accuracy\Accuracy.exe" -targetdir:"C:\Projects\Accuracy_With_Pdb\Acc
uracy" -output:"C:\Projects\Coverity\coverage-20161106_164706\Accuracy_CodeCove
rage.xml" -register:user -targetargs:"C:\Projects\Accuracy_With_Pdb\Accuracy\Acc
uracy.pdb /noshadow"

### Steps to reproduce the problem:
Use OpenCover to cover an application written in C#.

**Comment by sawilde** [comment]
Your 'targetargs' make no sense - I suspect a cut and paste from a nunit sample.

Are you using portable PDBs? if not is the PDB in the same folder as the target application?

**Comment by AdamOrHd123** [comment]
Hi,
Thanks for the assistance.
You're correct about the targetargs issue - it was an attempt that I tried.
But I also tried without it and it din't work.
I have a PDB in the location of the target application.
Can it be possible that version 4.5.3207 is not good enough for C# source code?

**Comment by sawilde** [comment]
OpenCover does not cover code it instruments the IL and tools like ReportGenerator turn the result that maps into your source files by that C#, VB.NET or C++.

What type of project is Accuracy i.e. what version of .NET are you compiling against?
