### ISSUE TITLE
Official Sample.cmd is not working

### ISSUE THREAD

**Issue by AltairCA** [OpenCover/opencover#639]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [x ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ x] repeated the problem using the latest stable release of OpenCover.
- [x ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

When run the Sample.cmd code is being covered.

### Actual Behavior

When run the official Sample.cmd file code is not being covered.

### Steps to reproduce the problem:

Just run the Sample.cmd

**Comment by AltairCA** [comment]
Solution

Open Up a Command prompt as Administrator and CD to the OpenCover folder

Rename the **-register:user** in the Sample.cmd file
example

if your administration account username is **admintest1**
rename the command as **-register:admintest1**

**Comment by sawilde** [comment]
`rename the command as -register:admintest1`

This is incorrect, `user` does not mean insert username here - it means current user and is related to the commands that are used by the regsvr32 utility.

**Comment by AltairCA** [comment]
oh I'm really sorry

**Comment by AltairCA** [comment]
Oh I'm really sorry
