### ISSUE TITLE
skippedDueTo="Unknown" when using liblog

### ISSUE THREAD

**Issue by mabead** [OpenCover/opencover#640]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

If I run OpenCover on a .net project that references LibLog, the code of LibLog should be properly detected by OpenCover.

### Actual Behavior

All the code of LibLog ends up as ``<Method skippedDueTo="Unknown"``.

### Steps to reproduce the problem:

- Create a console program that references LibLog (https://www.nuget.org/packages/LibLog)
- Add a dependency on OpenCover 4.6.519
- Simply write the following in the Main function:

```
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World.");
        }
```
- Compile
- Run OpenCover with this command

```
.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:bin\debug\OpenCoverIssue.exe -register:user -filter:"+[OpenCoverIssue*]*" -output:"bin\debug\OpenCover.xml" -hideskipped:all
```
- Look at OpenCover.xml

You will see that it contains a lot of the `<Method skippedDueTo="Unknown"`. In fact, all the methods of LibLog have this result. As a consequence, the final code coverage is wrong. All the methods that are flagged as skipped due to unknown are considered in the coverage.

**Comment by sawilde** [comment]
Please provide a repeatable sample - I may not be able to recreate your scenario so it is better if you provide it yourself that way I repeat your exact conditions.

**Comment by mabead** [comment]
Steps:

- Clone this repository `https://github.com/mabead/OpenCoverIssue`
- Open the sln in VisualStudio
- Compile in debug mode
- From the directory that contains the .sln, run the following:

```
.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:bin\debug\OpenCoverIssue.exe -register:user -filter:"+[OpenCoverIssue*]*" -output:"bin\debug\OpenCover.xml" -hideskipped:all
```
- Look at bin\debug\OpenCover.xml. You will see that it contains the "Unknown" skipped methods.

**Comment by mabead** [comment]
@sawilde Were you able to reproduce the issue?

**Comment by sawilde** [comment]
Hi @mabead I haven't had an opportunity to do so.

**Comment by sawilde** [comment]
@mabead The few I analysed seemed to be delegates that come back with the `skippedDueTo="Unknown"`

Not sure why this hasn't been raised before but perhaps people don't care about whether that are called or not - I am also not sure at this point whether I can add any instrumentation for these methods.
