### ISSUE TITLE
Trouble Covering .Net app in IIS

### ISSUE THREAD

**Issue by raghunat** [OpenCover/opencover#644]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [x] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [x] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

IIS service starts, and able to generate code coverage

### Actual Behavior

OpenCover Fails with a an Invalid Cast Exception

### Steps to reproduce the problem:

Windows Server 2k12R2 IIS 8, Web any web app.

![screen shot 2016-11-26 at 12 54 23 pm](https://cloud.githubusercontent.com/assets/7767618/20642246/ce7e2010-b3d7-11e6-969a-a869c0e6d65b.png)

**Comment by raghunat** [comment]
Correct, it is IIS 8.5

**Comment by raghunat** [comment]
I can now get IIS to load, but getting 403.18

**Comment by sawilde** [comment]
Sorry I am unable to repeat - if you have a reproducible solution/project please share.
