### ISSUE TITLE
OpenCover does not work with MsTest

### ISSUE THREAD

**Issue by unittester57** [OpenCover/opencover#645]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [X] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Should give code coverage details

### Actual Behavior

No code coveraege details produced

### Steps to reproduce the problem:

Feel this is a simple issue. But I am not getting. I am thankful for any help from the community. 

I am using below script to code cover my unit test:

```
"C:\Users\uname\Documents\Visual Studio 2015\Projects\firstproject\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe" -register:user  "-target:C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" "-targetargs:/noshadow .\firstprojectTests1.dll"

"C:\Users\uname\Documents\Visual Studio 2015\Projects\firstproject\packages\ReportGenerator.2.5.1\tools\ReportGenerator.exe" "-reports:results.xml" "-targetdir:.\coverage"

pause
```

Below is my scripts output captured:

```
C:\Users\uname\Documents\Visual Studio 2015\Projects\firstproject\firstprojec
tTests1\bin\Debug>"C:\Users\uname\Documents\Visual Studio 2015\Projects\first
project\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe" -register:user
"-target:C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.
exe" "-targetargs:/noshadow .\firstprojectTests1.dll"
Executing: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTes
t.exe
Microsoft (R) Test Execution Command Line Tool Version 14.0.23107.0
Copyright (c) Microsoft Corporation. All rights reserved.

Invalid switch "/noshadow".
Invalid switch ".\firstprojecttests1.dll".
For switch syntax, type "MSTest /help"
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

C:\Users\uname\Documents\Visual Studio 2015\Projects\firstproject\firstprojec
tTests1\bin\Debug>"C:\Users\uname\Documents\Visual Studio 2015\Projects\first
project\packages\ReportGenerator.2.5.1\tools\ReportGenerator.exe" "-reports:resu
lts.xml" "-targetdir:.\coverage"
Loading report 'C:\Users\uname\Documents\Visual Studio 2015\Projects\firstpro
ject\firstprojectTests1\bin\Debug\results.xml'
 Preprocessing report
 Initiating parser for OpenCover
Initializing report builders for report types: Html
Analyzing 0 classes
 Creating summary
Report generation took 0.2 seconds

C:\Users\uname\Documents\Visual Studio 2015\Projects\firstproject\firstprojec
tTests1\bin\Debug>pause
Press any key to continue . . .

```

**Comment by sawilde** [comment]
mstest doesn't understand the switches you are sending it - why are you sending it nunit switches?

**Comment by unittester57** [comment]
Hi @sawilde , thanks for the reply. I tried running after removing switches. Below is the command line output I got. I think there is a some basic mistake I am doing. Kindly help me with this.

`
C:\Users\username\Documents\Visual Studio 2015\Projects\firstproject\firstprojec
tTests1\bin\Debug>"C:\Users\username\Documents\Visual Studio 2015\Projects\first
project\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe" -register:user
-target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.
exe"
Executing: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTes
t.exe
Microsoft (R) Test Execution Command Line Tool Version 14.0.23107.0
Copyright (c) Microsoft Corporation. All rights reserved.

Please specify tests to run, or specify the /publish switch to publish results.

For switch syntax, type "MSTest /help"
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

C:\Users\username\Documents\Visual Studio 2015\Projects\firstproject\firstprojec
tTests1\bin\Debug>"C:\Users\username\Documents\Visual Studio 2015\Projects\first
project\packages\ReportGenerator.2.5.1\tools\ReportGenerator.exe" "-reports:resu
lts.xml" "-targetdir:.\coverage"
Loading report 'C:\Users\username\Documents\Visual Studio 2015\Projects\firstpro
ject\firstprojectTests1\bin\Debug\results.xml'
 Preprocessing report
 Initiating parser for OpenCover
Initializing report builders for report types: Html
Analyzing 0 classes
 Creating summary
Report generation took 0.2 seconds

C:\Users\username\Documents\Visual Studio 2015\Projects\firstproject\firstprojec
tTests1\bin\Debug>pause
Press any key to continue . . .`

**Comment by sawilde** [comment]
> Please specify tests to run, or specify the /publish switch to publish results.

It doesn't look like you are using mstest properly - first learn how to use mstest on the command line before you try to wrap it with OpenCover.

1. Can you get the tests to run on the command line? What does that look like?
