### ISSUE TITLE
No coverage for AutoMapper project

### ISSUE THREAD

**Issue by TommyEsteban** [OpenCover/opencover#646]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

running Code Coverage in AutoMapper with dotCover gets coverage results

### Actual Behavior

running Code Coverage in AutoMapper with OpenCover gets zero code coverage

### Steps to reproduce the problem:
1. Download AutoMapper from Git: https://github.com/AutoMapper/AutoMapper
2. Compile the code with Visual Studio
3. Run OpenCover with standard commands in AutoMapper\src\UnitTests\bin\Debug\AutoMapper.UnitTests.Net4.dll
4. check results
5. Run any other code coverage tool like dotCover and compare results.

**Comment by sawilde** [comment]
What commands are you using to run OpenCover?
