### ISSUE TITLE
One single assembly is missing from codecoverage while not filtered out.

### ISSUE THREAD

**Issue by marcofranssen** [OpenCover/opencover#649]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [X] .NET Core 1.0.0

### My Environment

- [X] Windows 10

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x ] no coverage being recorded

### Expected Behavior

The API assembly should also get coverage. Currently I have following project structure.

- API.Test
  - API
  - Repository
  - Services
- API
  - Repository
  - Services
- Repository
- Services
  - Repository

So when I run the tests I expect also to get coverage on my API assembly. But for some bizarre reason only the Repo and Services are covered. The test are calling methods on the MVC controller to test the solution.

### Actual Behavior

Only coverage on Services and Repository. The only difference is that the API project depends on the Microsoft stuff for MVC etc. and the Services and Repository is all own code only having the Repository project depend on MongoDB.

### Steps to reproduce the problem:

```
"%userprofile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe" ^
-oldStyle ^
-register:user ^
-target:"C:/Program Files/dotnet/dotnet.exe" ^
-targetargs:"test" ^
-filter:"+[*]* -[API.Tests]* -[Humanizer]* -[Castle.Core]* -[Moq]* -[xunit.*]* -[FluentValidation]*" ^
-mergebyhash ^
-skipautoprops ^
-output:"%~dp0\reports\API.Tests.Coverage.xml"
```

**Comment by sawilde** [comment]
What does it say in the XML file as to the reason for the skip for that assembly?

**Comment by marcofranssen** [comment]
It says MissingPdb. Hmmmm.... Now I'm wondering why it is only this assembly that is missing the pdb file.

**Comment by marcofranssen** [comment]
The strange thing is that the `.pdb` file is in the place where the xml says it is missing.

**Comment by sawilde** [comment]
Then it may be of a format we don't currently handle

**Comment by marcofranssen** [comment]
Basically all the assemblies in the project are build on .net core. All the others are there, except the aspnet core mvc one.

**Comment by sawilde** [comment]
We are dependant on a 3rd party library to handle PDB formats (they keep changing) - unfortunately the latest library is in beta when it comes out of beta then we will integrate it.
