### ISSUE TITLE
DirectoryNotFoundException in console logs in opencover console 

### ISSUE THREAD

**Issue by HPVRNP** [OpenCover/opencover#654]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [X] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [X] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Steps to reproduce the problem:

Fill me in...
I am running below command to generate coverage report for my unit tests.
Command to run my unit tests: 
**OpenCover.Console.exe -register -target:nunit-console.exe "-targetargs:UnitTests.nunit /noshadow /xml:UnitTestResults.xml" -output:UnitTestCoverageResults.xml, -filter:"+[ABC*]*"]**

The coverage reports are generated successfully. 
But I get "DirectoryFileNotFoundException" log in the console output.
PFA the below image for reference
![image](https://cloud.githubusercontent.com/assets/24714755/21422978/858ef01c-c860-11e6-874b-ac502b002ba6.png)

**Comment by sawilde** [comment]
You will have to supply a repeatable scenario; I suspect it is coming from the thing you are running rather than OpenCover.

**Comment by HariPrasadVijayaRani** [comment]
I am getting these errors when I use -register option in the command. 
But my command does not work all the time if I dont use that option

**Comment by sawilde** [comment]
Hi @HariPrasadVijayaRani, as I have said before - you will need to supply a repeatable scenario.

**Comment by HPVRNP** [comment]
What do you mean by repeatable scenario ?

**Comment by sawilde** [comment]
Well something we can run that repeats your scenario - since I don't see what you see, and never have, I can't replicate it and so I am unable to attempt to resolve it.
