### ISSUE TITLE
Comment and empty lines are counted as unreached

### ISSUE THREAD

**Issue by corentinaltepe** [OpenCover/opencover#656]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Do not count the comments and empty lines as uncovered code.

### Actual Behavior

Behavior is strange in some of my files. MOST of the code is counted properly, but still in many places I have have comment lines and empty lines counted as uncovered. Yesterday, OpenCover was accounting the lines properly. Since then, I have added some code, but nothing exceptionnal, (no new project, no more nugget, no new reference).

See here:
![screenshot_20170113_122619_26](https://cloud.githubusercontent.com/assets/14869153/21925043/b7ea1cde-d98c-11e6-9a39-0c4efd603553.png)

I'm using MSTest and the latest version of OpenCover available on Nuget. Here is below the script used to generate the report:

```bat
REM Create a 'GeneratedReports' folder if it does not exist
if not exist "%~dp0GeneratedReports" mkdir "%~dp0GeneratedReports"

REM Remove any previous test execution files to prevent issues overwriting
IF EXIST "%~dp0\GeneratedReports\Innovasub.JapaneseDivePlan.trx" del "%~dp0\GeneratedReports\Innovasub.JapaneseDivePlan.trx%"

REM Remove any previously created test output directories
CD %~dp0
FOR /D /R %%X IN (%USERNAME%*) DO RD /S /Q "%%X"

REM Run the tests against the targeted output
call :RunOpenCoverUnitTestMetrics

REM Generate the report output based on the test results
if %errorlevel% equ 0 (
 call :RunReportGeneratorOutput
)

REM Launch the report
if %errorlevel% equ 0 (
 call :RunLaunchReport
)
exit /b %errorlevel%

:RunOpenCoverUnitTestMetrics
"%~dp0\..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe" ^
-register:user ^
-target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" ^
-targetargs:"/testcontainer:\"%~dp0..\..\Libraries\ProjectName\ProjectName.Test\bin\Debug\ProjectName.Test.dll\" /testcontainer:\"%~dp0..\ProjectNameUI.Test\bin\Debug\ProjectNameUI.Test.dll\" /resultsfile:\"%~dp0\GeneratedReportsProjectName.trx\"" ^
-mergebyhash ^
-skipautoprops ^
-output:"%~dp0\GeneratedReports\ProjectName.xml"
exit /b %errorlevel%

:RunReportGeneratorOutput
"%~dp0..\packages\ReportGenerator.2.5.2\tools\ReportGenerator.exe" ^
-reports:"%~dp0\GeneratedReports\ProjectName.xml" ^
-targetdir:"%~dp0\GeneratedReports\ReportGenerator Output"
exit /b %errorlevel%

:RunLaunchReport
start "report" "%~dp0\GeneratedReports\ReportGenerator Output\index.htm"
exit /b %errorlevel%
```

### Steps to reproduce the problem:

I'm sorry, I cannot disclose my source code or the .dlls. Could you give me any pointer to what might be the cause of the issue or what info I should be providing to fixing the issue? If I can fix it, I'll promise to tell you what was the cause.

Many thanks!

**Comment by sawilde** [comment]
OpenCover only knows about the IL and what the PDB says are the lines covered by each instrumented sequence point, it does not know what the lines of code actually are.

Check that the DLL/PDB match the code being reported against; it is not uncommon for tests to be run but between the coverage being run and the report generated the code files have since changed.

**Comment by corentinaltepe** [comment]
Hi,
thank you for your reply. I'll make sure to erase all .dll, .pdb and .exe manually. Sometimes Visual Studio's 'clean' doesn't work really well. I'll post again whether this worked or not.

**Comment by corentinaltepe** [comment]
Hello,

indeed, a good clean solved the issue. I manually deleted all the files laying in the /bin/ folder. Thank you for the pointers!
