### ISSUE TITLE
Coverage on CI (GitLab)

### ISSUE THREAD

**Issue by wahmedswl** [OpenCover/opencover#659]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [x] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Coverage information should be extracted just like i normally able to get on Local Machine.
```
Committing...                                                                                    
Visited Classes 66 of 168 (39.29)                                                                
Visited Methods 391 of 986 (39.66)                                                               
Visited Points 2432 of 5980 (40.67)                                                              
Visited Branches 1422 of 3874 (36.71)                                                            
                                                                                                 
==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 86 of 183 (46.99)                                                    
Alternative Visited Methods 457 of 1143 (39.98)                                                  
```

### Actual Behavior

When its run in Gitlab Runner, its not able to get coverage and gives up following message
```
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
```

### Steps to reproduce the problem:

I am using OpenCover with Cake on GitLab, following is the minimal build.cake file

```
#tool "nuget:?package=xunit.runner.console"
#tool "nuget:?package=OpenCover"
#tool "nuget:?package=ReportGenerator"

Task("Run-Unit-Tests").Does(() =>
{
    EnsureDirectoryExists("./build/32+64bit/OpenCover/");
    OpenCover(tool => {
        tool.XUnit2("./build/32+64bit/TestAndPerf/**/TestAndPerf.dll", new XUnit2Settings {
            Parallelism = ParallelismOption.Collections,
            ShadowCopy = false
        });
    },
    "./build/32+64bit/OpenCover/OpenCover.xml",
    new OpenCoverSettings { ReturnTargetCodeOffset = 0, Register = "user" }
        .WithFilter("+[SequelMed*]*")
        .WithFilter("-[*]xunit.*"));

    // TODO: Need to think about how to bring this out in a generic way for all Test Frameworks
    ReportGenerator("./build/32+64bit/OpenCover/OpenCover.xml", "./build/32+64bit/OpenCover");
});

Task("Default").IsDependentOn("32+64bit").IsDependentOn("Run-Unit-Tests").IsDependentOn("64bit").IsDependentOn("32bit");

RunTarget(target);

```

Any help would be appreciated
Thanks

**Comment by wahmedswl** [comment]
Tweaked OpenCover setting in build.cake and its working now
```
Task("Run-Unit-Tests").Does(() =>
{
    EnsureDirectoryExists("./build/32+64bit/OpenCover/");
    OpenCover(tool => {
        tool.XUnit2("./build/32+64bit/TestAndPerf/**/TestAndPerf.dll", new XUnit2Settings {
            Parallelism = ParallelismOption.Collections,
            ShadowCopy = false
        });
    },
    "./build/32+64bit/OpenCover/OpenCover.xml",
    new OpenCoverSettings { ReturnTargetCodeOffset = 0, Register = "Path64" }
        .WithFilter("+[SequelMed*]*")
        .WithFilter("-[*]xunit.*"));

    // TODO: Need to think about how to bring this out in a generic way for all Test Frameworks
    ReportGenerator("./build/32+64bit/OpenCover/OpenCover.xml", "./build/32+64bit/OpenCover");
});
```

Thanks @pitermarx from cake gitter channel who helped me

**Comment by sawilde** [comment]
glad you got it sorted as I know nothing about cake
