### ISSUE TITLE
Escaping quotation in targetargs in powershell

### ISSUE THREAD

**Issue by garyamorris** [OpenCover/opencover#660]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [x] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [x] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I'm attempting to call Nunit console runner from opencover, and I need to specify the target args in powershell with an escaped quotation. 

PS C:\build> C:\OpenCover.Console.exe -target:"C:\nunit3-co
nsole.exe" "-targetargs:C:\UnitTest.dll \"--result=output.xml;format=nunit2\" "

### Actual Behavior

This doesn't get passed in as an argument but it rather is evaluated as another Test.dll.

### Steps to reproduce the problem:

Run open cover from powershell with Nunit-console test runner and supply -result argument in escaped quotations.

**Comment by sawilde** [comment]
If you are going to use quotes in quotes you will need to escape them e.g.

    C:\OpenCover.Console.exe -target:"C:\nunit3-console.exe" "-targetargs:C:\UnitTest.dll \"--result=output.xml;format=nunit2\" "

**Comment by garyamorris** [comment]
Sorry, I should have been more clear, I did try that escape method and it still didn't work. I eventually found that the issue lay with a missing v2 result writer reference on my build server and was not related to opencover.

**Comment by sawilde** [comment]
@garyamorris ah yes I see - it looks like the markup hid your escaping - glad you got it sorted
