### ISSUE TITLE
Some xUnit and NUnit test attributes are not supported by cover by test feature

### ISSUE THREAD

**Issue by axodox** [OpenCover/opencover#661]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior

OpenCover should support all xUnit and NUnit test attributes, including NUnit.Framework.TestCaseSourceAttribute and Xunit.TheoryAttribute.

### Actual Behavior

Cover-by-test feature does not track all the test methods in xUnit and NUnit with the attributes mentioned above.

### Steps to reproduce the problem:

Create xUnit and NUnit tests with the mentioned attributes and enable the cover by test feature, the tests marked by the said attributes will not be tracked in the results.

**Comment by sawilde** [comment]
should've been closed a long time ago
