### ISSUE TITLE
OpenCover & NUnit release build tests fail

### ISSUE THREAD

**Issue by fakeplayerr** [OpenCover/opencover#663]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

To run tests in release mode

### Actual Behavior

When I run the OpenCover with the tests from release build it doesn't work. If i run the same build with debug tests it works.

### Steps to reproduce the problem:

Running opencover with Nunit from console with -register:user.
When I use -register:Path32 or -register:Path64 it works but i want it to work with register:user, otherwise it will not cover all the paths in my application

Fill me in...

Error received:
System.InvalidProgramException : Common Language Runtime detected an invalid program

For other details please ask

**Comment by sawilde** [comment]
Unfortunately I am unable to repeat your issue - are you able to supply a sample project that repeats the scenario?

**Comment by fakeplayerr** [comment]
sorry for late reply. i was at a training but now i am back to work. unfortunately i can't because it's work related. the thing is when i use it in release mode the tests are failing but when i run them in debug mode it works. i think is something related with the compression of minifcation of the files to build for release and it's conflicting some variables. But this is something i am thinking about. I am not sure if this is the problem

**Comment by goflyapig** [comment]
I believe I'm having the same issue (I can open another issue if you'd prefer). Here is a repro: 
[OpenCoverOptimizedCodeBug.zip](https://github.com/OpenCover/opencover/files/865732/OpenCoverOptimizedCodeBug.zip)

To run, check the three paths at the top of `RunDemo.ps1` (modify if necesssary), and run it (you can double-click `RunDemo.cmd`).

It first runs the tests via NUnit directly (they pass), and then via OpenCover (they fail with `System.InvalidProgramException`). It seems to happen because a try-catch is being optimized away.

BTW, I was *trying* to create a minimal reproduction of a different issue that I'm seeing where I actually get wrong results (e.g. "Expected 5, got 7") rather than an InvalidProgramException. I can't come up with a small repro, so my hope is that that issue has the same underlying cause as this.

**Comment by sawilde** [comment]
@goflyapig very interesting - the profiler should disable optimisations so what makes you think that?

**Comment by goflyapig** [comment]
Well, it was really a wild guess. I only noticed that the issue only occurs when the try-catch is there *and* `/optimize` is passed to `csc`. I admittedly don't know much about how the profiler works.

**Comment by sawilde** [comment]
@goflyapig - I see you mean compiler optimisation - the profiler only disables runtime optimisations so that it can instrument the assembly.

**Comment by sawilde** [comment]
@goflyapig when this build is done you should be able to download a beta version for local testing

**Comment by sawilde** [comment]
A beta build is available here https://ci.appveyor.com/project/sawilde/opencover/build/4.6.682/artifacts

**Comment by balaji8** [comment]
> @goflyapig A beta build is available here https://ci.appveyor.com/project/sawilde/opencover/build/4.6.682/artifacts

Hi @sawilde, 

Would it be possible to make this version available via Nuget?

Thanks!

**Comment by sawilde** [comment]
@balaji8 a release candidate is already on nuget

**Comment by balaji8** [comment]
> @balaji8 a release candidate is already on nuget

Thank you for the quick response. It looks like OpenCover 4.7.870-rc requires .Net 4.7.2 and we are unable to install/upgrade to it at the moment. We are on .Net 4.6 and are affected by this issue as well. Hence my request to have 4.6.682 available in Nuget.

**Comment by sawilde** [comment]
@balaji8 I have uploaded 682 as an RC package as I am not sure as to its quality and can't support it

**Comment by balaji8** [comment]
> @balaji8 I have uploaded 682 as an RC package as I am not sure as to its quality and can't support it

Thank you @sawilde! Much appreciated..
