### ISSUE TITLE
Unable to see code coverage for one of my projects

### ISSUE THREAD

**Issue by kalyanbhave** [OpenCover/opencover#667]
I am not able to see code coverage value to one of my projects.I execute below commands to fetch the same in Jenkins.

### My Framework

- [ ] .C#
- [ ] .Open-cover
- [ ] .NUnit
- [ ] .Sonarqube
- [ ] .Jenkins

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded

### Actual Behavior

![untitled](https://cloud.githubusercontent.com/assets/17975836/23985136/5d90a7de-0a43-11e7-8047-0a390b3d8726.png)
![image](https://cloud.githubusercontent.com/assets/17975836/23985154/7a7ab646-0a43-11e7-9f0a-ac1220c0ac2e.png)

### Error Logs

C:\TravelInsurance\BTS>C:\Users\Administrator\AppData\Local\Apps\OpenCover\OpenCover.Console.exe "-target:C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "-targetargs:C:\Example.Tests.dll /exclude:Unit" -register:Administrator 
Executing: C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe
NUnit Console Runner 3.5.0 
Copyright (C) 2016 Charlie Poole

Invalid argument: /exclude:Unit
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

### Steps to reproduce the problem:

NUnit Condition
"C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "C:\Example.Tests.dll"  --where "cat == Unit" --result:Example.nunit-result.xml

Open-cover Condition

C:\Users\Administrator\AppData\Local\Apps\OpenCover\OpenCover.Console.exe "-target:C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "-targetargs:C:\result:Example.Tests.dll /exclude:Unit" -register:Administrator

**Comment by sawilde** [comment]
Can you make it work on the command line outside of the sonar/jenkins environment?

**Comment by kalyanbhave** [comment]
Finally got the answer of this. C:\Users\Administrator\AppData\Local\Apps\OpenCover\OpenCover.Console.exe "-target:C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "-targetargs:C:\result:Example.Tests.dll --**where=cat=Unit**" -register:Administrator
