### ISSUE TITLE
Code Coverage for .NET Core Integration tests

### ISSUE THREAD

**Issue by kohli-harshit** [OpenCover/opencover#668]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [X] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior

Coverage.XML should have the footprints.

### Actual Behavior

Blank Coverage file after the site has been hit with some requests.

### Steps to reproduce the problem:

C:\tools\OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"C:\MyAppPath\MyApplication.DLL" -targetdir:"C:\MyAppPath" -register:administrator -output:coverage.xml

Executing: C:\Program Files\dotnet\dotnet.exe
Hosting environment: Test
Content root path: C:\MyAppPath
Now listening on: http://localhost:5000

Application Started. Press Ctrl+C to shut down.

After this, I hit some requests to localhost:5000 and then press Ctrl+C. After this, the coverage.xml is a blank file.

**Comment by sawilde** [comment]
We don't support .NET core yet but we do have an old beta that we produced as an experiment.

see - https://github.com/OpenCover/opencover/pull/613

**Comment by kohli-harshit** [comment]
Hi,

I was able to resolve this issue by registering the profiler from your beta build. The only caveat here is that for OpenCover to exit gracefully, I can't use Ctrl + C as this doesn't generate the coverage file, so I kill the dotnet.exe process and then OpenCover generates the coverage file.

Thanks for pointing me to the right direction !

Regards,
Harshit Kohli
