### ISSUE TITLE
Windows2012 & Dot NET CLR v4.0.30319&IIS7.5 support

### ISSUE THREAD

**Issue by qshxn** [OpenCover/opencover#671]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [X] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [X] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request
- [X] win2012 support

### Expected Behavior

I expected that my application could run under IIS7.5& win2012 via opencover like win2008 and win7. 

IIS7.5
Windows2012
Framework is the Dot NET CLR v4.0.30319.

### Actual Behavior
 OpenCover could not  run the w3wp.exe process.

### Steps to reproduce the problem:

1.1 stop IIS service
net stop w3svc /y
1.2 via OpenCover.Console.exe run IIS for my application 
OpenCover.Console.exe -target:C:\Windows\System32\inetsrv\w3wp.exe -targetargs:-debug -targetdir:D:\WebSites\test\payment-base-managedservice\353708\bin -filter:+[Ctrip.Payment*]* -register:user -output:D:\WebSites\test\result\coverage.xml
1.3 test the application 

1.4 stop opencover，restart IIS service
console quit, and net start w3svc

**Comment by sambafeng** [comment]
I meet the same problem.

**Comment by sawilde** [comment]
I've never tried it myself as I don't use OpenCover with IIS as I prefer to use IISExpress. 

Are you seeing any errors/messages in the Application EventLog?

**Comment by qshxn** [comment]
hi sawilde,thanks for your nice help. Multiple attempts, we discovered it is ok when pool same name as the website. then we blocked by another question. we expect the report can be generated when IIS are runing, In other words need not press "Q"and reset IIS process ,the report can be generated via other command . And then the report are accumulation, until we set replacement of assets.

**Comment by sawilde** [comment]
@qshxn this is not currently possible - you could raise it is a feature and if urgent implement it yourself.

**Comment by qshxn** [comment]
@sawilde we filter testcases via code coverage, because we have  a lot of testcases, many of them can't raise the report. we need the testcases can raise the report for next test pass, then save time of regression testing pass.

**Comment by sawilde** [comment]
@qshxn perhaps you need to write a program that will automate the process for you e.g.
- list all tests (group by categories)
- launch opencover and execute each batch of tests against your site
- once complete aggregate your reports

**Comment by qshxn** [comment]
yep,we really write the program. so we need aggregate the reports after each test against my site. the testcases can't be classified. the testcases are the request that  the site open many APIs.

**Comment by qshxn** [comment]
@sawilde help, when we write the program,  stop opencover manual press "Q", how to write automate via the program. we try to send ascii of Q, but it is not ok. thank you for your support.

**Comment by qshxn** [comment]
@sawilde we downloaded your source code. miss version.cs, it can not be built complete. Could you give us the source code can be built complete,thank you.


_Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'D:\opencover-master\opencover-master\main\OpenCover.Console\..\..\build\Version\Version.cs' could not be found.	OpenCover.Console	D:\opencover-master\opencover-master\main\OpenCover.Console\CSC	1	Active
Error	CS2001	Source file 'D:\opencover-master\opencover-master\main\OpenCover.Extensions\..\..\build\Version\Version.cs' could not be found.	OpenCover.Extensions	D:\opencover-master\opencover-master\main\OpenCover.Extensions\CSC	1	Active
Error	CS2001	Source file 'D:\opencover-master\opencover-master\main\OpenCover.Framework\..\..\build\Version\Version.cs' could not be found.	OpenCover.Framework	D:\opencover-master\opencover-master\main\OpenCover.Framework\CSC	1	Active
Error	CS0006	Metadata file 'D:\opencover-master\opencover-master\main\OpenCover.Framework\bin\Debug\OpenCover.Framework.dll' could not be found	OpenCover.Integration.Test	D:\opencover-master\opencover-master\main\OpenCover.Integration.Test\CSC	1	Active
Error	CS2001	Source file 'D:\opencover-master\opencover-master\main\OpenCover.MSBuild\..\..\build\Version\Version.cs' could not be found.	OpenCover.MSBuild	D:\opencover-master\opencover-master\main\OpenCover.MSBuild\CSC	1	Active
Error	RC1015	cannot open include file '..\..\build\version\version.h'.	OpenCover.Profiler	D:\opencover-master\opencover-master\main\OpenCover.Profiler\OpenCover.Profiler.rc	59	
Error		3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.	OpenCover.Simple.Target.Core	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262	
Error		2. The project does not list one of 'win7-x64' in the 'runtimes' section.	OpenCover.Simple.Target.Core	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262	
Error		1. The project has not been restored or restore failed - run `dotnet restore`	OpenCover.Simple.Target.Core	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262	
Error		Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win7-x64'. Possible causes:	OpenCover.Simple.Target.Core	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262	
Error	CS2001	Source file 'D:\opencover-master\opencover-master\main\OpenCover.Test\..\..\build\Version\Version.cs' could not be found.	OpenCover.Test	D:\opencover-master\opencover-master\main\OpenCover.Test\CSC	1	Active_

**Comment by sawilde** [comment]
you didn't build from the command line (it will generate the missing files and do other build magic) - try building from the command line as described here (and make sure you have all the prerequisites)

https://github.com/OpenCover/opencover#building

**Comment by qshxn** [comment]
thank you.  and could you have a good idea for press "Q" in our program?

**Comment by sawilde** [comment]
this is where the host waits for the target process to exit

https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Console/Program.cs#L373

Why can't you terminate the target process from your scripts - when it terminates opencover will generate the report.
