### ISSUE TITLE
Since DeploymentItem doesn't work, can we configure where to start mstest?

### ISSUE THREAD

**Issue by rpokrovskij** [OpenCover/opencover#673]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [X] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior
opencover used with VisualStudio (as NUGET package to test project) with multiple projects in powershel script.

1) It should be clear from documentation does nuint's DeploymentItem attribute work when user starts mstest from opencover. In my case I can't get it work. output folder doesn't contain .json file that should be used by tests (and specified in DeploymentItem). Documentation should be appended. 

2) In mstest /noisolation mode I expect that mstest will be started in current folder. But this is not true. It is always started in the MSTest.exe location folder (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\). Setting -targetdir doesn't help  I have a doubts that opencover can help me there, but if it will be possible to run mstest in folder I need, there will be no problem for mstest to find a json file I need.

Of course I can copy file manually, but I want to automatize it.

TRX file

```
          <Message>Test method Vse.Routines.Configuration.NETStandard.Test.StandardConfigurationUnitTest.JsonConfigurationTest threw exception: 
System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\appsettings.json'.</Message>
```

PS opencover call

`& $openCoverLocation "-register:user" "-target:$mstestLocation" "-targetargs:$targetargs" "-targetdir:$targetdir" "-filter:$filters" "-mergebyhash"  "-skipautoprops" "-output:$OpenCoverOutput" "-mergeoutput" `

where $targetargs

`$targetargs="/testcontainer:$testDll /nologo /usestderr /noisolation /resultsfile:$MsTestFolder\results$trx.trx"`

**Comment by sawilde** [comment]
If you have an example project that replicates the issue then I may be able to help but otherwise you are on your own.

**Comment by rpokrovskij** [comment]
After studding the situation  I get it as mstest do not interpetate DeploymentItem (or in many cases do it wrong) so it is either impossible or wrong to solve the problem on the opencover layer.

I have summarized it and workaround there:  https://github.com/rpokrovskij/opencover4vs.ps1

**Comment by sawilde** [comment]
@rpokrovskij I agree it isn't really an OpenCover issue

**Comment by rpokrovskij** [comment]
@sawilde , but still, please, add an argument to setup "target" (mstest) execution/working folder. It would add flexibility experimenting with command line. -targetdir doesn't setup the target's working folder (at least in case when target/mstest configured with full pass).

**Comment by sawilde** [comment]
@rpokrovskij I don't understand - if you know what needs to be done then please add it yourself and submit a PR

**Comment by rpokrovskij** [comment]
@sawilde I see that you do not understand what is working folder. The folder that would be returned as Directory.GetCurrentDirectory by the process.  

https://msdn.microsoft.com/en-us/library/system.io.directory.getcurrentdirectory%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

E.g. if target is mstest
then it should be started as
cd %workingdir%
mstest.exe

Currently it is impossible to setup working folder (the folder from which the mstest will be started).

**Comment by sawilde** [comment]
@rpokrovskij perhaps you need to launch mstest differently.

For complex test scenarios I often wrap my test executions in a batch file and then get OpenCover to execute that instead.
