### ISSUE TITLE
"using" statement causes incorrect Branch Coverage percentage

### ISSUE THREAD

**Issue by haison8x** [OpenCover/opencover#675]
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [X] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior

The branchCoverage percentage must be 100%

### Actual Behavior

The branchCoverage percentage only is 83.33%

### Steps to reproduce the problem:
My problem is similar with the [issue #207](https://github.com/OpenCover/opencover/issues/207). This issue was fixed 2 years ago, but I think there are something should be rechecked

I have following codes:
        `public async Task<string> Test()`
       ` {`
            `using (var client = new HttpClient())`
           ` {`
                `var response = await client.GetAsync("http://google.com.vn");`
                `return await response.Content.ReadAsStringAsync();`
            `}`
       ` }`

(You can get this code from https://github.com/haison8x/TestCoverage.git)

However, the coverage.xml show that the branchCoverage only 83.33%

`<Summary numSequencePoints="11" visitedSequencePoints="11" numBranchPoints="6" visitedBranchPoints="5" sequenceCoverage="100" branchCoverage="83.33" maxCyclomaticComplexity="9" minCyclomaticComplexity="1" visitedClasses="2" numClasses="2" visitedMethods="2" numMethods="2" />`

And the report which generated by ReportGenerator.exe shows inconsistency information

![coverage](https://cloud.githubusercontent.com/assets/3090475/24646437/2e06b8a2-1946-11e7-821f-429e799a2775.png)

**Comment by sawilde** [comment]
> My problem is similar with the issue #207. This issue was fixed 2 years ago, but I think there are something should be rechecked

This is the problem with branch coverage from the IL itself as the compiler may add extra branches for scenarios you haven't tested or are unable to. 

We can try and fix the issue again but it can easily break the next time the compiler changes what it outputs for the code.
