### ISSUE TITLE
Always skipping my project if this starts with System or System.Linq ?

### ISSUE THREAD

**Issue by StefH** [OpenCover/opencover#676]
### My Framework
- [x] .NET Core App 1.x

### My Environment
- [x] Windows 10
### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):
- [x] no correct coverage being recorded

### Expected Behavior

**All** my code should be processed when the filter option `-filter:"+[*]*"` is used.

### Actual Behavior

My main project is called `System.Linq.Dynamic.Core`, however it seems that this namespace is always skipped!

### Steps to reproduce the problem:
See my project : https://github.com/StefH/System.Linq.Dynamic.Core and see the codecov report here https://codecov.io/gh/StefH/System.Linq.Dynamic.Core

**Comment by sawilde** [comment]
Thanks for letting us know - I'll have a look but support for .NET core is sketchy at best at the moment.

**Comment by sawilde** [comment]
@StefH I had a look at codecov and I see you have coverage - did you resolve your issue?

**Comment by StefH** [comment]
I did take a look at the source code from opencover, and I found out that you can supply the ` -nodefaultfilters` argument. This solved my problem.
