### ISSUE TITLE
How to terminate OpenCover.Console process on remote server

### ISSUE THREAD

**Issue by SuSaiGit** [OpenCover/opencover#713]
I have managed to start OpenCover session on a remote server using below command
------------------------
Invoke-Command -ComputerName $vm -Credential $cred -ScriptBlock {
    net stop w3svc /y
    C:\OpenCoverIIS\OpenCoverIISOnVM.bat
}
--------------------------
---Inside OpenCoverIISOnVM.bat-------------
C:\OpenCoverIIS\OpenCover.Console.exe -target:C:\Windows\System32\inetsrv\w3wp.exe -targetargs:"-debug -s 1" -targetdir:C:\inetpub\wwwroot\apiv3\bin -register:administrator -output:SystemTestResults.xml
--------------------------
It is impossible to send Q key event to the process since the OpenCover.Console process is running in session 0 on remote server which doesn't have desktop or UI involved.
Is there any other method to terminate the OpenCover.Console session/process?
----------------------------

Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [X] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by sawilde** [comment]
Stop the IIS process - this will terminate the profiler and OpenCover should 'eventually' detect that and close down.

**Comment by SuSaiGit** [comment]
Thank you. Below command made the magic.
Invoke-Command -ComputerName $vm -Credential $cred -ScriptBlock { Stop-Process -Name "w3wp" }
