### ISSUE TITLE
NPath complexity overflows.

### ISSUE THREAD

**Issue by jswolf19** [OpenCover/opencover#717]
Calculating NPath complexity is prone to integer overflow leading to incorrect results.

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [X] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I'm not sure. One method would be to use a long or decimal, but the chance for overflow still exists, and there's probably little value in getting the exact result over a certain threshold. Perhaps a special value for the nPathComplexity attribute if overflow occurs, a separate attribute to convey that overflow occured, or just omitting it altogether.

### Actual Behavior

The result eventually wraps to 0, then gets reassigned to a non-zero value and continues increasing again.

### Steps to reproduce the problem:

Test a method such as the following:

```
        public static int NPathOverflows() {
            var rand = new Random();

            int result = 0;

            if(rand.Next(2) == 0) result++; //  1
            if(rand.Next(2) == 0) result++; //  2
            if(rand.Next(2) == 0) result++; //  3
            if(rand.Next(2) == 0) result++; //  4
            if(rand.Next(2) == 0) result++; //  5
            if(rand.Next(2) == 0) result++; //  6
            if(rand.Next(2) == 0) result++; //  7
            if(rand.Next(2) == 0) result++; //  8
            if(rand.Next(2) == 0) result++; //  9
            if(rand.Next(2) == 0) result++; // 10
            if(rand.Next(2) == 0) result++; // 11
            if(rand.Next(2) == 0) result++; // 12
            if(rand.Next(2) == 0) result++; // 13
            if(rand.Next(2) == 0) result++; // 14
            if(rand.Next(2) == 0) result++; // 15
            if(rand.Next(2) == 0) result++; // 16
            if(rand.Next(2) == 0) result++; // 17
            if(rand.Next(2) == 0) result++; // 18
            if(rand.Next(2) == 0) result++; // 19
            if(rand.Next(2) == 0) result++; // 10
            if(rand.Next(2) == 0) result++; // 21
            if(rand.Next(2) == 0) result++; // 22
            if(rand.Next(2) == 0) result++; // 23
            if(rand.Next(2) == 0) result++; // 24
            if(rand.Next(2) == 0) result++; // 25
            if(rand.Next(2) == 0) result++; // 26
            if(rand.Next(2) == 0) result++; // 27
            if(rand.Next(2) == 0) result++; // 28
            if(rand.Next(2) == 0) result++; // 29
            if(rand.Next(2) == 0) result++; // 30
            if(rand.Next(2) == 0) result++; // 31
            if(rand.Next(2) == 0) result++; // 32
            if(rand.Next(2) == 0) result++; // 33

            return result;
        }
```

**Comment by sawilde** [comment]
we use an `int` so surprised you managed to overflow it but if you did then you should really rewrite you code - again this value is more of a guide since it is based on IL branches and not source code.

**Comment by jswolf19** [comment]
I wholly agree on the likely need for rewriting, but that's unfortunately not my decision. Being based on IL branches isn't an issue in my mind, that's the more correct value. I also agree that there's a point where the actual value isn't important. However when it's very large but is reported as 64 or so, then that's not a very good guide in my mind.

**Comment by sawilde** [comment]
What number are you expecting for the sample you gave? Since we are using an `int` the max value for this is 2,147,483,647 - so I do not understand how you managed to get it to overflow.

**Comment by sawilde** [comment]
No worries I am being dim this morning I mixing up npath and cyclomatic complexity.

**Comment by jswolf19** [comment]
@sawilde It should be 2<sup>33</sup>, since it is exponential with conditionals in series like the example I provided. It may be best to keep it an int and just let it be 0 once it gets too big (since 0 is not a valid nPath result, and any tools relying on the value of the nPathComplexity attribute to be an int value won't be surprised).

**Comment by jswolf19** [comment]
It looks like [ReportGenerator](https://github.com/danielpalme/ReportGenerator/blob/1598611cbec16dbc8a9d28f33d9f1b74aa61584a/ReportGenerator/Parser/OpenCoverParser.cs#L129) is using int.Parse, so putting in non-int values would require a change there.

Using 0 or a negative value makes it more obvious that it's an invalid result, but that might mess up someone looking for a min value, so the best bet might be to just cap it at int.MaxValue. If you want to make the final call on what to do, @sawilde, I'll look into putting together a pull request for the fix.

**Comment by sawilde** [comment]
I think capping it an `int.MaxValue` will signify *big*

**Comment by jswolf19** [comment]
It looks like I can either do a `checked` multiplication and handle any `OverflowException` that results, or I can check the result myself to avoid exception usage. Do you have a preference?

**Comment by sawilde** [comment]
I think `checked` as it is more obvious about what the intention is

**Comment by jswolf19** [comment]
Okay. I'm also getting having trouble building from the command line.

One issue is that I don't have a 4.6 Tools folder in my SDK dir, only 4.6.1, 4.6.2, and 4.7 even after installing the Windows SDK and .Net 4.6.2 dev pack linked in the readme. (I'm using a pretty new PC...) If I change the build script to look in 4.6.1 Tools, then I can build with errors from the command line and can build successfully from OpenCover.sln in Visual Studio (Community Edition). I've attached the output from executing build.
[buildLog.txt](https://github.com/OpenCover/opencover/files/1033361/buildLog.txt)

**Comment by sawilde** [comment]
Do you have the c++ build tools installed as part of Visual Studio (not a lot of people do)?

**Comment by jswolf19** [comment]
I have the Desktop development with C++ workload installed with most optional components included. I don't see anything called c++ build tools in the Individual components list... If you want, I can list up all the ones I have checked (or the ones I don't)

Also, my VS installation isn't in the regular program files directory because it wanted more space than I wanted to give up on my system drive, if that makes a difference.

**Comment by sawilde** [comment]
Sorry I am at a loss then, I assume you followed the instructions in the readme?

https://github.com/OpenCover/opencover#building

I don't recall doing anything unusual - the build server is 3rd party and the only thing I add on top of that image is 4.6.2.

**Comment by jswolf19** [comment]
It seems to be the msbuild that's being used by the build scripts. It seems that opencover.build looks for msbuild in program.files.x86, and if it doesn't find it there, it uses msbuild in netfx4.folder, so it was because I changed the location of my installation... If I change the fallback to use msbuild from the path, then I can build in a Developer Command Prompt.

I've got some failing tests when I build, but build create-release succeeds.

**Comment by sawilde** [comment]
> I've got some failing tests when I build, but build create-release succeeds.

we'll see when the PR goes through

**Comment by sungam3r** [comment]
It seems to me that I too ran into this error. Please look at this issue: danielpalme/ReportGenerator#199

**Comment by jswolf19** [comment]
> 
> 
> It seems to me that I too ran into this error. Please look at this issue: [danielpalme/ReportGenerator#199](https://github.com/danielpalme/ReportGenerator/issues/199)

Do you know if you are using a version of OpenCover that includes PR #719?

**Comment by sungam3r** [comment]
I'm using the latest stable version - 4.6.519.

**Comment by sawilde** [comment]
@sungam3r only the release candidates have this fix in

**Comment by sungam3r** [comment]
Ok. Can you tell me when the next stable version is expected?

**Comment by sawilde** [comment]
@sungam3r hopefully by end Jan/early Feb - all depends on how many people take up the RC (also on nuget) and if any issues arise from it.
