### ISSUE TITLE
Null propagation operator usage in an if statement leads to incorrectly calculated branch count

### ISSUE THREAD

**Issue by voodookoop** [OpenCover/opencover#718]
Null propagation operator usage in an if statement leads to incorrectly calculated branch count.

### My Framework

- [X] .NET Core 1.0.0

### My Environment

- [X] Windows 7 or below (not truly supported due to EOL)

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

The following if statement should be considered as 3 possible branches:

`if (dc?.Address == null)`

, as the following cases can occur:

1. dc is null
2. dc is not null and Address is null
3. dc is not null and Address is not null

### Actual Behavior

OpenCover calculates `if (dc?.Address == null)` as 4 branches .

`<SequencePoint ... bec="4" ... />`

### Steps to reproduce the problem:

Write a null check into an if statement that contains null propagation. See code snippets above.

**Comment by sawilde** [comment]
Opencover uses IL branches not source code branches and so the count is correct as your null propagation expands to 4 branch paths - you may want o look at what IL code has been produced.

    if (dc?.Address == null) { ... }

becomes (in IL) see the two conditional branches at IL_0002 and IL_0012

````
.method public hidebysig static 
	void Test (
		class nullprop.Context dc
	) cil managed 
{
	// Method begins at RVA 0x2074
	// Code size 34 (0x22)
	.maxstack 2
	.locals init (
		[0] bool
	)

	IL_0000: nop
	IL_0001: ldarg.0
	IL_0002: brtrue.s IL_0007

	IL_0004: ldnull
	IL_0005: br.s IL_000d

	IL_0007: ldarg.0
	IL_0008: call instance string nullprop.Context::get_Address()

	IL_000d: ldnull
	IL_000e: ceq
	IL_0010: stloc.0
	IL_0011: ldloc.0
	IL_0012: brfalse.s IL_0021

	IL_0014: nop
	IL_0015: ldstr "haha"
	IL_001a: call void [mscorlib]System.Console::WriteLine(string)
	IL_001f: nop
	IL_0020: nop

	IL_0021: ret
} // end of method Program::Test
````

and when decompiled back to C#

    bool flag = ((dc != null) ? dc.Address : null) == null;
    if (flag)
    {
        Console.WriteLine("haha");
    }

**Comment by voodookoop** [comment]
@sawilde thanks for the detailed explanation. I still think that this is a misleading measurement, hence a bug. There is no possibility to write any unit tests that cover 4 cases for this statement.

Moreover:

`if (dc == null || dc.Address == null)`

is equivalent to

`if (dc?.Address == null)`

by their possible outcomes, still, the former will be marked by OpenCover as 2 branches, the latter as 4 branches, while both of them are 3 branches in my opinion.

Can you or someone confirm or disprove my theory?

**Comment by sawilde** [comment]
It is only a bug if it wasn't intentional, OpenCover measures IL branches and is hence correct in its calculation even if not the one you want. 

There should be 2 branch statements and hence 4 paths with either so that is a possible defect.

There are though as you say only 3 possible cases and they should exercise all 4 paths through the code as the `number of branches` != `number of paths` through the code.

**Comment by sawilde** [comment]
> so that is a possible defect.

yes it is a defect but only for assemblies built in debug mode - if your target assembly is in release mode then it correctly identifies both branches
