### ISSUE TITLE
Is it compatible with net standard?

### ISSUE THREAD

**Issue by ComptonAlvaro** [OpenCover/opencover#721]
I am trying to test a .net standard 1.4 library and I don't get the results of this library, just the test assembly. So I am wondering if opencover is compatible with .net standard or not.

Thanks.

**Comment by sawilde** [comment]
@ComptonAlvaro it is if you use full pdbs - we do have a new build coming soon that will deal with embedded and portable pdbs

**Comment by ComptonAlvaro** [comment]
@sawilde Thanks for your help. Could you tell me how to use full pdbs with .net Sstandard assembly? There are documentation about this?

Thanks so much.

**Comment by sawilde** [comment]
@ComptonAlvaro we do support .netstandard but you'll need to use the beta package

https://ci.appveyor.com/project/sawilde/opencover/build/artifacts

**Comment by thnk2wn** [comment]
How do we get the beta package exactly @sawilde? The link provided only shows me a build log. Is there a prerlease nuget or a binary I'm not seeing? 

Also will this support .net standard 1.4 or is it 2.0 only?

**Comment by sawilde** [comment]
the above link is to the latest build, the current one of which just happened to be a special analysis build and not one that creates redistributable artifacts

https://ci.appveyor.com/project/sawilde/opencover/build/4.6.766/artifacts

**Comment by mac31** [comment]
@sawilde does 4.6.766 build support xunit?

**Comment by sawilde** [comment]
@mac31 It should but you never know :) best thing is to try and see

**Comment by mac31** [comment]
Thanks @sawilde! just wanted to confirm that as I was getting 0% coverage, then I added -noshadow switch. It works okay now :)

**Comment by sawilde** [comment]
yeah `-noshadow` switches work on the test executable if available or using `-searchdirs:` with OpenCover may also achieve what you want.

**Comment by mac31** [comment]
thanks @sawilde !

**Comment by thnk2wn** [comment]
@sawilde We were able to use the beta package from AppVeyor in PowerShell. However for our CI build we use Cake and I'm not sure I can easily point Cake OpenCover to a local package (don't think #tool supports it). Is it possible to get the beta package on NuGet as a prerelease version? Or if it's likely to roll into non-prerelease soon we can just revisit later. Thanks

**Comment by sawilde** [comment]
@thnk2wn I honestly don't know - there is stuff that needs doing and well life has got in the way.

**Comment by thnk2wn** [comment]
@sawilde Certainly understand that. Thanks for the update and all your work!
