### ISSUE TITLE
Sufficiently complicated switch reports wrong branch coverage.

### ISSUE THREAD

**Issue by GregReddick** [OpenCover/opencover#724]
When there is a sufficiently complicated switch statement, coverage is not showing all branches are being hit, even though they are. Slightly reducing the complexity of the switch results in 100% branch coverage. Has something to do with the compiler using a different technique to manage complicated switch statements.

### My Framework

- [X ] .NET 4.5

### My Environment

- [ X] Windows 10

### I have already...

- [ X] repeated the problem using the latest stable release of OpenCover.
- [ X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ X] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

100% branch coverage

### Actual Behavior

60% branch coverage

### Steps to reproduce the problem:

Here is the code:
```
namespace ConsoleApp1
{
	using System;

	public class Program
	{
		public static void Main(string[] args)
		{
			string result = TestSwitch(args[0]);
			Console.WriteLine(result);
		}

		public static string TestSwitch(string arg)
		{
			string result;

			switch (arg)
			{
				default:
					result = arg;
					break;
				case "Blank":
					result = arg;
					break;
				case "CalendarRound":
					result = arg;
					break;
				case "CGlyph":
					result = arg;
					break;
				case "CGlyphType":
					result = arg;
					break;
				case "DistanceNumber":
					result = arg;
					break;
				case "DistanceNumberPlus":
					result = arg;
					break;
				case "DistanceNumberDecimal":
					result = arg;
					break;
			}

			return result;
		}
	}
}
```
Here is the test project code:
```
using NUnit.Framework;

namespace ConsoleApp1.Tests
{
	[TestFixture]
	public class ProgramTests
	{
		[Test]
		public void MainTest()
		{
			Program.Main(new string[] { null });
			Program.TestSwitch("Blank");
			Program.TestSwitch("CalendarRound");
			Program.TestSwitch("CGlyph");
			Program.TestSwitch("CGlyphType");
			Program.TestSwitch("DistanceNumber");
			Program.TestSwitch("DistanceNumberPlus");
			Program.TestSwitch("DistanceNumberDecimal");
		}
	}
}
```
If you comment out one of the cases from the switch statement, you get 100% branch coverage.
Reported here https://github.com/axodox/AxoTools/issues/82 but it is an opencover bug. Happens in both NUnit and MSTest.

**Comment by sawilde** [comment]
OpenCover uses IL branches (not source code) for branch coverage as such if the compiler creates more branches than can be executed through tests there is not much we can do. 

We have tried to match scenarios like this in the past and then all it takes is a single change to how the compiler works and all our work comes to nothing - it is a game we can't win and I don't intend to keep playing it anymore.

**Comment by GregReddick** [comment]
I understand the complication. However, it really screws with the coverage statistics. Is there some compromise that can make the branch statistics meaningful when the switch statement uses a hash? Or alternately make the branch statistics calculated false, by just not including them in the total? Or maybe there is, or could be, a compiler switch for debug code that turns off the hash on switch statements so the performance is worse, but the statistics are right?

**Comment by sawilde** [comment]
When we look at the IL we don't know what your source code is, we have line numbers etc but not the actual content. So how do we know what the compiler did and what your code actually looks like? Okay, we could make guesses but as we have frequently discovered when people stress over branch coverage that we get it wrong as much as right when we try to hide these unwanted compiler generated branches.

Personally, in this scenario (I know yours is just representative), I would use an enum e.g.

````
public enum Widget
{
	Unknown,
	Blank,
	CalendarRound,
	CGlyph,
	CGlyphType,
	DistanceNumber,
	DistanceNumberPlus,
	DistanceNumberDecimal
}

public static string TestSwitch2(string arg)
{
	Program.Widget widget;
	Enum.TryParse<Program.Widget>(arg, out widget);
	string result;
	switch (widget)
	{
	case Program.Widget.Blank:
		result = arg;
		break;
	case Program.Widget.CalendarRound:
		result = arg;
		break;
	case Program.Widget.CGlyph:
		result = arg;
		break;
	case Program.Widget.CGlyphType:
		result = arg;
		break;
	case Program.Widget.DistanceNumber:
		result = arg;
		break;
	case Program.Widget.DistanceNumberPlus:
		result = arg;
		break;
	case Program.Widget.DistanceNumberDecimal:
		result = arg;
		break;
	default:
		result = arg;
		break;
	}
	return result;
}
````

which produces the following IL (debug) and is not subject to the complex hashing (also probably much faster though obviously not tested)

````
.method public hidebysig static 
	string TestSwitch2 (
		string arg
	) cil managed 
{
	// Method begins at RVA 0x2170
	// Code size 88 (0x58)
	.maxstack 2
	.locals init (
		[0] valuetype branches.Program/Widget,
		[1] string,
		[2] valuetype branches.Program/Widget,
		[3] string
	)

	IL_0000: nop
	IL_0001: ldarg.0
	IL_0002: ldloca.s 0
	IL_0004: call bool [mscorlib]System.Enum::TryParse<valuetype branches.Program/Widget>(string, !!0&)
	IL_0009: pop
	IL_000a: ldloc.0
	IL_000b: stloc.2
	IL_000c: ldloc.2
	IL_000d: ldc.i4.1
	IL_000e: sub
	IL_000f: switch (IL_0036, IL_003a, IL_003e, IL_0042, IL_0046, IL_004a, IL_004e)

	IL_0030: br.s IL_0032

	IL_0032: ldarg.0
	IL_0033: stloc.1
	IL_0034: br.s IL_0052

	IL_0036: ldarg.0
	IL_0037: stloc.1
	IL_0038: br.s IL_0052

	IL_003a: ldarg.0
	IL_003b: stloc.1
	IL_003c: br.s IL_0052

	IL_003e: ldarg.0
	IL_003f: stloc.1
	IL_0040: br.s IL_0052

	IL_0042: ldarg.0
	IL_0043: stloc.1
	IL_0044: br.s IL_0052

	IL_0046: ldarg.0
	IL_0047: stloc.1
	IL_0048: br.s IL_0052

	IL_004a: ldarg.0
	IL_004b: stloc.1
	IL_004c: br.s IL_0052

	IL_004e: ldarg.0
	IL_004f: stloc.1
	IL_0050: br.s IL_0052

	IL_0052: ldloc.1
	IL_0053: stloc.3
	IL_0054: br.s IL_0056

	IL_0056: ldloc.3
	IL_0057: ret
} // end of method Program::TestSwitch2
````
and IL (Release)

````
.method public hidebysig static 
	string TestSwitch2 (
		string arg
	) cil managed 
{
	// Method begins at RVA 0x214c
	// Code size 77 (0x4d)
	.maxstack 2
	.locals init (
		[0] valuetype branches.Program/Widget thing,
		[1] string result
	)

	IL_0000: ldarg.0
	IL_0001: ldloca.s thing
	IL_0003: call bool [mscorlib]System.Enum::TryParse<valuetype branches.Program/Widget>(string, !!0&)
	IL_0008: pop
	IL_0009: ldloc.0
	IL_000a: ldc.i4.1
	IL_000b: sub
	IL_000c: switch (IL_0031, IL_0035, IL_0039, IL_003d, IL_0041, IL_0045, IL_0049)

	IL_002d: ldarg.0
	IL_002e: stloc.1
	IL_002f: br.s IL_004b

	IL_0031: ldarg.0
	IL_0032: stloc.1
	IL_0033: br.s IL_004b

	IL_0035: ldarg.0
	IL_0036: stloc.1
	IL_0037: br.s IL_004b

	IL_0039: ldarg.0
	IL_003a: stloc.1
	IL_003b: br.s IL_004b

	IL_003d: ldarg.0
	IL_003e: stloc.1
	IL_003f: br.s IL_004b

	IL_0041: ldarg.0
	IL_0042: stloc.1
	IL_0043: br.s IL_004b

	IL_0045: ldarg.0
	IL_0046: stloc.1
	IL_0047: br.s IL_004b

	IL_0049: ldarg.0
	IL_004a: stloc.1

	IL_004b: ldloc.1
	IL_004c: ret
} // end of method Program::TestSwitch2
````

**Comment by GregReddick** [comment]
I simplified the example to the minimum to show the issue. The actual code that is generating the problem can't use an enum for complicated reasons related to extending how DateTime Format works in the .NET Framework, which limits what I can do with refactoring the code. I absolutely see why you don't want to special case this in the OpenCover code. Besides switch, what other things cause hidden branches that muck with the branching coverage? 

If I'm reading the IL right, what's happening is that it calculates a hash of the string to be compared. Then it checks serially to see what bucket that hash appears in. Then it runs through the bucket and sees if the strings compares. To get full coverage, I'd have to find strings that hash to the same value as an existing string, but is not the existing string. It becomes an exercise in cryptography just to get coverage!

**Comment by GregReddick** [comment]
It turns out the exercise in cryptography is not too bad. The ComputeStringHash function is not very complex. Generating a hash collision is not terrible. I brute forced it, which takes some time, but if I think about it a bit more, it might be able to be done fast . My hash collisions are all one or two Unicode characters. By calling the switch with these hash collisions from my unit test, I can force coverage of the branches. I'll give some sample code in the next couple of days after I think through trying to improve the algorithm. It looks like it just takes more sophisticated unit tests to get full coverage.

**Comment by sawilde** [comment]
@GregReddick 

> Generating a hash collision is not terrible.

true, but do you really need to do it? Writing tests for the sake of coverage is not a path I agree with and to totally misquote Yoda "will only lead to madness, it will".

**Comment by GregReddick** [comment]
Well, it really is a legitimate test. The logic where a hash collision happens is an actual path through the code. Is it likely to detect bugs in my code? I'd say probably not, since the compiler generated code _should_ always work. It could detect compiler bugs though!  But generating hash collisions does avoid having deceptively low statistics on the coverage. Now another approach I was thinking about would be for OpenCover to support an attribute on the method where it just doesn't factor in the branching statistics for that method. If the switch was isolated into a method, the attribute would avoid having low coverage results. Some managers get all ticked off if the unit tests say that coverage results are low.

**Comment by SteveGilham** [comment]
What a switch statement compiles to depends on what's being switched.  Switched on strings, like in the original report, become a series of if/else rather than an actual `switch` opcode, as it can be for integers.  The if/else cascade can have an early exit for an input null (as it obviously couldn't match any of the non-null candidates).

In the case where I encountered it, that early exit was an uncovered branch when the value being switched on was non-null by construction.

The C# compiler is also getting rather clever about how it can optimize when integer cases are involved.

The failing unit test `GetBranchPointsForMethodToken_SwitchWithMultipleCases()` fails because it is working on IL that looks like `return (uint)(input - 1) <= 2;`  Using cases 1,2,4 still turns into an arithmetic comparison; going to 1,3,5 does generate a `switch` (but one with extra branches for cases 2 and 4, as well as a catch-all for numbers outside the range).  Adding the obvious handing of points[4] and [5] then runs the test through.

**Comment by pkruk2** [comment]
If anyone is interested, IL Spy decompiles the code into following:
```
public static string TestSwitch(string arg)
{
	uint num = <PrivateImplementationDetails>.ComputeStringHash(arg);
	string result;
	if (num <= 1122240865u)
	{
		if (num != 243305629u)
		{
			if (num != 602070688u)
			{
				if (num == 1122240865u)
				{
					if (arg == "Blank")
					{
						result = arg;
						return result;
					}
				}
			}
			else if (arg == "CGlyphType")
			{
				result = arg;
				return result;
			}
		}
		else if (arg == "CalendarRound")
		{
			result = arg;
			return result;
		}
	}
	else if (num <= 2112925928u)
	{
		if (num != 2000468655u)
		{
			if (num == 2112925928u)
			{
				if (arg == "CGlyph")
				{
					result = arg;
					return result;
				}
			}
		}
		else if (arg == "DistanceNumber")
		{
			result = arg;
			return result;
		}
	}
	else if (num != 3242433966u)
	{
		if (num == 3378230451u)
		{
			if (arg == "DistanceNumberPlus")
			{
				result = arg;
				return result;
			}
		}
	}
	else if (arg == "DistanceNumberDecimal")
	{
		result = arg;
		return result;
	}
	result = arg;
	return result;
}
```

**Comment by sawilde** [comment]
I am not sure this is worth pursuing anymore - the compiler will produce what it will produce
