### ISSUE TITLE
Provide detailed logging for "Cannot instrument .dll"

### ISSUE THREAD

**Issue by MNF** [OpenCover/opencover#729]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [x ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ X] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

"Cannot instrument .dll as no PDB/MDB could be loaded" provides detailed information what's wrong.
It will be very helpful for troubleshooting , if log (at least verbose) show more details of the process, e.g. "PDB file was found, but format is unknown".

### Actual Behavior
The summary message shows only some possible reasons for it and not one that applicable for my cases
      

> No results, this could be for a number of reasons. The most common reasons are:
>     1) missing PDBs for the assemblies that match the filter please review the
>     output file and refer to the Usage guide (Usage.rtf) about filters.
>     2) the profiler may not be registered correctly, please refer to the Usage
>     guide and the -register switch.
> 

### Steps to reproduce the problem:

There are different reasons that cause  warnings
Cannot instrument FullpassToYours.dll as no PDB/MDB could be loaded. 
I had VS2017 projects , that were set to generate portable PDBs, and the open cover reported just general error until I changed format to full PDB.
The same no coverage ( unfortunately I don't have small reproducible example) was when VS2015 solution was tested using VSTest, but was successfully covered when I used MSTest instead.

Anyway this issue is about improve diagnostics to troubleshoot "no coverage" errors, not about fixing indivigual issues

**Comment by sawilde** [comment]
We've added extra commentary on possible causes - Embedded, Potable PDBs are now supported
