### ISSUE TITLE
No results and missing pdb when running OpenCover script on Windows 10 VM, but works on dev machine

### ISSUE THREAD

**Issue by shrub77** [OpenCover/opencover#730]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [x] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

We have a mac build server which is hosting a windows 10 VM which runs the latest OpenCover on our NUnit tests. When I run the coverage batch file on the VM, It produces no output with the "No results, this could be..." message. The XML produced produced says "Missing PDBs" as the reason for skipping coverage. My NUnit tests are built and run, but coverage is not being reported. I can provide output if needed. I can confirm the PDB files are in the same directory as the test DLL. 

When I run the same script on my development machine, the coverage is generated without any issue.

### Steps to reproduce the problem:
The script I am using to generate reports is below. This script is placed in the root level of my VS solution. I attempted the regsvr32 command but that did not work 
```
SET DllContainingTests=%~dp0NUnit.TreeGo\bin\Debug\NUnit.TreeGo.dll
SET OutputDirectory=%~dp0\out

for /R "%~dp0packages" %%a in (*) do if /I "%%~nxa"=="nunit3-console.exe" SET TestRunnerExe=%%~dpnxa

for /R "%~dp0packages" %%a in (*) do if /I "%%~nxa"=="OpenCover.Console.exe" SET OpenCoverExe=%%~dpnxa

"%OpenCoverExe%" ^
 -target:"%TestRunnerExe%" ^
 -targetargs:"\"%DllContainingTests%\"" ^
 -filter:"+[*]* -[*NUnit*]* -[*]*.*Config" ^
 -mergebyhash ^
 -skipautoprops ^
 -register:user ^
 -output:"%OutputDirectory%\CoverageReport.xml"
```

**Comment by shrub77** [comment]
This is a fresh VM, maybe I am missing some prereq package?

**Comment by sawilde** [comment]
You'll probably want to add `/noshadow` to the command line arguments that are passed to nunit

**Comment by shrub77** [comment]
I am using nunit3, isn't noshadow deprecated?

**Comment by sawilde** [comment]
You're right apparently now you need to use `--shadowcopy` to force it the other way.

What does it say in the output XML for when the assembly isn't covered?

**Comment by shrub77** [comment]
Here is the output xml:

```
<?xml version="1.0" encoding="UTF-8"?>

-<CoverageSession xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<Summary numMethods="0" visitedMethods="0" numClasses="0" visitedClasses="0" minCyclomaticComplexity="0" maxCyclomaticComplexity="0" branchCoverage="0" sequenceCoverage="0" visitedBranchPoints="0" numBranchPoints="0" visitedSequencePoints="0" numSequencePoints="0"/>


-<Modules>


-<Module hash="1E-37-42-6E-A6-E4-D9-20-34-4B-DE-B4-FE-2E-1F-7B-40-B6-7C-2E" skippedDueTo="Filter">

<ModulePath>C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll</ModulePath>

<ModuleTime>2017-04-21T21:50:55.2504992Z</ModuleTime>

<ModuleName>mscorlib</ModuleName>

<Classes/>

</Module>


-<Module hash="70-0A-8C-00-26-D7-8E-3A-41-3C-43-6D-01-3C-09-CC-C9-73-85-C0" skippedDueTo="MissingPdb">

<ModulePath>Z:\myagent\_work\1\s\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe</ModulePath>

<ModuleTime>2017-03-07T00:27:00Z</ModuleTime>

<ModuleName>nunit3-console</ModuleName>

<Classes/>

</Module>


-<Module hash="5C-87-CD-3C-EA-9E-9D-D7-D7-F8-B6-C3-72-72-58-EC-97-33-9D-31" skippedDueTo="Filter">

<ModulePath>C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll</ModulePath>

<ModuleTime>2017-04-21T21:53:36Z</ModuleTime>

<ModuleName>System</ModuleName>

<Classes/>

</Module>


-<Module hash="90-A5-CB-F1-B1-A1-C2-DE-2A-BF-0B-6F-28-E9-82-CA-41-44-09-3A" skippedDueTo="MissingPdb">

<ModulePath>Z:\myagent\_work\1\s\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit.engine.api.dll</ModulePath>

<ModuleTime>2017-03-07T00:27:00Z</ModuleTime>

<ModuleName>nunit.engine.api</ModuleName>

<Classes/>

</Module>


-<Module hash="96-DE-EF-3F-02-DC-0C-37-07-3E-B9-1D-D2-EF-F9-A2-D3-8E-11-00" skippedDueTo="MissingPdb">

<ModulePath>Z:\myagent\_work\1\s\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit.engine.dll</ModulePath>

<ModuleTime>2017-03-07T00:27:00Z</ModuleTime>

<ModuleName>nunit.engine</ModuleName>

<Classes/>

</Module>


-<Module hash="B9-8B-21-12-C1-A8-63-27-37-43-85-65-6A-15-A6-C6-5A-C6-BF-D7" skippedDueTo="Filter">

<ModulePath>C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll</ModulePath>

<ModuleTime>2017-04-21T21:53:36Z</ModuleTime>

<ModuleName>System.Xml</ModuleName>

<Classes/>

</Module>


-<Module hash="C7-07-9B-C6-63-92-48-80-97-A7-FD-17-12-A8-06-13-15-67-58-41" skippedDueTo="Filter">

<ModulePath>C:\Windows\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll</ModulePath>

<ModuleTime>2017-04-21T21:50:55.2661246Z</ModuleTime>

<ModuleName>System.Web</ModuleName>

<Classes/>

</Module>


-<Module hash="A1-47-D1-CE-C9-BC-C0-A8-0B-2A-B5-42-EF-73-A0-6C-13-30-72-81" skippedDueTo="Filter">

<ModulePath>C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll</ModulePath>

<ModuleTime>2017-04-21T21:53:36Z</ModuleTime>

<ModuleName>System.Runtime.Remoting</ModuleName>

<Classes/>

</Module>


-<Module hash="FB-D4-0E-90-EA-AB-B0-1B-C4-12-8E-0A-26-C7-FA-75-AA-39-11-98" skippedDueTo="Filter">

<ModulePath>C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll</ModulePath>

<ModuleTime>2017-04-21T21:53:36Z</ModuleTime>

<ModuleName>System.Configuration</ModuleName>

<Classes/>

</Module>


-<Module hash="8A-2E-8F-D6-9D-39-02-4A-2F-30-FC-06-42-F7-0F-A8-32-69-07-72" skippedDueTo="MissingPdb">

<ModulePath>Z:\myagent\_work\1\s\packages\NUnit.ConsoleRunner.3.6.1\tools\Mono.Cecil.dll</ModulePath>

<ModuleTime>2017-03-07T00:27:00Z</ModuleTime>

<ModuleName>Mono.Cecil</ModuleName>

<Classes/>

</Module>


-<Module hash="75-5F-1A-C1-0E-E6-C9-A3-EC-A1-F0-6E-89-B4-98-86-0B-A8-B2-AD" skippedDueTo="MissingPdb">

<ModulePath>Z:\myagent\_work\1\s\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit-agent.exe</ModulePath>

<ModuleTime>2017-03-07T00:27:00Z</ModuleTime>

<ModuleName>nunit-agent</ModuleName>

<Classes/>

</Module>


-<Module hash="DE-6F-4F-B5-38-CC-77-7B-8C-2C-DD-D4-82-02-87-E2-91-2C-AE-6A" skippedDueTo="MissingPdb">

<ModulePath>Z:\myagent\_work\1\s\NUnit.TreeGo\bin\Debug\nunit.framework.dll</ModulePath>

<ModuleTime>2017-06-06T01:49:18Z</ModuleTime>

<ModuleName>nunit.framework</ModuleName>

<Classes/>

</Module>


-<Module hash="E9-52-4C-A8-FB-A9-89-80-87-43-18-E5-B9-E0-08-1E-24-69-C1-56" skippedDueTo="Filter">

<ModulePath>C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll</ModulePath>

<ModuleTime>2017-04-21T21:53:36Z</ModuleTime>

<ModuleName>System.Core</ModuleName>

<Classes/>

</Module>


-<Module hash="A5-15-B3-24-DC-ED-A7-D7-DB-55-BD-AE-CB-BE-85-1C-7B-76-C1-A0" skippedDueTo="Filter">

<ModulePath>Z:\myagent\_work\1\s\NUnit.TreeGo\bin\Debug\NUnit.TreeGo.dll</ModulePath>

<ModuleTime>2017-07-08T21:56:47Z</ModuleTime>

<ModuleName>NUnit.TreeGo</ModuleName>

<Classes/>

</Module>


-<Module hash="9B-8A-7C-43-41-9F-23-9D-09-E6-ED-F3-1C-EA-7D-AD-EB-8D-B8-47" skippedDueTo="MissingPdb">

<ModulePath>Z:\myagent\_work\1\s\NUnit.TreeGo\bin\Debug\TreeGo.dll</ModulePath>

<ModuleTime>2017-07-08T21:56:45Z</ModuleTime>

<ModuleName>TreeGo</ModuleName>

<Classes/>

</Module>

</Modules>

</CoverageSession>
```

**Comment by sawilde** [comment]
And do the .pdb files for TreeGo.dll exist in the same folder?

**Comment by shrub77** [comment]
![image](https://user-images.githubusercontent.com/6591138/28251816-73cfb2ea-6a53-11e7-8eb4-3a8c1d90b2d8.png)

Yep

**Comment by sawilde** [comment]
Well, it seems to not like it. Can you share the code/repo so I can investigate further?

**Comment by shrub77** [comment]
Is there an email where I can send you a zip of the solution? I'd like to avoid posting it publicly

**Comment by shrub77** [comment]
I only get a missing pdb issue when I run OpenCover on a Windows VM. You may have to try on a VM to reproduce the issue

**Comment by sawilde** [comment]
@shrub77 sure `shaun(underscore)wilde(at)hotmail(dot)com`

**Comment by shrub77** [comment]
sent email

**Comment by shrub77** [comment]
@sawilde Any update on this?

**Comment by sawilde** [comment]
Looks like you'll need to use the beta version

https://ci.appveyor.com/project/sawilde/opencover/build/4.6.762/artifacts

**Comment by tsauvajon** [comment]
I've had the same problem with the latest nuget module.
v4.6.762 doesn't work for me (I get loads of directory not found exceptions).

I downloaded the last build artifacts from AppVeyor [v4.7.831](https://ci.appveyor.com/project/sawilde/opencover/build/4.7.831/artifacts) and it correctly exports my project now.

**Comment by hemalatha-nallusamy** [comment]
EDIT2: More info about this -
It worked perfectly well before: I was building for .Net 4.6.1 with MSBuild 14. I updated to a newer .csproj syntax, and I am now building with dotnet.exe for .Net 4.6.2. After some issues, everything but OpenCover is working correctly. Any idea what I might have missed ?

Can I know the solution to this scenario as I am facing the same issue?

**Comment by sawilde** [comment]
@hemalatha-nallusamy if you can supply a sample that repeats it, it would be hard to say for sure.

I would check that you are using the latest build, see releases as we created an RC recently. You may also want to check that you are producing a full pdb.
