### ISSUE TITLE
OpenCover can't find source from 3rd party and throws DirectoryNotFoundException 

### ISSUE THREAD

**Issue by Jericho** [OpenCover/opencover#731]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [X] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [X] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I expect OpenCover to report coverage of only my code (as specified in the `Filter` parameter I specify).

### Actual Behavior

OpenCover is reporting coverage of my code in addition to the code of some of the nuget packages my library references. In my case I reference Microsoft's Azure storage nuget package and OpenCover is searching for the .CS source files of the Microsoft package. Since it can't find these files, it throws numerous `NotFound` exceptions.
 
Here's some more details: 
The build script for my library (called `Picton`) has a step to invoke `dotnet.exe` to build the projects in my solution followed by a step for code coverage. The code coverage step looks like this:
```
E:/_build/Picton/tools/OpenCover/tools/OpenCover.Console.exe
 -target:"C:/Program Files/dotnet/dotnet.exe"
 -targetargs:"test ./Source/Picton.UnitTests/Picton.UnitTests.csproj --configuration Release --no-build"
 -filter:"+[Picton]* -[Picton]Picton.Properties.* -[Picton]Picton.Logging.*"
 -excludebyattribute:"*.ExcludeFromCodeCoverage*"
 -excludebyfile:"*/*Designer.cs;*/*AssemblyInfo.cs"
 -register:user
 -output:"E:/_build/Picton/artifacts/CodeCoverage/coverage.xml"
 -hideskipped:Filter
 -mergeoutput
```
The output of this step looks like this:
```
Loading coverage file E:/_build/Picton/artifacts/CodeCoverage/coverage.xml
Executing: C:\Program Files\dotnet\dotnet.exe
Test run for E:\_build\Picton\Source\Picton.UnitTests\bin\Release\netcoreapp1.1\Picton.UnitTests.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.1250051]   Discovering: Picton.UnitTests
[xUnit.net 00:00:01.4153004]   Discovered:  Picton.UnitTests
[xUnit.net 00:00:01.4228087]   Starting:    Picton.UnitTests
[xUnit.net 00:00:04.3388824]   Finished:    Picton.UnitTests

Total tests: 96. Passed: 96. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 5.5122 Seconds


Committing...
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\AspNet\Microsoft.WindowsAzure.Storage\Extensions\StreamExtension.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\AspNet\Microsoft.WindowsAzure.Storage\Extensions\TaskExtension.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\AccessCondition.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\CloudStorageAccount.cs'.
... followed by many more DirectoryNotFoundException. I didn't count them, but there are probably 100+ ...

Visited Classes 23 of 855 (2.69)
Visited Methods 48 of 4357 (1.1)
Visited Points 278 of 16472 (1.69)
Visited Branches 155 of 10461 (1.48)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 24 of 1033 (2.32)
Alternative Visited Methods 66 of 5645 (1.17)
```
Please note: my library contains 15 classes (as opposed to 855) and probably 100 or so methods (nowhere near 4,357).

### Steps to reproduce the problem:

1. Clone `https://github.com/Jericho/Picton.git`
2. Check out the ` feature/vs_2017 ` branch
2. Execute `.\build.ps1 -target Coverage` from a PowerShell prompt

**Comment by Jericho** [comment]
(please note, I gave you the wrong repo URL in `Steps to reproduce`. I just made the correction. Sorry about the confusion)

**Comment by Jericho** [comment]
I can't believe it: I ran my build script again this morning and all the `DirectoryNotFound` exceptions are gone! Was there something cached on my machine that got cleared during the night???

However, OpenCover says that 0% of my code is covered despite the fact that it discovered my 96 unit tests. Something doesn't seem right...

```
========================================                                                                 
Run-Code-Coverage    
========================================                                                                 
Executing task: Run-Code-Coverage
Executing: "E:/_build/Picton/tools/OpenCover/tools/OpenCover.Console.exe" -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test \"./Source/Picton.UnitTests/Picton.Uni
tTests.csproj\" --configuration Release --no-build" -filter:"+[Picton]* -[Picton]Picton.Properties.* -[Picton]Picton.Logging.*" -excludebyattribute:"*.ExcludeFromCodeCoverage*
" -excludebyfile:"*/*Designer.cs;*/*AssemblyInfo.cs" -register:user -output:"E:/_build/Picton/artifacts/CodeCoverage/coverage.xml" -mergeoutput
Executing: C:\Program Files\dotnet\dotnet.exe
Test run for E:\_build\Picton\Source\Picton.UnitTests\bin\Release\netcoreapp1.1\Picton.UnitTests.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.1532762]   Discovering: Picton.UnitTests
[xUnit.net 00:00:01.4507312]   Discovered:  Picton.UnitTests
[xUnit.net 00:00:01.4588266]   Starting:    Picton.UnitTests
[xUnit.net 00:00:04.4316659]   Finished:    Picton.UnitTests

Total tests: 96. Passed: 96. Failed: 0. Skipped: 0.
Test Run Successful.   
Test execution time: 5.6321 Seconds

Committing...              
Visited Classes 0 of 45 (0)
Visited Methods 0 of 143 (0)
Visited Points 0 of 660 (0)
Visited Branches 0 of 421 (0)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 0 of 49 (0)
Alternative Visited Methods 0 of 208 (0)
Finished executing task: Run-Code-Coverage
```

**Comment by Jericho** [comment]
Please note that I am aware of the need for full PDBs and I have configured my library [csproj](https://github.com/Jericho/Picton/blob/feature/vs_2017/Source/Picton/Picton.csproj#L19) accordingly.

**Comment by Jericho** [comment]
My latest symptoms seem to be similar to this other [issue](https://github.com/OpenCover/opencover/issues/707)

**Comment by Jericho** [comment]
I upgraded a second project to VS.NET 2017 earlier this morning and experiencing the exact same issue: coverage is 0% despite many unit tests

To reproduce:
1. Clone `https://github.com/Jericho/StrongGrid.git`
2. Check out the `feature/vs_2017` branch
3. Execute `.\build.ps1 -target Coverage` from a PowerShell prompt

in case it can be helpful, here's the XML file generate by OpenCover:
[coverage.xml.txt](https://github.com/OpenCover/opencover/files/1142356/coverage.xml.txt)
(changed the extension to TXT because github does not allow uploading XML file)

**Comment by Jericho** [comment]
After reading this seemingly unrelated [issue](https://github.com/OpenCover/opencover/issues/601), I learned that adding `-oldstyle` should resolve the 0% problem. I tested it and indeed coverage is now reported as expected.

**Comment by sawilde** [comment]
@Jericho have you also tried the beta version that is referenced in the above issue #601 ?

**Comment by Jericho** [comment]
@sawilde I just tried v4.6.690 and it worked. Which is better: sticking with the "old" opencover in conjunction with the `-oldstyle` parameter, or the beta version?

Also, it's no longer a problem but I'm still curious: do you have any idea why I was getting all the `DirectoryNotFound' exceptions and then why they suddenly went away?

**Comment by sawilde** [comment]
@Jericho which ever works for you - we have to do different injection method for safe mode but I am not sure what value it has anymore with .net core as that was really for sliverlight and other assemblies that used trust models from the main framework that I don't think are available in .net core.

**Comment by sawilde** [comment]
The exceptions I believe are part of the branch analysis i.e. trying to discount false positives by looking at the code - it really shouldn't log to the user console like that.
