### ISSUE TITLE
Can't find pdbs for .net 4.6.2 assembly

### ISSUE THREAD

**Issue by awr** [OpenCover/opencover#732]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [X] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [X] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

It's only finding the pdb for the tests assembly (KafkaClient.Tests), but not for the actual code under test (KafkaClient), even though both pdbs are in the same directory. 

### Actual Behavior

It will find the pdbs for the code under test (KafkaClient), and provide coverage for that.

The output is:

```
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
```

### Steps to reproduce the problem:

It's an open source project, on github here: https://github.com/awr/KafkaClient. The tests are being run through appveyor here: https://ci.appveyor.com/project/AndrewRobinson/kafkaclient, with the config here: https://github.com/awr/KafkaClient/blob/master/appveyor-net462.yml (also tried locally, same effect).

Note that this library supports both .netstandard 1.6 and .net 4.6.2 (I'm trying this with 4.6.2) -- not sure whether that's related though.

Thanks for the cool library, and looking forward to getting it working on this project! :)

**Comment by awr** [comment]
Note that this is related to #720 but the environment looks a bit different.

**Comment by awr** [comment]
Here's the pdbs in the same folder as the test assembly and pdbs (the test pdbs do get picked up):

![image](https://user-images.githubusercontent.com/422274/28507258-78d07dcc-6fff-11e7-9432-65c0ff3b4e88.png)

**Comment by awr** [comment]
Tried this with nunit to see if there was a difference, but seems to have hit the same issue. Here's a build with nunit https://ci.appveyor.com/project/AndrewRobinson/kafkaclient/build/0.2.22

**Comment by sawilde** [comment]
@awr You are going to need to use the 'beta' package as the old version can no longer handle the PDB format being produced - https://ci.appveyor.com/project/sawilde/opencover/build/artifacts

```
Results (nunit3) saved as TestResult.xml
Committing...
Visited Classes 285 of 369 (77.24)
Visited Methods 1169 of 1457 (80.23)
Visited Points 5076 of 6281 (80.82)
Visited Branches 2958 of 4180 (70.77)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 285 of 391 (72.89)
Alternative Visited Methods 1169 of 1997 (58.54) 
```

**Comment by awr** [comment]
will do, thanks!
