### ISSUE TITLE
XML file is not generating

### ISSUE THREAD

**Issue by gambheera88** [OpenCover/opencover#733]
I'm getting the following issue when I'm trying to get the output:
**Committing...
No results, this cou
[issue.files.zip](https://github.com/OpenCover/opencover/files/1168752/issue.files.zip)

ld be for a number of reasons. The most common reasons are:
1) missing PDBs for the assemblies that match the filter please review the
output file and refer to the Usage guide (Usage.rtf) about filters.
2) the profiler may not be registered correctly, please refer to the Usage
guide and the -register switch.**

I have tried with admin privileges and using -register:administrator as well.

I have attached the output I'm getting. and the batch file I'm running

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework
- [x] .NET Core 1.0.3

### My Environment
- [x] Windows 10

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

**Comment by sawilde** [comment]
try using 
1) full PDBs rather than portable
2) the `-oldstyle` switch

**Comment by gambheera88** [comment]
Yes already done...
Here is the batch file I'm running. Can you find an error?

**@echo off

SET dotnet="C:/Program Files/dotnet/dotnet.exe"  
SET opencover=C:\Users\Lahiru\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe  
SET reportgenerator=C:\Users\Lahiru\.nuget\packages\ReportGenerator\2.4.5\tools\ReportGenerator.exe

SET targetargs="test"  
SET filter="+[*]SJCNet.APIDesign.* -[*.Test]* -[xunit.*]* -[FluentValidation]*"  
SET coveragefile=Coverage.xml  
SET coveragedir=Coverage

REM Run code coverage analysis  
%opencover% -oldStyle -register:path32 -target:%dotnet% -output:%coveragefile% -targetargs:%targetargs% -filter:%filter% -skipautoprops -hideskipped:All

REM Generate the report  
%reportgenerator% -targetdir:%coveragedir% -reporttypes:Html;Badges -reports:%coveragefile% -verbosity:Error

REM Open the report  
start "report" "%coveragedir%\index.htm"**

**Comment by sawilde** [comment]
you may want to try `-register:user` unless there is a specific reason you only want to instrument 32 bit processes

**Comment by gambheera88** [comment]
I tried with -register:user  option. But still the issue is appearing.

Here is my changed script:

@echo off

SET dotnet="C:/Program Files/dotnet/dotnet.exe"  
SET opencover=C:\Users\Lahiru\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe  
SET reportgenerator=C:\Users\Lahiru\.nuget\packages\ReportGenerator\2.4.5\tools\ReportGenerator.exe

SET targetargs="test"  
SET filter="+[*]SJCNet.APIDesign.* -[*.Test]* -[xunit.*]* -[FluentValidation]*"  
SET coveragefile=Coverage.xml  
SET coveragedir=Coverage

REM Run code coverage analysis  
%opencover% -oldStyle -register:user -target:%dotnet% -output:%coveragefile% -targetargs:%targetargs% -filter:%filter% -skipautoprops -hideskipped:All

REM Generate the report  
REM %reportgenerator% -targetdir:%coveragedir% -reporttypes:Html;Badges -reports:%coveragefile% -verbosity:Error

REM Open the report  
REM start "report" "%coveragedir%\index.htm"

**Comment by gambheera88** [comment]
Hi Shaun,

Thank you for helping me. Really appreciate your commitment.

I followed your instructions. But the problem is still there...

Here is my new script.

@echo off

SET dotnet="C:/Program Files/dotnet/dotnet.exe"  
SET opencover=C:\Users\Lahiru\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe  
SET reportgenerator=C:\Users\Lahiru\.nuget\packages\ReportGenerator\2.4.5\tools\ReportGenerator.exe

SET targetargs="test"  
SET filter="+[*]SJCNet.APIDesign.* -[*.Test]* -[xunit.*]* -[FluentValidation]*"  
SET coveragefile=Coverage.xml  
SET coveragedir=Coverage

REM Run code coverage analysis  
%opencover% -oldStyle -register:%user% -target:%dotnet% -output:%coveragefile% -targetargs:%targetargs% -filter:%filter% -skipautoprops -hideskipped:%All%

REM Generate the report  
REM %reportgenerator% -targetdir:%coveragedir% -reporttypes:%Html%;Badges -reports:%coveragefile% -verbosity:%Error%

REM Open the report  
REM start "report" "%coveragedir%\index.htm"

**Comment by sawilde** [comment]
no it is `-register:user` that is what the switch is

**Comment by gambheera88** [comment]
Yes I did... But same issue is there... 

Here is my updated script
@echo off

SET dotnet="C:/Program Files/dotnet/dotnet.exe"  
SET opencover=C:\Users\Lahiru\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe  
SET reportgenerator=C:\Users\Lahiru\.nuget\packages\ReportGenerator\2.4.5\tools\ReportGenerator.exe

SET targetargs="test"  
SET filter="+[*]SJCNet.APIDesign.* -[*.Test]* -[xunit.*]* -[FluentValidation]*"  
SET coveragefile=Coverage.xml  
SET coveragedir=Coverage

REM Run code coverage analysis  
%opencover% -oldStyle -register:user -target:%dotnet% -output:%coveragefile% -targetargs:%targetargs% -filter:%filter% -skipautoprops -hideskipped:%All%

REM Generate the report  
REM %reportgenerator% -targetdir:%coveragedir% -reporttypes:%Html%;Badges -reports:%coveragefile% -verbosity:%Error%

REM Open the report  
REM start "report" "%coveragedir%\index.htm"

**Comment by sawilde** [comment]
Why do you keep wrapping everything in environment variables, I don't see on for `all` of for `html`?

I can't see what is wrong so it may be to do with the dlls and pdbs themselves, are you using `portable` or `fullpdb`s? The version of opencover you are using works best with the main dotnet frameworks and needs a lot of tinkering to work with dotnet core and the like.

**Comment by sawilde** [comment]
@gambheera88 you may want to try the beta version of OpenCover

https://ci.appveyor.com/project/sawilde/opencover/build/artifacts
