### ISSUE TITLE
Source code full path is empty in coverage snapshot

### ISSUE THREAD

**Issue by gregbty** [OpenCover/opencover#734]
When generating coverage, there seems to be an issue that is causing some of the full path values under the source code files collection to be empty. The solution is using PostSharp for injecting code at compile time as well as [Fody Costura](https://github.com/Fody/Costura/) for combing all assemblies into a single package. There is also a linked T4 file that produces a shared AssemblyInfo.cs file. This is causing: https://github.com/danielpalme/ReportGenerator/issues/97.

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

There is a full path value for all source code files in the coverage snapshot: `<File uid="2" fullPath="C:\Code\Source.cs" />`

### Actual Behavior

There is are empty full path values: `<File uid="2" fullPath="" />`.

**Comment by sawilde** [comment]
@gregbty can you supply a sample that repeats the issue?

**Comment by gregbty** [comment]
I switched to another coverage tool, but I'll backtrack to see if I can reproduce it.
