### ISSUE TITLE
OpenCover could not find any result due to unkown MissingPdb

### ISSUE THREAD

**Issue by rgl** [OpenCover/opencover#736]
### My Framework

- [X] The project targets .NET 4.5.2

### My Environment

- [X] Windows 10
- [X] Windows Server 2016
- [X] AppVeyor Visual Studio 2017 WITH xUnit and OpenCover manually installed from chocolatey

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Actual coverage

### Actual Behavior

No coverage

```xml
<Module skippedDueTo="MissingPdb" hash="E2-37-B1-33-53-77-C0-06-31-4E-2D-D8-CF-9C-8D-AF-0F-95-59-EC">
  <ModulePath>C:\projects\mailbouncedetector\MailBounceDetector.Tests\bin\Release\net452\MailBounceDetector.dll</ModulePath>
  <ModuleTime>2017-07-31T20:04:58.5989323Z</ModuleTime>
  <ModuleName>MailBounceDetector</ModuleName>
  <Classes/>
</Module>
```

### Steps to reproduce the problem:

See the output at https://ci.appveyor.com/project/rgl/mailbouncedetector/build/1.0.0.21 (check the artifacts at https://ci.appveyor.com/project/rgl/mailbouncedetector/build/1.0.0.21/artifacts too, in particular the 7z file which contains the opencover and xunit result xml files)

At the top of the output it has all the executed commands.

The source code is at https://github.com/rgl/MailBounceDetector.git

**Comment by sawilde** [comment]
Are you producing PDBs for the assemblies you are trying to cover?

**Comment by rgl** [comment]
Yes, it has PDBs. In Release and Debug builds. But OpenCover does not seem to pick them up for some reason.

**Comment by rgl** [comment]
BTW, you can find the PDBs at the AppVeyor artifacts page inside the symbols.nupkg file, e.g. at MailBounceDetector.1.0.3.symbols.nupkg available at https://ci.appveyor.com/project/rgl/mailbouncedetector/build/1.0.0.21/artifacts

**Comment by sawilde** [comment]
@rgl looks like you are going to have to wait until the next release of OpenCover or use the latest artifacts 

https://ci.appveyor.com/project/sawilde/opencover/build/artifacts

**Comment by rgl** [comment]
You've found out what the problem was?

**Comment by sawilde** [comment]
@rgl I needed to use some later packages as it looks like the pdb format has changed and is no longer supported by the libraries I was using.
