### ISSUE TITLE
Using OpenCover to generate test report incremently.

### ISSUE THREAD

**Issue by bayantt** [OpenCover/opencover#737]
We are using OpenCover in C# project. Is there any way to append the result of new runs of the tests to the old results.xml generated by OpenCover?

**Comment by sawilde** [comment]
looks like the `-mergeoutput` switch is what you are looking for, see the [wiki](https://github.com/OpenCover/opencover/wiki/Usage)

**Comment by bayantt** [comment]
@sawilde Suppose if I have changed the name of my test method that was in my old report and re-run the new (renamed one) test and try to merge the output, will it detect that name change and remove the previous method from the report and replace with the output of renamed method?

**Comment by sawilde** [comment]
no - opencover cares nothing about your tests it is only looking at the code that is running
