### ISSUE TITLE
Coverage report not Generating (XMl file showing empty)

### ISSUE THREAD

**Issue by SrinathUpadhya** [OpenCover/opencover#738]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ X] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [X ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X ] no coverage being recorded
- [X ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

C:\Users\srinath.upadhya\.nuget\packages\opencover\4.6.519\tools>OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test C:\ThermoFisher\Adapt\adapt\srcapi\Adapt.
UnitTests" -output:coverage.xml -register:user
Executing: C:\Program Files\dotnet\dotnet.exe
Build started, please wait...
Build completed.

Test run for C:\ThermoFisher\Adapt\adapt\srcapi\Adapt.UnitTests\bin\Debug\netcoreapp2.0\Thermo.Adapt.UnitTests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.8654776]   Discovering: Thermo.Adapt.UnitTests
[xUnit.net 00:00:00.9655394]   Discovered:  Thermo.Adapt.UnitTests
[xUnit.net 00:00:01.0172726]   Starting:    Thermo.Adapt.UnitTests
[xUnit.net 00:00:01.1522760]   Finished:    Thermo.Adapt.UnitTests

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 3.4056 Seconds
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

XML output

<Module skippedDueTo="MissingPdb" hash="4C-41-23-CC-68-44-BC-96-7A-9A-5F-43-91-98-C4-D2-3C-39-96-7D">
      <ModulePath>C:\ThermoFisher\Adapt\adapt\srcapi\Adapt.UnitTests\bin\Debug\netcoreapp2.0\xunit.runner.reporters.netstandard15.dll</ModulePath>
      <ModuleTime>2017-02-19T09:54:26Z</ModuleTime>
      <ModuleName>xunit.runner.reporters.netstandard15</ModuleName>
      <Classes />
    </Module>

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...
C:\Users\srinath.upadhya\.nuget\packages\opencover\4.6.519\tools>OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test C:\ThermoFisher\Adapt\adapt\srcapi\Adapt.
UnitTests" -output:coverage.xml -register:user

**Comment by sawilde** [comment]
please make sure you have `fullpdb`s for your assemblies and if that does not work try the `-oldstyle` switch

**Comment by SrinathUpadhya** [comment]
Even after trying with oldstyle the problem is same.

Here is my batch file

@echo off

SET dotnet="C:/Program Files/dotnet/dotnet.exe"
SET opencover=C:\Users\srinath.upadhya\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe
SET reportgenerator=C:\Users\srinath.upadhya\.nuget\packages\ReportGenerator\2.4.5\tools\ReportGenerator.exe

SET targetargs="test"
SET filter="+[*]Adapt.* -[*.Test]* -[xunit.*]*"
SET coveragefile=Coverage.xml
SET coveragedir=Coverage


REM Run code coverage analysis
%opencover% -oldStyle -register:user -target:%dotnet% -output:%coveragefile% -targetargs:%targetargs% -filter:%filter% -skipautoprops -hideskipped:All

REM Generate the report
%reportgenerator% -targetdir:%coveragedir% -reporttypes:Html;Badges -reports:%coveragefile% -verbosity:Error

the code location is C:\ThermoFisher\Adapt\adapt\srcapi

srcapi folder contains all the source code and unit tests as well
Unit tests are under the same location mentioned above with folder name Adapt.UnitTests

**Comment by SrinathUpadhya** [comment]
If you want more info, I can send you the recording

I am using windows7 os

**Comment by sawilde** [comment]
@SrinathUpadhya I don't know what you mean

**Comment by SrinathUpadhya** [comment]
The above mail says  about the batch file i am using to generate the coverage using opencover.

My source code (.net core 2.0) location in my system is  C:\ThermoFisher\Adapt\adapt\srcapi and the xunit test cases are also available in the same location.  When i try to generate the coverage for the same using opencover (%opencover% -oldStyle -register:user -target:%dotnet% -output:%coveragefile% -targetargs:%targetargs% -filter:%filter% -skipautoprops -hideskipped:All)

I am not able to generate the coverage.


The batch file i am using is as below

@echo off

SET dotnet="C:/Program Files/dotnet/dotnet.exe"
SET opencover=C:\Users\srinath.upadhya.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe
SET reportgenerator=C:\Users\srinath.upadhya.nuget\packages\ReportGenerator\2.4.5\tools\ReportGenerator.exe

SET targetargs="test"
SET filter="+[]Adapt. -[.Test] -[xunit.]"
SET coveragefile=Coverage.xml
SET coveragedir=Coverage

REM Run code coverage analysis
%opencover% -oldStyle -register:user -target:%dotnet% -output:%coveragefile% -targetargs:%targetargs% -filter:%filter% -skipautoprops -hideskipped:All

REM Generate the report
%reportgenerator% -targetdir:%coveragedir% -reporttypes:Html;Badges -reports:%coveragefile% -verbosity:Error

**Comment by sawilde** [comment]
I can't see what is wrong so it may be on how you've built the code or something else - if you can't give me a repeatable sample then you'll need to diagnose it yourself.

**Comment by SrinathUpadhya** [comment]
I have run the code in debug mode.
OS used Windows7
Visual studio IDe 2017
.NET Framework version.NET core 2.0
unit tests xUnit.

**Comment by SrinathUpadhya** [comment]
I have run the code in debug mode.
OS used Windows7
Visual studio IDe 2017
.NET Framework version.NET core 2.0
unit tests xUnit.

**Comment by SrinathUpadhya** [comment]
Any updates or whom i need to contact on the same

**Comment by sawilde** [comment]
@SrinathUpadhya try using the latest version of OpenCover (still in beta)

https://ci.appveyor.com/project/sawilde/opencover/build/artifacts

**Comment by riezebosch** [comment]
@sawilde There are no `pkg's` available in the artifacts. I'm facing the same problem.

**Comment by ZAHEERPASHA** [comment]
Hi Guys, I am facing similar issue where OpenCover.Console.exe is generating empty Coverage.xml report. I am using OpenCover 4.7.922.0 installed on Windows 2016 Server and using MSTEST to run the unit test cases on VS 2019.
Below is the coverage.xml content:
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="4.7.922.0">
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" maxCrapScore="0" minCrapScore="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>

Can some one help to know the root cause?
