### ISSUE TITLE
How to exclude Smocks assemblies from coverage

### ISSUE THREAD

**Issue by unittester57** [OpenCover/opencover#741]
(**_Copied_** from #364 )
**_Using Smocks (https://github.com/vanderkleij/Smocks) seems to distort the calculation of branch points. If I add one test that uses Smocks all branch points in all tests (except for the test using Smock) increase by 2, adding 2 tests increase the branch points by a further 2, as far as I can see branch_points = branch_points + 2 * amount_smock_tests._**

As I understand reading comments I need to exclude Smocks assemblies. I tried below script to achieve this. Please help me where I am doing wrong

`"C:\Users\uname\Documents\Visual Studio 2015\Projects\firstproject\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe" -register:Path32 "-target:MSTest.exe" -targetargs:"/testcontainer:firstprojectTests1.dll" -excludebyfile:<"C:\Users\uname\Documents\Visual Studio 2015\Projects\firstproject\firstprojectTests1\bin\Debug\Smocks.dll">[]`

I have pointed to Smocks.dll as I did-not see where Smocks assemblies are created. Any help is appreciated.

**Comment by sawilde** [comment]
`-excludebyfile` is for excluding source files i.e. autogenerated stuff, you should use the normal filters for excluding assemblies i.e. `-filter:"-[Smocks]* +[*]*"`
