### ISSUE TITLE
-coverbytest is not finding nested test classes

### ISSUE THREAD

**Issue by akamud** [OpenCover/opencover#742]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [x] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I have a test class like this:

```csharp
namespace MyApp.Tests.Unit.MyTests
{
    [TestFixture]
    public class MyTests
    {
        [Test]
        public async Task MyTest()
        {
            // test here 
        }

        [TestFixture]
        public class MyNestedTests
        {
            [TestCase(1, 100)]
            [TestCase(1, 200)]
            [TestCase(2, 200)]
            public async Task MyTestCase(int x, int y)
            {
                // test here
            }
        }
    }
}
```

Then I'm generating the report using:
```bash
.\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"Tests.Unit\bin\Debug\MyApp.Tests.Unit.dll" -mergebyhash -skipautoprops -output:".\GeneratedReports\MyAppReport.xml" -filter:"+[MyApp*]* -[MyApp.Tests.Unit]*" -coverbytest:*.Tests.Unit.dll
```

I'm using ReportGenerator to generate HTML files for me, and I'm trying to see the "Coverage by test methods". I'm generating the report like this:

```bash
.\packages\ReportGenerator.2.5.10\tools\ReportGenerator.exe -reports:".\GeneratedReports\MyAppServiceReport.xml" -targetdir:".\GeneratedReports\ReportGenerator Output"
```

I want the "Coverage by test methods" section to contain all the tests from my classes, even the nested ones.

### Actual Behavior

I see all the tests from `MyTests` in the "Coverage by test methods", but I don't see the nested tests from `MyNestedTests` there.

I looked at the XML generated by OpenCover and I can see that the nested class is never listed there, so I believe it is a problem from the OpenCover itself, and not from ReportGenerator.

### Steps to reproduce the problem:

Create a nested test and generate a report using `coverbytest`.

**Comment by akamud** [comment]
I'm looking at the reports again and I'm not sure how to identify if the method coverage is being reported.

Does this information in the XML mean that it is?

```xml
<Method visited="true" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="100" branchCoverage="100" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="1" visitedSequencePoints="1" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="1" numMethods="1" />
              <MetadataToken>100664078</MetadataToken>
              <Name>FluentAssertions.Equivalency.EquivalencyAssertionOptions`1&lt;MyApp.Data&gt; MyApp.Tests.Unit.Services.MyServiceTests/MyFilterTests/&lt;&gt;c::&lt;FilterTest&gt;b__3_0(FluentAssertions.Equivalency.EquivalencyAssertionOptions`1&lt;MyApp.Data&gt;)</Name>
              <FileRef uid="105" />
              <SequencePoints>
                <SequencePoint vc="3" uspid="2418" ordinal="0" offset="0" sl="140" sc="79" el="140" ec="103" bec="0" bev="0" fileid="105" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="3" uspid="2418" ordinal="0" offset="0" sl="140" sc="79" el="140" ec="103" bec="0" bev="0" fileid="105" />
            </Method>
```

**Comment by sawilde** [comment]
@akamud `sequenceCoverage="100" branchCoverage="100"`  is 100% covered

I've never seen anyone do nested classes for tests before

**Comment by akamud** [comment]
It is more common in other languages, I like to group some tests, like described [here](http://haacked.com/archive/2012/01/02/structuring-unit-tests.aspx/). It helps with readability.

I'm sorry, I wasn't clear enough about the -coverbytest. OpenCover is indeed reporting 100% correctly, but apparently it is not generating enough data for ReportGenerator to correctly show them here:
![image](https://user-images.githubusercontent.com/954102/29459540-8b8da610-83fa-11e7-8e75-8ac1a2d3bb3b.png)

It is only showing the tests in the first class.

I'm not sure if this is an issue with OpenCover or ReportGenerator itself, I'm not sure how to confirm that OpenCover is generating enough data for ReportGenerator.
If you confirm it is, then I'll open this on ReportGenerator.

**Comment by sawilde** [comment]
It seems we don't identify nested test classes at the moment.

**Comment by sawilde** [comment]
it'll be available in the latest build https://ci.appveyor.com/project/sawilde/opencover
