### ISSUE TITLE
When building OpenCover in Visual Studio 15.3.2, the Test Adapter for Google Test does not find the C++ unit tests

### ISSUE THREAD

**Issue by SteveGilham** [OpenCover/opencover#746]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [X] Something else -- .net 4.7

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10 (1703 Home)
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

The unmarked items are actually N/A

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior

Once I shut Visual Studio up by acceding to its suggestion that I install the Adapter Extension (presumably detecting some of the inclusions in the project), I expected it to discover the C++ unit tests and present/run them in the Test Explorer window

### Actual Behavior

Instead it presented messages as follows in the Output[Tests] window

```
[25/08/2017 21:11:41 Informational] 21:11:41.096 - No Google Test indicator file found for executable C:\Users\steve\Documents\GitHub\opencover\main\bin\Debug\x64\OpenCover.Test.Profiler.exe
[25/08/2017 21:11:41 Informational] 21:11:41.096 - 'C:\Users\steve\Documents\GitHub\opencover\main\bin\Debug\x64\OpenCover.Test.Profiler.exe' does not match default regex '[Tt]est[s]?[0-9]*\.exe'
```

In addition, even with the indicator file present, the tests are not discovered until the debug executables are built with /DEBUG:FULL

### Steps to reproduce the problem:

Install the latest Test Adapter for Google Test extension, and do "Run All" in the Test Explorer window.

**Comment by sawilde** [comment]
@SteveGilham Not sure what this has to do with OpenCover sounds like a VS issue

**Comment by sawilde** [comment]
@SteveGilham ah I see - thanks

**Comment by SteveGilham** [comment]
Master is now good.  Thanks!
