### ISSUE TITLE
When running the C++ unit tests I have no metric of their coverage

### ISSUE THREAD

**Issue by SteveGilham** [OpenCover/opencover#749]
Please provide the following information when submitting an issue. 

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [X] Something else (.net 4.7)

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10 (1703 Home)
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

Unchecked items are N/A; I'm using master at commit 8777060 as a baseline

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior

I should be able to get a measure of where code is being tested, so I know whether any changes made are in code that is already unit tested appropriately.

### Actual Behavior

Zip.  Nada.  Nothing.

### Steps to reproduce the problem:

Use any of the currently provided build tools or targets...

**Comment by sawilde** [comment]
@SteveGilham I was actually looking at that project last week as I noticed that the sonar coverage had plummeted and realised they were now counting the c++ code.

**Comment by SteveGilham** [comment]
At the moment I'm just generating the pretty HTML report with this change.  Generating Cobertura XML is a simple extension; not sure what Sonar would be expecting for C++ code.

**Comment by sawilde** [comment]
@SteveGilham, when we make it produce the XML and can always look to transform it to the required XML using XSLT if necessary.

**Comment by SteveGilham** [comment]
I guess I shoudl mark this one as closed, since the substance has moved to #753
