### ISSUE TITLE
Coverage of an F# assembly built in Release configuration misses some code

### ISSUE THREAD

**Issue by SteveGilham** [OpenCover/opencover#760]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [X] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [X] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Executing these unit tests should show the same results for both debug and release builds (ignoring the spurious coverage reported in #615)

```
namespace N
open NUnit.Framework
module M =
  type Thing = { Thing: string } with
    member this.bytes () = System.Text.Encoding.UTF8.GetBytes(this.Thing)
  let makeThing s = { Thing = s }

  [<Test>]
  let testMakeThing() =
    Assert.AreEqual("s", (makeThing "s").Thing)
    Assert.AreEqual(5, (makeThing "aeiou").bytes().Length)

module DU =
    type MyUnion =
        | Foo of int
        | Bar of string
    with member this.as_bar() = match this with
                                | Foo n -> Bar (string n)
                                | bar -> bar

    let returnFoo v = Foo v

    let returnBar v = Bar v

    [<Test>]
    let testMakeUnion() =
        Assert.AreEqual(returnFoo 10, Foo 10)
        Assert.AreEqual(returnBar "s", Bar "s")
        Assert.AreEqual(Bar "10", (Foo 10).as_bar())
```

### Actual Behavior

In the debug build, we see `returnFoo`, `returnBar`, `bytes` and `makeThing` showing expected coverage, but in release build they aren't.  Coverage results and reports from OpenCover 4.6.519 on a F#4.1 build attached

[debug.zip](https://github.com/OpenCover/opencover/files/1272806/debug.zip)
[release.zip](https://github.com/OpenCover/opencover/files/1272807/release.zip)

In practice, master and my branch to answer issue #615 give the same results (modulo fixes for that issue), as do libraries built in F#2.0 and F#4.1

### Steps to reproduce the problem:

As above.

**Comment by SteveGilham** [comment]
After further examination. I conclude that this is probably not fixable.

For example, where the debug build decompiles to the following C#
```
// N.DU
[Test]
public static void testMakeUnion()
{
	Assert.AreEqual(DU.returnFoo(10), DU.MyUnion.NewFoo(10));
	Assert.AreEqual(DU.returnBar("s"), DU.MyUnion.NewBar("s"));
	Assert.AreEqual(DU.MyUnion.NewBar("10"), DU.MyUnion.NewFoo(10).as_bar());
}
```
the release build decompiles to
```
[Test]
public static void testMakeUnion()
{
	Assert.AreEqual(DU.MyUnion.NewFoo(10), DU.MyUnion.NewFoo(10));
	Assert.AreEqual(DU.MyUnion.NewBar("s"), DU.MyUnion.NewBar("s"));
	Assert.AreEqual(DU.MyUnion.NewBar("10"), DU.MyUnion.NewFoo(10).as_bar());
}
```
showing that the no longer covered functions have been inlined here.  However they remain in the assembly, as part of its public API, if nothing else.

As  F#'s `private` corresponds to C#'s `internal`, marking the functions as F#-private doesn't actually hide them enough that the compiler will eliminate them for lack of callers (presumably because of reflection).

**Comment by sawilde** [comment]
@SteveGilham thanks for persevering on this - your contribution is appreciated.
