### ISSUE TITLE
Branch coverage explanation

### ISSUE THREAD

**Issue by kuskmen** [OpenCover/opencover#761]
Hey guys, this is not really an issue, but more likely asking for explanation.(I noticed gitter room is not used anymore.)

I ran opencover and I noticed that 
![image](https://user-images.githubusercontent.com/710652/30055083-fb8b763c-9236-11e7-86fd-d3acb9711ab4.png)
for some reason
`ProcessorContext context = null;` has two branches? Why is that?

**Comment by kuskmen** [comment]
Also I noticed some weird branching here which I thought I understand, but it appears I do not, here is my SO question -> https://stackoverflow.com/questions/46056691/how-do-i-verify-if-something-didnt-happen

**Comment by sawilde** [comment]
@kuskmen I see the SO question was answered.

The two branches I don't know without access to the compiled assembly - OpenCover counts IL branches not source code branches, sometimes the compiler likes to mess with our heads.

Open the assembly using ILSpy and you may be able to determine why the output is the way it is.
