### ISSUE TITLE
List tests that touched SUT lines

### ISSUE THREAD

**Issue by lukas-lansky** [OpenCover/opencover#765]
### My Framework

- [X] .NET 2
- [X] .NET 3.5
- [X] .NET 4
- [X] .NET 4.5
- [X] .NET 4.6
- [X] .NET 4.6.1
- [X] .NET 4.6.2
- [X] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [X] Windows 7 or below (not truly supported due to EOL)
- [X] Windows 8
- [X] Windows 8.1
- [X] Windows 10
- [X] Windows 10 IoT Core
- [X] Windows Server 2012
- [X] Windows Server 2012 R2
- [X] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [x] feature request

### Expected Behavior

OpenCover provides granual reporting on what test hit what line, as in [this SO question](https://stackoverflow.com/questions/43227142/get-list-of-covered-lines-per-unit-test-to-process-programmatically) of mine. Such reporting could be used for analytical purposes: is the codebase covered by a large number of unit tests, or by a low number number of integration tests that call everything without attention to detail?

### Actual Behavior

OpenCover aggregates all hits into single number (`vc`, "visit count") in its XML output.

### Steps to reproduce the problem:

Run the tool on a project with tests.

### Notes

Even if you are not interested in the feature, would you be able to just advise me where to start hacking in your codebase?

**Comment by sawilde** [comment]
You mean something like the functionality provided by the `-coverbytest:` switch that is described in the [usage document](https://github.com/opencover/opencover/wiki/usage)?

**Comment by lukas-lansky** [comment]
I can't believe I missed that. Thanks for the great piece of software!

**Comment by sawilde** [comment]
no worries
