### ISSUE TITLE
How to get the outputCoverage.xml data file automatically instead of press "Q" manually

### ISSUE THREAD

**Issue by ShootingStarLele** [OpenCover/opencover#766]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [X] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior

I use OpenCover to get the coverage of integration test, following is the details step (Operate in cmd):
1. net stop w3svc /y
2. OpenCover.Console.exe -target:C:\Windows\System32\inetsrv\w3wp.exe -targetargs:-debug -targetdir:C:\Inetpub\wwwwoot\MyWebApp\bin\ -filter:+[] -register:user -output:"C:\Desktop\Report\outputCoverage.xml"
3. Then there has a message: 
"Executing: C:\Windows\System32\inetsrv\w3wp.exe" 
"Press 'Q' to close the process"
4. Press 'Q' manually, then it will generate the data xml successfully 
Now, my question is: 
Is these a way to generate the data xml automatically instead of press "Q" manually? Please give me a help, thanks!

### Actual Behavior
Following is my attemption:
Scenarion1:
Press 'Q' manully, then will print
Committing...
Visited Classes 5 of 62 (8.06)
Visited Methods 45 of 741 (6.07)
Visited Points 102 of 4082 (2.50)
Visited Branches 65 of 2687 (2.42)
Then will generate the outputCoverage.xml file, and all the coverage data is right;

Scenarion2:
Kill the w3wp.exe process instead of Press 'Q', then will print
Committing...
Visited Classes 0 of 62 (8.06)
Visited Methods 0 of 741 (6.07)
Visited Points 0 of 4082 (2.50)
Visited Branches 0 of 2687 (2.42)
Then it also can generate the outputCoverage.xml file, but the coverage data is 0%

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by sawilde** [comment]
OpenCover produces its report at the end of the coverage run e.g. when the target process closes down.

You could try using "net stop" again or use some script e.g. powershell, to find the process and stop/kill it.
