### ISSUE TITLE
Multiple OpenCover reports

### ISSUE THREAD

**Issue by kandoeniko** [OpenCover/opencover#767]
Hello,

Do you know if it is possible that having multiple OpenCover reports which are merged in a single xml by Report Generator to be provided to SonarQube?

The structure of the xml generated by OpenCover and the one obtained by merging several reports is different.

Thanks in advance,

**Comment by sawilde** [comment]
I am afraid I don't know, I only ever send one report.

You might want to direct your question to the sonar people as it might be a feature that others may find useful.

**Comment by kandoeniko** [comment]
Thank you, indeed there is a sonar feature which enables it.

2017-10-14 11:00 GMT+03:00 Shaun Wilde <notifications@github.com>:
