### ISSUE TITLE
Running OpenCover from code

### ISSUE THREAD

**Issue by aireq** [OpenCover/opencover#769]
Is it possible to enable OpenCover from within the code itself rather than `OpenCover.Console.exe`?

The reason I ask is I'm working on a project that is a plug-in for another piece of of software with a .NET API. My code references the types of the API which only exist in the context of the application.  

I'm using NUnit for my unit tests. But to run my tests I have to manually invoke a custom command I created in the application as part of my plug-in.  This then uses [SimpleTestRunner ](https://stackoverflow.com/questions/2798561/how-to-run-nunit-from-my-code)to run the tests.

So would it be possible to enable code coverage tracking with OpenCover in the same sort of way from the code?

**Comment by sawilde** [comment]
If you can run the tests on the command line then you can run them with OpenCover

**Comment by aireq** [comment]
Sorry but no I wish I could run these test from a command line, but this is not possible. The .Net API my tests reference can only be accessed and manipulated via a thread provided by the main application.

Here's how I am currently running my unit test from a custom add-in using an NUnit SimpleTestRunner.

https://bitbucket.org/somddg/revit-unit-tests-visual-studio-template/src/038ede965ea92deaf3acfb84fb75c1a2e538b17c/RunUnitTestsCommand.cs?at=master&fileviewer=file-view-default#RunUnitTestsCommand.cs-59

There's no way I can trigger this code from the outside. It can only be run by clicking a button in the host application to trigger my custom command.

**Comment by sawilde** [comment]
how about you find a way to trigger your tests another way e.g. a command line switch to your application.
