### ISSUE TITLE
DirectoryNotFoundException

### ISSUE THREAD

**Issue by Jericho** [OpenCover/opencover#771]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [X] .NET 4.6.1
- [ ] .NET 4.6.2
- [X] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [X] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I expect OpenCover to report coverage of only my code.

### Actual Behavior

OpenCover is trying to report coverage of code from nuget packages my library references in addition to my own code. For example, it tries to locate the source code for `moq4`. Since it can't find these files, it throws numerous NotFound exceptions.

This issue seems to be the same as reported in #654 (which was closed due to insufficient information provided by OP, but never investigated or resolved) and #731. Please note that I'm the one who opened #731 but the NotFound exceptions "magically" disappeared and the discussion in the ticket switched to a different issue I was experiencing and was resolved by adding the `-oldstyle` parameter.

In this instance I have tried using the latest OpenCover (4.6.519), also tried using various beta versions (4.6.690, 4.6.780 and 4.6.793) and always I made sure to use the `-oldstyle` parameter. Unfortunately the result is always the same. 

The build script for my library has a step to invoke dotnet.exe to build the projects in my solution followed by a step for code coverage. The code coverage step looks like this:
```
E:/_build/Cake.SendGrid/tools/OpenCover.4.6.519/OpenCover/tools/OpenCover.Console.exe
 -target:"C:/Program Files/dotnet/dotnet.exe"
 -targetargs:"test E:/_build/Cake.SendGrid/Source/Cake.SendGrid.Tests/Cake.SendGrid.Tests.csproj --configuration Release --no-build"
 -filter:"+[*]* -[xunit.*]* -[Cake.Core]* -[Cake.Testing]* -[*.Tests]* -[Cake.Email.Common]*"
 -excludebyattribute:"*.ExcludeFromCodeCoverage*"
 -excludebyfile:"*/*Designer.cs;*/*.g.cs;*/*.g.i.cs"
 -oldStyle
 -register:user
 -returntargetcode:0
 -output:"E:/_build/Cake.SendGrid/BuildArtifacts/TestCoverage/OpenCover.xml"
 -returntargetcode
```

The output of this step looks like this:
```
Executing: C:\Program Files\dotnet\dotnet.exe
Test run for E:\_build\Cake.SendGrid\Source\Cake.SendGrid.Tests\bin\Release\netcoreapp1.1\Cake.SendGrid.Tests.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.1587426]   Discovering: Cake.SendGrid.Tests
[xUnit.net 00:00:01.2361794]   Discovered:  Cake.SendGrid.Tests
[xUnit.net 00:00:01.2417651]   Starting:    Cake.SendGrid.Tests
[xUnit.net 00:00:01.3642517]   Finished:    Cake.SendGrid.Tests

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.9074 Seconds
Test run for E:\_build\Cake.SendGrid\Source\Cake.SendGrid.Tests\bin\Release\net46\Cake.SendGrid.Tests.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.7121328]   Discovering: Cake.SendGrid.Tests
[xUnit.net 00:00:00.9005889]   Discovered:  Cake.SendGrid.Tests
[xUnit.net 00:00:00.9070292]   Starting:    Cake.SendGrid.Tests
[xUnit.net 00:00:01.0666095]   Finished:    Cake.SendGrid.Tests

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.6383 Seconds
Committing...
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\AdvancedMatcherAttribute.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\AsInterface.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\Capture.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\CaptureMatch.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\ConditionalContext.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\EmptyDefaultValueProvider.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\Evaluator.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\ExpressionExtensions.cs'.
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\ExpressionStringBuilder.cs'.
.. and several more DirectoryNotFoundException exceptions ...
```

### Steps to reproduce the problem:

You can see an example [here](https://ci.appveyor.com/project/cakecontrib/cake-sendgrid/build/0.5.0-rc.6.build.69#L682).

1. Clone `https://github.com/cake-contrib/Cake.SendGrid`
2. Check out the `release/0.5.0` branch
3. Execute  `.\build.ps1 -Target AppVeyor --settings_skipverification=true` from a PowerShell prompt

**Comment by Jericho** [comment]
**Additional Info**
After a lot of trial and errors and assistance from @pascalberger, we discovered that removing the reference to the moq nuget package makes the problem go away. So it seems to me there is something specific to moq that's causing OpenCover to behave differently.

**Comment by sawilde** [comment]
try excluding `moq` using the filters.

**Comment by Jericho** [comment]
I tried already and it didn't change anything. Also, my unit testing project references other nuget packages (such as `Shouldly` for example) and they do not cause this problem. For some reason OpenCover seems to have an issue specific to `moq`.

**Comment by SteveGilham** [comment]
I've seen this behaviour as well when there are any third-party files (not moq in my case) with matching `.pdb` files caught up in the process, and the source locations from those files get processed.  Since source isn't necessary for any of the process at this point, the exception is purely a cosmetic nuisance (being the sort of thing that only ought be seen in logfiles or at an explicitly selected verbose level of console logging).

Personally, in this context, I'd start my filter expression with `+[Cak*]*` rather than including the whole world by default.

**Comment by SteveGilham** [comment]
For the record, when trying to repro -- release/0.5.0 at Commit: b47b1235817e91962f0a185a8ded0d9d2dacd717 doesn't show the problem, as Commit: fe099dd7d89640344aec90a9a04cca2ebbf71769 does the necessary to the OpenCover filter.  Trying to build earlier commits than the current tip has consistently failed for me with `Error: GitVersion: Process returned an error (exit code 1).`

**Comment by SteveGilham** [comment]
Finally, purely as an example, here's simple repro case (assuming no inadvertent name matches) using just a "Hello, World!" program.  Unpack [Throwaway.zip](https://github.com/OpenCover/opencover/files/1424265/Throwaway.zip) and run
```
OpenCover.Console.exe "-target:.\Debug\Throwaway.exe" "-filter:+[*]*" -register:user
```

**Comment by Jericho** [comment]
@SteveGilham thanks for helping me research this issue but I'm not sure what your "throwaway" console example proves. You are demonstrating that OpenCover can run successfully against a console application but it's neither proving nor disproving that the issue I am reporting is legitimate. 

I am able to consistently reproduce the issue where OpenCover throws `DirectoryNotFound` exceptions under the following circumstances:
- C# library project
- unit test project
- unit test project is referencing `moq` nuget package

As further evidence of what I'm saying, please consider the attached "HelloWorld" project. Unzip it and run `.\build.ps1` from a PowerShell prompt. You can also run `.\build.ps1 -verbosity diagnostic` if you want to see more detailed logging.

To be clear: I can reproduce this issue consistently using `+[*]* -[*.Tests]*` and also `+[*]* -[*.Tests]* -[moq*]*` and let me reiterate that this issue seems to be triggered only when my unit testing project references `moq`. When I remove the `moq` reference, the problem goes away.

**Comment by Jericho** [comment]
One thing just occurred to me: the namespace for the `moq` nuget package is spelled `Moq` (notice the upper case first letter). Could it be that OpenCover's filtering is case sensitive? I just tried filtering `+[*]* -[*.Tests]* -[Moq*]*` and, sure enough, the problem goes away! As far as I'm concerned, this is an acceptable workaround but I would still be curious to get to the bottom of the underlying issue: what is it about the `moq` nuget package that triggers this issue in a way to other nuget packages don't?

@SteveGilham Having said all this, I think you make a valid point that my filter might be too broad. I changed it to a simpler `+[HelloWorld.*]* -[*.Tests]*` and I don't experience this problem.

**Comment by SteveGilham** [comment]
Yes, the filters are case-sensitive.  Although having names differing only in case is bad style and against framework guidelines, they are still distinct, and the filtering as implemented follows that.

The point of the "Throwaway" example -- an .exe with its .pdb, but no code -- is that it is a minimal example that provokes the DirectoryNotFoundException, as in
```
Executing: C:\Users\steve\Documents\Visual Studio 2017\Projects\Debug\Throwaway.exe
Hello, world!
Committing...
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\Users\steve\Documents\Visual Studio 2017\Projects\Throwaway\Throwaway\Program.cs'.
Visited Classes 1 of 1 (100)
Visited Methods 1 of 1 (100)
Visited Points 3 of 3 (100)
Visited Branches 1 of 1 (100)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 1 of 1 (100)
Alternative Visited Methods 1 of 2 (50)
```

**Comment by Jericho** [comment]
oh I see. I re-ran your "throwaway" example and I am now noticing the exception. I didn't notice it the first time I ran it and thought it completed successfully. What makes this situation particularly confusing, is that OpenCover throws an exception but it seemingly completes successfully.

**Comment by SteveGilham** [comment]
The comment in the `catch` clause which traps the exception and emits that message is 
```
// Source is optional (for excess-branch removal), application can continue without it
```
The message is logged at level `Info`, which is the default logging level -- but, [as noted earlier](https://github.com/OpenCover/opencover/issues/731#issuecomment-323549650), "it really shouldn't log to the user console like that."

**Comment by radheshchamarti** [comment]
I am also facing the same issue by using Moq
I used below filter and still it is working
-filter:"+[*]* -[Moq*]*"

OpenCover installed is 4.6.519

I used batch file as below

========================================================================================================

REM

dotnet build "E:\Radhesh\Code\Test_webapi_networkCall\networkCall.sln" /p:DebugType=Full

D:\Users\radhesh\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test E:\Radhesh\Code\Test_webapi_networkCall\networkCall.Tests\" -filter:"+[*]* -[Moq*]*" -oldStyle -register:user -output:"OpenCover.xml"

D:\Users\radhesh\.nuget\packages\reportgenerator\3.0.2\tools\ReportGenerator.exe -reports:"E:\Radhesh\Code\Test_webapi_networkCall\networkCall.Tests\OpenCover.xml" -targetdir:"E:\Radhesh\Code\Test_webapi_networkCall\networkCall.Tests\\Report"

pause

========================================================================================================

i am getting below error

`
Test run for E:\Radhesh\Code\Test_webapi_networkCall\networkCall.Tests\bin\Debug\netcoreapp2.0\networkCall.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:08.0154173]   Discovering: networkCall.Tests
[xUnit.net 00:00:08.2251636]   Discovered:  networkCall.Tests
[xUnit.net 00:00:08.2419303]   Starting:    networkCall.Tests
[xUnit.net 00:00:10.4010041]   Finished:    networkCall.Tests

Total tests: 6. Passed: 6. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 18.3953 Seconds
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.`

**Comment by d1820** [comment]
This worked for me
```
-filter:+[*Market*]* -[*Moq*]* -[*Microsoft.WindowsAzure.Storage*]* 
```
