### ISSUE TITLE
Reg - Filters Excluded

### ISSUE THREAD

**Issue by raj651985** [OpenCover/opencover#773]
Hi Team,

I am new to OpenCover, I have requirement in Filters
ex: 1.cs
2.cs
3.cs
4.cs

Assume 4 power shell script is there.
I need to exclude 3 files and need to add 1 files for include.
This is my requirments. Please help me on this.
Please correct me if i am wrong.

1.cs file i need to include and all 3 needs to exclude. Please correct me

my namespace is CommunicationService

-Filter:"+[*BAL.CommunicationService.1.cs] -[BAL.CommunicationService]*.cs" 

Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [x] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [x] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [x] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by raj651985** [comment]
help me on this!

**Comment by SteveGilham** [comment]
Filters work on IL-level concepts like assemblies, namespaces and classes, not on the level of source files (as the prevalence of `.cs` in your example suggests you are trying to do).

**Comment by SteveGilham** [comment]
On reflection, I wonder, did you mean you want something like
```
-excludebyfile:1.cs;3.cs,4.cs
```
to include only those methods defined in (from whichever types) 2.cs, by excluding the rest, for example?

**Comment by raj651985** [comment]
Thanks for your reply.
I have 3 projects like A and B and C. In all 3 projects having file called 1.cs,2.cs,3.cs,4.cs
Assembly name is ProjectAssemblyApi1, ProjectAssemblyApi2, ProjectAssemblyApi3, ProjectAssemblyApi4..

example - namespace1, namespace2, namespace3, namespace4

[string]$excludeFile = "+[*]* -[*\*1.cs]* - [*\*2.cs] -[*\*3.cs] -[*\*4.cs]"


please help me to filter only that 4 files in all 3 projects. The above it will work ? Plz help me on that...

**Comment by sawilde** [comment]
@raj651985 to exclude by file you need to use the syntax as described in the wiki

https://github.com/OpenCover/opencover/wiki/Usage#optional-arguments

```
-excludebyfile:<filename>[;<filename>][;<filename>]
```
