### ISSUE TITLE
No Coverage recorded in conjunction with NUnit 3

### ISSUE THREAD

**Issue by pchinery** [OpenCover/opencover#774]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I have set up this test project:
https://github.com/pchinery/opencover-bugreport

This executes OpenCover to call NUnit 3 with a single test to record the coverage.

### Actual Behavior

No coverage data can be recorded

### Steps to reproduce the problem:

Simply run build.cmd to see the result that no data can be recorded. This results in the usual "No results, this could be for a number of reasons. The most common reasons are..." message. The same call produced output with NUnit 2 (the parameters were adapted for NUnit 3 though).

As it is a problem with capturing the output, I thought that this would be the right place though instead of asking for help at the NUnit project.

**Comment by SteveGilham** [comment]
Although Paket didn't want to load some of the packages, 

- Downloading NUnit.Extension.NUnitProjectLoader 3.6.0
- Downloading NUnit.Extension.NUnitV2Driver 3.7.0
- Downloading NUnit.Extension.NUnitV2ResultWriter 3.6.0
- Downloading NUnit.Extension.TeamCityEventListener 1.0.2
- Downloading NUnit.Extension.VSProjectLoader 3.6.0
- Downloading NUnit.Runners 3.7.0

enough came down that I could manually kick off the Fake script and see it run through and generate this coverage.
[coverage.txt](https://github.com/OpenCover/opencover/files/1423596/coverage.txt)

This successful run is in line with my own experience of running NUnit 3 under OpenCover 4.6.519

**Comment by SteveGilham** [comment]
Logs scraped from the console for reference
[paket-fail.txt](https://github.com/OpenCover/opencover/files/1424035/paket-fail.txt)
[build-log.txt](https://github.com/OpenCover/opencover/files/1424036/build-log.txt)

**Comment by pchinery** [comment]
I have not fixed the paket files, the pointed to our internal nuget proxy. On my notebook, I can generate stats now, but on my main dev machine I am not able to produce them (in the test project as well as in our main project).

Do you know of any incompatibilities with .Net runtimes? What can I do to provide more useful information for debugging or finding the source of the problem?

**Comment by pchinery** [comment]
I don't know what has happened, but after the weekend, it works on the main machine as well (without code changes). So, I am sorry for bothering you, but many thanks for looking into this!
