### ISSUE TITLE
AppVeyor build not generating artifacts anymore

### ISSUE THREAD

**Issue by rgl** [OpenCover/opencover#776]
The [AppVeyor build](https://ci.appveyor.com/project/sawilde/opencover) is not producing artifacts anymore (the last one with a `.zip` was [build 4.6.793](https://ci.appveyor.com/project/sawilde/opencover/build/4.6.793/artifacts)), is that expected?

**Comment by SteveGilham** [comment]
My pull request (build 4.6.793), was the last time anything provoked a build.

**Comment by SteveGilham** [comment]
My most recent pull request (build 4.6.796), was the last time anything provoked a build.  It produced [artifacts as expected](https://ci.appveyor.com/project/sawilde/opencover/build/4.6.796/artifacts).

**Comment by SteveGilham** [comment]
Actually, there are builds up to [4.6.798 with artifacts](https://ci.appveyor.com/project/sawilde/opencover/build/4.6.798/artifacts).

**Comment by rgl** [comment]
Ah only your builds generate full artifacts?

When I meant that a build was not generating artifacts, I meant, a build like https://ci.appveyor.com/project/sawilde/opencover/build/4.6.798/artifacts, only produced the `cov-int\build-log.txt` articat. Is that expected?

**Comment by sawilde** [comment]
@rgl yes those builds are [Coverity](https://scan.coverity.com/) builds where the code is analysed weekly (automated) for any new issues. Because of the instrumentation that is added by the processing, we don't release those artifacts.
