### ISSUE TITLE
filter coverage not creaged by tests when using coveragebytest 

### ISSUE THREAD

**Issue by jmecosta** [OpenCover/opencover#778]
hi @sawilde,

quick question, i did not find this in any of the open/closed issues. 

im trying to do some test impact analysis for our integration/function tests so we only run the relevant tests.

our application is started and we have a dedicated runner running inside the process that loads nunit dlls and runs those tests. 

When collecting coverage i use the -coveragebytest and this works fine. however there is still coverage related with application initialization that i would like to filter when creating a report. Is there a switch that can be enabled that when coveragebytest is used then anything without test is ignored? Having that would already clean a bit of the artificial coverage numbers created by starting the app.

another question, is if this is not possible, do you have documentation on how i can parse the report to know what test tests what?

regards

jorge costa

**Comment by jmecosta** [comment]
@sawilde another question, what is needed to extend opencover to support other frameworks. we have our own custom framework for system tests and would like to get this there also

**Comment by sawilde** [comment]
@jmecosta I don't have any switches available that do what you want.

as for documentation, I haven't written anything up but I thought it would be simple to follow as the tests get an ID and the ID is recorded against the instrumentation point when it is hit.

Writing your own plugin should be possible (I think).

Have a look at 

https://github.com/OpenCover/opencover/tree/master/main/OpenCover.Extensions
and then you plug it into the OpenCover via the config file
https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Console/app.config#L8

**Comment by jmecosta** [comment]
@sawilde yep, ive eventually follow up the test report and i am able to filter all the artificial coverage as post process step. 

thanks for the link for the extensions, it was i i tought it would look like. So now i just need to work on the framework from my side.

regards

**Comment by jmecosta** [comment]
@sawilde i gave a try to my custom strategy and it did not work. then i wen i also used both nunit and xunit attributes on my test methods and even those are not reported. 

from what i see, ive attached to opencover.exe and i all the register strategy are called and loaded. 

so my guess its related with how the test run.

Basically this is a kind of macro based runner, so there is bit of code that gets compiled into a dll and then there is a application module inside the main application that loads the dll and calls this method named Run(IPlayer agent) for example:

```
namespace TheNameSpace
{
	using WhereAttribeIsDefined;
  
   [CustomScript]
    public class Script
    {
        [CustomRunMethod]
        public static void Run(TheRunner runner)
        {
            runner.Callback("");            
        }
    }
}
```

From the coverage report i can see the method is called:

```
          <Summary numSequencePoints="7" visitedSequencePoints="7" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="1" numClasses="1" visitedMethods="1" numMethods="1" />
          <FullName>TheNameSpace.Script</FullName>
          <Methods>
            <Method visited="true" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="100" branchCoverage="100" isConstructor="false" isStatic="true" isGetter="false" isSetter="false">
              <Summary numSequencePoints="7" visitedSequencePoints="7" numBranchPoints="1" visitedBranchPoints="1" sequenceCoverage="100" branchCoverage="100" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" visitedClasses="0" numClasses="0" visitedMethods="1" numMethods="1" />
              <MetadataToken>100663297</MetadataToken>
              <Name>TheNameSpace.Script::Run(TheRunner)</Name>
              <FileRef uid="19841" />
```

I also try to instead of using my custom attribute, to use directly teh name of the class: TheNameSpace.Script but with similar results. 

One thing that never changes between scripts is that all of them will have a similar signature TheNameSpace.Script::Run(TheRunner) but in different files. Im not really interested in the coverage in those methods, but only on the coverage that those methods generate. Because we can have multiple methods during a run then the final value of the coverage that all the scripts call will be the so called coverage by my test.

I would though that this would be comming out really easily, but its not. Can it be its because the script runner is native and the callstack can go from manage -> native -> manage and in different app domains?

I would be great if you would have some idea on whats going on. thanks

**Comment by sawilde** [comment]
@jmecosta The call-stack transition should not matter. Alas, I can't think of what is happening here - code sample?

**Comment by jmecosta** [comment]
@sawilde what kind of code sample. the extension point i can provide, however the application code im afraid i cant. 

maybe the best is to try to debug myself? can you point out what is the relevant area where i should place breakpoints to investigate from opencover side

**Comment by jmecosta** [comment]
im back at this, it all works now. i suspect the problem was the filtering for the -coverbytest switch.

thanks for the help.
