### ISSUE TITLE
I meet the No results with MissingPDB in xml, but it is there.

### ISSUE THREAD

**Issue by watsonsong** [OpenCover/opencover#781]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [X] Something else .NET Core 2.0

### My Environment

- [X] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior
I hope can get the coverage result.

### Actual Behavior
The symbol I want to test is MissingPDB

### Steps to reproduce the problem:
I am using the netcore2.0 and MSTest to do unit test. I called the OpenCover in this way:
`
SET OPENCOVER="C:\Users\Administrator\AppData\Local\Apps\OpenCover\OpenCover.Console.exe"
%OPENCOVER% -register:user -target:"dotnet.exe" ^
    -targetargs:"test -f netcoreapp2.0 -c Release D:\Repositories\MyProj\MyProj.Test\MyProj.Test.csproj" ^
    -targetdir:"D:\Repositories\MyProj\MyProj.Test\bin\Release\netcoreapp2.0" ^
    -searchdirs:"D:\Repositories\MyProj\MyProj.Test\bin\Release\netcoreapp2.0" ^
    -filter:"+[MyProj*]* -[MyProj.Test*]**" ^
    -mergebyhash ^
    -output:"D:\Repositories\MyProj.coverage.xml"
`

And I got the xml report with a lot of Filter(which is what I want), but two MissingPdb:
`
<Module skippedDueTo="MissingPdb" hash="59-45-4F-CC-DD-41-A3-0F-0C-47-4F-90-95-76-F9-C1-D7-5E-FF-A5">
      <ModulePath>D:\Repositories\MyProj\MyProj.Test\bin\Release\netcoreapp2.0\MyProj.Test.dll</ModulePath>
      <ModuleTime>2017-12-12T05:17:06Z</ModuleTime>
      <ModuleName>MyProj.Test</ModuleName>
      <Classes />
    </Module>
  </Modules>
`

**Comment by sawilde** [comment]
The release version of OpenCover does not handle the latest PDBs produced by .net core - this is currently in development - you'll need to take an experimental build directly from the build server.

https://ci.appveyor.com/project/sawilde/opencover/build/4.6.804

**Comment by watsonsong** [comment]
Thank you, I will test and waiting for the final release of  the new version.

**Comment by MNie** [comment]
@sawilde 
I encounter the same issue with F# project targeting .net core 2.0:
![image](https://user-images.githubusercontent.com/7689103/34109543-35705c5e-e404-11e7-98f7-0ae160c8ebcb.png)
![image](https://user-images.githubusercontent.com/7689103/34109577-53c5651e-e404-11e7-82f2-47b928f8f8c5.png)
[Repository](https://github.com/MNie/Codecov.FSharpExample) with code to reproduce error. I try to use opencover [from here](https://ci.appveyor.com/project/sawilde/opencover/build/4.6.804) but the same error occurs.
