### ISSUE TITLE
Pdb files for F# .net core 2.0 project were not found

### ISSUE THREAD

**Issue by MNie** [OpenCover/opencover#787]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [X] .NET Core 2.0

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/OpenCover/opencover/issues/781) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Report to be generated.

### Actual Behavior

Pdb files for project were not found:
![image](https://user-images.githubusercontent.com/7689103/34109543-35705c5e-e404-11e7-98f7-0ae160c8ebcb.png)
![image](https://user-images.githubusercontent.com/7689103/34109577-53c5651e-e404-11e7-82f2-47b928f8f8c5.png)

### Steps to reproduce the problem:

[Repository](https://github.com/MNie/Codecov.FSharpExample) with code to reproduce error. I try to use opencover [from here](https://ci.appveyor.com/project/sawilde/opencover/build/4.6.804) but the same error occurs.

CC: @sawilde

**Comment by sawilde** [comment]
thanks

**Comment by jp7677** [comment]
@MNie Your debugtype is set to "full" (https://github.com/MNie/Codecov.FSharpExample/blob/master/src/CodecovExample.TargetProject/CodecovExample.TargetProject.fsproj#L5). Please use "portable" and try again. See https://github.com/jp7677/hellocoreclr and https://github.com/jp7677/hellocoreclr/blob/master/src/HelloCoreClrApp.Rules/HelloCoreClrApp.Rules.fsproj for a working example.

**Comment by sawilde** [comment]
I couldn't get the project to compile
