### ISSUE TITLE
OpenCover for Mono on all platforms

### ISSUE THREAD

**Issue by savornicesei** [OpenCover/opencover#788]
Hi all,

### My Framework

- [x ] .NET 4.7
- [x ] .NET Core 2.0
- [x ] Mono 5.4

### My Environment
- [x ] Windows 10
- [x ] Linux (OpenSUSE 42.3)
- [x ] MacOS Sierra

### I have already...
- [ x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known. Seems like support for .NET Core on linux is WIP: https://github.com/OpenCover/opencover/issues/703 and https://github.com/dotnet/corefx/issues/17107

### My issue is related to (check only those which apply):
- [x ] feature request

### Expected Behavior
I was wondering if there are any plans to also support mono, since .NET Core and Mono do not overlap 100%. From a dev. perspective - what effort would imply supporting mono?

Thanks,
Simo

**Comment by SteveGilham** [comment]
OpenCover relies on the .net profiling APIs to inject instrumentation at run-time, 
but those aren't there on Mono.

Blowing my own trumpet here, but if you need something right now, I've recently dusted off [an old project of mine I've called AltCover](https://github.com/SteveGilham/altcover) that does the instrumentation by weaving the instrumentation as a separate step, and that does work on .net framework, .net core, and Mono, on Windows and (at least) Linux.  Line coverage only in classic NCover format, at the moment.

**Comment by savornicesei** [comment]
Hi @SteveGilham ,

I didn't know about AltCover. I will have to check if it reports similar statistics as OpenCover. Are there any plans to move it under OpenCover umbrella? 

It also seems that .NET Core 2.1  will contain a part of the Profiling API ([here](https://github.com/dotnet/coreclr/issues/15136) and [here](https://github.com/noahfalk/coreclr/blob/master/Documentation/project-docs/profiling-api-status.md))

Thanks,
Simo

**Comment by SteveGilham** [comment]
@ savornicesei 
Sequence point coverage only ATM in AltCover, and currently only in the classic NCover format (but watch this space).
Because of the separate instrumentation step and the dancing around required to work with `dotnet test`, I view AltCover as an interim solution until something less cumbersome comes along, now as it was when I wrote the first iteration back in 2010-11 after CLR4 broke freeware NCover.  Consequently I hadn't even considered trying to cosy up under the OpenCover banner.

**Comment by savornicesei** [comment]
Thanks @SteveGilham for the explanations.
