### ISSUE TITLE
When runnning MSTest coverage with multiple assemblies the merge is not done correctly

### ISSUE THREAD

**Issue by jupaol** [OpenCover/opencover#79]
Hi

I have been reading and I found this issue reported earlier, but it is not working for me, perhaps I am missing something

This is the scenario

I am using Visual Studio 2010 Ultimate on a 64 Bits laptop
OpenCover.3.0.121
ReportGenerator.1.2.6.0

The projects related are 3:
- One console project where I have the logic I am testing
- One test project where I have the Unit tests
- One test project where I am doing some integration test

Considerations
*\* I am using MSTest for all tests (both projects)
*\* All dlls are in the same directory
*\* I am using -mergebyhash

When I run the test coverage with only one assembly I can see in the report generated that the code is being reported as "visited", but when I run both projects some fragments of the code are reported as "not visited".

it seems when OpenCover merge the assemblies coverage, it takes the results where the code has not been covereged, I tried modifying the assemblies order just to see if the results of the last assembly specified were used but nope, it was the same result

Here are the xml fragments related to the projects

*_Without using -mergebyhash
*_Using -mergebyhash

https://skydrive.live.com/?cid=E047F6DFEA6C038C&id=E047F6DFEA6C038C%21756&sc=documents

This is the command line I am using to run: (I am formatting and  simplifying the paths for readability)

"OpenCover.Console.exe" 
   -mergebyhash 
   -returntargetcode 
   -register:user 
   -filter:"+[NCastor.Console]*" 
   -output:"OpenCover_MSTest_CodeCoverage.xml" 
   -target:"MSTest.exe"  
   -targetargs:"
      /testcontainer:\"Debug\NCastor.Console.Tests.dll\" 
      /testcontainer:\"Debug\NCastor.Console.Integration.Tests.dll\" 
      /detail:errormessage 
      /detail:errorstacktrace 
      /resultsfile:\"MSTestReport.trx\""

If you need more information please let me know

Thank you

**Comment by Samirshnino** [comment]
I have a problem that paths does not would as it it writen in my script
I've written the following but I got  "The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again."

Any help?




**C:\TFS\Sources\Trunk\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -targetdir: "C:\TFS\Sources\Trunk\Skuld\Skuld.Integration\bin\Debug" -mergebyhash -register -returntargetcode -filter:"+[Skuld.Integration*]*" -output:"C:\TFS\Sources\Trunk\Skuld\Skuld.Integration.Test\CodeCoverage.xml" -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\MSTest.exe" -targetargs:"C:\TFS\Sources\Trunk\Skuld\Skuld.Integration.Test\bin\Debug\Skuld. Integration.test.dll\ "/resultsfile:\"C:\TFS\Sources\Trunk\Skuld\Skuld.Integration.Test\bin\Debug\TestReport.trx\""**

**Comment by sawilde** [comment]
@Samirshnino it is hard to tell as the command you pasted got a little mangled when pasted into the comment. 

In the wiki we have a section on dealing with spaces - https://github.com/OpenCover/opencover/wiki/Usage#notes-on-spaces-in-arguments

e.g. you may want to do something like this

```
-target:"\"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\MSTest.exe\""
```

**Comment by jeevithakandasami** [comment]
Hi I am just started OpenCover 4.6.519.0 for C# project automation code cover ,its running the test case but i am getting error and coverage not updated but xml is created. Kindly help me.
![scr1](https://user-images.githubusercontent.com/43036118/45158335-4ceb4a80-b201-11e8-8dea-a417e2e5f249.PNG)

**Comment by jeevithakandasami** [comment]
![capture](https://user-images.githubusercontent.com/43036118/45158532-e0bd1680-b201-11e8-9627-70af407244ed.PNG)

**Comment by sawilde** [comment]
@jeevithakandasami - sorry I don't see this - please do not hijack closed issues - create new ones - more likely to be seen
