### ISSUE TITLE
OpenCover.Console MSbuild target -register flag

### ISSUE THREAD

**Issue by varun7447** [OpenCover/opencover#792]
I am currently using the latest version of opencover nuget package: I am running it as a MSBuild target. With register=true flag. How do I set register=:user flag? How to register profiler inside a target? I am not able to see any coverage results.

**Comment by sawilde** [comment]
The MSBuild target does not currently support per-user registration

**Comment by varun7447** [comment]
Oh ok, any suggestions? Currently we are having issues as no coverage

05:49:32 No results, this could be for a number of reasons. The most common reasons are: 05:49:32 1) missing PDBs for the assemblies that match the filter please review the 05:49:32 output file and refer to the Usage guide (Usage.rtf) about filters. 05:49:32 2) the profiler may not be registered correctly, please refer to the Usage 05:49:32 guide and the -register switch
