### ISSUE TITLE
Run OpenCover IISExpress with sembols

### ISSUE THREAD

**Issue by firatoltulu** [OpenCover/opencover#793]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [X ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X ] repeated the problem using the latest stable release of OpenCover.
- [ X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

Hi,
I Used OpenCover on IISExpress, but  IISExpress not loaded symbols.
I set targetdir and searchdir but it not loaded my symbols, 
what can i do? it run with symbols?

**Comment by sawilde** [comment]
OpenCover is really for testing against unit test libraries such as xunit, nunit etc. 

When you use IISxpress etc you are mostly on your own.

What is in the XML output of oepncover?
