### ISSUE TITLE
skippedDueTo="AutoImplementedProperty" Included in coverage output when -hideskipped:ALL is used

### ISSUE THREAD

**Issue by cjablonski76** [OpenCover/opencover#794]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X ] repeated the problem using the latest stable release of OpenCover.
- [X ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Class properties that are considered **AutoImplementedProperty** should be hidden from the code coverage output file if **-hideskipped:ALL** is passed.

### Actual Behavior

When running code coverage with **-hideskipped:ALL** passed, the coverage report will is hiding other skipped types, but still listing **skippedDueTo="AutoImplementedProperty"** results.
i.e.
`<Method skippedDueTo="AutoImplementedProperty" visited="false" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" crapScore="0" isConstructor="false" isStatic="false" isGetter="false" isSetter="true">
              <MetadataToken>12345</MetadataToken>
              <Name>System.Void Domain.Address::set_Address1(System.String)</Name>
              <FileRef uid="1" />
              <SequencePoints />
              <BranchPoints />
            </Method>`

### Steps to reproduce the problem:

1. run OpenCover from console

2. use the -skipAutoProps and -hideskipped:ALL arguments

3.  example command: 

> OpenCover.Console.exe -target:"C:\code\git\DTR\buildscripts\tools\NUnit.ConsoleRunner\tools\nunit3-console.exe" -targetargs:"C:\code\git\Services.Tests\bin\Debug\Services.Tests.dll" -filter:"+[MyAssembly*]* -[*Test*]*" -register:user -hideskipped:All -skipautoprops -mergebyhash -output:C:\myOutput\projectCoverageReport.xml

**Comment by cjablonski76** [comment]
I did dig around in the source quickly, and saw that in the **BasePersistance** class it has the following:
```
case SkippedMethod.AutoImplementedProperty:
                    RemoveSkippedMethods(SkippedMethod.Attribute);
                    RemoveEmptyClasses();
                    break;
```

I believe that the `SkippedMethod.Attribute` should be `SkippedMethod.AutoImplementedProperty` as the `SkippedMethod.Attribute` is already being covered in the `case SkippedMethod.Attribute` just above it.

I was unable to build the project locally, or I would have tried it out and contributed if it was the fix.

**Comment by sawilde** [comment]
thanks - I'll have a look
