### ISSUE TITLE
Update nuget packages

### ISSUE THREAD

**Issue by stromblom** [OpenCover/opencover#796]
Unless I'm completely missing something, the packages on nuget.org have not been updated since February of 2016. Are there any specific reasons as to why?

**Comment by sawilde** [comment]
No major updates to OpenCover - we've been waiting on the latest version of mono.cecil and I don't have the time to support OpenCover properly never mind one using beta packages.

**Comment by stromblom** [comment]
Could you just push it as a preview or something?

**Comment by sawilde** [comment]
Potentially but I haven't been able to test it and it will only lead to more support requests than I can handle at the moment.

**Comment by sawilde** [comment]
@stromblom a release candidate is now available with the expectation of a new version by the end of the month
