### ISSUE TITLE
Is OpenCover designed to skip assemblies that are not covered by tests?

### ISSUE THREAD

**Issue by nathanbedford** [OpenCover/opencover#797]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [X] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

OpenCover generates coverage for all assemblies that I care about (regardless of whether they have covering tests or not).  This way I can see quickly that a project (which is part of the solution) has zero test coverage.

### Actual Behavior

OpenCover only generates coverage output for assemblies that are executed by the target.  Other project assemblies that have zero test coverage are ignored, and don't negatively affect the project coverage scores.  

These assemblies have pdbs, and in a few cases I do see coverage for an assembly here or there (zero-coverage, like I would hope for), but in most cases, if an assembly isn't exercised, it doesn't show up in the output at all.

### Steps to reproduce the problem:

* Create solution with multiple projects
* Write unit test that only exercises one of the projects
* No coverage is reported for projects that are not tested

**Comment by sawilde** [comment]
You can use filters to stop `other` assemblies from being covered

**Comment by sawilde** [comment]
@quetzalcoatl OpenCover only instruments assemblies if they are loaded so if the test does nothing to force those assemblies to be loaded then OpenCover will not see them

**Comment by quetzalcoatl** [comment]
That's right! That's why, to get full coverage, I implemented a dumb hack in form of an additional always-succeeding test that "blindly loads every DLL from project output dir". I don't recommend that due to security problems, but - it worked, of course. A better way would be to scan the .sln/.csproj and load only specific dlls, but that's a lot more work to spend on it and I was just curious to see the full %

**Comment by sawilde** [comment]
Yup - I can see how that would work

**Comment by papauorg** [comment]
I just had the same problem with my solution. I tried to load all assemblies in the output directory like @quetzalcoatl suggested - with this snippet from SO: https://stackoverflow.com/a/2384679
I just put that in a test of a testproject and added all other projects as project reference.

The resulting report does not include the untested projects, though. Am I doing something wrong here? Or do I have to write a test that actually calls a method of each referenced project as mentioned in #300.

Thanks for your help.

**Comment by sawilde** [comment]
Just load an assembly is probably not enough. OpenCover needs a specific event (`ModuleAttachedToAssembly`) that will cause it to track an assembly. 

You could try iterating the types in the assembly you just loaded or instantiating at least one of the types.
