### ISSUE TITLE
OpenCover not generating proper coverage for projects with target framework net4.6.1

### ISSUE THREAD

**Issue by Sandipan-Ghosh** [OpenCover/opencover#799]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [x] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

OpenCover is suppose to  generate coverage for Net2+

### Actual Behavior

But in my case with the above configuration and with the follwing command line:

../OpenCover/OpenCover.Console.exe -target:"C:\Program Files\d
otnet\dotnet.exe" -targetargs:"test -f net461  -c Debug D:\OpenCoverSample\OpenCoverSampleGit\Sample.API.Test\Sample.API.Test.csproj" -mergeoutput -oldstyle -hideskipped:File -output:coverage\coverage.xml -filter:"+[Sample.API*]*" -searchdirs:D:\OpenCoverSample\OpenCoverSampleGit\Sample.API.Test\bin\Debug\net461 -register:user

led to the result:
Committing...
Visited Classes 0 of 2 (0)
Visited Methods 0 of 2 (0)
Visited Points 0 of 10 (0)
Visited Branches 0 of 2 (0)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 0 of 2 (0)
Alternative Visited Methods 0 of 4 (0)
and the generated :- coverage.xml (https://github.com/Sandipan-Ghosh/OpenCoverSample/blob/master/OpenCoverSampleGit/Sample.API.Test/coverage/coverage.xml) in the module name "Sample.API" and "Sample.API.Test" skippeDueTo=MissingPdb occurs, even though i have provided the path where pdb files are present
and the coverage calculation is incorrect.
I have tried all the work arounds, the debugtype is "full" in both the projects
 and i have also kept xunit.runner.console in the Sample.API.Test project,also tried to run the command from xunit.runner.console.exe, but nothing worked and every time the coverage calculated was zero.
the link to the project is https://github.com/Sandipan-Ghosh/OpenCoverSample/tree/master

After trying out all possible solutions i made a new application in a different folder and then changed the target frame work of the projects to netcoreapp2.0 and kept everything same and edited the command line to make it look like

../OpenCover/OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe"
 -targetargs:"test -f netcoreapp2.0 -c Debug D:\SampleApplication\Sample.API.Test\Sample.API.Test.csproj" -mergeoutput -
hideskipped:File -output:coverage\coverage.xml -oldstyle -filter:"+[Sample.API*]*" -searchdirs:D:\SampleApplication\Samp
le.API.Test\bin\Debug\netcoreapp2.0 -register:user

which led to the result 

Committing...
Visited Classes 2 of 3 (66.67)
Visited Methods 2 of 3 (66.67)
Visited Points 10 of 12 (83.33)
Visited Branches 2 of 3 (66.67)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 2 of 3 (66.67)
Alternative Visited Methods 2 of 6 (33.33)

and the generated coverage.xml(https://github.com/Sandipan-Ghosh/SampleApplication/blob/master/SampleApplicationGit/Sample.API.Test/coverage/coverage.xml) in the module name "Sample.API" and "Sample.API.Test" skippeDueTo=MissingPdb didnot occur, and the report was properly generated.
The link to the working project is:  https://github.com/Sandipan-Ghosh/SampleApplication/tree/master

So kindly help me out with the solution so that i can opencover generates proper coverage for projects with target framework net4.6.1

### Steps to reproduce the problem:

Make a solution with multiple projects and a test project the target framework of the projects should be net4.6.1

**Comment by sawilde** [comment]
Why do you think the coverage is wrong? Your Xunit test only executes AddTwoNumbers and that is the code that is showing coverage (including the test according to your filters)

**Comment by Sandipan-Ghosh** [comment]
well, as i have mentioned the link of the project that is provided below i.e. "https://github.com/Sandipan-Ghosh/SampleApplication/tree/master" with target framework netcoreapp2.0 it works absolutely fine ,
but the project with the link " https://github.com/Sandipan-Ghosh/OpenCoverSample/tree/master" with target framework net4.6.1 doesnot generate proper coverage although proper file is targeted according to the filter.Please take a look at this screenshot
![image](https://user-images.githubusercontent.com/25679980/37076400-6a3d337c-21fc-11e8-98d7-ae894b4f4d80.png),
you will see that the line coverage generated is 0%, and this is the issue.

**Comment by Sandipan-Ghosh** [comment]
If it is possible, please clone both the repositories(the working and the non-working) at your end, i am sure that will present you with a better overview.

**Comment by Sandipan-Ghosh** [comment]
you can see in the description that the syntax looks like this "../OpenCover/OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe"
-targetargs:"test -f netcoreapp2.0 -c Debug D:\SampleApplication\Sample.API.Test\Sample.API.Test.csproj" -mergeoutput -
hideskipped:File -output:coverage\coverage.xml -oldstyle -filter:"+[Sample.API*]*" -searchdirs:D:\SampleApplication\Samp
le.API.Test\bin\Debug\netcoreapp2.0 -register:user"

you can checkout the link of the working project as well.

**Comment by sawilde** [comment]
@Sandipan-Ghosh 4.6.519 will not deal with dotnet core applications very will due to recent changes in PDB/MDB files.

you may want to try one of the pre-release builds - https://ci.appveyor.com/project/sawilde/opencover/history - until we publish new packages
