### ISSUE TITLE
Issue in getting coverage for exe (console app). Only getting coverage for dll.

### ISSUE THREAD

**Issue by rajeevsoni** [OpenCover/opencover#813]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [X] .NET 4.7.1
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Coverage should be done for exe as well.

### Actual Behavior

Not getting coverage for exe. coverage is done only for dlls

### Steps to reproduce the problem:

Create any console app with target frame work 4.7.1 and add static class in it with some static functions(let say for getSum, getDifference etc for calculator )and a test project for testing the static functions testing .
Now try to get coverage for the exe project.

**Comment by sawilde** [comment]
Sorry can't repeat
