### ISSUE TITLE
Could not load a managed C# DLL from path instead of loading from GAC.

### ISSUE THREAD

**Issue by Anbu2388** [OpenCover/opencover#815]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [X] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [x] 32 or 64 bit support
- [X] feature request

### Expected Behavior

I tried to load the assembly in Assembly Resolve event. Also I got the hook up and loaded the assembly in the app domain using Assembly.LoadFrom.

### Actual Behavior

But when I access a method from the assembly in the same app domain I got assembly not found error, since it tries to bind in default load context.

### Steps to reproduce the problem:

I tried to load the assembly in Assembly Resolve event in an application. It will hook up and loaded the assembly in the app domain using Assembly.LoadFrom method. I got the error below,

> Could not load file or assembly 'MyDotNetAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8b6549a3d401ea66' or one of its dependencies. The system cannot find the file specified.

It tries to load using default load context. Please help me to load the assembly in default load context without putting in GAC.

@sawilde

**Comment by sawilde** [comment]
I don't understand the issue - and no code provided to repeat it
