### ISSUE TITLE
Vstest not discovering test after using custom test adapter  

### ISSUE THREAD

**Issue by akshukla009** [OpenCover/opencover#816]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [x ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ x] Windows Server 2016

### I have already...

- [x ] repeated the problem using the latest stable release of OpenCover.
- [x ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Unit test should be discovered.

### Actual Behavior
No unit tests are discovered even if providing the test adapter path.
I am using below nuget package  and vsstudio 2017 professional  
 MSTest.TestFramework.1.3.0-beta2
MSTest.TestAdapter.1.3.0-beta2 
OpenCover" version="4.6.519" targetFramework="net462"

**Comment by sawilde** [comment]
no repeatable sample provided
