### ISSUE TITLE
Identification of Namespaces using filters

### ISSUE THREAD

**Issue by ritwiksen** [OpenCover/opencover#817]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- .NET 4.5

### My Environment
Windows Server 2012 R2

### I have already...

- repeated the problem using the latest stable release of OpenCover.
- reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document]

### My issue is related to (check only those which apply):

- [yes ] no coverage being recorded

My issue is more around understanding the open cover filters better. For example,

I have an assembly called **TestProject.TestAssembly**. Within that I have a class called **ClassA** which sits under a chain of  Subfolders called **Subfolder1** and **Subfolder2**. Thus the namespace of the class, would be like **TestProject.TestAssembly.Subfolder1.Subfolder2**. Now to exclude all the classes inside the namespace with **Subfolder2**, would my exclusion filter be :  **-[TestProject.TestAssembly]\*Subfolder2.\***   or **-[TestProject.TestAssembly]\*.Subfolder2.\*** or **-[TestProject.TestAssembly]\*.Subfolder2\***.

Following up on the previous example, if I wanted to exclude all classes within any Module that contains **TestProject** in it, would the exclusion filter be something like :  **-[\*TestProject\*]***  or **-[\*.TestProject.\*]*** .

Thanks!

**Comment by sawilde** [comment]
Run coverage without any filters so it defaults to all and then use the output file to identify assemblies you wish to remove etc
