### ISSUE TITLE
Failed to register(user:True,register:True,is64:False):3 the profiler assembly;

### ISSUE THREAD

**Issue by coczero** [OpenCover/opencover#818]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [X ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X ] repeated the problem using the latest stable release of OpenCover.
- [X ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I should get a normal coverage report (the same .bat file works fine on my work machine (its literally the same paths))

### Actual Behavior

Getting the "Failed to register(user:True,register:True,is64:False):3 the profiler assembly;" error.
My whole bat file looks like this:

```
IF not exist "bin\Debug\CoverageReport" mkdir "bin\Debug\CoverageReport"
Coverage\OpenCover\OpenCover.Console.exe -register:user -target:"bin\Debug\Last.fm-Scrubbler-WPF-Test.exe" -output:"bin\Debug\CoverageReport\CoverageResult.xml" -filter:"+[Last.fm-Scrubbler-WPF]Scrubbler* -[Last.fm-Scrubbler-WPF]Scrubbler.Views.*" -log:Error
Coverage\ReportGenerator\ReportGenerator.exe -reports:"bin\Debug\CoverageReport\CoverageResult.xml" -targetdir:"bin\Debug\CoverageReport" -reporttypes:Html -verbosity:Error
start "" "bin\Debug\CoverageReport\index.htm"
```

and the whole output of my .bat file is then:
```
Failed to register(user:True,register:True,is64:False):3 the profiler assembly; you may want to look into permissions or using the -register:user option instead. C:\WINDOWS\system32\regsvr32.exe /s  /n /i:user "E:\Stuff\Github\Last.fm-Scrubbler-WPF\Last.fm-Scrubbler-WPF-Test\Coverage\OpenCover\x86\OpenCover.Profiler.dll"
If you are unable to resolve the issue please contact the OpenCover development team
see https://www.github.com/opencover/opencover/issues
```

### Steps to reproduce the problem:

Running the CreateCoverageReport.bat in the repo: https://github.com/coczero/Last.fm-Scrubbler-WPF

**Comment by numbworks** [comment]
I have also this issue :-/

**Comment by kevinwedwards** [comment]
We're having this issue too.  It worked on .NET 4.5.2, but on 4.6.1 it's failing

**Comment by sawilde** [comment]
can't repeat
