### ISSUE TITLE
Using Open cover and Sonar Qube,  Code coverage reporting showing zero in dashboard

### ISSUE THREAD

**Issue by gjayakumar92** [OpenCover/opencover#820]
I am able to all the bug reports other than code coverage. code coverage is coming as zero.

I am using below comments,

"C:\Sonar\sonar scanner\MSBuild.SonarQube.Runner.exe" begin /k:"org.sonarqube:sonarqube-scanner-msbuild" /n:"ProjectName" /v:"1.0" /d:sonar.cs.opencover.reportsPaths="%CD%\opencover.xml"

"C:\Program Files\dotnet\dotnet.exe" build

"C:\Sonar\opencover\OpenCover.Console.exe" -oldStyle -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -output:"%CD%\opencover.xml" -targetargs:"Tests\ProjectName.Services.Tests\ProjectName.Tests.csproj"

"C:\Sonar\sonar scanner\MSBuild.SonarQube.Runner.exe" end

**Comment by wburgers** [comment]
As target you use dotnet.exe.
As targetargs you just specify the test csproj.
Will dotnet.exe know what to do with this csproj or do you need to use `dotnet **test** <path/to/csproj>`

So -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test Tests\ProjectName.Services.Tests\ProjectName.Tests.csproj"

**Comment by gjayakumar92** [comment]
@wburgers I tried but still i am getting code coverage report as zero :(

**Comment by BilalChughtai** [comment]
@gjayakumar92 did you find the solution? I'm also having similar issue.

**Comment by medianick** [comment]
I initially tried the "%CD%\opencover.xml" approach, but what ultimately worked was simply specifying the filename by itself, i.e., /d:sonar.cs.opencover.reportsPaths="opencover.xml" (as this file was in the root of my build workspace). My OpenCover-generated coverage report was then successfully located and posted to SonarQube.
