### ISSUE TITLE
Nuget package doesnt install OpenCover in NetCore projects

### ISSUE THREAD

**Issue by Barsonax** [OpenCover/opencover#822]
I have installed the OpenCover nuget package in a NetCore project but I dont see anything getting installed on nuget restore.

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [x] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue. (OpenCover is not installed so I cannot do this)
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I expect OpenCover to be installed somewhere so I can use it

### Actual Behavior

Nothing happens

### Steps to reproduce the problem:

- Create NetCore project
- Install OpenCover
- Nothing is installed

**Comment by agray** [comment]
I always install OpenCover from NuGet at the project level, not the solution level.  For some reason it doesn't work at the solution level.  Working for me in .net core 2.1

**Comment by Barsonax** [comment]
I ended up installing it as a chocolatey package which actually works better and keeps the repo cleaner.
