### ISSUE TITLE
Coverage Results wrong when posted to SonarQube server

### ISSUE THREAD

**Issue by pkaramol** [OpenCover/opencover#823]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [X] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

Using MSBuild Sonar Scanner on docker container

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

To post (upload) coverage results in SonarQube Server

### Actual Behavior

Coverage is erroneously reported at 0.0%

### Steps to reproduce the problem:

Running unit tests in a job, producing coverage report and saving coverage artifacts:

    - git checkout origin/develop
    - git merge $CI_BUILD_REF --no-commit --no-ff
    - cp -r /tools .
    - dotnet restore
    - dotnet build
    - cd tools
    - dotnet minicover instrument --workdir ../ --assemblies test/**/bin/**/*.dll --sources src/**/*.cs
    - dotnet minicover reset
    - cd ..
    - for project in test/**/*.csproj; do dotnet test --no-build $project; done
    - cd tools
    - dotnet minicover uninstrument --workdir ../
    - dotnet minicover opencoverreport --workdir ../ --threshold $COV_THRES
    - dotnet minicover report --workdir ../ --threshold $COV_THRES
    - cd ..
    artifacts:
      name: "coverage-report"
      paths:
        - opencovercoverage.xml
        - coverage-hits.txt
        - coverage.json
      expire_in: 1 hour

Running SQ in **another** stage (the above files __are__ available as an `ls` command shows):

    script:
      - mono /msbuild/SonarQube.Scanner.MSBuild.exe begin /d:sonar.login=$SONARQUBE_TOKEN /d:sonar.host.url=$SONAR_URL /v:$PROJECT_VERSION /k:$SONAR_PROJECT_KEY /d:sonar.cs.opencover.reportsPaths="opencovercoverage.xml".
      - dotnet restore
      - dotnet build
      - ls -al
      - mono /msbuild/SonarQube.Scanner.MSBuild.exe end /d:sonar.login=$SONARQUBE_TOKEN

Sonarqube reports `0.0%` coverage.

This is __NOT__ the case when combining the above jobs in a single one.

Why is that?

  [1]: https://github.com/lucaslorentz/minicover

**Comment by sawilde** [comment]
@pkaramol - sorry don't know - you'd need to ask the sonar community
