### ISSUE TITLE
MEASURING MANUAL/AUTOMATED FUNCTIONAL TESTS CODE COVERAGE

### ISSUE THREAD

**Issue by Haripdurai** [OpenCover/opencover#824]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [x ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ x] repeated the problem using the latest stable release of OpenCover.
- [x ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

Issue: We are trying to generate code coverage on performing manual tests for application hosted in Azure app services using Open cover.

I have a trail account in portal.azure.com with 'user' privilege.
	
Opencover has been used in the localhost (IIS server) to successfully generate code coverage on runnign manual tests.
	
Steps for code coverage using Open Cover in Azure
	1. OpenCover.Console.exe -target:C:\Windows\System32\inetsrv\w3wp.exe -targetargs:"-debug -s 1" -targetdir:C:\inetpub\wwwroot\bin\ -filter:+[*]* -register:user -output:C:\Users\coverage2.xml
	
	Issue 2: Access denied is displayed when the application is not running.
	Issue 3: The generated coverage file is empty and doesn't has the same error mentioned in Issue 1, on executing the opencover command when the application is running.
	
	Reference: https://automationrhapsody.com/code-coverage-manual-automated-tests-opencover-net-applications/
	
	Any help on the reason for the generated coverage file to be empty ? or any reference to suffice my requirement would be much appreciated?

### Expected Behavior

Code coverage is generated

### Actual Behavior

The code coverage is not generated

**Comment by sawilde** [comment]
OpenCover is really for automation tests - supporting OpenCover outside of this realm is not something I currently have time for - sorry
