### ISSUE TITLE
Option -searchdirs is ignored if there is a mismatch with PDB on the same folder as the assembly

### ISSUE THREAD

**Issue by pjanotti** [OpenCover/opencover#825]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [X] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Typical search for PDBs: if there is a mismatch continue trying on the available paths

### Actual Behavior

OpenCover bails out if the PDB on the same folder as the assembly is a mismatch.

### Steps to reproduce the problem:

Put a mismatched pdb on the folder of the assembly and a correct one on a different folder and pass this extra folder to -searchdirs

**Comment by sawilde** [comment]
@pjanotti I think we are in a position to take the PR assuming it comes with proper tests

**Comment by pjanotti** [comment]
Hi @sawilde good to hear back. I'm really busy with some other stuff so for the time being I have no idea when I will be able to look back at this.

**Comment by sawilde** [comment]
@pjanotti no worries - I have given myself a deadline to release a version of OpenCover this month. I have an initial list of issues I want to address and then if I have time I'll pick up other pieces if I can replicate them.
