### ISSUE TITLE
Merging Reports after the run

### ISSUE THREAD

**Issue by corentinaltepe** [OpenCover/opencover#827]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [X] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [X] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [X] feature request

**Problem**
I have a need to merge OpenCover's output reports AFTER running tests coverage analysis separately. The reason behind this is I have a list of unit tests and a list of integration tests. I run coverage for each separately, generate reports, then I combine both reports for a global coverage. I use ReportGenerator to generate the reports, and it merges OpenCover reports well. However, Jenkins doesn't have an OpenCover plugin to nicely integrate the coverage reports, so I publish the ReportGenerator HTML reports into Jenkins.

I also use an OpenCover-to-Cobertura converter, and then use Jenkins' Cobertura plugin to pulish the results in a nice format in Jenkins, but that works for only 1 report (either Units Tests list or Integration Tests).
I would like to merge the Unit Tests and Integration Tests results of OpenCover, to then convert it to Cobertura for an easy publishing to Jenkins. I have looked at merging Cobertura reports as an alternative but without luck.

**Implementation**
Looking at OpenCover XML report structure, it should be quite easy to do :
1 . Copy/Paste the _Modules_ lists from each report to the merged report.
2. Compute the _Summary_ of each report, and this is where there is a bit of business logic to implement and will need maintenance later on. From my understanding : 
- _numSequencePoints_, _visitedSequencePoints_, _numBranchPoints_, _visitedBranchPoints_, _visitedClasses_, _numClasses_, _visitedMethods_, _numMethods_ are simply sums of each report's _Summary_ respective attributes
- _maxCyclomaticComplexity_ and _minCyclomaticComplexity_ are the min/max of all reports
- _sequenceCoverage_, _branchCoverage_ are trickier, would you explain how I can compute them properly ?
- Am I forgetting something ?

**Question**
Do you think a merging feature would have its place in OpenCover ? I would see it as a command line verb action such as : _opencover merge -source:unit.tests.xml,integration.tests.xml -output:global.xml_

I personnally believe such feature should be part of OpenCover's core, and not as a peripheral tool, because it's code should evolve with the core's business logic (if, for example, the sequence and brancheCoverage computation rules evolve or new ones are added).

Would you accept such pull request ?

**Comment by danielpalme** [comment]
You could also use the latest ReportGenerator release:
https://www.nuget.org/packages/ReportGenerator/4.0.0-rc2

It supports *Cobertura* as an output format.
Just use the following command line parameters:
`ReportGenerator.exe -targetdir:TODO -reports:TODO -reporttypes:HTML;Cobertura ...`

ReportGenerator merges the coverage reports and generates a Cobertura file, which you can use for Jenkins.

OpenCover also has a `-mergeoutput` parameter. Maybe this helps (I have not yet used it myself):
https://github.com/OpenCover/opencover/wiki/Usage

**Comment by mridulnahar** [comment]
OpenCover also has a -mergeoutput parameter. i tried this option to merge coverage report but it doesn't work. please guide me if there is any solution available to merge reports.
https://github.com/OpenCover/opencover/wiki/Usage

**Comment by sawilde** [comment]
@corentinaltepe yes but it would need to be supported with plenty of tests

**Comment by VishalKulkarni0787** [comment]
Hi, my solution has 80, UT assemblies, 160 Integration test assemblies.
I each of these individually these to cover 100 production assemblies.
So for each assembly execution i get a coverage session report. Each report being approx 250 MB.
Totally now i have 40GB of files 
Now i want to merge these reports to get overall coverage. 
I have not tried loading all these files together to ReportGenerator, will it work?
But would be great if i could do it one by one, merging and enhancing report.
This way consolidation could be parallelised and made faster.

**Comment by danielpalme** [comment]
@VishalKulkarni0787 
_ReportGenerator_ should be able to handle those files. Just give it a try.

**Comment by sawilde** [comment]
I always use report generator I see no need for this feature
