### ISSUE TITLE
No coverage being recorded for a .NET Website

### ISSUE THREAD

**Issue by er1csg** [OpenCover/opencover#828]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ Yes] .NET 4.7.1

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [Yes ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [Yes ] repeated the problem using the latest stable release of OpenCover.
- [Yes ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [Yes ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I was expecting OpenCover being able to detect the classes in my main Web project has been covered by matching the UnitTest project methods to my Web project method.
e.g. it should return like "35%" code coverage done for my main Web project based on the number of unit tests i have written

### Actual Behavior

OpenCover only returns my UnitTest project coverage as 100%.
![image](https://user-images.githubusercontent.com/7194860/43174090-df83c37e-8fea-11e8-92a5-dc7b121421a2.png)

1) Download .NET Webgoat project
https://www.owasp.org/index.php/Category:OWASP_WebGoat.NET
2) Upgraded the .NET Webgoat project to VS2018 solution and using .NET 4.7
3) Create UnitTest project for .NET WebGoat
4) Create OpenCover.ps1 based on references below:
https://codewithstyle.info/setting-up-coverage-reports-on-vsts-with-opencover/
5) Packages used
OpenCover.4.6.519
OpenCoverToCoberturaConverter.0.3.3
ReportGenerator.3.1.2

*I am using TFS2018 to build the project
![image](https://user-images.githubusercontent.com/7194860/43174159-24239e46-8feb-11e8-9d21-17d8f202389b.png)

**Comment by binoperez** [comment]
Hi er1csg, 

I am also trying Milosz post regarding publishing code coverage (https://codewithstyle.info/setting-up-coverage-reports-on-vsts-with-opencover/) however I am receiving this error on my end. May I know how you managed to publish your code coverage successfully? 

![image](https://user-images.githubusercontent.com/25294018/43926285-6b2383be-9bef-11e8-926a-a4cba0106c67.png)

Thanks in advanced!

**Comment by er1csg** [comment]
Hi there,

for the OpenCover, there is a need for *.pdb files to be existent in order for it to work.
For example below, my project (which is a web app) the pdb file exist in my bin folder
![image](https://user-images.githubusercontent.com/7194860/43932714-4c3342bc-9c78-11e8-9056-5e42dd309b57.png)

i hope this helps and shed some light.
thanks!

**Comment by binoperez** [comment]
Thanks eric! I will try that. Goodluck on your app! :)

**Comment by sawilde** [comment]
Are the target assemblies being loaded by nunit? If not then they are not unit tests and they are integration tests as such you would need to force Opencover to load when your website loads i.e. IIS - this is always problamatic we have some wiki entries on that and then execute your tests against the site.
