### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by Jarbasjuniorbh** [OpenCover/opencover#829]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ x ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [x] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ x ] repeated the problem using the latest stable release of OpenCover.
- [ x ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ x ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ x ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

The OpenCover profile is causing the following error in my application:

AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

I tried to play OpenCover with many different parameters, registering using -register:user, -register:Path64 and also manually with regsvr32, but it's crashing the application.
I also generated a full dump file according to its log, the root cause of it is the file OpenCover.Profiler.dll.
The weird thing is that executing the same code without opencover my application works as expected, without crash.

Thanks in advance.

**Comment by Jarbasjuniorbh** [comment]
Some additional details captured with WinDbg:

PROBLEM_CLASSES: 

    ID:     [0n309]
    Type:   [@ACCESS_VIOLATION]
    Class:  Addendum
    Scope:  BUCKET_ID
    Name:   Omit
    Data:   Omit
    PID:    [Unspecified]
    TID:    [0x13b8]
    Frame:  [0] : OpenCover_Profiler!DllRegisterServer

    ID:     [0n281]
    Type:   [INVALID_POINTER_READ]
    Class:  Primary
    Scope:  DEFAULT_BUCKET_ID (Failure Bucket ID prefix)
            BUCKET_ID
    Name:   Add
    Data:   Omit
    PID:    [Unspecified]
    TID:    [0x13b8]
    Frame:  [0] : OpenCover_Profiler!DllRegisterServer

BUGCHECK_STR:  APPLICATION_FAULT_INVALID_POINTER_READ

PRIMARY_PROBLEM_CLASS:  APPLICATION_FAULT

**Comment by sawilde** [comment]
@Jarbasjuniorbh - sorry I don't know and I don't have a way to repeat it.
