### ISSUE TITLE
Unable to load the test container 'C:\ABC\src\ABC.Mvc.Tests\bin\Debug\netcoreapp2.0\ABC.Mvc.Tests.dll' or one of its dependencies. Error details: System.IO.FileNotFoundException: 

### ISSUE THREAD

**Issue by anuragacharya** [OpenCover/opencover#832]
Please provide the following information when submitting an issue. 

### My Framework

- [x] .NET 2
-
### My Environment

- [X] Windows 10

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
(https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Actual Behavior

Its not loading the test dll file. Seem like a path mismatch issue and hence generated the blank report without any coverage numbers

![image](https://user-images.githubusercontent.com/3384586/43611170-4366bc16-9676-11e8-9c6d-2c9e49bf655e.png)

![image](https://user-images.githubusercontent.com/3384586/43611463-2fd903ec-9677-11e8-87b1-07347e742d21.png)

**Comment by sawilde** [comment]
no sample provided
