### ISSUE TITLE
How to do branch coverage in a visual studio project using msunittest

### ISSUE THREAD

**Issue by pani94** [OpenCover/opencover#834]
### My Framework
- [X ] .NET 4.7.2
### My Environment
- [X ] Windows 10

### I have already...

- [X ] repeated the problem using the latest stable release of OpenCover.
- [X ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

I have no idea how I can do a branch coverage using Visual Studio 2015. I have already used the opencover ui extension and I got a line coverage. I was wondering how to get a branch coverage. I have seen some examples that use the command line .I have not a file .exe in my directory. I have a directory UnitTestProject in which are presents the classes cointaing tests. How I can run them using openCover command line?

Thanks in advance,

**Comment by sawilde** [comment]
I don't follow - OpenCover does both line and branch coverage - if OpenCover UI does not show the branch coverage then you'll need to reach out to that team.
