### ISSUE TITLE
vstest take to much time using opencover 

### ISSUE THREAD

**Issue by ferste01** [OpenCover/opencover#836]
Hi,

i read a lot of issue but never find something that can help me so i try my chance opening a new one.
I m working on setting code analysis and code coverage on jenkins.

When i make  : 

Starting command line: "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "TestsUnitaires\bin\Debug\TestsUnitaires.dll" in a cmd console or jenkins i got : 

Total tests: 822. Passed: 822. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2,2007 Minutes
Process 2232 has disconnected

then i used opencover : 

"C:\opencover.4.6.519\OpenCover.Console.exe" -output:"D:\Jenkins\workspace\Test\opencover.xml" -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"TestsUnitaires\bin\Debug\TestsUnitaires.dll" 

and this is my result :  

Total tests: 822. Passed: 822. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 32,8578 Minutes
Committing...
Visited Classes 233 of 388 (60.05)
Visited Methods 3178 of 5318 (59.76)
Visited Points 20416 of 27636 (73.87)
Visited Branches 4737 of 8295 (57.11)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 275 of 469 (58.64)
Alternative Visited Methods 3335 of 5720 (58.3)

2 minutes vs 32 minutes just because of usin opencover.... Do i do something wrong ?

**Comment by AraHaan** [comment]
No, maybe some performance issue.

**Comment by sawilde** [comment]
@ferste01 - you are not doing anything wrong - OpenCover instruments your code i.e. adds lots of extra IL to gather data in the hit points. I don't know what tests you are running and if only certain tests are heavily impacted but I would look to isolate any problematic tests first and see what makes them different
