### ISSUE TITLE
memory trash when app contains too many classes

### ISSUE THREAD

**Issue by zvikab1** [OpenCover/opencover#837]
My tested app is a service containing ~10000 classes
When opencover tries to start my service the service (which is .NET 4.61) fails with 
Exception Info: System.AccessViolationException
   at System.CannotUnloadAppDomainException.VisitedCritical(Int32)
   at System.CannotUnloadAppDomainException.SafeVisited(Int32)
at a random place inside my app

Starting the service w/o opencover works succesfuly
If I add filters to the opencover parameters to exclude one dll (no matter which) this does not happen

I would speculate that when opencover is handling too many files or too many code lines during the instrumentation phase this causes some buffer ovverun or something like this, which causes a mem trash inside my app

I would really (and desperatelly!) appreciate any help here as our build process is currently stuck until we can solve this.
Thanks
Zvika

### My Framework
- [X ] .NET 4.6.1

### My Environment
- [X ] Windows Server 2012 R2

**Comment by sawilde** [comment]
Interesting but I don't have an easy way to repeat - make your assemblies smaller
