### ISSUE TITLE
Question - Brackets coverage

### ISSUE THREAD

**Issue by ful-stackz** [OpenCover/opencover#839]
### My Framework

- [x] .NET 4.5

### My Environment

- [x] Windows 10

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] question about coverage

### Current Behavior

I am using OpenCover + ReportGenerator and something in the output is bugging me. Methods that do not return a value have their closing bracket highlighted as covered line, whereas methods that do return a value do not have their closing bracket highlighted. These images will explain it better:

![non-return-1](https://user-images.githubusercontent.com/28789098/49441171-05efff80-f7c6-11e8-881f-eb7e64f04e80.PNG)
_Image 1.a Void method_

![non-return-2](https://user-images.githubusercontent.com/28789098/49441172-05efff80-f7c6-11e8-9ed3-b3752906c653.PNG)
_Image 1.b Void method_

![return-1](https://user-images.githubusercontent.com/28789098/49441174-06889600-f7c6-11e8-9c9c-90f0f93d7e77.PNG)
_Image 2.a Non-void method_

![return-2](https://user-images.githubusercontent.com/28789098/49441175-06889600-f7c6-11e8-8b00-5998896410b1.PNG)
_Image 2.b Non-void method_

### ReportGenerator

According to [issue #181](https://github.com/danielpalme/ReportGenerator/issues/181) at the ReportGenerator repo, ReportGenerator is only responsible for making the OpenCover report readable. So this issue is not caused by ReportGenerator.

### Question
I wonder why that happens. I guess the execution of a void method ends with the bracket and the execution of a type-returning method ends with the return statement?

**Comment by sawilde** [comment]
The line numbers covered by a sequence point are embedded in the PDB file - we only use what is supplied to us.
