### ISSUE TITLE
opencover exe is not in my path

### ISSUE THREAD

**Issue by red8888** [OpenCover/opencover#842]
installed via MSI and after closing and reopening a console session OpenCover.Console.exe is not in my path.

Are there msi switches to enable this?

**Comment by sawilde** [comment]
Sorry no

**Comment by red8888** [comment]
so looks like I was using the wrong choco package this package seems to work out of the box: https://chocolatey.org/packages/opencover.portable

Is this safe to use? It hasnt been updated in quite a while, but then neither has opencover so I feel like I can rely on choco to install for me

**Comment by sawilde** [comment]
yes that package is safe to use - we will hopefully pushing a new package at the end of the month
