### ISSUE TITLE
No results, this could be for a number of reasons. Following latest documentation

### ISSUE THREAD

**Issue by Coding-Hen** [OpenCover/opencover#849]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [X] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [X] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [X] Windows Server 2008
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior
Using the [https://docs.sonarqube.org/pages/viewpage.action?pageId=6389770#CodeCoverageResultsImport(C#,VB.NET)-OpenCover](SonarCube Documentation) for getting the opencover to intergrate should produce the test coverage to make the coverage report so that it can get uploaded.

### Actual Behavior
Results (nunit3) saved as TestResult.xml
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

### Steps to reproduce the problem:
Using nunit 3 and the latest build of the opencover. 
"G:\Program Files (x86)\OpenCover\OpenCover.Console.exe" -output:"Tests\TestCoverage.xml" -register:user -target:"G:\Program Files (x86)\Nunit\nunit-console\nunit3-console.exe" -targetargs:"Tests\Tests.csproj"

I have tried all the issue resolutions such as using the noshadow etc. these have been deprecated in nunit3 and no longer work and have also tried the --shadowcopy with no working solution found. Some help would be appreciated.

**Comment by sawilde** [comment]
Do you get an output file? If so what does it say for each assembly as to why it was skipped?

**Comment by Coding-Hen** [comment]
@sawilde Thanks for getting back. By output if you mean the results file it created then I get the nunit one but with the one from opencover it displays this (seems empty).

`<CoverageSession><Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0"/><Modules/></CoverageSession>`

**Comment by Coding-Hen** [comment]
Seem to have resolved the issue the file is now created and results populated needed to be run with -register:administrator rather than user

**Comment by sawilde** [comment]
@Coding-Hen - Ah - a build server - I think the Usage.pdf mentions that you should pre-register the profiler assemblies because the services are running under service accounts.

**Comment by nomi12345** [comment]
On running command:
image
image

I am getting following error:
Failed to register(user:False,register:True,is64:False):5 the profiler assembly; you may want to look into permissions or using the -register:user option instead. C:\WINDOWS\system32\regsvr32.exe /s

**Comment by sawilde** [comment]
and did you try `-register:user` ?

**Comment by Coding-Hen** [comment]
Intresting havent looked at our build for a while now but this issue has reappeared. Still running with the -register:administrator but is now presenting the no results error

**Comment by sawilde** [comment]
pretty sure `-register:administrator` shouldn't work - what version of OpenCover are you using.

**Comment by Coding-Hen** [comment]
Neither user or administrator seem to be working. Using the current latest release - OpenCover (Release) 4.7.922

**Comment by Coding-Hen** [comment]
I can further add to this I have successfully got it running by using the opencover nuget package on the same version 4.7.922 this leads me to believe that there some difference between the two executables provided?

**Comment by Krendeled** [comment]
Hi, I seem to have the same issue in [my project](https://github.com/Krendeled/TeaBagBot):
`No results, this could be for a number of reasons.`
Neither -register:admin, -register:user or -register didn't solve the problem. I'm using the latest version of OpenCover + Appveyor.

**Comment by sawilde** [comment]
@Krendeled I haven't had time to try the latest versions of .net core with opencover - it could be that the mono.cecil package we are currently using does not support that framework

**Comment by Krendeled** [comment]
@sawilde I recall it worked with .net core 2, but after a while I switched to latest version and it just stopped working. When should we expect a fix or a workaround for this issue?

**Comment by nacitar** [comment]
Just noting that I ran into this issue, it worked fine on my machine but not on my build server... I looked at it for a long time, and eventually realized that in add/remove programs installing the more recent version did not _replace_ the other, at least not fully, so there was some sort of weirdness where I'm guessing the prior version's dlls were registered instead of the new one.  Uninstalled both of them, installed the new one again... worked perfectly.

**Comment by slateAGF** [comment]
Hmm we are just seeing the opposite; our old build agents was recently updated to 4.7.922; they work.
We just added 3 new agents (using chef scripts); so they have a clean 4.7.922 install; they fail with "No results..."

Most of our projects are netcore 3.1 and netstandard2.0 with a few remaining net48. The tests are run with dotnet test.

<Exec Command="$(OpenCoverExe) -target:&quot;$(DotnetExe)&quot; -targetargs:&quot;test $(TestTarget).dll --logger:trx;LogFileName=$(XUnitResultXml)&quot; -oldstyle -output:&quot;$(CoverageResultDir)$(TestTarget).xml&quot;" WorkingDirectory="$(WorkDir)" IgnoreStandardErrorWarningFormat="true" />

**Comment by nacitar** [comment]
Ran into this again and it turned out to be bad programmatically generated filters effectively excluding everything.  Anyone who beats their head against this problem should consider any filters they may be using.
