### ISSUE TITLE
OpenCover 4.7 introduced a breaking change: dependency on .NET 4.7.2

### ISSUE THREAD

**Issue by splatteredbits** [OpenCover/opencover#878]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [X] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I expect that minor releases of OpenCover continue to work on the same frameworks as past minor releases. We are on .NET Framework 4.7.1 and can't upgrade to .NET Framework 4.7.2. The latest version of OpenCover requires 4.7.2. This is a breaking change.

### Actual Behavior

OpenCover fails to run with a prompt saying it requires .NET framework 4.7.2.

### Steps to reproduce the problem:

1. Try to run OpenCover 4.7 on a computer/server with .NET Framework 4.7.1 installed. Note that it fails.

Forcing people to use a different version of an underlying platform is a breaking change. Please 1. replace version 4.7 with 5.0; or publish a version of 4.7 that still works on 4.7.1.

- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
Hi - I am sorry you affected by the breaking change but it is expected. 

If you need the latest version of OpenCover then please install .NET 4.7.2 on your platform.

**Comment by splatteredbits** [comment]
Please don't do this in the future. If you introduce a breaking change, you need to change the major version number of your package. This should have been OpenCover 5.x.y.

**Comment by sawilde** [comment]
@splatteredbits I try keep the number in line with the version of .NET being supported - it isn't a perfect system but since this is a tool I am not bothered about assembly dependencies.

I'll try to make sure the release notes reflect the required version

**Comment by splatteredbits** [comment]
Since you're publishing to NuGet.org, it is expected/assumed you're using [semantic versioning](https://semver.org). I think most developers today assume that than assume you're following or trying to follow .NET versions. Your tool isn't .NET. It's confusing that you're following its version numbering.

**Comment by splatteredbits** [comment]
See also [NuGet Package Version Reference](https://docs.microsoft.com/en-us/nuget/reference/package-versioning). This is what most people who consume your package are expecting/assuming.

**Comment by sawilde** [comment]
@splatteredbits the tool is .NET (combination of C# and C++ and runs on the .NET API) but the API it is supporting is the .NET profiler API (and hence why I tied them together). Since none of the assemblies are referenced by your code (or shouldn't be) then it does not need to follow semantic versioning - IMO.

As I said I'll look to add any runtime prereqs to the release notes in the future.

**Comment by ZAHEERPASHA** [comment]
Hi @sawilde,
I am using OpenCover 4.7.922.0 and using mstest for .net framework projects.. When i run open cover i see all tests passed but it doesnt generate any outout in xml.
i see below message :
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

what change should i make to fix it.
