### ISSUE TITLE
Tests Failure : Setup Error

### ISSUE THREAD

**Issue by p51d78th** [OpenCover/opencover#88]
I am trying to setup OpenCover with RegortGenerator to try my hand at TDD.

I checked out the Code, compiled Release4 using nant, and then installed OpenCover. 

I implemented Microsofts BankAccount Tests and ran them in NUnits GUI and all the test (I implemented 3) passed. I also ran the nunit-console application on the DLL to check to see if that worked.

With both of those working I went onto getting OpenCover to work.

I ran a bat script to run the dll through OpenCover and received several errors.

```
NUnit-Console version 2.6.0.12051
Copyright (C) 2002-20011 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment -
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 2.0.50727.5448 ( Net 3.5 )

ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
.F.F.F
Tests run: 3, Errors: 0, Failures: 3, Inconclusive: 0, Time: 0.1195239 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Errors and Failures:
1) SetUp Error : BankAccount_Test.Account_Test
   SetUp : System.MissingMethodException : Method not found: 'Void System.CannotUnloadAppDomainException.SafeVisited(Int32)'.
   at BankAccount_Test.Account_Test..ctor()

2) Parent Failure : BankAccount_Test.Account_Test.New_Account_Negative_Opening_Test
   TestFixtureSetUp failed in Account_Test
3) Parent Failure : BankAccount_Test.Account_Test.New_Account_No_Opening_Sucess_Test
   TestFixtureSetUp failed in Account_Test
4) Parent Failure : BankAccount_Test.Account_Test.New_Account_Opening_Sucess_Test
   TestFixtureSetUp failed in Account_Test
```

Here is my bat script

```
"%HOMEPATH%\AppData\Local\Apps\OpenCover\OpenCover.Console.exe" ^
    -register:user ^
    -target:"C:\Program Files (x86)\NUnit 2.6\bin\nunit-console.exe" ^
    -targetargs:"BankAccount_Test\bin\Debug\BankAccount_Test.dll /noshadow" ^
    -filter:+[*]* ^
    -output:BankAccount_Test.xml

:"C:\bin\ReportGenerator\bin\ReportGenerator.exe" ".\BankAccount_Test.xml" TestReports
```

I tried to search for anyone else having this issue and the only reference was on stackoverflow but no resolution was provided.

I am running on Windows 7 64 bit Ultimate with Visual Studio 2010 Professional.
Is there something I am doing wrong? I can send the BankAccount Solution Folder if needed.
Let me know if there is anything I left out.

Thanks
David

**Comment by jldgit** [comment]
Excuse the thread necrophilia. I'm sure this is long dead and corrected, but I had an issue when writing my profiler. When creating my method signature inside of the CLR profiler I mistakenly used ELEMENT_TYPE_I instead of ELEMENT_TYPE_I4. 

So, later on when I made the profiler "smart" and it'd read the parameter list I was using a directive like this that would swap out the I for I4 in some cases.

Example:

```C
#ifdef _WIN64
	COR_SIGNATURE sigFunctionProbe[] = {
		IMAGE_CEE_CS_CALLCONV_DEFAULT,      // default calling convention
		0x04,                               // number of arguments == 4
		ELEMENT_TYPE_VOID,                  // return type == void
		ELEMENT_TYPE_U8,                    // arg 1: UInt64 moduleIDCur
		ELEMENT_TYPE_U4,                    // arg 2: UInt32 mdCur
		ELEMENT_TYPE_I4,                     // arg 3: int intA
		ELEMENT_TYPE_I4,                     // arg 4: int intB
	};
#else //  ! _WIN64 (32-bit code follows)
	COR_SIGNATURE sigFunctionProbe[] = {
		IMAGE_CEE_CS_CALLCONV_DEFAULT,      // default calling convention
		0x04,                               // number of arguments == 4
		ELEMENT_TYPE_VOID,                  // return type == void
		ELEMENT_TYPE_U4,                    // arg 1: UInt32 moduleIDCur
		ELEMENT_TYPE_U4,                    // arg 2: UInt32 mdCur
		ELEMENT_TYPE_I,                     // arg 3: int intA
		ELEMENT_TYPE_I,                      // arg 4: int intB
	};
#endif //_WIN64
```

This was because I had assumed that I'd be using the correct native integer value when, in fact, .NET compiled into Int32 each time (Duh).

```C#
static int AddNumbers(int i, int b)
{
   return i + b;
}
```

**Comment by sawilde** [comment]
@jldgit - thanks, I had a quick look but couldn't see anything obvious along those lines
