### ISSUE TITLE
I have a few files where closing brace considered as not tested

### ISSUE THREAD

**Issue by calimero1000582** [OpenCover/opencover#880]
I have a few files where closing brace considered as not tested
![image](https://user-images.githubusercontent.com/3637661/53642823-9e005800-3c00-11e9-856b-6f758038ca75.png)

There is 8 space before the closing brace

In OpenCover.xml, for this file, I have
```xml
<SequencePoint vc="0" uspid="11514" ordinal="8" offset="317" sl="502" sc="9" el="502" ec="10" bec="0" bev="0" fileid="1003" />
```

_Originally posted by @calimero1000582 in https://github.com/OpenCover/opencover/issues/219#issuecomment-468674225_

**Comment by calimero1000582** [comment]
As requested in issue #219, I have all the files, but I will do a couple of run to see if I have the same results between run and build

**Comment by sawilde** [comment]
@calimero1000582 I'd need a repeatable code sample as I need to see what the IL is that is being reproduced to see why the tool either failed to instrument the point or explain why the code didn't pass through the instrumentation.

**Comment by calimero1000582** [comment]
So far, I have the same result after few build, I will try to reduce the size of the code to the minimum

**Comment by calimero1000582** [comment]
So I have been able to reduce the code to this. I understand that we throw an exception, but the closing brace does not seem to be considered all the time, probably due to IL code, not expecting to reach it after return or throw

```csharp
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace DummyTestClass
{
    [TestClass]
    public class CoverageIssue
    {
        [TestMethod]
        [ExpectedException(typeof(NotImplementedException))]
        public void ExpectExeption_MissingCoverage()
        {
            ThrowException();
        }

        [TestMethod]
        public void NoExption_FullCoverage()
        {
            NoException();
        }

        [TestMethod]
        [ExpectedException(typeof(NotImplementedException))]
        public void ExpectExeption_AlsoMissingCoverage()
        {
            ThrowException();
        }

        [TestMethod]
        [ExpectedException(typeof(NotImplementedException))]
        public void ExpectExeptionLocal_FullCoverage()
        {
            throw new NotImplementedException();
        }

        public void NoException()
        {
        }

        public void ThrowException()
        {
            throw new NotImplementedException();
        }
    }
}
```

And the report
![image](https://user-images.githubusercontent.com/3637661/53889567-a091f180-3ff4-11e9-9b77-67d03b66ed41.png)

**Comment by sawilde** [comment]
Hi - yup you are right because the compiler sees that an exception is thrown it does not include the final `}` as part of the final sequence point. 

OpenCover uses the data in the PDB file as-is it makes no attempt to second guess the compiler's intentions.
