### ISSUE TITLE
opencover 4.7.922 hangs on Jenkins server

### ISSUE THREAD

**Issue by harinim02** [OpenCover/opencover#882]
Hi,
I am trying to run the latest opencover on Jenkins server, and the tests are taking a lot of time (more than 3 hours) and never completes. I tried the same command on my local (Windows 10) and it works perfectly fine and takes <1min for execution. 
I also noticed that if I reduce the version to 4.6.519, the Jenkins has no problem in executing it. 

`packages\OpenCover\tools\OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test .\MyApp.UnitTests\MyApp.UnitTests.csproj" -registe -filter:"+[MyApp]* -[MyApp.UnitTests]*" -output:"coverage\MyApp.xml" -searchdirs:".\MyApp.UnitTests\bin\Debug" -returntargetcode`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [X] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

It should run on the Jenkins server. 

### Actual Behavior

The Jenkins command reached the test command, and is just stuck there for hours and never completes. While the same command works perfectly fine on the local machine. 

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
Can you RDP on to your jenkins box and see what is happening?

**Comment by harinim02** [comment]
It is stuck coz the machine was running on .net 4.7.0. The builds started passing once we upgraded to 4.7.2

**Comment by sawilde** [comment]
Hi - that makes sense OpenCover 4.7.xxx requires .net 4.7.2 to be installed
