### ISSUE TITLE
I want to execute opencover for multiple windows services of my project. how can I achieve this?

### ISSUE THREAD

**Issue by pcmenon198** [OpenCover/opencover#885]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X ] .NET 4.5
- [ X] .NET 4.6
- [ X] .NET 4.6.1
- [X ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ X] Windows Server 2012
- [X ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

I want to execute opencover for multiple windows services of my project. how can I achieve this?

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ X] feature request

### Expected Behavior
I have 4 - 5 Windows Services of my application that I need to run opencover for and get coverage.
These services are running on the same system.
How can i run target multiple services on the a single command line execution frame.

### Actual Behavior
Need Assistance in command execution as Help page is not effective

### Steps to reproduce the problem:

- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
Run several copies of OpenCover (1 for each service) and then merge the results at the end using ReportGenerator
