### ISSUE TITLE
Running Open cover on remote process

### ISSUE THREAD

**Issue by asaffori** [OpenCover/opencover#886]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [X] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [X] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior
I am looking for the correct way to run the opencover and get my case answewred. I have multiple Nunit tests calling remote procedures in an executable file. In this case coverage in the test class itself will not reflect the right coverage but I need to run the coverage on the execuatble file while having the test(s) executed in parallel.
Is tehre anyway to do that with OpenCover?

**Comment by sawilde** [comment]
OpenCover will only gather coverage of the local process(es) under test it cannot get the coverage of a remote process. 

You could run the remote process using OpenCover and get the coverage of that process.

**Comment by asaffori** [comment]
What do you mean by local/remote process? Both are local running on same session. The process I want to cover is opening an application, so can I run it with open cover and in parallel run the test which will simulate some actions on that program to get the program coverage?

Sent from my iPhone

On 9 Apr 2019, at 0:56, Shaun Wilde <notifications@github.com<mailto:notifications@github.com>> wrote:


OpenCover will only gather coverage of the local process(es) under test it cannot get the coverage of a remote process.

You could run the remote process using OpenCover and get the coverage of that process.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenCover_opencover_issues_886-23issuecomment-2D481023173&d=DwMCaQ&c=YlQJHsR4e2z6sq5iNUb1-8UzPbEw9OnHGjBjyVyvpyA&r=_5UMdr8im-uIgK_EbTSAeCvw3vD1OgSUrFfh5W25p0Q&m=lX3ZBgX-wtULd7iBCJaF6cB02Q7JUXiNI2NvxEh6tkU&s=IgFq5BqSe1uqZw07QOWgH4IuFRau5kuHjPDZ6IE1Z48&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AZkBStQE4W74-5FjLGvPO4NNi1i4FWdt5Fks5ve7r2gaJpZM4cajsK&d=DwMCaQ&c=YlQJHsR4e2z6sq5iNUb1-8UzPbEw9OnHGjBjyVyvpyA&r=_5UMdr8im-uIgK_EbTSAeCvw3vD1OgSUrFfh5W25p0Q&m=lX3ZBgX-wtULd7iBCJaF6cB02Q7JUXiNI2NvxEh6tkU&s=Q1UmFpezf8BeH2mHROlbo8RTpZcxi0_AE4Q23snwO64&e=>.

KLA-Tencor is now KLA! Learn more at kla.com <https://www.kla.com/>

**Comment by sawilde** [comment]
When you said remote I assumed [wrongly it seems] it was on another machine.
 
OpenCover will only profile applications that were launched under its session (due to environment variables). If your test is making a remote call then the other app may not be in the same session and so will not be seen by OpenCover.

You can use OpenCover to launch a batch file which may of course launch your target application first and then your unit tests.
