### ISSUE TITLE
Exception "No method calls found in recording block" is raised when Opencover is used with Typemock.

### ISSUE THREAD

**Issue by amar89mech** [OpenCover/opencover#887]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [X] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [X] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1

- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [X ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior
Test case should run successfully without exception.

### Actual Behavior
TypeMock.TypeMockException: 
*** No method calls found in recording block. Please check:
 * Are you trying to fake a field instead of a property? try to set field
 * Are you are trying to fake an unsupported mscorlib type? See supported types here: http://www.typemock.com/mscorlib-types</Message>

Getting the above exception on the WhenCalled() method of Isolator. This exception is thrown out of following line of code where its trying to fake Directory.Exists() method of library System.IO.

Isolate.Whencalled(() => Directory.Exists("Temp")),WillReturn(true);

Important point to note is that, this work absolutely fine when TMockRunner is run alone and the issue is faced only when TMockrunner is run along with Opencover.
Typemock version: 8.2
OpenCover Version: 4.7

### Steps to reproduce the problem:
Below is the script used, when this issue is faced.
"C:\Program Files (x86)\Typemock\Isolator\8.2\TMockRunner.exe" "C:\Users\username\OpenCover\OpenCover.Console.exe" -oldstyle -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\mstest.exe" -targetargs:"/noisolation /testcontainer:"%%i"" -filter:"+[*]* -register:user -mergebyhash -output:"C:\Jenkins\AgilisUnitTest\Coverage\Coveragereport.xml" 

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
Both OpenCover and Typemock use the profiling API and so can get in each others way.

I believe Typemock supports OpenCover using configuration files (I assume to chain profiler calls) but I don't use it myself to help any further.

https://www.typemock.com/answers/19569/how-to-run-opencover-with-typemock

I did have some traction using Microsoft Fakes (also used a profiler) but every version of Visual Studio made it a moving target that I sort of stopped (and that no one seemed to be asking for it anymore).
