### ISSUE TITLE
Coverage reports fail when pdbs for xunit are not loaded.

### ISSUE THREAD

**Issue by AraHaan** [OpenCover/opencover#888]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [x] Something else (.NET Core 2.1.x)

### My Environment

Unsure, issue is only present on my Azure Pipelines and AppVeyor builds so far.
- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover. (Will see if there is a update to the msbuild package to use opencover with ``dotnet test``.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue. (Cant due to it not being generated)
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Coverage report getting generated.

### Actual Behavior

No coverage report generated.

### Steps to reproduce the problem:

- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [x] sample code or link to repository/gist is available (support is much faster this way) 

https://github.com/AraHaan/XmlAbstraction/

**Comment by sawilde** [comment]
It looks like you are using `coverlet.msbuild` not `OpenCover`.

`coverlet.msbuild` is **not** a wrapper for `OpenCover`.
