### ISSUE TITLE
OpenCover seems to be stuck in an infinite loop

### ISSUE THREAD

**Issue by SeppPenner** [OpenCover/opencover#889]
### My Framework

- [x] .NET Core 2.2.x

### My Environment

- [x] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded

### Expected Behavior

Generate a `coveragexml` file from the test project's dll.

### Actual Behavior

Stuck in some infinite loop?

### Steps to reproduce the problem:

- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [x] sample code or link to repository/gist is available (support is much faster this way): https://gist.github.com/SeppPenner/21aff2363dfb15baf026f68e9cac7e45

### Further information:

* I have updated today from OpenCover version `4.6.519` to `4.7.922`
* The runs before (I have a build script with more than one project) run without problems
* With version `4.6.519`, there have been no issues
* The `coveragexml` file is empty
* The log (Check out the log4net.config in the gist) does not show anything
* Maybe this helps: The dll is the first one that has failing tests, all others before do not have failing tests.

**Comment by sawilde** [comment]
@SeppPenner if you can supply a repeatable example I may be able to help.

OpenCover waits on events i.e. the child process to stop etc so it doesn't terminate too soon. However sometimes it does not get these events. You could try running [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) at the same time as OpenCover and see if anything useful is emitted - YMMV.

There are a number of switches that may help

1. `-log:All` to increase the verbosity of the logging
2. `-communicationtimeout:<millseconds>` between 10000 and 60000 - how long to wait for messages from the target process(es).

**Comment by SeppPenner** [comment]
@sawilde I will try these and provide some results.

**Comment by SeppPenner** [comment]
@sawilde I've added two new files (`log.txt` which contains the logging from OpenCover with `-log:All` and `DebugView.log` which contains the logging from the `DebugView`) to the gist: https://gist.github.com/SeppPenner/21aff2363dfb15baf026f68e9cac7e45.

> @SeppPenner if you can supply a repeatable example I may be able to help.

The problem is that the project is not open source and I'm not allowed to share it. Maybe you can find something that helps in the logs. This issue occured since I updated from .NetCore 2.2.106 to .NetCore 2.2.203 while I'm not completely sure if it's related to this update.

All .Net versions installed:

![image](https://user-images.githubusercontent.com/9639361/56813969-65ff4500-683e-11e9-8261-afc154bbdb9b.png)

**Comment by sawilde** [comment]
First I would look to add some filters so that you only get coverage of what you need - this will also speed things up as you will not be instrumenting code that is not yours. e.g. `-filters:"+[MyProject*]* -[*Test*]*"`

**Comment by SeppPenner** [comment]
@sawilde I will try that, too.

**Comment by SeppPenner** [comment]
@sawilde I will need to re-check this again, but it seems like the filters have helped a lot (Seems like I was loading to much references into the project and OpenCover simply took ages to calculate this and ran into timeouts.

**Comment by SeppPenner** [comment]
Ok, I'm not seeing the issue with the project again.

**Comment by sawilde** [comment]
@SeppPenner thanks for the update and glad you've got it going.
