### ISSUE TITLE
Code coverage for UWP project

### ISSUE THREAD

**Issue by balamgithub** [OpenCover/opencover#890]
Please provide the following information when submitting an issue. 

I have created Windows 10 UWP project and test case written by MSTest framework. I am working in Jenkins pipeline. I tried to create code coverage using OpenCover and ReportGenerate exe. I have used below commend to generate the file.

 OpenCover.Console.exe -register:user -target:"C:\Users\murubala\source\repos\UWP\Devices\DevicesTest\bin\x64\Debug\DevicesTest.exe" -output:"C:\Users\murubala\Documents\LocalDeployment\Sideloading\Result.xml" -targetdir:"C:\Users\murubala\source\repos\UWP\Devices\DevicesTest\bin\x64\Debug" -searchdirs:"C:\Users\murubala\source\repos\UWP\Devices\DevicesTest\bin\x64\Debug" -mergebyhash -skipautoprops  -filter:"+[UWP*]*" -log:All 

The command is executed successfully and generated the output, but there is no code coverage for reference [main] project. The output file has code coverage details for test project. 

I have included DebugType>full</DebugType all reference project and also verified the "PDB" file available in the folder. 

Please let me know what I have done wrongly

**Comment by sawilde** [comment]
I haven't tried OpenCover against a UWP projects - my understanding is that they compile against the WinRT and not .NET framework and so the assemblies are not .NET compatible and so OpenCover will not profile them. What details are you seeing in the output file for the assemblies you are trying to get coverage for?

**Comment by balamgithub** [comment]
The opencover is returning test project code coverage details, I am expecting main project code coverage details which is referenced in test project

**Comment by sawilde** [comment]
@balamgithub I can't repeat your issue so please provide a repeatable sample.

**Comment by balamgithub** [comment]
[OpenCover_UWP.zip](https://github.com/OpenCover/opencover/files/3098215/OpenCover_UWP.zip)

Project: UWP
IDE: VS 2017
Test Framework: MSTest

**Comment by sawilde** [comment]
It says it is being `skippedDueTo='Filter'` - change your filters - I can't advise as you have hidden the name of the module - if you are not sur eof what filters to use then don't use any at first and then start excluding utnil your are happy.

**Comment by sawilde** [comment]
Also I don't see how you are running your tests? you may have written them using MSTest but they are not being executed - you need to use a test runner e.g. vstest.console.exe or something similar.

**Comment by balamgithub** [comment]
I have used "vstest.console.exe". The test result is generated successfully, but the code coverage file is generated for vstest.console.exe, not for my project. The command is given below
**OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"C:\Users\murubala\source\repos\Devices\bin\x64\Debug\DevicesTest.build.appxrecipe /Framework:FrameworkUap10 /EnableCodeCoverage /logger:"trx;LogFileName=C:\Users\murubala\Documents\LocalDeployment\Sideloading\Result.trx"" -mergebyhash -output:"C:\Users\murubala\Documents\LocalDeployment\Sideloading\Result.xml"**

**Comment by sawilde** [comment]
I don't understand why you have this `/EnableCodeCoverage` this looks like the switch for vstest.console.exe - I'd remove that as any code coverage being injected by vstest.console.exe will probably interfere with what OpenCover is trying to do.

**Comment by sawilde** [comment]
Okay - I've managed to repeat your issue and it doesn't look like I can help you at this point.

The application containing the tests is not running with the same environment variables that `vstest.console.exe` was executed with. These environment variables tell the .NET runtime what profiler [e.g. OpenCover] to load when launching a new .NET application. Since these environment variables are not there, no profiler loaded and so no coverage captured.

If you are looking to capture coverage of your tests then don't hide them inside your UWP application but use a normal .NET assembly.

**Comment by balamgithub** [comment]
I have corrected the filters and got the code coverage report for the main project, but I am not able to get code coverage for the reference UWP project. 

Example: Main project is device.exe which is referred "devicehelper.dll" [reference project].

My question is that how to get code coverage for  [devicehelper.dll] referenced UWP project.

**Comment by sawilde** [comment]
You're managing better than I did then - I got nothing.

If the library is being loaded you'll see it in the XML file produced by OpenCover - it will give a reason as to why it was not instrumented.

**Comment by balamgithub** [comment]
I wrote a test method for "CodeCoverageClass.OpenCoverExecution" method, then I run the below command. the report does not show the coverage line.

OpenCover.Console.exe -register:user -target:"C:\Users\murubala\Documents\Audible\Research\CICD\OpenCover\MainLibrary\MainApp\bin\x64\Debug\MainApp.CodeCoverage.exe" -mergebyhash -output:"C:\Users\murubala\Documents\Audible\LocalDeployment\Sideloading\Result.xml" -targetdir:"C:\Users\murubala\Documents\Audible\Research\CICD\OpenCover" -searchdirs:"C:\Users\murubala\Documents\Audible\Research\CICD\OpenCover"  -log:ALL -coverbytest:"Main.Test.build.appxrecipe""

[Result.txt](https://github.com/OpenCover/opencover/files/3113802/Result.txt)

Please let me know how to get code coverage

**Comment by sawilde** [comment]
Hi @balamgithub

I don't know - I don't see the profiler running when the application is executed after deployment and I don't know how to make it work it there - sorry. It seems that to even run tests you need to use a special deployed application to act as your test runner.

![image](https://user-images.githubusercontent.com/297165/56702612-51408580-6748-11e9-976a-de4b594b9af6.png)

What I would do is break the code that needs testing into a shared library (.NET Standrd 2.0) and then you can execute the tests and code on the .NET Framework/Core and get coverage that way - https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-migrate - good luck

**Comment by noxo** [comment]
Any updates on UWP "Code coverage" support into opencover? At the moment of writing this it seems to be still unsupported even in Visual Studio 2019 Enterprise (16.5.5) with following error:

_Empty results generated: No binaries were instrumented. Make sure the tests ran, required binaries were loaded, had matching symbol files, and were not excluded through custom settings. For more information see https://go.microsoft.com/fwlink/?LinkID=253731_

**Comment by sawilde** [comment]
Sorry no and probably no intention to support it either - it is not something I need.
