### ISSUE TITLE
Code coverage not reported in .NET Core 3.0 since preview 4

### ISSUE THREAD

**Issue by martincostello** [OpenCover/opencover#894]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [x] .NET Core 3.0.0 preview 5

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [x] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Code coverage metrics are reported for .NET Core 3.0 applications.

### Actual Behavior

Code coverage metrics are reported for .NET Core 3.0 applications using preview 4 or later.

_Copied from https://github.com/dotnet/coreclr/issues/24402_

I've just noticed in some 3.0 branches of some applications I'm maintaining as the previews ship, that code coverage metrics have stopped being reported with OpenCover in preview 4. The code coverage was being reported using preview 3.

Below are links to two commits of an application and its AppVeyor CI build showing code coverage being reported with preview 3, but not with preview 4. I've observed this with multiple applications, so I do not believe it is specific to this particular application.

| Release | Commit | Build |
|:-:|:-:|:-:|
| 3.0.100-preview3-010431 | https://github.com/martincostello/website/pull/254/commits/f1e71c056818cbc1d7470b3e8806745601dd6cd6 | [Logs](https://ci.appveyor.com/project/martincostello/website/builds/22879215#L218) |
| 3.0.100-preview4-011223 | https://github.com/martincostello/website/pull/254/commits/ac210c0baa6bd56a0826e275056928105107e5be | [Logs](https://ci.appveyor.com/project/martincostello/website/builds/23967773#L229) |
| 3.0.100-preview5-011568 | https://github.com/martincostello/website/pull/254/commits/e6f6627ac312aa62be0de717b3c785a9b88a5bea | [Logs](https://ci.appveyor.com/project/martincostello/website/builds/24344819#L228) |

### Steps to reproduce the problem:

- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [x] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
I'd have to have a look and see if it is a quick win

**Comment by syncrisis** [comment]
I can confirm this also does not work in preview 6.

**Comment by sawilde** [comment]
I tend to not support previews as they are a moving target and I have limited time - I also depend on a 3rd party library to parse the PDBs and if it is not able to handle the new formats then neither can OpenCover

**Comment by charzhao** [comment]
Now preview 8 has released,  hope it can be supported by opencover

**Comment by aelassas** [comment]
@sawilde .net core 3.0 was released yesterday and I can confirm that OpenCover does not support it yet. Are you planning to support .net core 3.0?

**Comment by sawilde** [comment]
@aelassas at some point I may do so but I have no specific timelines at the moment

**Comment by skovsende** [comment]
Having this problem with .net core 3.1 as well. Any news or anything that can be done to help things?

**Comment by martincostello** [comment]
If it helps anyone else, I migrated off of OpenCover and over to coverlet to continue getting code coverage results with .NET Core 3.x.

**Comment by MarkKharitonov** [comment]
We switched over to DotCover. Also works.
