### ISSUE TITLE
my service fails to start when started from opencover 4.7.922

### ISSUE THREAD

**Issue by zvikab1** [OpenCover/opencover#895]
Please provide the following information when submitting an issue. 

running OpenCover 4.7.922 with "-service" breaks after ~30 secs with : "The service did not respond to the start or control request in a timely fashion".
This does not happen in OpenCover 4.6.519 and also does not happen if I specify a filter that reduces the covered code to half its size (current size 2MLOC, ~700K coverable lines)
I can also run my app as a console app from OpenCover (instead of service) and when doing so it seems that the time until it prints "hello I started" is about 1m
My guess would be that instrumentation starts on load and takes too much time for my service to be able to start and send its initial keep-alive to Windows.

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [X ] .NET 4.6.1

### My Environment

- [X ] Windows 10
- [ X] Windows Server 2012 R2

### I have already...

- [X ] repeated the problem using the latest stable release of OpenCover.
- [ X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
There is an option described in `Usage.pdf` that may help with service start time issues  

```
-servicestarttimeout:[1m|23s|1m23s]
        Overrides the default time to wait for the profiled service to start. The examples above
        correspond to a timeout of 1 minute, 23 seconds and 1 minutes and 23 seconds accordingly.
```

**Comment by zvikab1** [comment]
Hi Shawn
Sorry for not mentioning but I use this option with the value of 6 mins and the problem does happen (after ~20-30 secs) on the new build but not on 4.6.519 (use same param in both cases). I assume that the issue is not how much time OpenCover waits for the service,  but rather the service not getting to making the initial report to Windows on time. (the interaction with service control manager)
Thanks
Zvika

**Comment by sawilde** [comment]
Odd - as I don't recall any changes with anything around service launching between the two releases... 

You may need to investigate this yourself if possible.
