### ISSUE TITLE
Code Coverage for Integration Test Suite execution

### ISSUE THREAD

**Issue by Praveen-A-Maxval** [OpenCover/opencover#896]
I have a .NET application build in Framework 4.5.2 and able to write Unit test cases ( XUnit ) and execute the code coverage using OpenCover. 

We use katalon studio to run the Integration Test suite/cases. 

Does OpenCover produce code coverage for Integration test cases ?

**Comment by sawilde** [comment]
Only for the processes loaded under OpenCover directly; OpenCover was only meant for unit testing scenarios.

Most integration environments are distributed across multiple machines and OpenCover will only instrument the assemblies loaded locally.
