### ISSUE TITLE
Does not work with vstest.console.exe

### ISSUE THREAD

**Issue by HardySoftware** [OpenCover/opencover#897]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [X] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Be able to work withhvstest.console.exe

### Actual Behavior

Failed to execute tests with vstest.console.exe

### Steps to reproduce the problem:
https://github.com/OpenCover/opencover/issues/597 has the same error, but I don't see it is addressed but the ticket is closed.

If I run command from my own desktop

`"%PROGRAMFILES(X86)%\Microsoft` Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" .\MyProj.Tests\bin\Debug\MyProj.Tests.dll

I get proper response that all my unit tests are executed. But if I run 

`".\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe"` -register:user -target:"%PROGRAMFILES(X86)%\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:".\MyProj.Tests\bin\Debug\MyProj.Tests.dll" -mergebyhash -showunvisited -output:"code_coverage_report\codecoveragereport.xml"

I have errors

> Test Run Successful.
> Total tests: 81
>      Passed: 81
>  Total time: 12.7709 Seconds
> Committing...
> No results, this could be for a number of reasons. The most common reasons are:
>     1) missing PDBs for the assemblies that match the filter please review the
>     output file and refer to the Usage guide (Usage.rtf) about filters.
>     2) the profiler may not be registered correctly, please refer to the Usage
>     guide and the -register switch.

The project file already has PDB defined. I also confirmed PDB file exists together with my DLL file for both test project and the actual project to be tested.

```
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodeAnalysisRuleSet>MyProj.ruleset</CodeAnalysisRuleSet>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DocumentationFile>bin\MyProj.xml</DocumentationFile>
  </PropertyGroup>
```

**Comment by sawilde** [comment]
@HardySoftware I can't repeat locally - do you have something you can share to help investigate?

**Comment by lucadistefano** [comment]
same for me: VS 2019 and .Net Framework 4.5.2

**Comment by HardySoftware** [comment]
[ConsoleApp2.zip](https://github.com/OpenCover/opencover/files/3647430/ConsoleApp2.zip)

Steps to produce the issue

- Download this attached file
- Restore nuget packages
- Open command window, and navigate to the folder with solution file
- Run command `.\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -output:".\1.xml" -register:path64 -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:".\ConsoleApp2Tests\bin\Debug\ConsoleApp2Tests.dll" -mergebyhash -skipautoprops`
- Check your result

**Comment by sawilde** [comment]
vstest.console.exe is a 32 bit process and you were only asking for the 64bit profiler to be registered
