### ISSUE TITLE
Opencov crashes at launching test application 

### ISSUE THREAD

**Issue by qliagz** [OpenCover/opencover#898]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [x] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x ] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Opencov should launch the app and then generate covreage result when the app exits

### Actual Behavior

Opencov intermittently crashed with one of two when launching my app

![image](https://user-images.githubusercontent.com/2784042/59236779-7aa85a00-8bac-11e9-8cec-d0e757e34e77.png)
 
![image](https://user-images.githubusercontent.com/2784042/59237575-a1b45b00-8baf-11e9-91ff-359db18124f9.png)

Fill me in...

### Steps to reproduce the problem:

- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [x] sample code or link to repository/gist is available (support is much faster this way) 
run:
opencover.4.7.922\\OpenCover.Console.exe ^
-register:user ^
-skipautoprops ^
-threshold:1 ^
-log:All ^
"-target: MyApp.exe" ^
"-output: coverage.xml" ^
"filter: +[MyApp.*]*" ^

Additional notes:
- The filtering is quite aggressive with the matching number of dll amounts to around 400
- The likelihood of crashes goes down with more granular filtering, i.e. reducing number of matching dll. 
- the size of cover-able code could go as many as 900K lines of code

**Comment by sawilde** [comment]
@qliagz I can't repeat and so I'll need an example that repeats the issue

**Comment by qliagz** [comment]
@sawilde thanks for looking into this! Unfortunately my application is proprietary so I am not able to share that in public. But I'd greatly appreciate if you could guide me to debug this issue.

Firstly, the crashes happened when I am running opencov with my application with large number of dlls in the filter. If the number of dlls reduced to smaller amount, the crash is less likely to occur

Secondly the crashes happened when my application tried to invoke a reflection call after all dlls are loaded. 
Exception thrown: 'System.AccessViolationException' in mscorlib.dll
Exception thrown: 'System.TypeInitializationException' in mscorlib.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Exception thrown: 'System.AccessViolationException' in mscorlib.dll
An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll

Note that if I run my application without openCov, everything works fine.

Thirdly In opencov code, the crash happens at https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Console/Program.cs#L323

Questions: 
1. could you explain to me what OpenCov does in  Process.Start(startInfo) and which part of code are executed?
2. what type of causes it might be for this type of memory corruption? Does the number of dlls or size of dlls play a role here?

**Comment by qliagz** [comment]
After some investigation, it seems to me that the AccessViolationException is caused by both OpenCov and MyApp are reading the same object file. @sawilde do you have any suggestion to avoid situation like this? 

I see that OpenCov has an option "targetdir", would that be something I can leverage on?

e.g. currently I have all dll and pdb files reside in <path> directory where MyApp.exe is. Can I have OpenCov reading from another <alt-path> instead where I have an identical set of dll and pdb?

Thanks in advance!

**Comment by qliagz** [comment]
Also found some exceptions whiling running the debug build of opencov. attached (url
[opencov.crash.txt](https://github.com/OpenCover/opencover/files/3293857/opencov.crash.txt)
)

**Comment by qliagz** [comment]
It seems the crash is related to opencov.profiler.dll, is there a way to disable profiling in opencov and just do coverage?

**Comment by sawilde** [comment]
The `profiler` is the thing that does the coverage.

`IgnoreConditionalBranchSequence` is new and I need to investigate why this is crashing - it is probably IL related but that'll be dependent on your code and of course I can't see that .

**Comment by sawilde** [comment]
I did address an issue with `IgnoreConditionalBranchSequence` as part #993 but this wasn't crashing the code just ignoring the assembly.
