### ISSUE TITLE
[FeatureRequest] Cobertura output

### ISSUE THREAD

**Issue by SychevIgor** [OpenCover/opencover#899]
Thank you for all what you are doing in this project.

My team working on a project hosted in Azure DevOps (ex VSTS/VSO) and actively using code coverage. [Azure DevOps supports only "Cobertura and JaCoCo."](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops) formats.

With .net core based project- everything work great using [coverlet.msbuild](https://www.nuget.org/packages/coverlet.msbuild/ ) for .net core
Unfortunately, for one of our app we were forces to use **.net framework 4.6.1** and faced with a challenge- how to use the same engineering practices with .net framework. 

We are using this converter https://github.com/danielpalme/OpenCoverToCoberturaConverte , but if you will include "-outputFormat" commandline option and "Cobertura" as an output option - you will significantly simplify our CI pipeline and help to many projects and finally make code/world better. 

May I request such feature?

P.S.
- We don't want to use Visual Studio Enterprise Edition to calculate code coverage, because it's expensive to buy this edition of VS.
- We also don't wanna use other paid tools like DotCover if it's possible.
- We can use such [custom task](https://gist.github.com/tverboon/1c187b082b9597abef89dcec3df2422c) for Azure DevOps, but it's anyway looks like odd behavior - create report in one task just to convert it in an another task.

### My Framework
- [x] .NET 4.6.1

### My Environment
- [x] Windows 10

### My issue is related to (check only those which apply):
- [x] feature request

**Comment by SteveGilham** [comment]
With that selection of majority tool of choice, have you considered [converting the .net framework project to the new style](https://www.nuget.org/packages/Project2015To2017.Migrate2017.Tool/), using the appropriate reference assembly package as needed and simply using coverlet there too?

Here's an example for net461 -- just cd to the Tests directory and go `dotnet test --settings .\coverletArgs.runsettings`

[net461.zip](https://github.com/OpenCover/opencover/files/5801233/net461.zip)
