### ISSUE TITLE
Opencover & report generator and Axocover report generated from visual studio has an mismatch - NUnit - how to fix

### ISSUE THREAD

**Issue by prakashorton** [OpenCover/opencover#901]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework
- [x] .NET 4.7
- [x] .NET 4.7.1
- [X] .NET 4.7.2

### My Environment
- [x] Windows 10
- [X] Windows 10 IoT Core

I have a test application return in NUnit it has a reference for two different projects.

I'm trying to generate the code coverage report from Axocover I'm getting two projects in reports but while performing from the command line using the open cover I'm getting only one project in my report.

Sharing you the open cover command which I have tried
`OpenCover.Console.exe 
-register:user 
-target:nunit3-console.exe 
-targetargs:"c:\path\Integrations.FI.Tests.dll "
-output:"C:\projects.net\automation\fi\output\fi.xml"  
-filter:"-[Integrations.FI.Tests]*"`

`OpenCover.Console.exe 
-register:user 
-target:nunit3-console.exe 
-targetargs:"c:\path\Integrations.FI.Tests.csproj"
-output:"C:\projects.net\automation\fi\output\fi.xml"  
-filter:"-[Integrations.FI.Tests]*"`

### Actual Behavior

There is a mismatch in reports xml which are generated

Kindly help me in fixing this issue and is there any probability to see the commands executed from axo cover 
Thanks in advance

**Comment by sawilde** [comment]
@prakashorton you'll need to share the results 

I don't use AxoCover myself so you may need to address the difference between OpenCover and AxoCover with them

**Comment by prakashorton** [comment]
@sawilde  Axo cover is the IDE for generating code coverage, it uses the open cover to generate a result.

have shared result of both axo cover and open cover below 

Axo cover result 
[axocover.log](https://github.com/OpenCover/opencover/files/3324785/axocover.log)

Filter in axocover
![image](https://user-images.githubusercontent.com/25571549/60092978-e5899180-9765-11e9-8762-c6b747bfd1b0.png)


Opencover result
OpenCover.Console.exe -target:"C:\Users\pravindran\.nuget\packages\nunit.consolerunner\3.10.0\tools\nunit3-console.exe" -targetargs:"C:\projects.net\app.csproj"  -output:"C:\projects.net\automation\output\report.xml" -register:user -filter:"+[IF]* -[IF.Tests]* +[emaObjects]*" 

[opencover.log](https://github.com/OpenCover/opencover/files/3324865/opencover.log)

**Comment by sawilde** [comment]
looks like Axo is using a different version of OpenCover (4.6.0.0 - private build it seems as I have never released an official version with that number) and 4.7.922

**Comment by Tkael** [comment]
I'm having a similar (or perhaps the same) issue with OpenCover.4.7.922 targeting vstest.console.exe vs. AxoCover. 

OpenCover + VsTest.Console.exe:
```
Visited Classes 109 of 670 (16.27)
Visited Methods 225 of 5251 (4.28)
Visited Points 1305 of 23799 (5.48)
Visited Branches 402 of 14882 (2.70)
==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 109 of 698 (15.62)
Alternative Visited Methods 225 of 5675 (3.96)
```

AxoCover:
```
Visited Classes 548 of 795 (68.93)
Visited Methods 2158 of 5832 (37)
Visited Points 14501 of 28671 (50.58)
Visited Branches 5079 of 15798 (32.15)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 548 of 844 (64.93)
Alternative Visited Methods 2158 of 6387 (33.79)
```

OpenCover command:
```
.\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -mergebyhash -skipautoprops -excludebyattribute:*.ExcludeFromCodeCoverage* -excludebyfile:*\*.Designer.cs,*\*.Generated.cs -filter:"+[*]*" -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"bin\Release\Tests.dll /tests:UnitTests /Parallel /InIsolation /Blame" -output:.\TestResults\coverage.xml
```

AxoCover settings: default

Comparing the .xml output of the reports, I've noticed that the AxoCover .xml includes elements like the following which are missing from the OpenCover report for each sequence point:
```
                <TrackedMethodRefs>
                  <TrackedMethodRef uid="51" vc="1" />
                  <TrackedMethodRef uid="195" vc="4" />
                  <TrackedMethodRef uid="194" vc="2" />
                  <TrackedMethodRef uid="103" vc="1" />
                </TrackedMethodRefs>
```
Could the missing `<TrackedMethodRefs>` in the OpenCover report explain the difference in coverage that I'm observing? If so, is there something that I'm may not be configuring correctly that is causing this data to not be recorded?

Github branch under test: https://github.com/EDCD/EDDI/tree/wip/coverage-tweaks
Latest build results using the OpenCover command above: https://ci.appveyor.com/project/richardbuckle/eddi/builds/26119823

Thank you for any insight that you are able to provide!

P.S. I hope that this isn't hijacking the OP... it does seem to me like it may be related but if you say otherwise I'm happy to re-post this as a separate issue.

**Comment by sawilde** [comment]
> looks like Axo is using a different version of OpenCover (4.6.0.0 - private build it seems as I have never released an official version with that number) and 4.7.922

at the time it looks like AxoCover have an unofficial release of OpenCover 4.6.0.0 and so this would explain why the result align more with 4.6.519 than 4.7.922.

Between OpenCover versions we may tweak how we instrument the code to hide sequence points and branches that were affecting people and so the results may vary between releases.
