### ISSUE TITLE
excludeByFile does not work

### ISSUE THREAD

**Issue by alexey-aurea** [OpenCover/opencover#902]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [X] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [X] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request
- [X] feature is broken

### Expected Behavior

Once excludeByFile is specified files with the matching names will be excluded from the coverage
A file name is expressionLexer.cs located in the generated folder.
opencover cal looks like this:

> .\openCover\OpenCover.Console.exe -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:" ExpressionTranslator.Test.dll /Logger:trx /Platform:x86 /Parallel"  -register -excludeByFile:equationParser*;equationLexer.cs;*\*Designer.cs;*\*.g.cs;*.g.i.cs;*.xaml.cs  -returntargetcode -hideskipped:All -output:TestResults\OPENCOVER_VSTEST_FILE.xml 

Still expressionLexer class is present in the output xml file.

### Actual Behavior

Files with the matching names are not being excluded from the coverage report.

### Steps to reproduce the problem:

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [X] sample code or link to repository/gist is available (support is much faster this way)

**Comment by herbfickes** [comment]
I've seen this problem as well.  I'm using Sonar so I excluded the files in their interface, though I'd prefer to do it with the opencover excludebyfile switch for code maintenance reasons.

**Comment by sawilde** [comment]
I can't repeat
