### ISSUE TITLE
simple support question: just install; no need to build from source

### ISSUE THREAD

**Issue by tscilipoti** [OpenCover/opencover#903]
Just trying to figure out where I can download an installable version of opencover for Windows 10. I  am having all kinds of dependency issues trying to build the source, and I don't actually NEED to do that; I just need to work through some issues with calling opencover from the command line. (Could not find any sort of support page or forum that addresses this question, so fell back to posting here.)

**Comment by Malivil** [comment]
An MSI installer is available on the releases tab here in GitHub: https://github.com/OpenCover/opencover/releases

**Comment by tscilipoti** [comment]
Doh! Thank you. [retreats into doghouse]
