### ISSUE TITLE
Linux support NET core 2.0

### ISSUE THREAD

**Issue by giorgiozoppi** [OpenCover/opencover#904]
Dear all,
which are the tech limitations for supporting Linux?

Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [x] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
I believe the profiler API for .NET core is now there/ready for .NET core 2.0 or 3.0 

The biggest issue is time and resources

**Comment by giorgiozoppi** [comment]
Can you lead me on that?

**Comment by sawilde** [comment]
A thread was started here https://github.com/OpenCover/opencover/issues/703 and https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/profiling-api-status.md

There are few alternatives mentioned that would work on .NET core that don't use the Profiler API

And of course the OpenCover source code - you need to be familiar with c++ and crossplatform (linux/windows) development

**Comment by giorgiozoppi** [comment]
No problem with C++.

**Comment by sawilde** [comment]
I have decided that I will not be porting OpenCover to Linux - sorry
