### ISSUE TITLE
OpenCover with the vstest.console runner always reports 0 visits / no coverage when tests have [DeploymentItem] attribute

### ISSUE THREAD

**Issue by Tkael** [OpenCover/opencover#905]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [X] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10 (for local coverage evaluation attempts)
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [X] Windows Server 2016 (for AppVeyor coverage evaluation attempts)

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Various classes, methods, points, branches, etc. visited

### Actual Behavior

Committing...
Visited Classes 0 of 773 (0)
Visited Methods 0 of 5636 (0)
Visited Points 0 of 28439 (0)
Visited Branches 0 of 18800 (0)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 0 of 816 (0)
Alternative Visited Methods 0 of 6147 (0)

### Steps to reproduce the problem:

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [X] sample code or link to repository/gist is available (support is much faster this way) 

I've spent the last 72 hours trying to get this to work and I'm at my wits end - I'm sure I missed something simple but I can't seem to get OpenCover to register any visits with the vstest.console runner no matter what I change, either on my local machine or on my CI (AppVeyor). 

Project: 
https://github.com/EDCD/EDDI

Current AppVeyor.yml script (ref. results at https://ci.appveyor.com/project/richardbuckle/eddi/builds/25835952):
```
 - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:vstest.console.exe -targetargs:"Tests.dll /logger:Appveyor /tests:UnitTests /Parallel /InIsolation" -targetdir:"bin\Release" -mergebyhash -skipautoprops -output:coverage.xml -filter:"+[Eddi*]* +[Utilities*]* -[Tests*]*"
```

Things I've tried:
- Examining coverage.xml files generated by my various attempts. Modules which should have seen frequent visits were not skipped and yet record zero visits. Example module summary:
```xml
      <Summary numSequencePoints="1688" visitedSequencePoints="0" numBranchPoints="842" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="19" minCyclomaticComplexity="1" maxCrapScore="380" minCrapScore="2" visitedClasses="0" numClasses="128" visitedMethods="0" numMethods="478" />
```
- Preregistering OpenCover.Profiler.dll with regsvr32 (both x86 and x64 versions, with and without calling the `-register:path32` and `-register:path64` switches
- Using the -register:user switch
- Removing the `-filter:` switch (in case my filters were blocking results)
- Using the `-targetdir:` switch (based on some online comments I found while Googling this issue, though I suspect it was an unrelated cause)
- Removing all unnecessary switches from the command - the following stripped down script still fails with zero visits (see https://ci.appveyor.com/project/richardbuckle/eddi/builds/25836835):
```
 - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:vstest.console.exe -targetargs:"bin\Release\Tests.dll /tests:UnitTests" -output:coverage.xml
```

Please let me know if there is any additional information that I can provide and thank you very much for your assistance!

**Comment by gremlm** [comment]
I have the same issue when using -target:vstest.console.exe from Visual Studio **2019**.
When selecting as target vstest.console.exe from Visual Studio **2015** on the same system, it works just fine!
What is more: when using -target:vstest.console.exe from Visual Studio **2019**, I see that .coverage file is created under \TestResults\(GUID-base named) subdirectory, as vstest.console.exe is executed with \Enablecodecoverage option!

This is a new option available for vstest.console.exe from Visual Studio **2019** for generation .coverage files.

**Comment by Tkael** [comment]
I am using Visual Studio 2019 locally but AppVeyor is using a Visual Studio 2017 image.

**Comment by Tkael** [comment]
Ok. I've done some additional testing by small segments of my tests at a time. OpenCover with vstest.console.exe seems to have a problem whenever I run tests that include the `[DeploymentItem]` attribute. Removing that attribute from the tests and embedding the resource files directly resolved the issue for me.

**Comment by sawilde** [comment]
That is odd - OpenCover only executes vstest.console.exe it shouldn't stop vstest.console.exe from doing what it is supposed to do

**Comment by Tkael** [comment]
Well, the tests all execute so I'm not sure it's accurate to say that it's not doing what it's supposed to do. 
The problem is that OpenCover records 0 visits to after tests have executed when those tests include the [DeploymentItem] attribute.

**Comment by gremlm** [comment]
I have seen that OpenCovere with vstest.console reports 0 visits fo tests without Deployment attribute. But the same tests are covered when it started under
vstest.console from VS2015.

Sincerely, Grigoriy Milman

On Jul 15, 2019 1:55 AM, Brian Wilson <notifications@github.com> wrote:

Well, the tests all execute so I'm not sure it's accurate to say that it's not doing what it's supposed to do.
The problem is that OpenCover records 0 visits to after tests have executed when those tests include the [DeploymentItem] attribute.

**Comment by Tkael** [comment]
I'm not claiming that this is the only thing that could cause OpenCover to report zero visits, just that from my observations this thing ([DeploymentItem]) does.

**Comment by GaTechThomas** [comment]
Same issue here, but we don't have DeploymentItem anywhere. Some projects in the solution show 0 visits and therefore 0% coverage and other projects coverage seem to be as expected. Spent a full work day so far trying to sort this out. VS2017 Pro.

**Comment by matyuda** [comment]
Hi!
The same problem occurred when I used Ver.4.6.519. 

> .nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:LoggerTest.dll -targetdir:"LoggerTest\bin\Debug\netcoreapp3.0" -filter:"+[*]*" -output:result.xml

> Committing...
> Visited Classes 0 of 4 (0)
> Visited Methods 0 of 10 (0)
> Visited Points 0 of 58 (0)
> Visited Branches 0 of 18 (0)

When Ver.4.7.922 is used instead, the coverage can be displayed correctly.

> .nuget\packages\OpenCover\4.7.922\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:LoggerTest.dll -targetdir:"LoggerTest\bin\Debug\netcoreapp3.0" -filter:"+[*]*" -output:result.xml
> 
> Committing...
> Visited Classes 3 of 4 (75)
> Visited Methods 9 of 10 (90)
> Visited Points 42 of 58 (72.41)
> Visited Branches 13 of 18 (72.22)
>

**Comment by niwrA** [comment]
I have this same issue when trying to run OpenCover against vstest.console to run tests in .NET Core projects. In .NET Framework it works fine and I get my results, but in .NET Core I get 0 visits on everything. 

They are all NUnit tests and I am using the latest release (4.7.922.0) with vstest 16.4 ...
