### ISSUE TITLE
Opencover not works with ObsoleteAttribute

### ISSUE THREAD

**Issue by pemola** [OpenCover/opencover#906]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [X ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X ] repeated the problem using the latest stable release of OpenCover.
- [ X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I want to skip son methods mark with [Obsolete] in the coverage analysis but OpenCover doesn't do.
I try it by command line by this way:

packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -output:"OpenCover.xml" -target:"packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -targetargs:"miPrograma\miPrograma.Test\bin\x64\Release\miPrograma.Test.dll --trace=Verbose" -log:All -excludebyattribute:\*.ObsoleteAttribute\* -register:user 

### Actual Behavior

OpenCover ignore the code marked with [Obsolete] and this decreases my coverage. ¿Is there any way to do this or Have I to mark my code with [ExcludeFromCoverage] attribute too?

Thanks!

**Comment by sawilde** [comment]
@pemola it should work with any attribute - I'll add this as a defect to be investigated

**Comment by pemola** [comment]
Finally, it worked adding the next parameters:

packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"\packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -targetargs:"miPrograma\miPrograma.Test\bin\x64\Release\miPrograma.Test.dll " -log:All -mergebyhash -skipautoprops -coverbytest:"*.Test*" -excludebyattribute:"*Obsolete*" -excludebyfile:"*Settings*;*Global.asax*" -filter:"+[*.Interfaces]* +[*.Services]* +[*.DataAcces]* +[*.Entities]* +[*.Test]*" -searchdirs: miPrograma\miPrograma.TestTest\\bin\\x64\\Release -hideskipped:All -output:"OpenCover.xml" -register:user

I don't know why, but I need this comand so Opencover Works with ObsoleteAttribute or any other.

**Comment by sawilde** [comment]
unless the expected default filter `+[*]*` isn't being applied
