### ISSUE TITLE
MSBuild project is not automatically imported from NuGet package

### ISSUE THREAD

**Issue by ap0llo** [OpenCover/opencover#910]
Please provide the following information when submitting an issue. 

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [x] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

OpenCover provides support for running coverage analysis from within a MSBuild project. 
After installing the package, I would expect the `OpenCover` task to be available in the project.

### Actual Behavior

The `OpenCover` task is not available. 
An import of `OpenCover.targets` has needs to be added to the project file manually. Since the path where the NuGet package is installed includes the version, this import has to be adjusted when OpenCover is updated.

### Steps to reproduce the problem:

- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [x] sample code or link to repository/gist is available (support is much faster this way):
  https://gist.github.com/ap0llo/197efbd6d630e56b323718b29512730f

### Suggested solution

NuGet can automatically import MSBuild `props` and `targets` files when they are placed in the package's `build` directory. 

I'd suggest to rename the `MSBuild` directory in the package to `build`. If backwards-compatibility of the package layout is a concern, an additional `OpenCover.targets` could be added to `build` that in turn imports `MSBuild\OpenCover.targets`

I would be happy to provide a Pull Request for this change.

**Comment by sawilde** [comment]
> I would be happy to provide a Pull Request for this change.

please do - I believe this was only supplied as an example of how to use the targets, I don't recall any work on making it integrate as part of the package install
