### ISSUE TITLE
AppVeyor build of current master has started failing

### ISSUE THREAD

**Issue by squid-box** [OpenCover/opencover#911]
This is branched off of what I found in #909 

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [X] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [X] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Rebuilding the latest master commit should work, as it did when it was last build 4 months ago.

### Actual Behavior

Three tests are failing with the latest AppVeyor VS2017 build worker image:
* OpenCover.Specs.PackagingFeature.RunOpenCoverAfterInstallingFromANugetPackage
* OpenCover.Specs.PackagingFeature.RunOpenCoverAfterInstallingFromAnInstaller
* OpenCover.Specs.PackagingFeature.RunOpenCoverAfterInstallingFromZipFile

### Steps to reproduce the problem:

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [X] sample code or link to repository/gist is available (support is much faster this way) 

Start a build of the current master on Appveyor.

**Comment by squid-box** [comment]
I tried just [changing to the previous VS17 image](https://github.com/squid-box/opencover/pull/1/commits/89a42a9e430e28e581ff5aff9b86d75308bdbb1c) on AppVeyor, and the build works - so I guess something that was [changed in the last update](https://www.appveyor.com/updates/2019/08/01/) has messed up something for those tests.

I don't think it's proper to just reference the previous image, as that's a temporary state that will be broken at the next update - but I also don't really understand how the test fails.

**Comment by splatteredbits** [comment]
I'm having the same problem. Just discovered. The new AppVeyor image breaks OpenCover when I'm using filters. It reports that it can't generate any code coverage stats:

```
No results, this could be for a number of reasons. The most common reasons are:
          1) missing PDBs for the assemblies that match the filter please review the
          output file and refer to the Usage guide (Usage.rtf) about filters.
          2) the profiler may not be registered correctly, please refer to the Usage
          guide and the -register switch.
```

Here's my call to OpenCover:

```
"C:\Users\appveyor\AppData\Local\Temp\1\69dbfa38-f6ea-46af-9935-83f208746e37\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe" -target:C:\Users\appveyor\AppData\Local\Temp\1\69dbfa38-f6ea-46af-9935-83f208746e37\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe "-targetargs:\"C:\Users\appveyor\AppData\Local\Temp\1\69dbfa38-f6ea-46af-9935-83f208746e37\NUnit2PassingTest.dll\" \"C:\Users\appveyor\AppData\Local\Temp\1\69dbfa38-f6ea-46af-9935-83f208746e37\NUnit2FailingTest.dll\" /noshadow /framework=4.0 /xml=\"C:\Users\appveyor\AppData\Local\Temp\1\69dbfa38-f6ea-46af-9935-83f208746e37\.output\nunit2+0smawxzx.rpy.xml\"   " "-filter:-[NUnit2FailingTest]* +[NUnit2PassingTest]*" -register:user -output:C:\Users\appveyor\AppData\Local\Temp\1\69dbfa38-f6ea-46af-9935-83f208746e37\.output\opencover\openCover.xml -returntargetcode 
```

**Comment by squid-box** [comment]
If you were to change from `-register:user` to `-register:Path32`, would that fix your problem?
I'm seeing similar, but intermittent, behavior on Azure DevOps - changing to Path32 seems to have fixed it for me. (Got the idea from #912)

This issue was mainly intended to point to the problems with building OpenCover (but it could be the same issue, since it's the tests that are failing.)

**Comment by SteveGilham** [comment]
Looking at this recent cluster of reports, this is probably the same issue as #914 as [the recent AppVeyor image update](https://www.appveyor.com/updates/2019/08/01/) put .net 4.8 up  (and most likely #915 was as well, too).
