### ISSUE TITLE
Fully support xUnit like MSTest & NUnit

### ISSUE THREAD

**Issue by tb-mtg** [OpenCover/opencover#919]
The OpenCover Usage Guide states:

> Can record which tests where executing at a particular time when a coverage point was visited – only MSTest and NUnit supported (requests accepted for others). 

> Gather coverage by test by analysing the assemblies that match these filters for Test methods. Currently only MSTest and NUnit tests are supported; other frameworks can be added on request – please raise support request on GitHub.

Can xUnit be as supported as MSTest & NUnit are?

**Comment by sawilde** [comment]
xUnit is supported (docs are a little out of date)

https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Extensions/Strategy/TrackXUnitTestMethods.cs
