### ISSUE TITLE
Add a wiki page explaining how to get started with OpenCover

### ISSUE THREAD

**Issue by Timwi** [OpenCover/opencover#920]
Hello! I’ve looked at the Usage Guide (both the wiki page and the PDF) but neither of them explain how to get started. They both assume that the user already knows how to obtain and run OpenCover. I’ve added the OpenCover nuget package to my solution but I could not figure out how to go from there. The Usage Guide talks about a “console application” but there is no console application anywhere that I could find.

Please provide some step-by-step instructions on how to get code coverage on a project that already has unit tests in it. Do not assume that the user already knows OpenCover. Give clear and precise instructions starting from a project with unit tests but without OpenCover already installed or familiar.

This would be really great so I can try this out! Thank you!

**Comment by ekolis** [comment]
I think the "console application" is this:

> C:\Path\To\Solution\packages\OpenCover.4.7.922\tools\OpenCover.console.exe

**Comment by sawilde** [comment]
@ekolis yup and unit tests suites such as xunit and nuinit have a console based runner for use on build platforms

**Comment by ekolis** [comment]
@sawilde hmm, what about MSTest?

**Comment by sawilde** [comment]
Yes it also has a console based runner - the name has changed over the years but I believe it is now called `vstest.console.exe`

**Comment by toebens** [comment]
it would be nice to have a "tutorial" wiki page on how to get opencover running on i.e. nunit3; what nuget packages would be needed (even nunit ones) and what needs to be configured how, what needs to be called. (Usage.rtf is not helping unfortunately)

**Comment by sawilde** [comment]
@toebens I have made the assumption that if you are attempting to use OpenCover then you already have a command line like build for your project i.e. build server and that you are comfortable using the command line.

If you need to know how to run nunit on the command line then I refer you to the nunit documentation - https://nunit.org/docs/2.6.3/nunit-console.html

Other test frameworks have their own command line runners I also do not intend to document how to use them either
