### ISSUE TITLE
Unable to generate (showing 0%) code coverage report for xunit tests. 

### ISSUE THREAD

**Issue by khawaleshrikant** [OpenCover/opencover#921]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ X] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ X] repeated the problem using the latest stable release of OpenCover.
- [ X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

code coverage should not be zero , as it is non zero on other tool. 
it should contain code classes , it showing coverage for test classes. 

### Actual Behavior

code coverage is showing 0% 
not including code classes. 

### Steps to reproduce the problem:

- [ X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by khawaleshrikant** [comment]
getting  Could not find file: E:\JENKINS_HOME\jobs\CM_Core\sample\dir\Core.Application.Tests\bin\x86\Release\xunit.dll
Committing...

**Comment by sawilde** [comment]
Since OpenCover does not have a reference to xunit itself I can only assume at this point that the error is coming from your own test infrastructure

**Comment by khawaleshrikant** [comment]
Thanks for the reply , I have resolved that xunit issue , when am using "xunit.console.x86.exe", it is not showing xunit.dll error . earlier I was using "xunit.console.clr4.x86.exe"

but issue is still there , as it is skipping all the classes , not sure why 

E:\JENKINS_HOME\jobs\CM_Core\branches\feature-DI-158.9p4tae\workspace>"C:\Tools\OpenCover.4.6.519\tools\OpenCover.Console.exe" -register:admin "-target:E:\JENKINS_HOME\TOOLS\xUnit\tools\net472\xunit.console.x86.exe" "-targetargs:"E:\JENKINS_HOME\jobs\CM_Core\branches\feature-DI-158.9p4tae\workspace\Core.Application.Tests\bin\x86\Release\Core.Application.Tests.dll" "E:\JENKINS_HOME\jobs\CM_Core\branches\feature-DI-158.9p4tae\workspace\Core.DataAccess.Tests\bin\x86\Release\Core.DataAccess.Tests.dll" "E:\JENKINS_HOME\jobs\CM_Core\branches\feature-DI-158.9p4tae\workspace\Core.Tests\bin\x86\Release\Core.DataAccess.Tests.dll" "E:\JENKINS_HOME\jobs\CM_Core\branches\feature-DI-158.9p4tae\workspace\Core.Tests\bin\x86\Release\Core.Tests.dll" "E:\JENKINS_HOME\jobs\CM_Core\branches\feature-DI-158.9p4tae\workspace\Render.Tests\bin\x86\Release\Core.Plugins.Tests.dll"" "-output:E:\JENKINS_HOME\jobs\CM_Core\branches\feature-DI-158.9p4tae\workspace\opencovertests.xml" -mergebyhash  -filter:"+[Core*]* -[*Tests]*"			  			 
Executing: E:\JENKINS_HOME\TOOLS\xUnit\tools\net472\xunit.console.x86.exe
xUnit.net Console Runner v2.4.1 (32-bit Desktop .NET 4.7.2, runtime: 4.0.30319.42000)
  Discovering: Core.Application.Tests
  Discovered:  Core.Application.Tests
  Starting:    Core.Application.Tests
  Finished:    Core.Application.Tests
  Discovering: Core.DataAccess.Tests
  Discovered:  Core.DataAccess.Tests
  Starting:    Core.DataAccess.Tests
  Finished:    Core.DataAccess.Tests
  Discovering: Core.DataAccess.Tests
  Discovered:  Core.DataAccess.Tests
  Starting:    Core.DataAccess.Tests
  Finished:    Core.DataAccess.Tests
  Discovering: Core.Tests
  Discovered:  Core.Tests
  Starting:    Core.Tests
  Finished:    Core.Tests
  Discovering: Core.Plugins.Render.Tests
  Discovered:  Core.Plugins.Tests
  Starting:    Core.Plugins.Tests
  Finished:    Core.Plugins.Tests
=== TEST EXECUTION SUMMARY ===
   Core.Application.Tests     Total:   6, Errors: 0, Failed: 0, Skipped: 0, Time: 1.219s
   Core.DataAccess.Tests      Total:  18, Errors: 0, Failed: 0, Skipped: 0, Time: 0.836s
   Core.Plugins.Render.Tests  Total:   6, Errors: 0, Failed: 0, Skipped: 0, Time: 0.860s
   Core.Tests                 Total:  88, Errors: 0, Failed: 0, Skipped: 0, Time: 2.825s
                                     ---          -          -           -        ------
                        GRAND TOTAL: 118          0          0           0        5.740s (10.984s)
Committing...
Visited Classes 0 of 166 (0)
Visited Methods 0 of 452 (0)
Visited Points 0 of 1498 (0)
Visited Branches 0 of 760 (0)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 0 of 200 (0)
Alternative Visited Methods 0 of 502 (0)

**Comment by sawilde** [comment]
what does it say in the xml output file - it should provide a reason

**Comment by khawaleshrikant** [comment]
<Summary numSequencePoints="50" visitedSequencePoints="0" numBranchPoints="7" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" maxCrapScore="2" minCrapScore="2" visitedClasses="0" numClasses="1" visitedMethods="0" numMethods="7" />
          <FullName>Core.Plugins.Render.Tests.ScreenshotPathHandlerTests</FullName>
          <Methods>
            <Method visited="false" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" crapScore="2" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="3" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" maxCrapScore="2" minCrapScore="2" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="1" />
              <MetadataToken>100663297</MetadataToken>
              <Name>Core.Plugins.Render.Utils.ScreenshotPathHandler Core.Plugins.Render.Tests.ScreenshotPathHandlerTests::CreateScreenshotPathHandler()</Name>
              <FileRef uid="9267" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="127651" ordinal="0" offset="0" sl="18" sc="13" el="18" ec="60" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127652" ordinal="1" offset="16" sl="19" sc="13" el="19" ec="61" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127653" ordinal="2" offset="32" sl="21" sc="13" el="21" ec="73" bec="0" bev="0" fileid="9267" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="0" uspid="127651" ordinal="0" offset="0" sl="18" sc="13" el="18" ec="60" bec="0" bev="0" fileid="9267" />
            </Method>
            <Method visited="false" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" crapScore="2" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="6" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" maxCrapScore="2" minCrapScore="2" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="1" />
              <MetadataToken>100663298</MetadataToken>
              <Name>System.Void Core.Plugins.Render.Tests.ScreenshotPathHandlerTests::ScreenshotPathHandling_FullPathProvidedWithFileName_SamePathReturned()</Name>
              <FileRef uid="9267" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="127654" ordinal="0" offset="0" sl="28" sc="13" el="28" ec="89" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127655" ordinal="1" offset="7" sl="29" sc="13" el="29" ec="62" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127656" ordinal="2" offset="13" sl="31" sc="13" el="33" ec="40" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127657" ordinal="3" offset="37" sl="36" sc="13" el="36" ec="71" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127658" ordinal="4" offset="45" sl="39" sc="13" el="39" ec="46" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127659" ordinal="5" offset="52" sl="40" sc="9" el="40" ec="10" bec="0" bev="0" fileid="9267" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="0" uspid="127654" ordinal="0" offset="0" sl="28" sc="13" el="28" ec="89" bec="0" bev="0" fileid="9267" />
            </Method>
            <Method visited="false" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" crapScore="2" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="7" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomaticComplexity="1" maxCrapScore="2" minCrapScore="2" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="1" />
              <MetadataToken>100663299</MetadataToken>
              <Name>System.Void Core.Plugins.Render.Tests.ScreenshotPathHandlerTests::ScreenshotPathHandling_PathWithMappingAndFileNameProvided_PathWithReplacedMappingReturned()</Name>
              <FileRef uid="9267" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="127660" ordinal="0" offset="0" sl="46" sc="13" el="46" ec="89" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127661" ordinal="1" offset="7" sl="48" sc="13" el="48" ec="73" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127662" ordinal="2" offset="13" sl="49" sc="13" el="49" ec="86" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127663" ordinal="3" offset="30" sl="51" sc="13" el="53" ec="40" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127664" ordinal="4" offset="54" sl="56" sc="13" el="56" ec="71" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127665" ordinal="5" offset="62" sl="59" sc="13" el="59" ec="46" bec="0" bev="0" fileid="9267" />
                <SequencePoint vc="0" uspid="127666" ordinal="6" offset="69" sl="60" sc="9" el="60" ec="10" bec="0" bev="0" fileid="9267" />
              </SequencePoints>
              <BranchPoints />
              <MethodPoint xsi:type="SequencePoint" vc="0" uspid="127660" ordinal="0" offset="0" sl="46" sc="13" el="46" ec="89" bec="0" bev="0" fileid="9267" />
            </Method>
            <Method visited="false" cyclomaticComplexity="1" nPathComplexity="0" sequenceCoverage="0" branchCoverage="0" crapScore="2" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="9" visitedSequencePoints="0" numBranchPoints="1" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="1" minCyclomati

**Comment by khawaleshrikant** [comment]
Core.Plugins.Render.Tests.ScreenshotPathHandlerTests::ScreenshotPathHandling_FullPathProvidedWithFileName_SamePathReturned() 

is this a reason , which is in the name tag.

**Comment by khawaleshrikant** [comment]
[results.txt](https://github.com/OpenCover/opencover/files/3787292/results.txt)  

here is the output file.

**Comment by sawilde** [comment]
@khawaleshrikant it looks like it is instrumenting the code correctly but none of the sequence points are being hit

**Comment by arunkabilan** [comment]
i am facing similar issue unable to get coverage for test result 
Feature.Account.Tests  Total: 117, Errors: 0, Failed: 1, Skipped: 0, Time: 11.667s
Committing...
Visited Classes 0 of 277 (0)
Visited Methods 0 of 761 (0)
Visited Points 0 of 5735 (0)
Visited Branches 0 of 2555 (0)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 0 of 409 (0)
Alternative Visited Methods 0 of 1063 (0)
