### ISSUE TITLE
Possibility to pass multiple targetdirs 

### ISSUE THREAD

**Issue by Poojashree04** [OpenCover/opencover#922]
It's possible to pass multiple targetdirs when starting open cover.

I have an application which requires 2 different solutions (Central and Remote) I will cover the code usage over the complete application (Central and Remote).

I run the command from jenkins, but i can only cover the complete code from Central, which i define over the targetdirs parameter. but i missing the coverage from the second application.

**Comment by sawilde** [comment]
@Poojashree04 if you mean for looking for the PDBs then yes use the `searchdirs` option [Usage](https://github.com/OpenCover/opencover/wiki/Usage)
