### ISSUE TITLE
-mergeoutput doesn't work

### ISSUE THREAD

**Issue by Poojashree04** [OpenCover/opencover#923]
We have two solutions so we would have to run the separate commands for each of the solution by specifying the solution path in “targetdir:”. Without specifying “targetdir:” we wouldn’t get code coverage is sonarcube. Also, i have to provided output path(Same path as given while initializing sonarqube) in both batch commands. So while executing the batch command for the first solution it will calculate code coverage properly. But while executing the batch command for the second solution it doesn’t consider the previously calculated code coverage as result of this we are seeing only the result of second solution in both CodeCoverage(SonarCube) and TestResults.trx(Jenkins dashboard).

I've used -mergeoutput option but it is not merging the result.

bat """OpenCover.Console.exe "-targetdir:${pwd()}\\Central\\bin" "-output:${pwd()}\\opencover.xml" "-register:user" "-target:vstest.console.exe" "-targetargs:${pwd()}\\Central\\bin\\Central.Test.dll --logger:trx;LogFileName=${pwd()}\\TestResults\\vstest-results.trx" -mergeoutput"""

bat """OpenCover.Console.exe "-targetdir:${pwd()}\\Remote\\bin" "-output:${pwd()}\\opencover.xml" "-register:user" "-target:vstest.console.exe" "-targetargs:${pwd()}\\Remote\\bin\\Remote.Tests.dll --logger:trx;LogFileName=${pwd()}\\TestResults\\vstest-results.trx" -mergeoutput"""

Am i missing anything?

**Comment by sawilde** [comment]
not that I can see based on what you have currently supplied me with - what is `bat`?

**Comment by Poojashree04** [comment]
It is a batch command.

**Comment by sawilde** [comment]
After the first command is run does the file `opencover.xml` exist and if so what is in it?
