### ISSUE TITLE
OpenCover doesn't find all assemblies

### ISSUE THREAD

**Issue by ZavalichiR** [OpenCover/opencover#924]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [x ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ x] repeated the problem using the latest stable release of OpenCover.
- [x ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Fill me in...

### Actual Behavior
I am trying to use AxoCover from cmd, for this I have OpenCover and ReportGenerator. If I start AxoCover from visual studio, it founds 50 Assemblies, but when I use cmd, it founds only 16 Assemblies. Can you help me? This is the script:
```
SET testTool="c:\path\VSTest.Console.exe"
SET testAssembly=""pathForDll\first.dll" "pathForDll\second.dll"" 
SET coverTool="path\OpenCover.Console.exe"
SET reportTool="path\ReportGenerator.exe"
SET coverXML="OpenCoverResults\OpenCover.xml"
SET coverReportLocation="CoverageReport"
SET history="OpenCoverResults\History\"
echo CoverTool
%coverTool% -target:%testTool% -targetargs:%testAssembly% -mergebyhash -skipautoprops -register:user 
-hideskipped:All -filter:"+[*]*" -output:%coverXML% 

echo ReportTool
%reportTool% -reports:%coverXML% -targetdir:%coverReportLocation% 
start c:\1.PROJECTS\ARIA\Others\Scripts\CoverageReport\index.htm
```

**Comment by sawilde** [comment]
AxoCover is just a UI wrapper over OpenCover.

Remove the `-hideskipped:All` since you are hiding the assemblies classes that are not being instrumented

**Comment by ZavalichiR** [comment]
Not working

**Comment by sawilde** [comment]
@ZavalichiR then you will need to provide more information but I do not have enough to go on to help you at the moment
