### ISSUE TITLE
Could not load file or assembly 'MyReference' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by VicZhang1** [OpenCover/opencover#925]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

All test passed

### Actual Behavior

When I run following command in CMD against my NUnit test, I get failures of test cases because of `Could not load file or assembly 'MyReference' or one of its dependencies. The system cannot find the file specified.` exception:
> .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -target:.\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe -register:Path64 -targetargs:"MyUnitTests.nunit /config=Debug /result=MyUnitTests.UnitTest.xml" -output:"OOPCollector.OpenCover.xml" -filter:"+[Te*]* -[*Test*]* -[*Demo*]* -[Trace*]*"

But if I run `nunit3-console.exe` successfully(all passed) in CMD directly like:

> .\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe .\UnitTests\bin\Debug\MyUnitTests.dll

I checked `MyReference.dll` after compilered unit test project, the `MyReference.dll` is in the same folder where the `MyUnitTests.dll` is in.

The `MyUnitTests.nunit` file is:
```
<NUnitProject>
  <Settings activeconfig="Debug"/>
  <Config name="Debug">
    <assembly path="UnitTests\bin\Debug\MyUnitTests.dll"/>
  </Config>
  <Config name="Release">
    <assembly path="UnitTests\bin\Release\MyUnitTests.dll"/>
  </Config>
</NUnitProject>
```

### Steps to reproduce the problem:

- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
Sorry I do not have enough information to help you. You'll need to create a sample that someone can reproduce the issue
