### ISSUE TITLE
IIS : OpenCover running under IIS with website application pool Identity as custom account not allowing to launch website - 403 Forbidden error

### ISSUE THREAD

**Issue by saranyas** [OpenCover/opencover#927]
I have website hosted in IIS (Windows 10 Version 10.0.18362.1) with Application Pool Identity as Custom account and trying to attach OpenCover in debug mode to get the code coverage.

**Problem** : After attaching the Opencover.exe to w3wp.exe process, when I tried to launch website with custom account Application Pool Identity from IIS getting the below error.

Note : This works perfect when using Application Pool used as ASP.NET V4.0 Integrated. But with custom account Application Pool Identity

**Error Details:**
From the windows log:

The World Wide Web Publishing Service (WWW Service) did not register the URL prefix http://*:80/rfapi_v10 for site 1. The necessary network binding may already be in use. The site has been disabled. The data field contains the error number.
From the browser:

HTTP Error 403.18 - Forbidden
The specified request cannot be processed in the application pool that is configured for this resource on the Web server.

Steps followed:

Website setup:

1. In IIS, **I created an application pool with Application Pool Identity as Custom account** - Which prompts to enter username and password. **NOT** with Build-in account like ApplicationPoolIdentity which is default.
Example : TestAppPool - Identity as custom account.

2. I added new website under Default Web Site.

Example : Website name : Test
                In the 'Test' Website Settings updated the Application Pool as 'TestAppPool' (Created in step 1.)

Commands:

1. Stopping the w3svc before opencover command : C:\WINDOWS\system32>net stop w3svc

OpeCover commands:

2. Open the command window as administrator.
3. Run the command

C:\..\opencover.4.7.922>OpenCover.Console.exe -target:C:\Windows\System32\inetsrv\w3wp.exe -targetargs:"-debug -s 1"-targetdir:C:\Project\bin\ -register:user -output:"C:\opencover.xml"
Executing: C:\Windows\System32\inetsrv\w3wp.exe
Press 'Q' to shutdown the process:

4. Now start C:\WINDOWS\system32>net start w3svc

5. Browse the website startup page from IIS.

 ![image](https://user-images.githubusercontent.com/1814806/70276816-1cd18500-177f-11ea-8354-60bc6bccec7f.png)
![image](https://user-images.githubusercontent.com/1814806/70276829-265aed00-177f-11ea-8318-eecb228ca7aa.png)

![image](https://user-images.githubusercontent.com/1814806/70276902-4c808d00-177f-11ea-931e-5cde521a6ca7.png)

**Comment by sawilde** [comment]
I believe it is because you are using the `-register:user` switch which is registering OpenCover for the current user - try using `-register` or `-register:path64`

**Comment by saranyas** [comment]
Thanks for the reply.

I found this to be happening when Apppool is different for Website and projects hosted within it.

It works perfectly when DefaultAppPool is selected for the website and projects. Regardless of built in or Custom identity set to that apppool.

**Question** : Does OpenCover launches the w3wp.exe IIS in debug mode with DefaultAppPool always? Is any way set different apppool when the w3wp.exe launched in debug mode?

**Comment by saranyas** [comment]
Please let me know for the below question to proceed.

**Question** : Does OpenCover launches the w3wp.exe IIS in debug mode with DefaultAppPool always? Is any way set different apppool when the w3wp.exe launched in debug mode?

**Comment by sawilde** [comment]
OpenCover just launches IIS as a service it does not do anything with AppPools directly - if you are using a custom app pool with a specific identity the registering the profiler under you local user account (`-register:user`) will not work. 

> I believe it is because you are using the -register:user switch which is registering OpenCover for the current user - try using -register or -register:path64

If those don't work then try just plain `-register` which will do a system registration of OpenCover profiler
