### ISSUE TITLE
Rename OpenCover Chocolatey package to OpenCover.install

### ISSUE THREAD

**Issue by pascalberger** [OpenCover/opencover#928]
Since there is already a [opencover.portable](https://chocolatey.org/packages/opencover.portable) Chocolatey package, the default naming convention would be to rename the [OpenCover](https://chocolatey.org/packages/OpenCover) package to `opencover.install` and let the `OpenCover` package have a dependency on `opencover.install`.

**Comment by sawilde** [comment]
Why would we need to do this? What advantages?

**Comment by pascalberger** [comment]
There's no technical need to do this. Currently it is just mainly just a convention used in the community repository (see e.g. Git, VsCode, 7Zip, etc). In the future there might be a feature of virtual packages which can help to take either a dependency on the `.install` or `.portable` package. Following the three-package-name convention also makes clear that there is an installer option for users. Currently with `OpenCover` and `opencover.portable` it could also be that `OpenCover` is just a meta package for `opencover.portable`, without inspecting the content of the package.

See also [What is the difference between packages with no suffix as compared to *.install & *.portable?](https://chocolatey.org/docs/chocolatey-faqs#what-is-the-difference-between-packages-no-suffix-as-compared-toinstallportable)

**Comment by sawilde** [comment]
thanks - I'll add that to the future list
