### ISSUE TITLE
OpenCover does not cover Microsoft Fakes (Shim) with ReportGenerator.exe and vstest.console.exe

### ISSUE THREAD

**Issue by barisgul** [OpenCover/opencover#932]
### My Framework
- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [X] .NET 4.6
- [X] .NET 4.6.1
- [X] .NET 4.6.2
- [X] .NET 4.7
- [X] .NET 4.7.1
- [X] .NET 4.7.2
- [X] .NET 4.8
- [X] .NET Core 1.0.0
- [X] .NET Core 2.0.0
- [ ] Something else

### My Environment
- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### My Test Framework
- [x] Xunit

### I have already...
- [X] repeated the problem using the latest stable release of OpenCover. (version 4.7.922)
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):
- [X] no coverage being recorded
- [X] different errors for register (user, path32, path64)
- [ ] 32 or 64 bit support
- [X] feature request

### Expected Behavior
I am trying to get coverage xml using OpenCover and vstest.console.exe with below batch code. 
It should create an xml like below
![image](https://user-images.githubusercontent.com/4164016/73740073-84448a80-4758-11ea-9434-0b02e2bdc0f0.png)

```batch
set unitTestDllPath=C:\\Tfs\\myProject\\myProject.UnitTest\\bin\\Release\\myProject.UnitTest.dll 
set coverageOutput=C:\\Tfs\\OpenCoverCoverage.xml  
set openCoverConsoleExe=C:\\sonarqube\\OpenCover\\opencover.4.7.922\\OpenCover.Console.exe
set vstestconsole=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe
set ReportGenerator=C:\\Tfs\\V2\\DEV\\myProject\\Solutions\\packages\\ReportGenerator.4.4.6\\tools\\net47\\ReportGenerator.exe
set xunitAdapter=C:\\Tfs\\V2\\DEV\\myProject\\Solutions\\packages\\xunit.runner.visualstudio.2.4.1\\build\\_common\\

"%openCoverConsoleExe%" -register:user -target:"%vstestconsole%" -targetargs:"%unitTestDllPath% /InIsolation /EnableCodeCoverage /TestAdapterPath:"%xunitAdapter%""  -output:%coverageOutput% -mergebyhash
%ReportGenerator% -reports:%coverageOutput% coverage
```

### Actual Behavior
with above batch code i should create a coverage xml report. It creates file but xml file is empty and looks below.
![image](https://user-images.githubusercontent.com/4164016/73726519-c8c42c00-4740-11ea-9cb6-a0db5bbebd80.png)

In addition, if i use register types with path32, unit tests written with Shim in my project are running, for others (user, path64) does not running as below.
In my project 2 of 19 tests written with microsoft shim, 17 are not.
**with -register:path32**
![image](https://user-images.githubusercontent.com/4164016/73727935-76d0d580-4743-11ea-82fa-574c31650553.png)

 **with -register:path64 and -register:user** 
**shim tests failed  and does not visiting any class**
![image](https://user-images.githubusercontent.com/4164016/73728040-a67fdd80-4743-11ea-9116-937a4a10a2c1.png)

How can i get coverage for Microsoft Fakes using OpenCover? vstest.console.exe creates an .coverage file and i need to convert this file to opencover xml format for sonarqube. So, i have used ReportGenerator.exe with vstest.console because nunit console runner and xunit console runner does not execute microsoft fakes tests.

**Comment by sawilde** [comment]
Microsoft.Fakes works by inserting it's own profiler and this overides the profiler registration we need for OpenCover to run.

We have tried supporting Fakes in the past but each release of MSTest broke the support. Usage is too low to bother with support
