### ISSUE TITLE
Running OpenCover shows 0% Code coverage.

### ISSUE THREAD

**Issue by sunpakky** [OpenCover/opencover#935]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [x] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [X] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior
Expected to show code coverage as the covered percentage.

### Actual Behavior
The Code coverage is always shown as 0

### Steps to reproduce the problem:

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [] sample code or link to repository/gist is available (support is much faster this way) 

Use the following command : 
`OpenCover.Console.exe -target:"<PATH>\xunit.runner.console.2.4.1\tools\net472\xunit.console.x86.exe" -targetargs:"<PATH>\bin\Debug\PROJECT_Tests.dll" -register:user -output:"<PATH>\bin\Debug\TestResults\OpenCover\coverage.xml"`

I have tried the same with vstest runner also. Is this the same issue as #921?
Visual Studio 2019 community edition

In cmd, the output is shown as : 

=== TEST EXECUTION SUMMARY ===
   PROJECT_Tests Total: 11, Errors: 0, Failed: 0, Skipped: 0, Time: 118.717s
Committing...
Visited Classes 235 of 1338 (17.56)
Visited Methods 942 of 17022 (5.53)
Visited Points 2632 of 58653 (4.49)
Visited Branches 1607 of 36315 (4.43)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 235 of 1570 (14.97)
Alternative Visited Methods 942 of 18541 (5.08)

But, when checking the coverage.xml file or using report generator (v4.5.0) we generate the report all the files are shown as 0% coverage.

```
<Method visited="false" cyclomaticComplexity="4" nPathComplexity="2" sequenceCoverage="0" branchCoverage="0" crapScore="20" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="8" visitedSequencePoints="0" numBranchPoints="3" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="4" minCyclomaticComplexity="4" maxCrapScore="20" minCrapScore="20" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="1" />
              <MetadataToken>100664627</MetadataToken>
              <Name>project.BusinessEntities.CoordinationNotes.CoordinationNotesInfo project.CoordinationNotes.DalCoordinationNotes::GetDetails(project.BusinessEntities.SystemManagement.GeneralRequest,project.BusinessEntities.Member.MemberTaskList&amp;,System.Object&amp;)</Name>
              <FileRef uid="2505" />
              <SequencePoints>
                <SequencePoint vc="0" uspid="75974" ordinal="0" offset="0" sl="38" sc="9" el="38" ec="10" bec="0" bev="0" fileid="2505" />
                <SequencePoint vc="0" uspid="75975" ordinal="1" offset="1" sl="39" sc="13" el="39" ec="131" bec="0" bev="0" fileid="2505" />
                <SequencePoint vc="0" uspid="75976" ordinal="2" offset="44" sl="41" sc="20" el="41" ec="56" bec="0" bev="0" fileid="2505" />
                <SequencePoint vc="0" uspid="75977" ordinal="3" offset="56" sl="42" sc="13" el="42" ec="14" bec="0" bev="0" fileid="2505" />
                <SequencePoint vc="0" uspid="75978" ordinal="4" offset="57" sl="43" sc="17" el="43" ec="75" bec="0" bev="0" fileid="2505" />
                <SequencePoint vc="0" uspid="75979" ordinal="5" offset="72" sl="45" sc="17" el="45" ec="115" bec="2" bev="0" fileid="2505" />
                <SequencePoint vc="0" uspid="75980" ordinal="6" offset="99" sl="47" sc="17" el="47" ec="29" bec="0" bev="0" fileid="2505" />
                <SequencePoint vc="0" uspid="75981" ordinal="7" offset="114" sl="49" sc="9" el="49" ec="10" bec="0" bev="0" fileid="2505" />
              </SequencePoints>
              <BranchPoints>
                <BranchPoint vc="0" uspid="75982" ordinal="0" offset="79" sl="45" path="0" offsetend="81" fileid="2505" />
                <BranchPoint vc="0" uspid="75983" ordinal="1" offset="79" sl="45" path="1" offsetend="84" fileid="2505" />
              </BranchPoints>
              <MethodPoint xsi:type="SequencePoint" vc="0" uspid="75974" ordinal="0" offset="0" sl="38" sc="9" el="38" ec="10" bec="0" bev="0" fileid="2505" />
            </Method>
```

**Comment by sawilde** [comment]
sorry can't repeat and not enough information to go on - are you sure you are looking at the right file?

**Comment by sunpakky** [comment]
Yes, The file being checked is correct. Is there any restriction how a unit test project needs to be setup. I have created my Unit Test project using simple class library and added references. 

Is there any specific information that you will need to check this in detail ?

**Comment by sawilde** [comment]
I am confused as the text says you have coverage but you say the XML is empty - but if I recall correctly the data shown on the screen to the user at the end of the run is generated from the data that is dumped to XML - so you see I can't see how you can coverage reported on the screen but not coverage data in your XML file.

**Comment by arjun-007** [comment]
Hi @sawilde , I have faced an issue while including some of the class in the data layer project into the unit test. That is, when some of the class libraries included, total line coverage in that entire project became zero. For further analysis, I have come to the assumption that there will be a maximum line of code coverage limit in class wise or project-wise.

Could you please clarify me assumption is right or wrong?

**Comment by arjun-007** [comment]
Hi Support,  I have faced an issue while including some of the class in the data layer project into the unit test. That is when some of the class libraries included, the total line of coverage in that entire project became zero. For further analysis, I have come to the assumption that there will be a maximum line of code coverage limit in class wise or project-wise.

Could you please clarify my assumption is right or wrong?

**Comment by arunkabilan** [comment]
hi support , my test methods are executed but coverage shows o

  Finished:    PACES.Feature.Account.Tests
=== TEST EXECUTION SUMMARY ===
   PACES.Feature.Account.Tests  Total: 117, Errors: 0, Failed: 1, Skipped: 0, Time: 11.667s
Committing...
Visited Classes 0 of 277 (0)
Visited Methods 0 of 761 (0)
Visited Points 0 of 5735 (0)
Visited Branches 0 of 2555 (0)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 0 of 409 (0)
Alternative Visited Methods 0 of 1063 (0)

please let me know the solutions
