### ISSUE TITLE
Coverage differs between 4.6.519 and 4.7.922

### ISSUE THREAD

**Issue by brennon** [OpenCover/opencover#937]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [X] .NET 4.5.2
- [ ] .NET 4.6
- [X] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [X] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Identical (or at least very similar) coverage reported from a run using OpenCover 4.7.922 as reported from a run using OpenCover 4.6.519.

### Actual Behavior

Far lower (but not zero) coverage reported from a run using OpenCover 4.7.922 than a run using OpenCover 4.6.519.

### Steps to reproduce the problem:

I'm running the following command:
```
"C:\\Apps\OpenCover\OpenCover.Console.exe" -register:Path64 -log:All -targetdir:C:\Build\Builds\Artifacts -target:C:\ProgramData\chocolatey\bin\nunit3-console.exe -targetargs:"C:\Build\Builds\Artifacts\MyApp.BLL.Tests.dll --seed=23 --work=C:\Build\Reports\nUnit --output=C:\Build\Reports\nUnit\MyApp.BLL.Tests.nunit.output --result=C:\Build\Reports\nUnit\MyApp.BLL.Tests.nunit.result" -output:C:\Build\Reports\nUnit\Data\MyApp.BLL.Tests.coverage.xml -mergebyhash
```
When, the `OpenCover.Console.exe` is at version 4.6.519, I get:
```
Visited Classes 789 of 4495 (17.55)
Visited Methods 6797 of 47600 (14.28)
Visited Points 21402 of 185869 (11.51)
Visited Branches 9260 of 81657 (11.34)
```
When, however, I use an `OpenCover.Console.exe` at version 4.7.922, I get:
```
Visited Classes 19 of 3763 (0.5)
Visited Methods 51 of 43113 (0.12)
Visited Points 119 of 167703 (0.07)
Visited Branches 67 of 84269 (0.08)
```
There's absolutely nothing that's changed between the two runs: same nUnit runner, same build, etc. Any ideas as to why I'm seeing such differences?

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
review the output files it may give you an indication

**Comment by brennon** [comment]
Any particular output files you'd suggest that I review?

**Comment by sawilde** [comment]
the xml output files that are created at the end - may give you an indication of what has vanished
