### ISSUE TITLE
Support net core and netstandard in sdk style csproj's.

### ISSUE THREAD

**Issue by AraHaan** [OpenCover/opencover#939]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [x] .NET 4
- [x] .NET 4.5
- [x] .NET 4.6
- [x] .NET 4.6.1
- [x] .NET 4.6.2
- [x] .NET 4.7
- [x] .NET 4.7.1
- [x] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [x] .NET Core 2.0.0
- [x] Something else
(net core 2.1, 2.2, 3.0, 3.1, and netstandard2.0)

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10 (absolute latest insider preview build)
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.
- [x] What I have already read from the project description here (on github) and on nuget.org.
I just want the package to be able to restore for my test projects and I would love to be able to run my tests on any OS, as well as test all of my TargetFrameworks and send them all at once to codecov.io (each framework appends to the same coverage report file).

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [x] feature request

### Expected Behavior

For my csproj that contains my tests to target all of the TargetFrameworks the actual project targets, and outputs the same test output results, for usage on codecov.io for any OS.

### Actual Behavior

Well if I use the same TargetFrameworks the tests *could* fail to compile saying that the package OpenCover does not support ``netstandard?.?`` or ``netcoreapp?.?``

### Steps to reproduce the problem:

- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [x] sample code or link to repository/gist is available (support is much faster this way) 
https://github.com/AraHaan/XmlAbstraction/ (the main library as well as the tests are inside there)

**Comment by sawilde** [comment]
Opencover shouldn't really be added to projects as it is not an assembly package but a tool it should be used a solution package - I don't see a way to do solution packages in nuget any more (was deprecated). The SampleSln provides a guide on how to install OpenVover at the solution level.

We have created chocolatey packages for OpenCover which are more tool orientated.

**Comment by sawilde** [comment]
I have added opencover (4.7.922) as a package reference to projects with 

net5.0
netstandard2.0
netcoreapp3.1
netcoreapp2.2

and saw no compilation issues

can't repeat - closing
