### ISSUE TITLE
Code coverage produces no results in case process is run in Administration mode

### ISSUE THREAD

**Issue by fabasoad** [OpenCover/opencover#940]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [x] .NET Core 3.1

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior
Correct result should be generated in case I run `OpenCover.Console.exe` in Administrator mode.

### Actual Behavior
There are no results generated in case I run `OpenCover.Console.exe` in Administrator mode.

### Steps to reproduce the problem:
I've found out this issue when I was configuring CI to collect the code coverage. The behavior was odd - locally results are collected and all works as expected but in CI I had this message:
```
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
```
[Here](https://github.com/fabasoad/ghacu/runs/625543417) is the CI results (`Run tests with coverage` step). After some investigation I recognized that actually I can reproduce the same behavior locally if I run `pwsh` in Administration mode. Here is the screenshot for more details (as you can see project path is the same and command is the same, the main difference is Administration mode):
![Annotation 2020-04-28 200145](https://user-images.githubusercontent.com/2127723/80480220-37550680-898b-11ea-9535-964f4f937b60.png)

- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [x] sample code or link to repository/gist is available (support is much faster this way)

**Comment by rafael-xpertgroup** [comment]
It's the same for me :|

**Comment by fabasoad** [comment]
Didn't find a workaround... Looking forward for author's feedback.

**Comment by MikeRosoft** [comment]
In my experience: if the current user is not running under administrator privileges, it is necessary to run OpenCover with `-register:user` parameter; if it is running under administrator privileges, it is necessary to run OpenCover with `-register:administrator` parameter. If you want to support both cases, you can create a MsBuild task to check if the current user is an admin, like:

```
  <UsingTask TaskName="CheckAdmin" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup>
      <IsAdmin ParameterType="System.Boolean" Output="True"/>
    </ParameterGroup>

    <Task>
      <Using Namespace="System.Security.Principal" />
      <Code Type="Fragment" Language="cs">
        WindowsIdentity identity = WindowsIdentity.GetCurrent();
        WindowsPrincipal principal = new WindowsPrincipal(identity);
        IsAdmin = principal.IsInRole(WindowsBuiltInRole.Administrator);
      </Code>
    </Task>
  </UsingTask>
```

I don't know why this is even necessary and why doesn't OpenCover default to either `-register:user` or `-register:administrator` depending on the current user's role.

**Comment by sawilde** [comment]
OpenCover has not been updated in some time and has limited coverage for .NET core especially any flavour of .NET core that was released after the latest release - YMMV

**Comment by fabasoad** [comment]
@MikeRosoft your solution works for me. Thanks!
`+1` for feature request that automatically detects user's current role.
