### ISSUE TITLE
Opencover doesnot include the test performed after application launch

### ISSUE THREAD

**Issue by VigneshRaju10** [OpenCover/opencover#942]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [x] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Fill me in...

### Actual Behavior

I have a windows application which will make a remote call to a windows service.
I did refer your comments on running the application with remote process by having a bat file launching the windows service first and my application next. The application and service are getting launched. I did login into my application and performed few tests which involves remote call to my windows service. when I observer the report , I am able to see that the assemblies used till the launch of the service and application are only getting covered and rest of the assemblies are always under zero coverage.
I also tried adding -targetdir,-searchdir parameters but no luck.
Please help me where I am heading wrong.

**Comment by sawilde** [comment]
A windows service is its own special beast - see if you can run that application as a console application.
