### ISSUE TITLE
Does OpenCover support code coverage for child process?

### ISSUE THREAD

**Issue by KesavaPindi** [OpenCover/opencover#943]
Hello,

I was successfully do the code cover for the parent process, but if the parent process launches any other child process to do something our OpenCover is unable to do the code coverage for child process. Even if we place the PDB's for the exe.

For Example : i have PatentApp which is launched through the NUnit based on the some of the commands it will launch ChildApp. 
Uisng OpenCover i was able to do the code coverage for ParentApp not for the ChildApp

Could you please let us know is there any additional commands or setting are need to do the child process.

Thanks In Advance 
Kesava

**Comment by sawilde** [comment]
It should pick up child processes assuming they are using the same environment variables from the parent process.
