### ISSUE TITLE
open cover and report generator- unable to generate report for the class files (.cs files) in asp.net web application

### ISSUE THREAD

**Issue by adithig** [OpenCover/opencover#945]
I am trying to perform a code coverage in a asp.net web application using open cover. As it is a web application i tried to do code coverage using iis express.
below is the structure of my solution
![image](https://user-images.githubusercontent.com/46962059/81814479-774ce980-9546-11ea-9390-9737b266f33e.png)

in open cover command file i have used the following command. OpenCover.Console -register:user -target:"C:\Program Files (x86)\IIS Express\iisexpress.exe" "-targetargs:/config:applicationhost.config /site:webapp /apppool:Clr4IntegratedAppPool" -targetdir:C:\Users\a.ganapathi\source\repos\webapp.vs\config\ -filter:+[] -output:C:\Users\a.ganapathi\source\repos\webapp\webapp\bin\WebApp.xml Pause

Report generator command that i used, eportGenerator.exe -reports:"C:\Users\a.ganapathi\source\repos\webapp\webapp\bin\WebApp.xml" -targetdir:"C:\Users\a.ganapathi\source\repos\webapp\webapp\html" -sourcedirs:"C:\Users\a.ganapathi\source\repos\webapp\webapp\bin" pause

When iam running the command file of open cover and report generator the reports are generated only for the cshtml files.there is no report generated for the class files. The register application using iis express after running the open cover command files works perfectly and hits all the classes but the report for the class files are not generated. so can anyone help me why this happens or is there any other way to perform code coverage using open cover and report generator for a web application.

even the result file that is created after the open cover command does not contain any content in the class tag.

this is a piece of code from the result xml file. webapp is my solution.

C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\9544d378\85a3833a\assembly\dl3\b68d8cea\fc9091ed_0529d601\webapp.dll 2020-05-13T10:59:38.7027397Z webapp

**Comment by sawilde** [comment]
not enough information to go on.
