### ISSUE TITLE
Coverage data is inconsistent (sometimes ~3% coverage, sometimes 0 coverage)

### ISSUE THREAD

**Issue by mwelsh1118** [OpenCover/opencover#946]
I have observed inconsistent results when running OpenCover.  So far I have identified one combination of production & test dll which exhibits the issue, but there may be more (we have a very large number of projects).  Roughly 3/4 of the time, when I run OpenCover against this particular production & test dll, I get zero for all coverage metrics --
```
Committing...
Visited Classes 0 of 5596 (0)
Visited Methods 0 of 30845 (0)
Visited Points 0 of 148408 (0)
Visited Branches 0 of 59301 (0)
```

The other 1/4 of the time, I get correct metrics --
```
Committing...
Visited Classes 176 of 5596 (3.15)
Visited Methods 836 of 30845 (2.71)
Visited Points 4439 of 148408 (2.99)
Visited Branches 1521 of 59301 (2.56)
```

I have observed the problem both on my workstation (Windows 10) and build machines (Windows Server 2016). The former seems to work correctly more often than the latter.

This is a simplified example command line:
`OpenCover.Console.exe -target:\\network\xunit\xunit.console.exe -targetargs:"\\network\CI-build\My.Tests.dll -nologo -noshadow -quiet -xml \\network\CI-build\My.Tests.Xunit.Results.xml" -filter:"+[My*]* -[*.Tests]*" -threshold:100 -output:\\network\CI-build\My.Tests.OpenCover.Results.xml`

In the example, My.dll is the production dll and My.Tests.dll is the test dll.  The file sizes are:
My.dll: 6MB
My.pdb: 24MB
My.Tests.dll: 2.5MB
My.Tests.pdb: 7MB

The reason coverage is so low (3%) is that we are running a small subset of tests from My.Tests.dll (this is accomplished via config files that are "passed" to the xunit run via environment variables).  In the problematic case, we are running ~225 out of 4,000 unit tests in My.Tests.dll. The rest are skipped.

My suspicion is that there's some sort of race condition that causes the OpenCover collection process to shut down before the coverage data is actually captured (maybe exacerbated by the relatively large size of the target dlls and relatively short run-time of the xunit.console.exe).

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [X] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [X] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Consistently return 3% coverage.

### Actual Behavior

Sometimes returns 3% coverage; other times, returns 0%

### Steps to reproduce the problem:

Reproducible on proprietary codebase, unfortunately.

- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by mwelsh1118** [comment]
One other note: the machine running the tests is not the machine that compiled the assemblies, so the pdb points to files that won't exist.  I see many warnings like this when OpenCover is committing results (and I turn up logging level to verbose):
`Source file XXX.cs is not found`
This doesn't seem to be a problem for other dlls, but I thought I would mention it.

**Comment by sawilde** [comment]
I don't have the ability to repeat this
