### ISSUE TITLE
Casting Instruction.Operand as FieldDefintion results in null object and proceeds to throw null exception in CecilSymbolManager.IgnoreConditionalBranchSequence(Instruction instruction, Collection<Instruction> instructions, int branchOffset)

### ISSUE THREAD

**Issue by Cjewett** [OpenCover/opencover#948]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ X] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X ] no coverage being recorded
- [X ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

All DLLs within the same directory as the unit test being run should have an entry in the output file as long as you don't specify the -hideskipped parameter.

### Actual Behavior

Output file is missing entries for DLLs even though the test run was 100% successful. 

After running tests successfully using the following command line there are results missing for PDBs that were not logged as being skipped or filtered out in the logs (when -log:all is specified). I used DebugViewer to see if I could find anything and it seems like for the DLLs in question are running into exceptions in the OpenCover code. 

`C:\Github\opencover\main\bin\Debug\OpenCover.console.exe -target:"C:\Program Files(x86)\Microsoft VisualStudio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"AlarmUtilsTests.dll /Logger:trx;LogFileName=AlarmUtilsTests.trx" output:"opencover.xml" -register:user`

Errors being hit:
```
`00000292	146.81094360	[17404]    at OpenCover.Framework.Communication.MessageHandler.HandleTrackAssemblyMessage(IntPtr pinnedMemory)	
00000293	146.91381836	[17404] OpenCover: (Host) HandleTrackAssemblyMessage => System.InvalidOperationException:System.InvalidOperationException: An error occurred with 'GetBranchPointsForToken' for method 'System.Func`2<System.String,T> UAParser.Parser::CreateParser(System.Collections.Generic.IEnumerable`1<System.Func`2<System.String,T>>,T)' ---> System.NullReferenceException: Object reference not set to an instance of an object. 	
00000294	146.91381836	[17404]    at OpenCover.Framework.Symbols.CecilSymbolManager.IgnoreConditionalBranchSequence(Instruction instruction, Collection`1 instructions, Int32 branchOffset) 	
00000295	146.91381836	[17404]    at OpenCover.Framework.Symbols.CecilSymbolManager.LoadPointsForConditionalBranch(List`1 list, Instruction instruction, Int32 branchingInstructionLine, String document, Int32 branchOffset, Int32 pathCounter, Collection`1 instructions, UInt32& ordinal) 	
00000296	146.91381836	[17404]    at OpenCover.Framework.Symbols.CecilSymbolManager.GetBranchPointsForToken(Int32 token, List`1 list) 	
00000297	146.91381836	[17404]    --- End of inner exception stack trace --- 	
00000298	146.91381836	[17404]    at OpenCover.Framework.Symbols.CecilSymbolManager.GetBranchPointsForToken(Int32 token, List`1 list) 	
00000299	146.91381836	[17404]    at OpenCover.Framework.Symbols.CecilSymbolManager.GetBranchPointsForToken(Int32 token) 	
00000300	146.91381836	[17404]    at OpenCover.Framework.Model.InstrumentationModelBuilder.BuildClassModel(Class class, File[] files) 	
00000301	146.91381836	[17404]    at OpenCover.Framework.Model.InstrumentationModelBuilder.CreateModule(Boolean full) 	
00000302	146.91381836	[17404]    at OpenCover.Framework.Service.ProfilerCommunication.TrackAssembly(String processPath, String modulePath, String assemblyName) 	
00000303	146.91381836	[17404]    at OpenCover.Framework.Communication.MessageHandler.HandleTrackAssemblyMessage(IntPtr pinnedMemory)`
```

I ran OpenCover locally to debug what was going on. The issue is https://github.com/OpenCover/opencover/blob/94c7e572a907ac1873b8f48324d0cbc0cf1e7456/main/OpenCover.Framework/Symbols/CecilSymbolManager.cs#L577 returns null. 

I added some debug code and ints.Operand isn't null but casting to FieldDefinition results in a null object. There is no null check on definition, so when calling definition.name it throws the exception.

As a result it seems like everything about that DLL isn't being saved after the exception is thrown but I might be wrong in that assumption. I'm still investigating but could use some assistance to understand what this function is trying to do and what potential fixes might be. 

### Steps to reproduce the problem:

- [X ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
obviously we are expecting a field definition at that point 

do you know what code is causing the problem as it would take a read of the code/IL being parsed to investigate the issue.
