### ISSUE TITLE
The app always doesn't load my assembly.

### ISSUE THREAD

**Issue by lwl5219** [OpenCover/opencover#949]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [x] .NET 4
- [x] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Actual Behavior

The app outputs **No results**

### Steps to reproduce the problem:

The app really prints very less log messages even I set the log level as Debug. 

The result file is [result.xml](https://www.dropbox.com/s/nd2t6zjjrf3bp2m/results.xml?dl=0)

The result file doesn't contain my assembly file(rssbus.APIServer.Test.dll).

The DebugType is full in .csproj file. My target assembly file is 9.17MB and the pdb file is 24.89MB. Is it because my assembly file it too big?

    λ D:\Util\opencover.4.7.922\OpenCover.Console.exe -target:"C:\Libs\NUnit-2.7.1\nunit-conso le.exe" -targetargs:"rssbus.APIServer.Test.dll" -targetdir:. -searchdirs:"C:\Dev\RSSBus\v18\APIServer\tests\web\bin" -register:user
    Executing: C:\Libs\NUnit-2.7.1\nunit-console.exe
    NUnit-Console version 2.7.1.0
    Copyright (C) 2002-2014, 2018 Charlie Poole.
    Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
    Copyright (C) 2000-2002 Philip Craig.
    All Rights Reserved.

    Runtime Environment -
       OS Version: Microsoft Windows NT 6.2.9200.0
      CLR Version: 4.0.30319.42000 ( Net 4.5 )

    ProcessModel: Default    DomainUsage: Single
    Execution Runtime: net-4.5
    .start
    F
    Tests run: 1, Errors: 0, Failures: 1, Inconclusive: 0, Time: 0.0941005 seconds
      Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

    Errors and Failures:
    1) Test Failure : rssbus.APIServer.Tests.ODataHandlerTest.FormatDecimal
         Expected: not null or empty string
      But was:  <string.Empty>

    at rssbus.APIServer.Tests.ODataHandlerTest.FormatDecimal() in C:\Dev\RSSBus\v18\APIServer\tests\ODataHandlerTest.cs:line 26

    Committing...
    No results, this could be for a number of reasons. The most common reasons are:
        1) missing PDBs for the assemblies that match the filter please review the
        output file and refer to the Usage guide (Usage.rtf) about filters.
        2) the profiler may not be registered correctly, please refer to the Usage
        guide and the -register switch.

**Comment by sawilde** [comment]
@lwl5219 have a look in the output file - it may provide the reason as to why it didn't load the PDB
