### ISSUE TITLE
Opencover code coverage is generating Empty coverage.xml file

### ISSUE THREAD

**Issue by ZAHEERPASHA** [OpenCover/opencover#952]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [X ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [X ] Windows Server 2016

### I have already...

- [X ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior
Should gererate Coverage.xml with the test execution details

### Actual Behavior
Coverage.xml file is empty: Refer below:
<?xml version="1.0" encoding="utf-8"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="4.7.922.0">
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" maxCrapScore="0" minCrapScore="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>

tried adding parameter -oldstyle. still same error
### Steps to reproduce the problem:
using below cmdline:

"C:\Users\OpenCover.Console.exe" -mergebyhash -returntargetcode -register:user -filter:"+[NCastor.Console]*" -output:"C:\Temp\OpenCover_MSTest_CodeCoverage.xml" -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\mstest.exe" -targetargs:"/testcontainer:"C:\Temp\src\bin\Release\steam.AM.Types.Tests.dll" /detail:errormessage /detail:errorstacktrace /resultsfile:"C:\Temp\MSTestReport.trx""

Same command works fine with same tool version and code base on another windows 2016 VM.
Please help me find resolution.

**Comment by sawilde** [comment]
Sorry I can't help on this one.
