### ISSUE TITLE
Coverage reports not being generated when running on Github actions

### ISSUE THREAD

**Issue by raschmitt** [OpenCover/opencover#954]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [X] .NET Core 3.1
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016
- [X] Windows Server 2019  - ([Github Actions VE](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md)) 

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

I'm trying to generate a covergae report using the following comand:

`OpenCover.Console.exe -target:"dotnet.exe" -targetargs:test -register:user`

Which runs fine if I use it locally on my machine, but when I try to run it trough this [Github Actions workflow](https://github.com/raschmitt/date-override/blob/master/.github/workflows/dotnet-core.yml), it simply doen't generates a report, as can be seen in [this run](https://github.com/raschmitt/date-override/runs/886141295?check_suite_focus=true).

### Actual Behavior

 - Local Run

Everything works as expected

- Github Actions

No report gets generated and I get the following error message: 

```
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
```

### Steps to reproduce the problem:

Simply run this worflow: [.NET Core - Build & Test](https://github.com/raschmitt/date-override/actions?query=workflow%3A%22.NET+Core+-+Build+%26+Test%22)

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [X] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
It could be a permissions thing - this is quite common with build platforms - I would raise this with github directly
