### ISSUE TITLE
No result!

### ISSUE THREAD

**Issue by bboysteed** [OpenCover/opencover#956]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ *] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ *] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ *] repeated the problem using the latest stable release of OpenCover.
- [ *] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [* ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ *] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [* ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

my command:
C:\Users\18811\AppData\Local\Apps\OpenCover>OpenCover.Console.exe -target:"D:\all_c_projects\untitled\a.exe" -output:".\aaaa.xml" -register:path32

### Actual Behavior

C:\Users\18811\AppData\Local\Apps\OpenCover>OpenCover.Console.exe -target:"D:\all_c_projects\untitled\a.exe" -output:".\aaaa.xml" -register:path32
Executing: D:\all_c_projects\untitled\a.exe
Path: [1, 1][2, 2][3, 3][4, 4][5, 5][6, 6][7, 7][8, 8][9, 9][10, 10][11, 11][12, 12][12, 13][12, 14][12, 15][12, 16][12, 17][12, 18][12, 19][12, 20][12, 21][12, 22][12, 23][12, 24][12, 25][12, 26][12, 27][12, 28][13, 29][14, 30][15, 31][16, 32][17, 31][18, 30][19, 29][20, 28][21, 27][22, 26][23, 25][24, 24][25, 23][26, 22][27, 21][28, 20][29, 19][30, 18][31, 17][31, 16][32, 15][33, 16][34, 17][35, 18][36, 19][37, 20][38, 21][39, 22][40, 23][41, 24][42, 25][43, 26][44, 27][45, 28][46, 29][47, 30][48, 31][48, 32][48, 33][48, 34][48, 35][48, 36][48, 37][48, 38][48, 39][48, 40][48, 41][48, 42][48, 43][48, 44][48, 45][48, 46][48, 47][48, 48]
Path length: 82
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    **1) missing PDBs** for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

### Steps to reproduce the problem:

- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
Everything looks correct based on what you've posted - I assume the PDBs (full) are not available
