### ISSUE TITLE
Generating coverage outside of test framework

### ISSUE THREAD

**Issue by majkinetor** [OpenCover/opencover#959]
I have a REST service that is being tested using Pester and our PowerShell REST client (implemented using PowerShell's `Invoke-RestMethod` and friends).

How would I generate code coverage for it ? 

Test is initiated using:

1. `dotnet run` to start the service in the background
2. `invoke-pester` that runs integration test

Since we don't have by the book testing here using dot net test project, nor `dotnet test` command is used, how would I generate code coverage in such scenario ?

I tried with OpenCover and it starts up the app this way and tests run trough it, but its `results.xml` is almost empty (I checked debug mode and presence of PDB files)

```
$env:ASPNETCORE_URLS = 'http://localhost:3001'
OpenCover -target:"c:\program files\dotnet\dotnet.exe" -targetargs:"run --no-build --no-restore --no-launch-profile --configuration Debug"
```

Is this possible at all ? What am I missing ? 

So the scenario in short is - start the REST app, drive it using `Invoke-RestMethod` a bit, generate coverage.

**Comment by sawilde** [comment]
OpenCover hooks into dotnet apps (and I am amazed it still works with dotnet core ones) using environment variables.

Try launching all the apps you want to instrument into single app - e.g. a custom .net one (even batch file has been see to work) and using OpenCover to execute that app.
