### ISSUE TITLE
switch expression only partialy covered, but same as statement fully covered

### ISSUE THREAD

**Issue by LukasGelke** [OpenCover/opencover#960]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [x] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [x] Something else: .NET CoreApp 3.0

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [x] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

`TransformEnum` and `TransformEnum2` be 100% covered

### Actual Behavior

`TransformEnum` is 100% and `TransformEnum2` 75/77.78%

![HTML Report](https://user-images.githubusercontent.com/71026023/93450505-5a4e6b80-f8d6-11ea-966a-0364318eada6.png)

### Steps to reproduce the problem:

- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [x] sample code or link to repository/gist is available (support is much faster this way):

Minimal Test in net472/netcoreapp3.0 project with LangVersion latest (switch expressions are a C#8 thing)
https://gist.github.com/LukasGelke/d6515a2282206c8babd4a1c879c76400

Using either framework in either Debug/Release has the same result.

From what I understand, both Transform-Functions produce similar IL Code, but notably the expression-version has a few more branch-instructions and does some additional locals/stack moving before returning.

**Comment by sawilde** [comment]
Thanks - we haven't updated OpenCover in a while to deal with .net core 3 etc and so the expected IL in these cases may be unexpected.

**Comment by sawilde** [comment]
latest build without any changes returns this

![image](https://user-images.githubusercontent.com/297165/105782054-d87af700-5fc7-11eb-856b-25dbf6e181e2.png)

The compiler generates some odd branches and sticks a sequence point on the nop which isn't being hit by your current tests

![image](https://user-images.githubusercontent.com/297165/105784296-a5873200-5fcc-11eb-8366-7706a5913643.png)

**Comment by sawilde** [comment]
this only happens with unoptimsed code (i.e. debug)
