### ISSUE TITLE
Cannot understand and get opencoverreturncodeoffset to work

### ISSUE THREAD

**Issue by Stupastian** [OpenCover/opencover#963]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [X] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

OpenCover exitcode should be a combination of actual return value + given offset value in some situations.

### Actual Behavior

OpenCover always returns 1 or 0 without adding the offset.

### Steps to reproduce the problem:

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way) 

Hi,
We have had occasional exceptions during test runs for our .net core 3 applications and it seems the problem is not directly related to our test implementations. I tried to implement more fault tolerant approach by utilizing the returntargetcode parameter but I don't seem to understand how it should work. I tried introducing one or more failing tests and throwing exceptions from the tests but the resulting exit code from OpenCover is always 1. 

Could someone give an example how the offset parameter should work and in which situations the return value should change? I tried to look at the OpenCover.cs too but couldn't see anything I could use.

OpenCover is run with following parameters:
-register:administrator
-target:dotnet.exe
-targetargs:[value] 
-output:[value]
-returntargetcode:100
-mergeoutput
-oldStyle
-excludebyattribute:System.CodeDom.Compiler.GeneratedCodeAttribute
Xunit is given as logger parameter in dotnet -targetargs.

Thanks,
Mikko

**Comment by sawilde** [comment]
@Stupastian the return target code is used to return the return code of the target process instead of the opencover return code. The offset parameter e.g. 100 is used to offset the opencover code if that is your need i.e
0-99 - range expected for codes returned from target process
100- range expected for codes returned form opencover
