### ISSUE TITLE
Unable to get coverage for service

### ISSUE THREAD

**Issue by Hack3l** [OpenCover/opencover#966]
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [X] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Getting Coverage for a service

### Actual Behavior

After stopping service OpenCover outputs:
```
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
```
### Steps to reproduce the problem:

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [X] sample code or link to repository/gist is available (support is much faster this way) 

`OpenCover.Console.exe -target:"<servicename>" -service:byname -log:All -output:"C:\Temp\unittest\coverage.xml"`

I tried to use the -register switch, now i have registered both profiles assemblies using regsvr32
The account starting OpenCover has administrator privileges and the service runs using the local system account
PDB files are in the folder containing the exe the services runs (tried using -targetdir switch with same result)
coverage.xml file contains:
```xml
<?xml version="1.0" encoding="utf-8"?>`
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="4.7.922.0">
  <Summary numSequencePoints="0" visitedSequencePoints="0" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="0" branchCoverage="0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" maxCrapScore="0" minCrapScore="0" visitedClasses="0" numClasses="0" visitedMethods="0" numMethods="0" />
  <Modules />
</CoverageSession>
```

**Comment by sawilde** [comment]
Hi @Hack3l 

It looks like the profiler isn't getting attached to the service and this has always been tricky to get working. 

It's been a long time since I have tried covering a service as it is so complicated and not something I ever do nowadays - at least 4+ years. Instead I always developed my services to also run in a console mode and that makes them much easier to execute and gather coverage metrics.
