### ISSUE TITLE
Visual Studio extension

### ISSUE THREAD

**Issue by FortuneN** [OpenCover/opencover#968]
Hello,

I have been working on a Visual Studio extension (Fine Code Coverage) that is powered by Coverlet, OpenCover and ReportGenerator.
The goal of the extension is to visualize coverage output inside VS while you code and run tests.
It is free and open source.

[View in Github](https://github.com/FortuneN/FineCodeCoverage)
[View in Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage)

Thank you for OpenCover which is a big part of the Fine Code Coverage extension.
I would also like to (shamefully) request a listing on your repo/blog/... for the benefit of OpenCover users who are interested in a Visual Studio extension that utilizes OpenCover.

I hope my efforts amplify yours for Visual Studio users and i eagerly await any terms, conditions, suggestions or feedback that you may have for me.

Regards

**Comment by sawilde** [comment]
@FortuneN welcome and thanks - I have added a link to the readme.md

**Comment by FortuneN** [comment]
Thank you, Thank you, Thank you
