### ISSUE TITLE
OpenCover is taking an extraordinarily long time (45 minutes) to process unit test output and produce the coverage report.

### ISSUE THREAD

**Issue by FrankRay78** [OpenCover/opencover#969]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [X] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

OpenCover processes unit test output and produces the coverage report in a timely fashion.

### Actual Behavior

OpenCover is taking an extraordinarily long time (45 minutes) to process unit test output and produce the coverage report.  However it does complete and operation is as per expected.  See below (marked by **----->**) where I point out this behaviour:

C:\Users\frank\Documents\Jenkins\workspace\SystemBackTester>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "SystemBackTesterTESTS\bin\Debug\SystemBackTesterTESTS.dll" /TestAdapterPath:"packages\MSTest.TestAdapter.1.3.2" /ResultsDirectory:TestResults /logger:trx  
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  û ShortTest_1stock_30days [2s 394ms]
  û ShortTest_SingleParameters [3s 338ms]
  û ShortTest_FiveParameterCombinations [22s 61ms]
  û ShortTest_FiveParameterCombinations_ParameterHashFileStore [21s 734ms]
  û ShortTest_Randomised_FiveParameterCombinations [21s 340ms]
  ! LongRunningTest_SingleParameters
  ! VeryLongRunningTest_SingleParameters
  ! LongRunningTest_MultipleParameters
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore [21s 547ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive [21s 460ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive2 [21s 217ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive2_ParameterList [36ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive_HasOutPerforming [21s 472ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive_HasUnderPerforming [18s 764ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive2_HasOutPerforming [26s 983ms]
  û BrokenTest_MissingParameters_OutputLogged [157ms]
  û ParametersBase_SetValue_RandomisedParameterBool [< 1ms]
  û ParametersBase_SetValue_SteppedParameterFloat [1ms]
  û ParametersBase_SetValue_SteppedParameterInt [< 1ms]
  û ParametersBase_SetValue_RandomisedParameterRoundedInt [< 1ms]
  û ParametersBase_SetValue_RandomisedParameterT [< 1ms]
  û ParametersBase_SetValue_FixedParameterTint [< 1ms]
  û ParametersBase_SetValue_FixedParameterTfloat [< 1ms]
  û RandomisedParameterIntTest [64ms]
  û DependentParameterTest_OverLapping [146ms]
  û DependentParameterTest_NotOverLapping [105ms]
Results File: C:\Users\frank\Documents\Jenkins\workspace\SystemBackTester\TestResults\FRANK-LAPTOP$_FRANK-LAPTOP_2020-11-19_13_59_34.trx

Test Run Successful.
Total tests: 26
     Passed: 23
    Skipped: 3
 Total time: 3.3983 Minutes

C:\Users\frank\Documents\Jenkins\workspace\SystemBackTester>if 0 NEQ 0 exit /b 0 

C:\Users\frank\Documents\Jenkins\workspace\SystemBackTester>packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" -targetargs:"SystemBackTesterTESTS\bin\Debug\SystemBackTesterTESTS.dll /TestAdapterPath:packages\MSTest.TestAdapter.1.3.2 /TestCaseFilter:TestCategory=IncludeInCover" -filter:"+[*]SystemBackTesterLIB.* -[*TESTS]*" -output:TestResults\OpenCover.XML -skipautoprops 
Executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  û ShortTest_1stock_30days [32s 911ms]
**----->**  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore [45m 25s]
  û BrokenTest_MissingParameters_OutputLogged [120ms]
  û ParametersBase_SetValue_RandomisedParameterBool [1ms]
  û ParametersBase_SetValue_SteppedParameterFloat [2ms]
  û ParametersBase_SetValue_SteppedParameterInt [< 1ms]
  û ParametersBase_SetValue_RandomisedParameterRoundedInt [2ms]
  û ParametersBase_SetValue_RandomisedParameterT [2ms]
  û ParametersBase_SetValue_FixedParameterTint [< 1ms]
  û ParametersBase_SetValue_FixedParameterTfloat [< 1ms]
  û RandomisedParameterIntTest [4s 85ms]
  û DependentParameterTest_OverLapping [10s 338ms]
  û DependentParameterTest_NotOverLapping [8s 761ms]

Test Run Successful.
Total tests: 13
     Passed: 13
 Total time: 46.3835 Minutes
Committing...
Visited Classes 43 of 49 (87.76)
Visited Methods 181 of 245 (73.88)
Visited Points 1318 of 1851 (71.20)
Visited Branches 516 of 725 (71.17)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 43 of 50 (86)
Alternative Visited Methods 181 of 274 (66.06)

C:\Users\frank\Documents\Jenkins\workspace\SystemBackTester>if 0 NEQ 0 exit /b 0 

### Steps to reproduce the problem:

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [_possibly -the code is checked-in to a private repo however the test and code base are a bit elaborate simply because of the functionality_] sample code or link to repository/gist is available (support is much faster this way)

**Comment by FrankRay78** [comment]
Open Cover xml output file attached FYI.  

[OpenCover.zip](https://github.com/OpenCover/opencover/files/5568946/OpenCover.zip)

**Comment by FrankRay78** [comment]
Ok, so I've investigated this a little further.  Apart from the very long period of time, I think it's all operating as expected.  

The test in question that produces a very long OpenCover is this one:  
ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore [45m 25s]

It's actually back testing a trading strategy over 20 stocks and 20 years of historical end of day data. It's not a huge dataset and the unit test itself, no OpenCover takes under 30 seconds:

ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore [21s 547ms]

I've worked around this issue for now on my build machine by defining the same test but for only 1 stock and 30 days of data, now it only takes this long to complete the OpenCover:

  û Database_Coverage_Test_1stock_30days [31s 170ms]

In my case, the shortened test still exercises exactly the same code (largely) but without the same volume of trades / objects being created / held / destroyed in memory etc.

**Comment by sawilde** [comment]
There are some really tight loops going on with a lot of hits

![image](https://user-images.githubusercontent.com/297165/99937987-091d9500-2dbb-11eb-90c0-7f2788ecbbc3.png)

and

![image](https://user-images.githubusercontent.com/297165/99938067-2eaa9e80-2dbb-11eb-81bd-47f1e9371ca7.png)

some things to try

1. you could try using the `-threshold:<count>` switch - the vc elements will no longer be accurate but it shouldn't affect line coverage.

2. mark those areas with a custom skip coverage attribute and when running the big tests that exercise these areas extensively - but still allow coverage on the smaller unit tests - merge the results from the two test runs to et overall coverage.

**Comment by FrankRay78** [comment]
Many thanks @sawilde , I'll try item 1 and let you know.  

I've effectively done part of point 2 by ignoring the big tests, but the idea of splitting them smaller and then merging results has merit too which I didn't think of doing.  However in my case, the code isn't easily split now and the time taken to do so won't be worth the benefits (given I already have pretty good coverage from the smaller tests). But like I said, an idea with merit.

**Comment by FrankRay78** [comment]
The improvement with the "-threshold:<count>" switch was dramatic @sawilde, not just that but I can now include the long running tests and profile coverage for those as well.  I'm going to mark this issue as closed.

**Comment by sawilde** [comment]
@FrankRay78 glad it helped - can you let me know what the new times are, it might make a good story about when to use the  `-threshold` switch

**Comment by FrankRay78** [comment]
Below is the latest OpenCover command with the threshold switch and log from the build server.   Compared to the log I posted previously showing circa 45 minutes, the below shows it's dropped to 8min which I'm happy with.  It's worth saying these tests are trawling through 20 years of end of day stock data for 20 stocks (loaded from file and held in memory).

C:\Users\frank\Documents\Jenkins\workspace\SystemBackTester>packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" -targetargs:"SystemBackTesterTESTS\bin\Debug\SystemBackTesterTESTS.dll /TestAdapterPath:packages\MSTest.TestAdapter.1.3.2" -filter:"+[*]SystemBackTesterLIB.* -[*TESTS]*" -output:TestResults\OpenCover.XML -skipautoprops -threshold:10 
Executing: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  û Database_Coverage_Test_1stock_30days [3s 666ms]
  û ShortTest_SingleParameters [7s 684ms]
  û ShortTest_FiveParameterCombinations [59s 609ms]
  û ShortTest_FiveParameterCombinations_ParameterHashFileStore [54s 49ms]
  û ShortTest_Randomised_FiveParameterCombinations [55s 465ms]
  ! LongRunningTest_SingleParameters
  ! VeryLongRunningTest_SingleParameters
  ! LongRunningTest_MultipleParameters
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore [56s 597ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive [57s 104ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive2 [1m]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive2_ParameterList [44ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive_HasOutPerforming [58s 574ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive_HasUnderPerforming [49s 472ms]
  û ShortTest_FiveParameterCombinations_ParameterHashDatabaseStore_Aggressive2_HasOutPerforming [1m 5s]
  û BrokenTest_MissingParameters_OutputLogged [110ms]
  û ParametersBase_SetValue_RandomisedParameterBool [1ms]
  û ParametersBase_SetValue_SteppedParameterFloat [2ms]
  û ParametersBase_SetValue_SteppedParameterInt [< 1ms]
  û ParametersBase_SetValue_RandomisedParameterRoundedInt [< 1ms]
  û ParametersBase_SetValue_RandomisedParameterT [2ms]
  û ParametersBase_SetValue_FixedParameterTint [< 1ms]
  û ParametersBase_SetValue_FixedParameterTfloat [< 1ms]
  û RandomisedParameterIntTest [148ms]
  û DependentParameterTest_OverLapping [379ms]
  û DependentParameterTest_NotOverLapping [256ms]

Test Run Successful.
Total tests: 26
     Passed: 23
    Skipped: 3
 Total time: 8.8374 Minutes
Committing...
Visited Classes 46 of 49 (93.88)
Visited Methods 192 of 245 (78.37)
Visited Points 1403 of 1857 (75.55)
Visited Branches 537 of 727 (73.87)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 46 of 50 (92)
Alternative Visited Methods 192 of 274 (70.07)
