### ISSUE TITLE
Spaces in TargetArgs

### ISSUE THREAD

**Issue by michaelfoster9** [OpenCover/opencover#970]
Hello, I'm trying to run OpenCover on a Visual Studio unit test on the command line below
& $OpenCoverTools\OpenCover.Console.exe -target:$vsTestConsoleLocation "-targetargs:Testing\Folder With Space\UnitTests.dll"

However, I get an argument that the file "Testing\Folder" was not found.  

I have tried the following
* wrapping the file name with "".  ie     "-targetargs:""Testing\Folder With Space\UnitTests.dll"""
* doing the same but using `\"`
* replacing the spaces in the directory names with  "` "

none of these things seem to work and renaming isn't really an option.  Am I out of luck or is there a workaround here.

thanks in advance!!

**Comment by sawilde** [comment]
There is a section in the wiki on this https://github.com/OpenCover/opencover/wiki/Usage#notes-on-spaces-in-arguments

I would try "-targetargs:Testing\Folder With Space\UnitTests.dll" or -targetargs:"Testing\Folder With Space\UnitTests.dll"

Alternatively if on windows you can also us the short name for a long name folder if you can work it out use `dir /X`

![image](https://user-images.githubusercontent.com/297165/99938856-d8d6f600-2dbc-11eb-9275-b72bb645d132.png)
