### ISSUE TITLE
ErrorSyntax with parameters -coverbytest

### ISSUE THREAD

**Issue by buiduythienbp96** [OpenCover/opencover#973]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework
- [ ] .NET 4.7
### My Environment
- [ ] Windows 10
### I have already...
- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.
### My issue is related to (check only those which apply):
- [ ] feature request
### Expected Behavior
I want to make unit test in specify file, not all files. 
### Actual Behavior
I find parameters "-coverbytest" to help me solve this. But when I operate the following command

```
 OpenCover.4.6.519\tools\OpenCover.Console.exe "-target:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\VSTest.Console.exe" "-targetargs:D:\Git_Source_Rashinban_Seihinka\WF_dev\compass_wf\compass_wf\compass_wf.Test\bin\Debug\compass_wf.Test.dll"  -register:user -coverbytest:"+[compasswf.*]RemaindController*" -output:UTResults.xml -mergebyhash

```

, I got an syntax error. Please help me to fixed it or give me an example about "-coverbytest".
Thanks alot.
### Steps to reproduce the [problem:](https://drive.google.com/file/d/14saNMrjYRNbAbT8cdH7KXt0yDWargQCv/view?usp=sharing)
- Error syntax when excuted command is as attached image.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment]
-coverbytest only uses assembly names e.g.

`-coverbytest:*.Test.dll`

I need to update the documentation to make that clearer

**Comment by sawilde** [comment]
documentation updated 
wiki - now
pdf - next release
