### ISSUE TITLE
Open Cover Sample Solution in nuget package doesn't work

### ISSUE THREAD

**Issue by shankbond** [OpenCover/opencover#975]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [X] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [ ] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Provided sample should work.

### Actual Behavior

Sample doesn't work after restoring mentioned nuget packages in batch file and as a result unable to use this exe.

### Steps to reproduce the problem:

Try to build provided sample solution that comes with nuget package.

**Comment by shankbond** [comment]
Any updates?

**Comment by sawilde** [comment]
the solution was meant more as a guide rather than to build out of the box - I have updated it so it should build but it is a manual process.

**Comment by shankbond** [comment]
Can you confirm whether Open Cover works on your system with mentioned environment. On my system it wasn't able to instrument any code with provided sample code. other than running bat file and restoring nuget packages do we need to do anything else?

**Comment by sawilde** [comment]
Other than saying it doesn't work you haven't really said what the error message is

The new solution is here https://github.com/OpenCover/opencover/tree/master/samples/SampleSln and will be part of the next release.

Once you've restored the packages you should have 4 packages in the packages folder.

OpenCover, ReportGenerator and two NUnit packages

I may tweak the sample again to upgrade to latest of the other packages
